-- ============================================
-- AZERBAIJAN OIL FIELDS - TABLE MODIFICATION & DATA INSERT
-- Generated from: Azerbaijan_all_sites_with_coordinates.json
-- Generated date: 2026-02-01
-- ============================================

-- ============================================
-- STEP 1: MODIFY TABLE STRUCTURE (if not already done)
-- ============================================

-- Add new columns to support comprehensive oil field data (if not exists)
ALTER TABLE public.commodity_locations
  -- Production data
  ADD COLUMN IF NOT EXISTS production_monthly DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS production_yearly DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS production_unit TEXT,
  
  -- Dates
  ADD COLUMN IF NOT EXISTS start_date DATE,
  ADD COLUMN IF NOT EXISTS closing_date DATE,
  
  -- Ownership details
  ADD COLUMN IF NOT EXISTS ownership_details TEXT,
  
  -- Reserves unit
  ADD COLUMN IF NOT EXISTS reserves_unit TEXT,
  
  -- Quality specifications
  ADD COLUMN IF NOT EXISTS quality_type TEXT,
  ADD COLUMN IF NOT EXISTS quality_sulfur_content DECIMAL(5, 2),
  ADD COLUMN IF NOT EXISTS quality_grade_percent DECIMAL(5, 2),
  
  -- Transaction data
  ADD COLUMN IF NOT EXISTS last_transaction_value DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS last_transaction_currency TEXT DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS last_transaction_date DATE,
  
  -- Contract information
  ADD COLUMN IF NOT EXISTS contract_duration_years INTEGER,
  
  -- Infrastructure arrays
  ADD COLUMN IF NOT EXISTS pipelines TEXT[],
  ADD COLUMN IF NOT EXISTS ports TEXT[],
  ADD COLUMN IF NOT EXISTS rail_connections TEXT[];

-- Update operational_status check constraint to include 'active' and 'closed'
ALTER TABLE public.commodity_locations
  DROP CONSTRAINT IF EXISTS commodity_locations_operational_status_check;

ALTER TABLE public.commodity_locations
  ADD CONSTRAINT commodity_locations_operational_status_check 
  CHECK (operational_status IN ('operational', 'under_construction', 'planned', 'inactive', 'depleted', 'active', 'closed'));

-- Update ownership_type check constraint (allow all variations)
ALTER TABLE public.commodity_locations
  DROP CONSTRAINT IF EXISTS commodity_locations_ownership_type_check;

ALTER TABLE public.commodity_locations
  ADD CONSTRAINT commodity_locations_ownership_type_check 
  CHECK (ownership_type IN (
    'private', 'public', 'state_owned', 'joint_venture', 
    'state-owned', 
    'State-owned',
    'JV', 
    'PSC', 
    'PSC/PSA',
    'PSC/JV',
    'JV / PSC', 
    'JV/PSC',
    'PSC / JV',
    'PSC/JV',
    'PSC (Production Sharing Agreement)',
    'PSC (Production Sharing Agreement) / JV with participating interests',
    'PSC / Consortium',
    'JV (50/50)',
    'JV/PSA rehabilitation (post-2009 agreement reported in secondary sources)',
    'PSA rehabilitation/development (post-2009)',
    'Risk Service Agreement (RSA)',
    'Risk Service Agreement (RSA) / JV participating interest transfer',
    'RSA / JV',
    'state-owned with service/rehabilitation agreement',
    'Exploration & development block with participating interests (details not fully disclosed in cited release)',
    'PSC/JV (Block 14 Contractor Group)',
    'JV / PSC-style partnership',
    'JV / PSC-style partnership (Sonatrach majority, foreign minority)',
    'JV / PSC (historical)',
    'JV (Sonatrach with foreign partners)',
    'JV / PSC / Unitized (multi-block)',
    'Unitized JV / PSC',
    'Production Sharing-style partnership with Sonatrach (national company)',
    'JV / Production Sharing-style partnership with Sonatrach (national company)',
    'state-owned (project history includes terminated foreign LNG development contract)',
    'JV (concession / joint participation)',
    'JV (exploration block participants)',
    'JV concession (Block 0 Association)',
    'JV (Concession/Association)',
    'JV (Block 14 contractor group / PSA-style deepwater block; concessionaire Sonangol/ANPG framework)',
    'JV (Block 14 contractor group)',
    'JV (Block 17 contractor group; concessionaire Sonangol/ANPG)',
    'JV / PSC-like block partnership (Angola ANPG concessionaire framework)',
    'JV / PSC-like deepwater block partnership (Angola concessionaire framework)',
    'JV / concession (Block 14 contractor group)',
    'unknown'
  ));

-- Update location_type check constraint
ALTER TABLE public.commodity_locations
  DROP CONSTRAINT IF EXISTS commodity_locations_location_type_check;

ALTER TABLE public.commodity_locations
  ADD CONSTRAINT commodity_locations_location_type_check 
  CHECK (location_type IN ('mine', 'oil_field', 'gas_field', 'storage', 'port', 'facility', 'farm', 'processing_plant', 'oil_and_gas_field'));

-- Make latitude/longitude nullable (if not already)
ALTER TABLE public.commodity_locations
  ALTER COLUMN latitude DROP NOT NULL,
  ALTER COLUMN longitude DROP NOT NULL;

-- ============================================
-- STEP 2: HELPER FUNCTIONS
-- ============================================

-- Helper function to parse date strings
CREATE OR REPLACE FUNCTION parse_site_date(date_str TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_str IS NULL OR date_str = 'unknown' OR date_str = '' THEN
    RETURN NULL;
  END IF;
  
  BEGIN
    RETURN date_str::DATE;
  EXCEPTION WHEN OTHERS THEN
    IF date_str ~ '^\d{4}$' THEN
      RETURN (date_str || '-01-01')::DATE;
    END IF;
    IF date_str ~ '^\d{4}-\d{2}$' THEN
      RETURN (date_str || '-01')::DATE;
    END IF;
    -- Handle dates like "1920s"
    IF date_str ~ '\d{4}s$' THEN
      RETURN (SUBSTRING(date_str FROM '\d{4}') || '-01-01')::DATE;
    END IF;
    RETURN NULL;
  END;
END;
$$ LANGUAGE plpgsql;

-- Function to extract primary company name from operator string
CREATE OR REPLACE FUNCTION extract_primary_company(operator_text TEXT)
RETURNS TEXT AS $$
BEGIN
  IF operator_text IS NULL OR operator_text = '' THEN
    RETURN NULL;
  END IF;
  
  IF operator_text ILIKE '%SOCAR%' THEN
    RETURN 'SOCAR';
  END IF;
  IF operator_text ILIKE '%BP%' THEN
    RETURN 'BP';
  END IF;
  IF operator_text ILIKE '%Total%' OR operator_text ILIKE '%TotalEnergies%' THEN
    RETURN 'TotalEnergies';
  END IF;
  IF operator_text ILIKE '%Exxon%' OR operator_text ILIKE '%Esso%' THEN
    RETURN 'ExxonMobil';
  END IF;
  IF operator_text ILIKE '%Lukoil%' THEN
    RETURN 'Lukoil';
  END IF;
  IF operator_text ILIKE '%Equinor%' OR operator_text ILIKE '%Statoil%' THEN
    RETURN 'Equinor';
  END IF;
  IF operator_text ILIKE '%Eni%' THEN
    RETURN 'Eni';
  END IF;
  IF operator_text ILIKE '%TPAO%' THEN
    RETURN 'TPAO';
  END IF;
  IF operator_text ILIKE '%Petronas%' THEN
    RETURN 'Petronas';
  END IF;
  IF operator_text ILIKE '%Rafi%' OR operator_text ILIKE '%Union Grand%' THEN
    RETURN 'Union Grand Energy';
  END IF;
  IF operator_text ILIKE '%Binagadi%' THEN
    RETURN 'Binagadi Oil Company';
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Insert/update companies from operators
INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('SOCAR', 'producer', 'Azerbaijan', ARRAY['Crude Oil', 'Natural Gas']),
  ('BP', 'producer', 'United Kingdom', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'France', ARRAY['Crude Oil', 'Natural Gas']),
  ('ExxonMobil', 'producer', 'United States', ARRAY['Crude Oil', 'Natural Gas']),
  ('Lukoil', 'producer', 'Russia', ARRAY['Crude Oil', 'Natural Gas']),
  ('Equinor', 'producer', 'Norway', ARRAY['Crude Oil', 'Natural Gas']),
  ('Eni', 'producer', 'Italy', ARRAY['Crude Oil', 'Natural Gas']),
  ('TPAO', 'producer', 'Turkey', ARRAY['Crude Oil', 'Natural Gas']),
  ('Petronas', 'producer', 'Malaysia', ARRAY['Crude Oil', 'Natural Gas']),
  ('Union Grand Energy', 'producer', 'Singapore', ARRAY['Crude Oil', 'Natural Gas']),
  ('Binagadi Oil Company', 'producer', 'Azerbaijan', ARRAY['Crude Oil'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- Delete existing Azerbaijan entries to avoid duplicates
DELETE FROM public.commodity_locations WHERE country = 'Azerbaijan';

-- Insert all Azerbaijan sites
INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  current_production,
  reserves_estimate,
  reserves_unit,
  start_date,
  closing_date,
  api_gravity,
  quality_type,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Balakhany–Sabunchu–Ramana (BSR) Oil & Gas Field (incl. Kurdakhani block under PSA)',
  'SOCAR (Balakhanineft OGPD) with UGE-Lancer PTI under PSA',
  'Absheron Peninsula (Baku), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku)',
  40.439,
  49.965,
  'Energy',
  'Crude Oil',
  'oil_and_gas_field',
  'active',
  'SOCAR (Balakhanineft OGPD) with UGE-Lancer PTI under PSA',
  'PSC/PSA',
  '2010 PSA for Balakhani-Sabunchu-Ramana & Kurdakhani onshore block: SOCAR 25%, UGE-Lancer PTI 75%; term 25 years with possible 5-year extension',
  146666.6667,
  1760000,
  'barrels/year (oil)',
  1760000,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1871'),
  NULL,
  NULL,
  'unknown (mature onshore crude)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2010-06-03'),
  25,
  ARRAY['Local SOCAR onshore gathering system (Absheron)', 'BTC (Baku–Tbilisi–Ceyhan) via SOCAR export system (typical for SOCAR crude)', 'Baku–Supsa via SOCAR export system (typical)'],
  ARRAY['Sangachal Terminal', 'Baku (Caspian) oil export facilities'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - used for petroleum products in region)'],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Bibi-Heybat Oil & Gas-Condensate Field (Bibiheybatneft OGPD)',
  'SOCAR (Azneft Production Union)',
  'Absheron Peninsula (Baku), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku)',
  40.342,
  49.805,
  'Energy',
  'Crude Oil',
  'oil_and_gas_field',
  'active',
  'SOCAR (Azneft Production Union)',
  'state-owned',
  'Operated by SOCAR Azneft (Bibiheybatneft OGPD); reported cooperation roadmap with Tatneft (not a disclosed equity transfer)',
  120000,
  1440000,
  'barrels/year (oil equivalent, estimated from 400 t/day statement)',
  1440000,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1873'),
  NULL,
  NULL,
  'unknown (mature onshore crude)',
  NULL,
  NULL,
  NULL,
  'AZN',
  parse_site_date('2024-07-12'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)', 'BTC (Baku–Tbilisi–Ceyhan) via SOCAR export system (typical for SOCAR crude)', 'Baku–Supsa via SOCAR export system (typical)'],
  ARRAY['Sangachal Terminal', 'Baku (Caspian) oil export facilities'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - used for petroleum products in region)'],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Surakhany Oil Field',
  'Rafi Oil (subsidiary of Union Grand Energy, Singapore)',
  'Absheron Peninsula (Baku), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku)',
  40.422,
  50.006,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Rafi Oil (subsidiary of Union Grand Energy, Singapore)',
  'PSC/JV',
  'Operated by Rafi Oil (Union Grand Energy group) under contract with SOCAR; detailed equity split not publicly confirmed in open sources used',
  90000,
  1095000,
  'barrels/year (oil, estimated from ~3,000 b/d average 2021-2025)',
  1095000,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1920s'),
  NULL,
  NULL,
  'unknown (mature onshore crude)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2021-01-01'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)', 'BTC (Baku–Tbilisi–Ceyhan) via SOCAR export system (typical for exports)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Union Grand Energy',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Binagadi Oil Field',
  'Binagadi Oil Company (operator under PSA)',
  'Absheron Peninsula (Baku, Binaqadi District), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku, Binaqadi District)',
  40.458,
  49.827,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA)',
  'PSC/PSA',
  'Agreement dated 2004-09-29 (effective 2005-09-01) for rehabilitation/development/PSA of block incl. Binagadi et al.: SOCAR (SOCAR Joint Oil Company / SOCAR ONŞ) 25%, Azen Oil Company B.V. 75%',
  82500,
  990000,
  'barrels/year (oil)',
  990000,
  0,
  'barrels (remaining reserves not publicly quantified in sources used)',
  parse_site_date('1896'),
  NULL,
  NULL,
  'unknown (mature onshore crude)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)', 'BTC (Baku–Tbilisi–Ceyhan) via SOCAR export system (typical)'],
  ARRAY['Sangachal Terminal', 'Baku (Caspian) oil export facilities'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - used for petroleum logistics in region)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Girmaki Oil Field (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (Baku/Binaqadi region), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku/Binaqadi region)',
  40.46,
  49.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block operated by Binagadi Oil Company: SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1930s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Chakhnaglar Oil Field (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (Baku/Binaqadi region), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku/Binaqadi region)',
  40.46,
  49.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block: SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1930s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Sulutepe Oil Field (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (Baku/Binaqadi region), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Baku/Binaqadi region)',
  40.46,
  49.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block: SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1950s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Masazir Oil Field (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (near Masazir/Binaqadi region), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (near Masazir/Binaqadi region)',
  40.48,
  49.73,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block: SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1950s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Shabandag Oil Field (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (Binaqadi/Absheron region), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (Binaqadi/Absheron region)',
  40.46,
  49.75,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block: SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1950s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Fatmayi Oil Field (incl. Sianshor & Muhammadli) (Binagadi block)',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'Absheron Peninsula (near Fatmayi), Azerbaijan',
  'Azerbaijan',
  'Absheron Peninsula (near Fatmayi)',
  40.57,
  49.78,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under PSA covering the block)',
  'PSC/PSA',
  'Covered by 2004-09-29 PSA block including Fatmayi (Sianshor & Muhammadli): SOCAR 25%, Azen Oil Company B.V. 75% (field-level splits not disclosed)',
  0,
  0,
  'barrels/year (unknown)',
  0,
  0,
  'barrels (unknown/est.)',
  parse_site_date('1940s'),
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2004-09-29'),
  NULL,
  ARRAY['Local SOCAR onshore gathering system (Absheron)'],
  ARRAY['Sangachal Terminal'],
  ARRAY['Azerbaijan Railways (Baku industrial rail network - potential)'],
  'Binagadi Oil Company',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Azeri–Chirag–Gunashli (ACG) block of fields (incl. Chirag, Central Azeri, West Azeri, East Azeri, Deepwater Gunashli, West Chirag, ACE)',
  'BP',
  'Caspian Sea (offshore), Absheron archipelago, Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), Absheron archipelago',
  40.22,
  51.1,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'BP',
  'PSC (Production Sharing Agreement) / JV with participating interests',
  'ACG participating interests (as reported for 1H 2025): SOCAR 31.65%, bp 30.37%, MOL 9.57%, INPEX 9.31%, ExxonMobil 6.79%, TPAO 5.73%, ITOCHU 3.65%, ONGC Videsh 2.92%. PSA extended in 2017 to 2049.',
  10260000,
  125000000,
  'barrels of oil',
  125000000,
  2700000000,
  'barrels (recoverable, remaining est.; derived from 64% produced / 36% remaining as of Mar 2025 on reported recoverable baseline)',
  parse_site_date('1997'),
  NULL,
  NULL,
  'crude oil (primarily medium-light; Azeri Light/BTC export blend)',
  NULL,
  'crude oil',
  NULL,
  'USD',
  parse_site_date('2017-09-14'),
  NULL,
  ARRAY['Baku–Tbilisi–Ceyhan (BTC) pipeline', 'Baku–Supsa (Western Route Export Pipeline)', 'Baku–Novorossiysk (Northern Route Export Pipeline)'],
  ARRAY['Ceyhan Marine Terminal (Türkiye)', 'Supsa Terminal (Georgia)'],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Shah Deniz gas-condensate field (condensate liquids)',
  'BP',
  'Caspian Sea (offshore), South Caspian Basin, Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), South Caspian Basin',
  39.937,
  50.377,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'BP',
  'PSC / Consortium',
  'Participating interests (bp statement): bp 29.99% (operator), LUKOIL 19.99%, TPAO 19.00%, SGC (Southern Gas Corridor CJSC) 16.02%, NICO 10.00%, MVM 5.00%.',
  2917000,
  35000000,
  'barrels of condensate',
  35000000,
  2000000000,
  'barrels (condensate initially in place; field note)',
  parse_site_date('2006'),
  NULL,
  NULL,
  'gas condensate (light)',
  NULL,
  'gas condensate',
  NULL,
  'USD',
  parse_site_date('1996-01-01'),
  NULL,
  ARRAY['South Caucasus Pipeline (SCP)', 'TANAP', 'TAP'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Absheron gas-condensate field (condensate liquids)',
  'JOCAP (Joint Operating Company of Absheron Petroleum)',
  'Caspian Sea (offshore), Absheron archipelago, Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), Absheron archipelago',
  40.009,
  50.798,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'JOCAP (Joint Operating Company of Absheron Petroleum)',
  'JV (50/50)',
  'TotalEnergies 50%, SOCAR 50%; operated by JOCAP. Phase 1 capacity stated at 12,000 b/d condensate.',
  360000,
  4380000,
  'barrels of condensate',
  4380000,
  629000000,
  'barrels (condensate; stated as 100 million tonnes condensate)',
  parse_site_date('2023-07-10'),
  NULL,
  NULL,
  'gas condensate (light)',
  NULL,
  'gas condensate',
  NULL,
  'USD',
  parse_site_date('2023-07-10'),
  NULL,
  ARRAY['SOCAR offshore network via Oil Rocks (Neft Dashlari) link (per project description)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Umid gas-condensate field (condensate liquids)',
  'Umid-Babek Operating Company (UBOC)',
  'Caspian Sea (offshore), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore)',
  40.0,
  50.1,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Umid-Babek Operating Company (UBOC)',
  'Risk Service Agreement (RSA)',
  'Operated by UBOC under a Risk Service Agreement established in 2017 (per UBOC / Ministry of Energy).',
  103000,
  1240000,
  'barrels of condensate (approx; derived from 470 t/day condensate)',
  1240000,
  251600000,
  'barrels (condensate; stated as 40 million m3 condensate)',
  parse_site_date('2012'),
  NULL,
  NULL,
  'gas condensate (light)',
  NULL,
  'gas condensate',
  NULL,
  'USD',
  parse_site_date('2017-01-01'),
  NULL,
  ARRAY['SOCAR offshore network to Dashgil terminal', 'Dashgil terminal to Sangachal Head Facilities'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Bulla-Deniz (Bulla Deniz) field',
  'SOCAR (operator not specified in cited source; SOCAR reported cumulative production)',
  'Caspian Sea (offshore), Baku archipelago, Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), Baku archipelago',
  40.15,
  50.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (operator not specified in cited source; SOCAR reported cumulative production)',
  'State-owned',
  'SOCAR (Azerbaijan state oil company) reported cumulative production and current well count.',
  0,
  0,
  'barrels of oil (current not found in sources; historical totals reported)',
  0,
  0,
  'barrels (not found)',
  parse_site_date('1975'),
  NULL,
  NULL,
  'oil and gas-condensate (mixed)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1975-01-01'),
  NULL,
  ARRAY['SOCAR offshore network (export via Sangachal area)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Neft Dashlari (Oil Rocks) field',
  'SOCAR Azneft Production Union (Neft Dashlari OGPD)',
  'Caspian Sea (offshore), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore)',
  40.31,
  50.16,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR Azneft Production Union (Neft Dashlari OGPD)',
  'State-owned',
  'Operated by Neft Dashlari OGPD of SOCAR’s “Azneft” Production Union.',
  0,
  0,
  'barrels of oil (current not found in sources; cumulative totals reported)',
  0,
  0,
  'barrels (not found)',
  parse_site_date('1949-11-07'),
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1949-11-07'),
  NULL,
  ARRAY['SOCAR offshore network to shore (not specified)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Karabakh oil field (offshore block)',
  'BP',
  'Caspian Sea (offshore), Absheron archipelago (northern part), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), Absheron archipelago (northern part)',
  40.4,
  50.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'BP',
  'Risk Service Agreement (RSA) / JV participating interest transfer',
  'bp acquired 35% and became operator in 2025; SOCAR counterparty (existing RSA signed in 2018 per bp). Ministry of Energy notes bp became operator in May 2025.',
  0,
  0,
  'barrels of oil (development stage; current production not found)',
  0,
  377000000,
  'barrels (geological; stated initially >60 million tonnes)',
  parse_site_date('2020'),
  NULL,
  NULL,
  'crude oil (expected)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2025-06-03'),
  NULL,
  ARRAY['Potential tie-back/export via SOCAR offshore network to Sangachal (not confirmed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Bahar field',
  'SOCAR (with Bahar Energy Ltd involvement)',
  'Caspian Sea (offshore), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (with Bahar Energy Ltd involvement)',
  'JV/PSA rehabilitation (post-2009 agreement reported in secondary sources)',
  'SOCAR and Bahar Energy Ltd reported as partners (secondary sources).',
  0,
  0,
  'barrels of oil (current not found; historical totals reported)',
  0,
  17000000,
  'barrels (recoverable oil equivalent; from 2.7 million tonnes oil stated)',
  parse_site_date('1969'),
  NULL,
  NULL,
  'oil and gas-condensate',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2009-12-22'),
  NULL,
  ARRAY['SOCAR offshore network (not specified)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Gum Deniz (Gumdeniz) field',
  'SOCAR (with Bahar Energy Ltd under 2009 PSA per secondary sources)',
  'Caspian Sea (offshore), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (with Bahar Energy Ltd under 2009 PSA per secondary sources)',
  'PSA rehabilitation/development (post-2009)',
  'SOCAR and Bahar Energy Ltd signed PSA (Dec 22, 2009) for exploration/rehabilitation/development of Bahar and Gum Deniz (secondary sources).',
  0,
  0,
  'barrels of oil (current not found; historical reference indicates ~50 tonnes/day in 2009)',
  0,
  0,
  'barrels (not found)',
  parse_site_date('1955'),
  NULL,
  NULL,
  'oil and gas',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2009-12-22'),
  NULL,
  ARRAY['SOCAR offshore network (not specified)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Darwin Bank (Darvin bankasi) field',
  'SOCAR (reported)',
  'Caspian Sea (offshore), Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (reported)',
  'State-owned',
  'SOCAR-operated legacy offshore field (secondary source).',
  0,
  0,
  'barrels of oil (current not found; historical totals reported)',
  0,
  18800000,
  'barrels (stated 3 million tonnes oil)',
  parse_site_date('1950'),
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2010-01-01'),
  NULL,
  ARRAY['SOCAR offshore network (not specified)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Ashrafi – Dan Ulduzu – Aypara (ADUA) area (offshore discoveries/prospects)',
  'BP',
  'Caspian Sea (offshore), NE of Baku, Azerbaijan',
  'Azerbaijan',
  'Caspian Sea (offshore), NE of Baku',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'BP',
  'Exploration & development block with participating interests (details not fully disclosed in cited release)',
  'bp completed acquisition of participating interests in ADUA area from SOCAR on 2025-06-03; contains existing discoveries and prospective structures; water depth 80–180 m.',
  0,
  0,
  'barrels of oil (not producing; exploration/development block)',
  0,
  0,
  'barrels (not found)',
  parse_site_date('2025-06-03'),
  NULL,
  NULL,
  'oil (prospective; not producing)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2025-06-03'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Azeri–Chirag–Gunashli (ACG) block (incl. Chirag, Azeri, Deepwater Gunashli, West Chirag, ACE)',
  'BP',
  'Baku (offshore Caspian, Absheron archipelago / near Sangachal terminal export corridor), Azerbaijan',
  'Azerbaijan',
  'Baku (offshore Caspian, Absheron archipelago / near Sangachal terminal export corridor)',
  40.24,
  51.06,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'BP',
  'PSC (Production Sharing Agreement)',
  'ACG PSA originally signed 1994; amended/restated and extended in 2017 effective until 2049. Partner shares vary by reporting period; SOCAR share increased under 2017 extension.',
  10571000,
  128614000,
  'barrels of oil (bbl)',
  128614000,
  300000000,
  'barrels (expected ACE project lifetime oil; field-wide remaining not consolidated here)',
  parse_site_date('1997'),
  NULL,
  36.6,
  'light crude (Azeri blend / Azeri Light)',
  0.16,
  'light crude',
  3600000000,
  'USD',
  parse_site_date('2017-09-14'),
  55,
  ARRAY['Baku-Tbilisi-Ceyhan (BTC) pipeline', 'Baku-Supsa (Western Route Export Pipeline)', 'Baku-Novorossiysk pipeline'],
  ARRAY['Ceyhan Marine Terminal (Türkiye)', 'Supsa Terminal (Georgia)'],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Absheron gas-condensate field (condensate production)',
  'JOCAP (Joint Operating Company of Absheron Petroleum)',
  'Baku (offshore Caspian Sea, Absheron archipelago), Azerbaijan',
  'Azerbaijan',
  'Baku (offshore Caspian Sea, Absheron archipelago)',
  40.009,
  50.798,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'JOCAP (Joint Operating Company of Absheron Petroleum)',
  'PSC / JV',
  'Equity: SOCAR 35%, TotalEnergies 35%, ADNOC 30% (after ADNOC joined Aug 2023).',
  360000,
  4380000,
  'barrels of condensate (bbl)',
  4380000,
  733000000,
  'barrels of condensate equivalent (100 million tonnes condensate reported by Ministry of Energy; converted using ~7.33 bbl/tonne)',
  parse_site_date('2023-07-10'),
  NULL,
  NULL,
  'condensate (light)',
  NULL,
  'condensate',
  NULL,
  'USD',
  parse_site_date('2023-08-04'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Karabakh oil field (offshore discovered field)',
  'BP',
  'Baku (offshore Caspian Sea, Absheron archipelago), Azerbaijan',
  'Azerbaijan',
  'Baku (offshore Caspian Sea, Absheron archipelago)',
  40.4,
  50.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'BP',
  'RSA / JV',
  'Risk Service Agreement signed 2018; bp acquired 35% participating interest from SOCAR in 2025 and became operator; SOCAR retains 65%.',
  0,
  0,
  'barrels of oil (bbl)',
  0,
  439800000,
  'barrels (geological estimate reported as >60 million tonnes; converted using ~7.33 bbl/tonne)',
  parse_site_date('2020'),
  NULL,
  NULL,
  'unknown (oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2025-06-03'),
  NULL,
  ARRAY['Baku-Tbilisi-Ceyhan (BTC) pipeline (via existing offshore-to-shore infrastructure and Sangachal corridor)'],
  ARRAY['Ceyhan Marine Terminal (Türkiye)'],
  ARRAY[]::TEXT[],
  'BP',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Balakhani–Sabunchu–Ramana (incl. Kurdakhani block under rehabilitation agreement)',
  'SOCAR (Balakhanineft OGPD)',
  'Baku (Absheron Peninsula; ~12 km NE of Baku), Azerbaijan',
  'Azerbaijan',
  'Baku (Absheron Peninsula; ~12 km NE of Baku)',
  40.439,
  49.965,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (Balakhanineft OGPD)',
  'state-owned with service/rehabilitation agreement',
  'Developed by SOCAR’s Balakhanineft OGPD; SOCAR signed a 25-year agreement (2010) with Germany’s UGE-Lancer covering Balakhani, Sabunchu, Ramana and Kurdakhani for exploration/rehabilitation/development/production.',
  144000,
  1730000,
  'barrels of oil (bbl)',
  1730000,
  0,
  'barrels',
  parse_site_date('1871'),
  NULL,
  NULL,
  'unknown (mature onshore oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2010'),
  25,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Surakhany oil field',
  'Rafi Oil (Union Grand Energy subsidiary) under PSA',
  'Baku (Absheron Peninsula; ~16 km NE of Baku), Azerbaijan',
  'Azerbaijan',
  'Baku (Absheron Peninsula; ~16 km NE of Baku)',
  40.422,
  50.006,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Rafi Oil (Union Grand Energy subsidiary) under PSA',
  'PSC',
  'PSA entered into force 2005-08-16; initially 25-year PSA with possible 5-year extension; associated gas delivered to national grid free of charge (per PSA terms reported).',
  85800,
  1030000,
  'barrels of oil (bbl)',
  1030000,
  49990000,
  'barrels (6.822 million tonnes reported remaining; converted using ~7.33 bbl/tonne)',
  parse_site_date('1904'),
  NULL,
  NULL,
  'unknown (mature onshore oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2005-08-16'),
  25,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Union Grand Energy',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Binagadi field (Binagadi block incl. Girmaki/Chakhnaglar/Sulutepe/Masazir/Fatmayi/Shabandag/Sianshor)',
  'Binagadi Oil Company (operator under SOCAR agreement)',
  'Baku (NW Absheron Peninsula; ~9 km north of Baku), Azerbaijan',
  'Azerbaijan',
  'Baku (NW Absheron Peninsula; ~9 km north of Baku)',
  40.458,
  49.827,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Binagadi Oil Company (operator under SOCAR agreement)',
  'PSC / JV',
  'Agreement dated 2004-09-29 for rehabilitation/development/production sharing of a block including Binagadi, Girmaki, Chakhnaglar, Sulutepe, Masazir, Fatmayi, Shabandag and Sianshor; share distribution stated by operator: SOCAR ONŞ 25%, Azen Oil Company B.V. 75%; entered into force 2005-09-01.',
  82500,
  990000,
  'barrels of oil (bbl)',
  990000,
  0,
  'barrels',
  parse_site_date('1900'),
  NULL,
  NULL,
  'unknown (mature onshore oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2005-09-01'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
),
(
  'Bibi-Heybat oil field (onshore/nearshore Baku)',
  'SOCAR (historically Baku onshore operations; current specific OGPD not confirmed)',
  'Baku (Bibi-Heybat area, west of central Baku), Azerbaijan',
  'Azerbaijan',
  'Baku (Bibi-Heybat area, west of central Baku)',
  40.342,
  49.805,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SOCAR (historically Baku onshore operations; current specific OGPD not confirmed)',
  'state-owned',
  'Historic field near Baku; official discovery date commonly cited as 1871; production has continued since late 19th century (current operator details not consolidated in sources retrieved).',
  0,
  0,
  'barrels of oil (bbl)',
  0,
  0,
  'barrels',
  parse_site_date('1871'),
  NULL,
  NULL,
  'unknown (mature onshore/nearshore oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'SOCAR',
  '{"source": "Azerbaijan_all_sites.json", "generated_date": "2026-01-21 22:32:30"}'::JSONB
)
;

-- Clean up helper functions
DROP FUNCTION IF EXISTS parse_site_date(TEXT);
DROP FUNCTION IF EXISTS extract_primary_company(TEXT);

-- Create indexes for better query performance (if not exists)
CREATE INDEX IF NOT EXISTS idx_commodity_locations_start_date ON public.commodity_locations(start_date);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_production_yearly ON public.commodity_locations(production_yearly);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_operator ON public.commodity_locations(operator);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_status ON public.commodity_locations(operational_status);

-- Update companies RLS policy for open access
DROP POLICY IF EXISTS "Authenticated users can read companies" ON public.companies;
DROP POLICY IF EXISTS "Anyone can read companies" ON public.companies;
CREATE POLICY "Anyone can read companies" ON public.companies
  FOR SELECT USING (true);

-- Verification query
SELECT COUNT(*) as total_azerbaijan_sites, 
       COUNT(CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN 1 END) as sites_with_coordinates,
       COUNT(CASE WHEN operational_status = 'active' THEN 1 END) as active_sites,
       COUNT(CASE WHEN operational_status != 'active' THEN 1 END) as inactive_sites
FROM public.commodity_locations 
WHERE country = 'Azerbaijan';