-- ============================================
-- CAMEROON OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T15:51:57.340798
-- Total sites: 25
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- Make latitude/longitude nullable
ALTER TABLE public.commodity_locations
  ALTER COLUMN latitude DROP NOT NULL,
  ALTER COLUMN longitude DROP NOT NULL;

-- ============================================
-- STEP 2: HELPER FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION parse_site_date(date_text TEXT) RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' OR date_text = 'unknown' OR date_text ILIKE '%unknown%' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================


INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('Addax Petroleum', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('NewAge', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Perenco', 'producer', 'France', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'France', ARRAY['Crude Oil', 'Natural Gas']),
  ('Tower Resources', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Victoria Oil & Gas', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])

ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;


-- ============================================
-- STEP 4: DELETE EXISTING CAMEROON DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Cameroon';

-- ============================================
-- STEP 5: INSERT CAMEROON SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Kita Eden field',
  'Perenco Rio del Rey',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.6,
  8.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Rio del Rey',
  'PSC',
  '20-year license/PSC signed in 2023 with Cameroon state (SNH) and partner Addax Petroleum Cameroon (percentages not disclosed in sources).',
  0,
  0,
  'bbl (unknown; development drilling campaign started 2024)',
  0,
  'bbl (unknown)',
  parse_site_date('1984'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2023-06-12'),
  20,
  ARRAY['(Field export via Perenco Rio del Rey basin existing infrastructure; specific line names not disclosed in sources)'],
  ARRAY['(Not specified in sources; Cameroon offshore crude typically exported via coastal terminals)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'South Kole Marine field',
  'Perenco (Cameroon) / Perenco Rio del Rey',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.55,
  8.45,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco (Cameroon) / Perenco Rio del Rey',
  'PSC/JV (not fully disclosed)',
  'Operated by Perenco in Cameroon under Rio del Rey basin framework; state partner SNH implied; working interests not provided in sources.',
  114000,
  1387000,
  'bbl (calculated from >3,800 bopd reported June 2023)',
  0,
  'bbl (unknown)',
  parse_site_date('2023-06-29'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2023-06-29'),
  20,
  ARRAY['(Tie-back as satellite to Tiko field; specific pipeline names not disclosed in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Tiko Marine field',
  'Perenco Rio del Rey',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.5,
  8.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Rio del Rey',
  'PSC/JV (not fully disclosed)',
  'Operated by Perenco Rio del Rey with Cameroon state partner SNH (percentages not provided in source).',
  73500,
  894250,
  'bbl (estimated from 2,450 bopd referenced for 2020 drilling campaign/wells)',
  4700000,
  'bbl',
  parse_site_date('(unknown; field development referenced 2018-2020)'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2020-02-28'),
  20,
  ARRAY['(Not specified in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Ekoundou Marine concession/field area',
  'Perenco Rio del Rey',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.48,
  8.55,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Rio del Rey',
  'PSC/JV (not fully disclosed)',
  'Operated by Perenco Rio del Rey with state partner SNH implied (working interests not given in sources).',
  0,
  0,
  'bbl (unknown)',
  0,
  'bbl (unknown)',
  parse_site_date('(unknown)'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2020-02-18'),
  20,
  ARRAY['(Not specified in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Moudi (Marine) concession/fields',
  'Perenco (Cameroon)',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.45,
  8.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco (Cameroon)',
  'JV/association with NOC (not fully disclosed)',
  'Perenco operates Moudi concession in Cameroon with SNH partnership referenced; equity/PSC terms not provided in source.',
  0,
  0,
  'bbl (unknown)',
  0,
  'bbl (unknown)',
  parse_site_date('(unknown)'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011-01-01'),
  NULL,
  ARRAY['(Not specified in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Ebome Marine concession/fields',
  'Perenco (Cameroon)',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.0,
  9.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco (Cameroon)',
  'JV/association with NOC (not fully disclosed)',
  'Perenco operates Ebome Marine concession in Cameroon with SNH partnership referenced; equity/PSC terms not provided in source.',
  0,
  0,
  'bbl (unknown)',
  0,
  'bbl (unknown)',
  parse_site_date('(unknown)'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011-01-01'),
  NULL,
  ARRAY['(Not specified in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Mokoko-Abana field complex (Mokoko-Abana concession)',
  'Addax Petroleum Cameroon Company (APCC)',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.52,
  8.48,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Addax Petroleum Cameroon Company (APCC)',
  'JV/association with NOC (not fully disclosed)',
  'Operated by Addax Petroleum Cameroon Company; Perenco holds 10% interest per source; other interests (incl. SNH) not detailed in source.',
  0,
  0,
  'bbl (unknown)',
  0,
  'bbl (unknown)',
  parse_site_date('(pre-2008; producing before Addax Iroko license award)'),
  NULL,
  'crude oil (unknown grade)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2008-04-04'),
  NULL,
  ARRAY['(Not specified in sources)'],
  ARRAY['(Not specified in sources)'],
  ARRAY[]::TEXT[],
  'Addax Petroleum',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Thali PSC (license area; prospective development at NJOM prospect)',
  'Tower Resources Cameroon S.A.',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.58,
  8.52,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Tower Resources Cameroon S.A.',
  'PSC (100%)',
  'Tower Resources holds 100% of Thali PSC (operator and full working interest) per company disclosure.',
  0,
  0,
  'bbl (no producing volumes disclosed; exploration/appraisal stage in sources)',
  0,
  'bbl (unknown)',
  parse_site_date('2015-09-15'),
  NULL,
  'crude oil (unknown; not yet producing)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2015-09-15'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Tower Resources',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Iroko exploration license area (license block; nearby Mokoko-Abana producing complex)',
  'Addax Petroleum (Cameroon)',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.5,
  8.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Addax Petroleum (Cameroon)',
  'Exploration license with SNH back-in right',
  'Addax awarded 100% stake in Iroko exploration license; SNH back-in right of 30% in case of development (per report).',
  0,
  0,
  'bbl (no producing wells reported in source)',
  0,
  'bbl (unknown)',
  parse_site_date('2008-04-04'),
  NULL,
  'crude oil (unknown; exploration)',
  NULL,
  NULL,
  NULL,
  3000000,
  'USD',
  parse_site_date('2008-04-04'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Addax Petroleum',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Lungahe exploration block',
  'Total Exploration & Production Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.4,
  8.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Total Exploration & Production Cameroon',
  'License (100% participation stake reported)',
  'Awarded by Cameroon ministry; Total E&P Cameroon operates with 100% participation stake per report.',
  0,
  0,
  'bbl (exploration block; no production disclosed)',
  0,
  'bbl (unknown)',
  parse_site_date('2009-07-23'),
  NULL,
  'crude oil (unknown; exploration)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2009-07-23'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'TotalEnergies',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Ebome Marine',
  'Perenco Cameroon',
  'Littoral (Offshore Douala Basin), Cameroon',
  'Cameroon',
  'Littoral (Offshore Douala Basin)',
  3.8,
  9.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Cameroon',
  'JV (concession)',
  'Owned by Perenco and SNH (National Hydrocarbons); specific percentages not found in public sources in this run.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl (remaining not publicly confirmed)',
  parse_site_date('1990s (peak production reported 1998)'),
  NULL,
  'conventional crude oil (API not found in open sources in this run)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011-01-01'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['FSO La Lobe (storage for Ebome crude; offshore Cameroon)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Sanaga South Field',
  'Perenco (partnered with SNH)',
  'South (Offshore near Kribi; Douala/Kribi-Campo Basin), Cameroon',
  'Cameroon',
  'South (Offshore near Kribi; Douala/Kribi-Campo Basin)',
  3.2,
  9.8,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'Perenco (partnered with SNH)',
  'JV / Association (SNH-Perenco)',
  'SNH and Perenco grouped under the ''Sanaga South Association'' (percentages not provided on SNH public pages in this run).',
  0,
  0,
  'boe (gas primarily; oil not specified)',
  0,
  'boe (remaining not publicly confirmed)',
  parse_site_date('2013'),
  NULL,
  'natural gas / condensate associated (oil quality N/A)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-09-01'),
  20,
  ARRAY['SNH-operated gas pipeline delivering to Kribi power plant (effective since 2013)', 'SNH-operated ~5.27 km pipeline to Bipaga Gas Processing Centre (commissioned 2024)'],
  ARRAY['Kribi (gas-to-power and LNG logistics offshore Kribi)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Kolé Crude Blend (FSO Massongo lifting system; multiple fields blend in Cameroon operations area including Douala Basin streams)',
  'Cameroon Oil Terminal SA (COTSA) / Perenco-affiliated (FSO operations)',
  'Littoral (Offshore; stored/lifted west of Limbe), Cameroon',
  'Cameroon',
  'Littoral (Offshore; stored/lifted west of Limbe)',
  4.0,
  8.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Cameroon Oil Terminal SA (COTSA) / Perenco-affiliated (FSO operations)',
  'Private (marketing/lifting system)',
  'FSO Massongo operated by COTSA (affiliated to Perenco); Kolé described as blend from ~half a dozen oil fields; specific field-by-field ownership not provided in this run.',
  360000,
  4380000,
  'bbl (oil)',
  0,
  'bbl (not applicable for blend system)',
  NULL,
  NULL,
  'medium gravity, very low sulfur crude blend',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['FSO Massongo (permanently moored ~51 miles west of Limbe; SPM loading point)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Matanda Block / North Matanda (gas/condensate discovery; Douala Basin)',
  'Gaz du Cameroun (GDC) / Victoria Oil & Gas (historical)',
  'Littoral (Douala Basin; onshore & shallow water near Wouri estuary / adjacent to Logbaba), Cameroon',
  'Cameroon',
  'Littoral (Douala Basin; onshore & shallow water near Wouri estuary / adjacent to Logbaba)',
  4.1,
  9.7,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'Gaz du Cameroun (GDC) / Victoria Oil & Gas (historical)',
  'PSC',
  'Victoria Oil & Gas/Gaz du Cameroun acquired 75% interest in Matanda block from Glencore Cameroon (subject to approvals); Afex Global held remaining interest in later reporting; SNH has back-in right upon exploitation license (specific terms vary by phase).',
  0,
  0,
  'bbl (condensate) / gas (not currently producing oil in public sources in this run)',
  136000000,
  'bbl (condensate in-place; per OGJ)',
  parse_site_date('1980 (discovery; not developed as producing oil field)'),
  NULL,
  'gas/condensate (oil quality N/A)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2016-02-18'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['Port of Douala (logistics for adjacent Logbaba operations; general regional export/logistics)'],
  ARRAY[]::TEXT[],
  'Victoria Oil & Gas',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Etinde Permit (Douala/Kribi-Campo Basin) - IM Field (development concept phase)',
  'New Age (CamOP) (operator per farm-in terms)',
  'South (Offshore near Kribi; Douala/Kribi-Campo Basin), Cameroon',
  'Cameroon',
  'South (Offshore near Kribi; Douala/Kribi-Campo Basin)',
  3.5,
  9.5,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'New Age (CamOP) (operator per farm-in terms)',
  'JV / PSC-style permit with state participation',
  'Post farm-in structure described publicly: NewAge 30%, Lukoil 30%, Bowleven 20%, SNH 20% (as reported in 2015); other sources describe slightly different pre-completion percentages and consideration values; treated here as best available open reporting.',
  0,
  0,
  'boe (no current production in cited sources)',
  263000000,
  'boe (P50 contingent resources pre-transaction; permit-level)',
  parse_site_date('unknown (discoveries; no production reported in cited sources)'),
  NULL,
  'oil & gas discoveries (specific crude API not provided in cited sources)',
  NULL,
  NULL,
  NULL,
  250000000,
  'USD',
  parse_site_date('2014-06-24'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['Kribi (nearest major export/industrial port for potential development)'],
  ARRAY[]::TEXT[],
  'NewAge',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Rio del Rey Basin (Perenco-operated PSC/Concession Area)',
  'Perenco Rio del Rey',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.5,
  8.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Rio del Rey',
  'PSC/JV with state participation',
  'Perenco under 20-year PSC with SNH; includes multiple mature shallow-water fields and satellite projects across Rio del Rey basin; partner mentioned in licensing context includes Addax Petroleum Cameroon for specific assets',
  1065000,
  12961250,
  'barrels (estimated; based on ~35,000 bbl/d basin average)',
  0,
  'barrels (unknown)',
  parse_site_date('1970s'),
  NULL,
  'mixed (multiple field crudes; includes heavy/sour and other grades)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2023-06-12'),
  20,
  ARRAY[]::TEXT[],
  ARRAY['Offshore loading via FSOs in region (e.g., Massongo; La Lobe)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'South Kole Marine Field',
  'Perenco',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.55,
  8.45,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'PSC/JV with state participation',
  'Operated by Perenco; development tied to Rio del Rey basin PSC with SNH',
  115900,
  1410000,
  'barrels (estimated; based on >3,800 bbl/d reported)',
  0,
  'barrels (unknown)',
  parse_site_date('2023-06-29'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2023-06-29'),
  20,
  ARRAY[]::TEXT[],
  ARRAY['Offshore export via Perenco Rio del Rey logistics (FSO/terminal not specified in public article)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Kita Eden Field',
  'Perenco Rio del Rey',
  'Southwest Region (offshore, northern Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, northern Rio del Rey Basin)',
  4.6,
  8.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco Rio del Rey',
  'PSC/JV with state participation',
  'Perenco Rio del Rey under 20-year license/PSC agreement signed 2023 with Cameroon state/SNH; partner referenced: Addax Petroleum Cameroon',
  0,
  0,
  'barrels (current rate not publicly stated; drilling campaign ongoing)',
  0,
  'barrels (unknown)',
  parse_site_date('1984'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2023'),
  20,
  ARRAY[]::TEXT[],
  ARRAY['Offshore export via Perenco Rio del Rey logistics (FSO/terminal not specified for this field)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Mokoko–Abana Field',
  'Addax Petroleum Cameroon Company (APCC)',
  'Southwest Region (offshore Cameroon, shallow water), Cameroon',
  'Cameroon',
  'Southwest Region (offshore Cameroon, shallow water)',
  4.52,
  8.48,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Addax Petroleum Cameroon Company (APCC)',
  'JV with state participation',
  'Owned by China Petrochemical (Sinopec/Addax), Creative Energy, SNH (National Hydrocarbons), and Perenco Holdings; Perenco reported to hold 10% interest (stake context)',
  555000,
  6752500,
  'barrels (estimated; based on 18,500 bbl/d referenced historically)',
  0,
  'barrels (unknown)',
  parse_site_date('1980s'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011-10-31'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['Offshore export infrastructure used by operators in Cameroon (specific terminal not stated in sources)'],
  ARRAY[]::TEXT[],
  'Addax Petroleum',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Thali PSC (Dissoni) – Njonji/Rumpi discoveries (undeveloped/awaiting drilling)',
  'Tower Resources Cameroon S.A.',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.58,
  8.52,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Tower Resources Cameroon S.A.',
  'PSC (private operator under state PSC)',
  'Tower Resources Cameroon S.A. holds 100% interest in Thali PSC; First Exploration Period extended to 2025-02-04 with further extension requested; drilling expected in Q1 2026 per company update',
  0,
  0,
  'barrels (not in production; exploration/appraisal)',
  18000000,
  'barrels (gross mean contingent resources cited for Njonji-1 & Njonji-2 fault blocks; additional prospective resources reported separately)',
  parse_site_date('2015-09-15'),
  NULL,
  'unknown (oil discoveries referenced; crude quality not disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2015-09-15'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Tower Resources',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Dissoni Field (Rio del Rey Basin)',
  'Perenco (current basin operator); historically Total E&P Cameroun as operator in development phase',
  'Southwest Region (offshore, Rio del Rey Basin), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin)',
  4.55,
  8.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco (current basin operator); historically Total E&P Cameroun as operator in development phase',
  'JV/PSC with state participation',
  'Historically described as a 143 km² Dissoni Field with SNH selecting Total to drill development wells; later Perenco operates Rio del Rey assets under PSC with SNH',
  0,
  0,
  'barrels (initial 15,000 bbl/d start-up referenced historically; current not publicly stated)',
  25000000,
  'barrels (estimated cited in historical report for two wells)',
  parse_site_date('2011'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011'),
  20,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Lokele Area Oil Fields (exported as Lokele crude via FSO Massongo)',
  'Perenco',
  'Littoral/Southwest (offshore Cameroon, Douala Basin/Rio del Rey logistics), Cameroon',
  'Cameroon',
  'Littoral/Southwest (offshore Cameroon, Douala Basin/Rio del Rey logistics)',
  4.0,
  8.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Concession/JV with state participation',
  'Perenco operates and uses FSO Massongo for storage/export of Lokelé crude (and Kolé)',
  0,
  0,
  'barrels (field-level production not stated; crude grade specs published)',
  0,
  'barrels (unknown)',
  parse_site_date('1983'),
  NULL,
  'heavy sour crude (Lokele)',
  20.2,
  0.45,
  NULL,
  NULL,
  'USD',
  parse_site_date('2012-10'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['Massongo FSO oil terminal (offshore storage/loading)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Ebome Marine Concession',
  'Perenco',
  'Littoral Region (offshore, Douala Basin), Cameroon',
  'Cameroon',
  'Littoral Region (offshore, Douala Basin)',
  3.8,
  9.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Concession/JV with state participation',
  'Perenco operates Ebome Marine concession in partnership framework with SNH; crude stored on FSO La Lobe per operator information',
  0,
  0,
  'barrels (not publicly stated)',
  0,
  'barrels (unknown)',
  parse_site_date('1990s'),
  NULL,
  'unknown (Ebome crude grade not specified in retrieved sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['FSO La Lobe (storage/loading for Ebome crude)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Moudi Concession (Mudi)',
  'Perenco',
  'Littoral Region (offshore Cameroon), Cameroon',
  'Cameroon',
  'Littoral Region (offshore Cameroon)',
  3.9,
  9.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Concession/JV with state participation',
  'Perenco entered Cameroon in 1993 by acquiring Moudi concession in association with SNH',
  0,
  0,
  'barrels (not publicly stated)',
  0,
  'barrels (unknown)',
  parse_site_date('1993'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1993'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY['Douala area port logistics (not specifically stated for Moudi)'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
),
(
  'Etinde Permit (formerly Block 7)',
  'New Age Ltd. (operator as reported in partner listing)',
  'Southwest Region (offshore, Rio del Rey Basin shallow water), Cameroon',
  'Cameroon',
  'Southwest Region (offshore, Rio del Rey Basin shallow water)',
  3.5,
  9.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'New Age Ltd. (operator as reported in partner listing)',
  'Permit/PSC with state participation',
  'Participants reported: New Age Ltd. 30% (operator), Lukoil 30%, EurOil/Bowleven 20%, SNH 20%; Perenco agreed to acquire operatorship/interest per 2022 agreement mention',
  0,
  0,
  'barrels (permit/field production not stated)',
  0,
  'barrels (unknown)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-06'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'NewAge',
  '{"source": "Cameroon_all_sites.json", "generated_date": "2026-01-21 21:51:57"}' ::JSONB
)
;


-- ============================================
-- STEP 6: VERIFICATION
-- ============================================

SELECT COUNT(*) as total_cameroon_sites, 
       COUNT(CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN 1 END) as sites_with_coordinates,
       COUNT(CASE WHEN operational_status = 'active' THEN 1 END) as active_sites,
       COUNT(CASE WHEN operational_status != 'active' THEN 1 END) as inactive_sites
FROM public.commodity_locations 
WHERE country = 'Cameroon';
