-- ============================================
-- CHAD OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T15:51:57.342500
-- Total sites: 22
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- Make latitude/longitude nullable
ALTER TABLE public.commodity_locations
  ALTER COLUMN latitude DROP NOT NULL,
  ALTER COLUMN longitude DROP NOT NULL;

-- ============================================
-- STEP 2: HELPER FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION parse_site_date(date_text TEXT) RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' OR date_text = 'unknown' OR date_text ILIKE '%unknown%' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================


INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('CNPC', 'producer', 'China', ARRAY['Crude Oil', 'Natural Gas']),
  ('Perenco', 'producer', 'France', ARRAY['Crude Oil', 'Natural Gas']),
  ('SHT', 'producer', 'Chad', ARRAY['Crude Oil', 'Natural Gas'])

ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;


-- ============================================
-- STEP 4: DELETE EXISTING CHAD DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Chad';

-- ============================================
-- STEP 5: INSERT CHAD SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Komé Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (Nya Department / Komé area), Chad',
  'Chad',
  'Logone Oriental (Nya Department / Komé area)',
  8.5428,
  16.7806,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Historically developed/operated by Esso consortium (ExxonMobil/Esso 40%, Petronas 35%, Chevron 25%); after 2022-2023 asset transfers/nationalization, SHT became operator/owner of upstream interests; some partner interests previously attributed to Petronas in legacy structure.',
  282500,
  3390000,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2004'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)', 'Komé gathering system / Central Treatment Facility (CTF) and feeder lines'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Miandoum Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (Doba area), Chad',
  'Chad',
  'Logone Oriental (Doba area)',
  8.4946,
  16.5225,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'SHT listed as operator; ownership reported (for some reporting years) as SHT 65% / Petronas 35% in public datasets; upstream interests affected by 2023 nationalization and 2023 Petronas sale to SHT.',
  444000,
  5328000,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2003-07'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)', 'Miandoum Gathering Station (feeds export system via Komé area facilities)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Bolobo Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (Doba area), Chad',
  'Chad',
  'Logone Oriental (Doba area)',
  8.4244,
  16.0639,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Public dataset reporting includes SHT 65% / Petronas 35% (reported for some years); field part of Doba Oil Project; upstream interests affected by 2023 nationalization and 2023 Petronas sale to SHT.',
  281600,
  3379200,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2004'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Nya Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (near Miandoum), Chad',
  'Chad',
  'Logone Oriental (near Miandoum)',
  8.5,
  16.55,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Satellite field produced through Miandoum Gathering Station; part of Doba Oil Project; post-2022/2023 ownership transitioned toward SHT following asset sales/nationalization.',
  0,
  0,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2005'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Miandoum Gathering Station connection', 'Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Moundouli Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (west of Miandoum gathering station), Chad',
  'Chad',
  'Logone Oriental (west of Miandoum gathering station)',
  8.45,
  16.45,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Developed as a satellite field tied back by gathering line to Miandoum Gathering Station; part of Doba Oil Project; post-2022/2023 ownership transitioned toward SHT following asset sales/nationalization.',
  0,
  0,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2006-03'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Moundouli–Miandoum gathering line (tie-back)', 'Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Maikeri Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (Doba Basin), Chad',
  'Chad',
  'Logone Oriental (Doba Basin)',
  8.48,
  16.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Part of Doba Oil Project group of producing fields referenced in nationalization and project reporting; operated by SHT per industry datasets.',
  0,
  0,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2007'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Timbre Oil Field (Doba Oil Project)',
  'Société des Hydrocarbures du Tchad (SHT)',
  'Logone Oriental (Doba Basin), Chad',
  'Chad',
  'Logone Oriental (Doba Basin)',
  8.52,
  16.65,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Société des Hydrocarbures du Tchad (SHT)',
  'State-owned / JV (legacy consortium interests)',
  'Identified as producing field within Doba Oil Project portfolio impacted by 2022 sale attempt and 2023 nationalization; operated by SHT per public reporting.',
  0,
  0,
  'barrels (oil)',
  142000000,
  'barrels (2P, Doba Oil Project fields combined; field-level not publicly broken out)',
  parse_site_date('2008'),
  NULL,
  'heavy (Doba Blend)',
  21.1,
  0.1,
  NULL,
  407000000,
  'USD',
  parse_site_date('2022-12'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'SHT',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Mangara Oil Field (Doba Basin)',
  'Perenco',
  'Logone Oriental / Moyen-Chari area (southern Chad, Doba Basin), Chad',
  'Chad',
  'Logone Oriental / Moyen-Chari area (southern Chad, Doba Basin)',
  8.6,
  16.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Private (Perenco) / JV with state partner',
  'Perenco became sole owner of PetroChad Mangara (PCM) after acquiring Glencore’s upstream interests (June 2022). Operations coordinated with Société des Hydrocarbures du Tchad (SHT) and the Ministry of Hydrocarbons.',
  270000,
  3240000,
  'barrels (oil, combined estimate for Mangara+Badila; field-level split not publicly disclosed)',
  0,
  'barrels (not publicly disclosed at field level in retrieved sources)',
  parse_site_date('2014'),
  NULL,
  'unknown (not found in retrieved sources; Doba Basin crudes often marketed/exported via Chad–Cameroon system)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-06'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)', 'Doba oil pipeline/export system (as referenced in operator communications)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Badila Oil Field (Doba Basin)',
  'Perenco',
  'Logone Oriental / Moyen-Chari area (southern Chad, Doba Basin), Chad',
  'Chad',
  'Logone Oriental / Moyen-Chari area (southern Chad, Doba Basin)',
  8.58,
  16.38,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Private (Perenco) / JV with state partner',
  'Perenco acquired Glencore’s Chad upstream interests and became ultimate sole owner of PetroChad Mangara (PCM) in June 2022; PCM operates Badila/Mangara/Krim with coordination with SHT and the Ministry of Hydrocarbons; as of Dec 2025, Perenco reports combined production from Badila and Mangara above 18,000 bopd.',
  270000,
  3240000,
  'barrels (oil, combined estimate for Badila+Mangara; operator reports combined >18,000 bopd as of Dec 2025)',
  0,
  'barrels (not publicly disclosed at field level in retrieved sources)',
  parse_site_date('2014'),
  NULL,
  'unknown (not found in retrieved sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-06'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)', 'Doba oil pipeline/export system (as referenced in operator communications)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Krim Oil Field (Doba Basin)',
  'Perenco',
  'Southern Chad (Doba Basin), Chad',
  'Chad',
  'Southern Chad (Doba Basin)',
  8.55,
  16.35,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Perenco',
  'Private (Perenco) / JV with state partner',
  'Krim described as an undeveloped/high-potential discovery operated by PCM (Perenco) in the Doba Basin; additional drilling campaign referenced for late 2025 and into 2026.',
  0,
  0,
  'barrels (oil)',
  0,
  'barrels (not publicly disclosed at field level in retrieved sources)',
  parse_site_date('2026'),
  NULL,
  'unknown (not found in retrieved sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-06'),
  NULL,
  ARRAY['Chad–Cameroon Export Pipeline (TOTCO/COTCO system)'],
  ARRAY['Kribi Marine Terminal (FSO Komé-Kribi 1), Cameroon'],
  ARRAY[]::TEXT[],
  'Perenco',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Ronier Oilfield (Bongor Basin, Block H/Permit H)',
  'CNPC',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area), Chad',
  'Chad',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area)',
  10.2,
  15.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'PSC / state–foreign partnership (exact equity not consistently disclosed publicly)',
  'Field is part of Block H (Permit H) in Bongor Basin operated by CNPC/CNODC with participation by Chad state entities (SHT) referenced in multiple public descriptions of Block H/Djermaya integrated project; specific field-level working interests not reliably disclosed in accessible public sources.',
  450000,
  5475000,
  'barrels (bbl)',
  800000000,
  'barrels (OOIP potential estimate for Block H; field-level remaining reserves not publicly disclosed)',
  parse_site_date('2007'),
  NULL,
  'crude oil (type not consistently published; generally described as high-quality/light in some industry commentary for nearby discoveries)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Mimosa Oilfield (Bongor Basin, Block H/Permit H)',
  'CNPC',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area), Chad',
  'Chad',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area)',
  10.18,
  15.82,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'PSC / state–foreign partnership (exact equity not consistently disclosed publicly)',
  'Mimosa-1 was CNPC’s first exploration well on Block H/Permit H and is cited as producing along with Ronier under CNODC/CNPC operations; field-level equity and PSC term length not reliably disclosed in accessible public sources.',
  0,
  0,
  'barrels (bbl)',
  800000000,
  'barrels (OOIP potential estimate for Block H; field-level remaining reserves not publicly disclosed)',
  parse_site_date('2007'),
  NULL,
  'crude oil (type not consistently published)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Baobab Oilfield (Bongor Basin, Block H/Permit H)',
  'CNPC International',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area), Chad',
  'Chad',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area)',
  10.15,
  15.85,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International',
  'State–foreign partnership / JV participation reported (CNPC + SHT)',
  'Public market/industry summaries report Baobab as operated by CNPC International with ownership by CNPC and Société des Hydrocarbures du Tchad (SHT). Exact percentages not consistently available in open sources.',
  1507200,
  18337600,
  'barrels (bbl)',
  119470000,
  'barrels (recoverable, remaining cited in industry market summaries)',
  parse_site_date('2007'),
  NULL,
  'crude oil (type not consistently published)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Kubla Oil-bearing Structure / Field (Bongor Basin, Block H/Permit H)',
  'CNPC',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area), Chad',
  'Chad',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area)',
  10.12,
  15.88,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'PSC / state–foreign partnership (exact equity not consistently disclosed publicly)',
  'Peer-reviewed reservoir literature and CNPC Block H descriptions reference Kubla as one of the oil-bearing structures discovered/defined in the mid-north Bongor Basin and developed under Block H; field-level equity, production and reserves not publicly disclosed.',
  0,
  0,
  'barrels (bbl)',
  800000000,
  'barrels (OOIP potential estimate for Block H; field-level remaining reserves not publicly disclosed)',
  parse_site_date('2007'),
  NULL,
  'crude oil (type not consistently published)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Cailcedra Oil-bearing Structure / Field (Bongor Basin, Block H/Permit H)',
  'CNPC',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area), Chad',
  'Chad',
  'Chari-Baguirmi / Mayo-Kebbi Est (Bongor Basin area)',
  10.1,
  15.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'PSC / state–foreign partnership (exact equity not consistently disclosed publicly)',
  'Peer-reviewed reservoir literature identifies Cailcedra as one of the oil-bearing structures discovered/defined in the mid-north Bongor Basin, within the CNPC-operated Block H development context; field-level equity, production and reserves not publicly disclosed.',
  0,
  0,
  'barrels (bbl)',
  800000000,
  'barrels (OOIP potential estimate for Block H; field-level remaining reserves not publicly disclosed)',
  parse_site_date('2007'),
  NULL,
  'crude oil (type not consistently published)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Koudalwa Oil Field (Bongor Basin source for Djermaya refinery pipeline)',
  'CNPC',
  'Chari-Baguirmi (reported), Chad',
  'Chad',
  'Chari-Baguirmi (reported)',
  10.25,
  15.75,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'State–foreign partnership (upstream not consistently disclosed publicly)',
  'SEC filings and project trackers describe a 300 km pipeline constructed to transport crude from Koudalwa field to the Djermaya refinery; upstream working interests and field-level ownership shares not reliably disclosed in accessible public sources.',
  0,
  0,
  'barrels (bbl)',
  800000000,
  'barrels (OOIP potential estimate for Block H / Bongor integrated project; field-level remaining reserves not publicly disclosed)',
  parse_site_date('2011'),
  NULL,
  'crude oil (type not consistently published)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2011-01-01'),
  NULL,
  ARRAY['Ronier–Djermaya crude oil pipeline (~300–311 km; operating; start year reported 2011)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Baobab (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.15,
  15.85,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium includes CNPC International (Chad) and Cliveden; SHT participates. For several Bongor exploitation permits cited: CNPC 45%, Cliveden 45%, SHT 10% (field/permit-specific).',
  1318767.75,
  15825213,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2007'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Daniela (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.22,
  15.78,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium: CNPC International (Chad) + Cliveden; SHT participates. Field-level shares vary by permit; sources show Bongor exploitation permits with CNPC/Cliveden/SHT participation (e.g., CNPC 45%, Cliveden 45%, SHT 10% for certain permits).',
  646972.4166666666,
  7763669,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2018-01-01'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2018-01-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Raphia (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.17,
  15.83,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium: CNPC International (Chad) + Cliveden; SHT participates. Field-level shares vary by permit; sources show Bongor exploitation permits with CNPC/Cliveden/SHT participation (e.g., CNPC 45%, Cliveden 45%, SHT 10% for certain permits).',
  206163.83333333334,
  2473966,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2018-08-01'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2018-08-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Prosopis (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.14,
  15.86,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium: CNPC International (Chad) + Cliveden; SHT participates. Permit signature cited for Prosopis: 29/05/2013 (per EITI scoping report excerpt), and OGJ reported Prosopis-1 test rates; production reported for 2018.',
  71838.25,
  862059,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2009-05-29'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Ronier (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.2,
  15.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium: CNPC International (Chad) + Cliveden; SHT participates. EITI scoping report excerpt lists Ronier among exploitation permits and indicates CNPC/Cliveden/SHT participation structure for Bongor fields. Petroleum Africa notes Ronier-1 discovery (2006) and commercial production (2007).',
  70692.58333333333,
  848311,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2007'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
),
(
  'Mimosa (Bongor Basin, Block H)',
  'CNPC International (Chad)',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area), Chad',
  'Chad',
  'Moyen-Chari / Chari-Baguirmi (Doseo/Bongor petroleum province - Block H area)',
  10.18,
  15.82,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC International (Chad)',
  'PSC / consortium (JV)',
  'Block H consortium: CNPC International (Chad) + Cliveden; SHT participates. EITI scoping report excerpt lists Mimosa among exploitation permits and indicates CNPC/Cliveden/SHT participation structure for Bongor fields. Petroleum Africa notes Mimosa-1 (2004) and commercial production (2007).',
  66884.41666666667,
  802613,
  'barrels (bbl)',
  0,
  'bbl (not publicly disclosed per field in available sources)',
  parse_site_date('2007'),
  NULL,
  'unknown (not disclosed per field in accessible public sources)',
  NULL,
  NULL,
  NULL,
  202500000,
  'USD',
  parse_site_date('2007-01-01'),
  NULL,
  ARRAY['CNPC crude pipeline to Djarmaya/N''Djamena refinery (approx. 300 km, Koudalwa-to-Djarmaya system referenced for CNPC crude evacuation)', 'Chad–Cameroon crude oil export pipeline (COTCo/Cameroon Oil Transportation Company system)'],
  ARRAY['Kribi (FSO/terminal area, Cameroon)'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "Chad_all_sites.json", "generated_date": "2026-01-21 21:54:38"}' ::JSONB
)
;


-- ============================================
-- STEP 6: VERIFICATION
-- ============================================

SELECT COUNT(*) as total_chad_sites, 
       COUNT(CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN 1 END) as sites_with_coordinates,
       COUNT(CASE WHEN operational_status = 'active' THEN 1 END) as active_sites,
       COUNT(CASE WHEN operational_status != 'active' THEN 1 END) as inactive_sites
FROM public.commodity_locations 
WHERE country = 'Chad';
