-- ============================================
-- CHINA OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T15:51:57.344818
-- Total sites: 65
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- Make latitude/longitude nullable
ALTER TABLE public.commodity_locations
  ALTER COLUMN latitude DROP NOT NULL,
  ALTER COLUMN longitude DROP NOT NULL;

-- ============================================
-- STEP 2: HELPER FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION parse_site_date(date_text TEXT) RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' OR date_text = 'unknown' OR date_text ILIKE '%unknown%' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================


INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('CNOOC', 'producer', 'China', ARRAY['Crude Oil', 'Natural Gas']),
  ('CNPC', 'producer', 'China', ARRAY['Crude Oil', 'Natural Gas']),
  ('Chevron', 'producer', 'United States', ARRAY['Crude Oil', 'Natural Gas']),
  ('Shell', 'producer', 'United Kingdom', ARRAY['Crude Oil', 'Natural Gas']),
  ('Sinopec', 'producer', 'China', ARRAY['Crude Oil', 'Natural Gas'])

ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;


-- ============================================
-- STEP 4: DELETE EXISTING CHINA DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'China';

-- ============================================
-- STEP 5: INSERT CHINA SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Daqing Oil Field (大庆油田)',
  'CNPC',
  'Heilongjiang (黑龙江省), Daqing City (大庆市), China',
  'China',
  'Heilongjiang (黑龙江省), Daqing City (大庆市)',
  46.59,
  125.02,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'CNPC/PetroChina wholly-owned operating subsidiary (Daqing Oilfield Co. Ltd.)',
  24600000,
  295200000,
  'barrels (bbl)',
  3600000000,
  'bbl (recoverable remaining estimate)',
  parse_site_date('1960'),
  NULL,
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian (Bohai Gulf)'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY['Northeast China rail network (historic crude-by-rail)'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Saertu Oilfield (萨尔图油田)',
  'CNPC',
  'Heilongjiang, Daqing City (core Daqing Changyuan area), China',
  'China',
  'Heilongjiang, Daqing City (core Daqing Changyuan area)',
  46.6,
  125.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by Daqing Oilfield Co. Ltd. under CNPC/PetroChina; no public PSC/JV terms for core conventional blocks found',
  0,
  0,
  'unknown (field-level breakdown not consistently published)',
  0,
  'unknown',
  parse_site_date('1960'),
  NULL,
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Xingshugang Oilfield (杏树岗油田)',
  'CNPC',
  'Heilongjiang, Daqing City (Changyuan area), China',
  'China',
  'Heilongjiang, Daqing City (Changyuan area)',
  46.55,
  125.05,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by Daqing Oilfield Co. Ltd.; literature places it within the central Daqing/Changyuan development area',
  0,
  0,
  'unknown (field-level breakdown not consistently published)',
  0,
  'unknown',
  parse_site_date('1960'),
  NULL,
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Lamadian Oilfield (喇嘛甸油田)',
  'CNPC',
  'Heilongjiang, Daqing City, Ranghulu District (让胡路区) / Lamadian area, China',
  'China',
  'Heilongjiang, Daqing City, Ranghulu District (让胡路区) / Lamadian area',
  46.731,
  124.867,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by Daqing Oilfield Co. Ltd.; Lamadian structure noted in technical literature as having original gas cap',
  0,
  0,
  'unknown (field-level breakdown not consistently published)',
  0,
  'unknown',
  parse_site_date('1960'),
  NULL,
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Chaoyanggou Oilfield (朝阳沟油田)',
  'CNPC',
  'Heilongjiang, Daqing City (Daqing Oilfield sub-field), China',
  'China',
  'Heilongjiang, Daqing City (Daqing Oilfield sub-field)',
  46.5,
  125.1,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Identified as one of the constituent oil/gas fields within the Daqing Oilfield complex',
  0,
  0,
  'unknown (field-level breakdown not consistently published)',
  0,
  'unknown',
  parse_site_date('1960'),
  NULL,
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Gulong Shale Oil Block / Gulong Shale Oil (古龙页岩油区块)',
  'CNPC',
  'Heilongjiang, Daqing City (Songliao Basin; within Daqing Oilfield area), China',
  'China',
  'Heilongjiang, Daqing City (Songliao Basin; within Daqing Oilfield area)',
  46.4,
  124.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'CNPC/PetroChina (Daqing Oilfield) national lacustrine shale oil demonstration zone; no foreign PSC terms found',
  0,
  0,
  'unknown (reported in tonnes; site reported >1 million tonnes/year in 2025)',
  0,
  'unknown',
  parse_site_date('2021'),
  NULL,
  'shale oil (lacustrine)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Daqing–Qinhuangdao crude oil pipeline ("August 3rd Project")', 'Daqing crude pipelines to Port of Dalian'],
  ARRAY['Port of Dalian', 'Port of Qinhuangdao'],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Songji-3 / Daqing Inaugural Oil Well (松基三井)',
  'Ministry-era predecessor organizations; later Daqing Oilfield system',
  'Heilongjiang, Daqing City, Datong District (大同区), Gaotaizi Town (高台子镇), China',
  'China',
  'Heilongjiang, Daqing City, Datong District (大同区), Gaotaizi Town (高台子镇)',
  46.0,
  124.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'inactive',
  'Ministry-era predecessor organizations; later Daqing Oilfield system',
  'state-owned',
  'Historic state-led development well; now a protected heritage site',
  0,
  0,
  'unknown (historic well; cumulative reported in tonnes)',
  0,
  'unknown',
  parse_site_date('1958-09-26'),
  parse_site_date('1988-07-25'),
  'paraffinic, low-sulfur crude (typically medium)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Shengli Oil Field (overall complex)',
  'Sinopec Shengli Oilfield Company (Shengli Petroleum Administration Bureau)',
  'Shandong (primarily Dongying; Yellow River Delta / Bohai Bay area), China',
  'China',
  'Shandong (primarily Dongying; Yellow River Delta / Bohai Bay area)',
  37.45,
  118.67,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Shengli Oilfield Company (Shengli Petroleum Administration Bureau)',
  'state-owned',
  'Wholly state-owned via Sinopec Group (China Petrochemical Corporation) subsidiaries/branches (reported as Shengli Oilfield Company / Shengli Petroleum Administrative Bureau).',
  19500000,
  237250000,
  'barrels (crude oil, approx; derived from ~650,000 bbl/d cited)',
  38200000000,
  'barrels (OOIP estimate; converted from ~5.21 billion tonnes cited for original oil in place; remaining/residual not publicly broken out at complex level)',
  parse_site_date('1964-01-25'),
  NULL,
  'mixed (varied across many reservoirs; includes viscous/high water-cut crudes; some heavy oil offshore)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shengli-to-Qingdao crude oil pipeline (completed 1974; to ports near Qingdao)', 'Shengli–Renqiu–Nanjing crude pipeline (approx. 1,100 km; completed 1979; cited as connecting Shengli & Renqiu to Nanjing)'],
  ARRAY['Qingdao Port (export/shipping via pipeline to ports near Qingdao)'],
  ARRAY['Dongying area rail connections (regional; specific crude-by-rail routes not consistently disclosed publicly)'],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Chengdao Offshore Oilfield (Shengli offshore; Chengdao No.1 Central Platform hub)',
  'Sinopec Shengli Oilfield (Shengli offshore operations)',
  'Shandong (Bohai Bay offshore, near Dongying), China',
  'China',
  'Shandong (Bohai Bay offshore, near Dongying)',
  38.15,
  118.95,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Shengli Oilfield (Shengli offshore operations)',
  'state-owned',
  'Operated by Sinopec Shengli Oilfield; exact platform/field JV/asset split not publicly detailed in the cited open sources.',
  0,
  0,
  'barrels (site-level current production not consistently disclosed in public sources)',
  0,
  'barrels (not publicly quantified in cited open sources)',
  parse_site_date('1990-01-01'),
  NULL,
  'includes heavy oil (offshore heavy oil wells referenced in Shengli offshore reporting)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore ''production platform + onshore terminal'' crude transfer system (Shengli offshore model; specific line names not consistently published in open sources)'],
  ARRAY['Dongying-area Bohai Bay terminals (specific terminal/port names not consistently published in open sources)'],
  ARRAY[]::TEXT[],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Chengbei Offshore Heavy Oil Area (e.g., Chengbei 208 well group within Shengli offshore)',
  'Sinopec Shengli Oilfield (offshore operations)',
  'Shandong (Bohai Bay offshore, near Dongying), China',
  'China',
  'Shandong (Bohai Bay offshore, near Dongying)',
  38.2,
  119.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Shengli Oilfield (offshore operations)',
  'state-owned',
  'Operated by Sinopec Shengli Oilfield; no foreign equity disclosed in cited open sources for this offshore area.',
  0,
  0,
  'barrels (public reporting cites tonnes/day for specific wells; field-level totals not disclosed)',
  0,
  'barrels (not publicly quantified in cited open sources)',
  parse_site_date('1996-01-01'),
  NULL,
  'heavy oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore-to-onshore gathering/export system (not consistently named in open sources)'],
  ARRAY['Dongying-area Bohai Bay terminals (not consistently named in open sources)'],
  ARRAY[]::TEXT[],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jiyang Shale Oil National Demonstration Zone (Shengli; Jiyang shale oilfield)',
  'Sinopec Shengli Oilfield (Sinopec Group)',
  'Shandong (Jiyang area; reported in Gaoqing County context for certified reserves announcement), China',
  'China',
  'Shandong (Jiyang area; reported in Gaoqing County context for certified reserves announcement)',
  37.17,
  117.83,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Shengli Oilfield (Sinopec Group)',
  'state-owned',
  'State-owned via Sinopec Group; certified proven geological reserves reported by Ministry of Natural Resources review process per Xinhua/People''s Daily/PRNewswire coverage.',
  0,
  0,
  'barrels (public reporting emphasizes reserves/resources; cumulative output >1 million tonnes; current rate not disclosed)',
  1018000000,
  'barrels (approx proven geological reserves; converted from >140 million tonnes reported as proven shale oil reserve; technically recoverable 11.3599 million tonnes not separately converted here)',
  parse_site_date('2021-01-01'),
  NULL,
  'shale oil (continental fault-lake basin; specific API/sulfur not disclosed in cited open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2025-03-24'),
  NULL,
  ARRAY['Local gathering systems to Shengli processing/transport network (not consistently named in open sources)'],
  ARRAY['Qingdao Port (via broader Shengli crude pipeline system; not uniquely attributable to shale zone)'],
  ARRAY[]::TEXT[],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Zhuangxi Buried Hill Oil Field (Shengli main producing area; Genting contract)',
  'Genting',
  'Shandong (Shengli main producing area; North Jiyang Depression, Bohai basin), China',
  'China',
  'Shandong (Shengli main producing area; North Jiyang Depression, Bohai basin)',
  37.7,
  118.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Genting',
  'PSC / contract with foreign operator',
  'Oil & Gas Journal reports Genting as operator and 100% interest holder in the Zhuangxi Buried Hill field contract signed with Sinopec in 1999; 20-year production period began 2002-10-01.',
  0,
  0,
  'barrels (public reporting cites historical tonnes/day and bo/d ranges rather than current)',
  0,
  'barrels (not publicly quantified in cited OGJ excerpt)',
  parse_site_date('2002-10-01'),
  NULL,
  'medium and light oil (fractured carbonates / granitic gneiss reservoirs)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1999-01-01'),
  20,
  ARRAY['Connected to Shengli regional crude gathering/transport systems (specific line names not provided in cited OGJ excerpt)'],
  ARRAY['Qingdao Port (via broader Shengli export pipeline system; not uniquely attributable)'],
  ARRAY[]::TEXT[],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Zhanhua Dong Block (Shengli area onshore PSC exploration block)',
  'Chevron Overseas Petroleum Ltd. (exploration PSC per OGJ)',
  'Shandong (Zhanhua area, near Bohai Bay; Shengli region), China',
  'China',
  'Shandong (Zhanhua area, near Bohai Bay; Shengli region)',
  37.7,
  118.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Chevron Overseas Petroleum Ltd. (exploration PSC per OGJ)',
  'PSC (exploration)',
  'Oil & Gas Journal reports Chevron signed a production-sharing contract in June 1997 with CNPC to explore the Zhan Hua Dong block (695 sq miles).',
  0,
  0,
  'barrels (exploration block; production not specified in cited open source excerpt)',
  0,
  'barrels (not publicly quantified in cited OGJ excerpt)',
  parse_site_date('1997-06-01'),
  NULL,
  'unknown (exploration focus on pre-Tertiary section per OGJ)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1997-06-01'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Chevron',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Shengli Oilfield Tuo 11 Well Area (Shengtuo/Shengli village historical high-rate well area)',
  'Sinopec Shengli Oil Production Plant (Shengli Oilfield)',
  'Shandong (Shengli Oil Zone / Dongying area context), China',
  'China',
  'Shandong (Shengli Oil Zone / Dongying area context)',
  37.45,
  118.67,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Shengli Oil Production Plant (Shengli Oilfield)',
  'state-owned',
  'Operated within Sinopec Shengli Oilfield organizational structure; reported as Shengli Oil Production Plant activity.',
  0,
  0,
  'barrels (single-well historical production reported in tonnes/day; not a field total)',
  0,
  'barrels (not disclosed)',
  parse_site_date('1965-01-25'),
  NULL,
  'unknown (legacy conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shengli regional gathering and trunk pipeline network'],
  ARRAY['Qingdao Port (via broader Shengli export pipeline system; not uniquely attributable)'],
  ARRAY[]::TEXT[],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Sulige Gas Complex (苏里格)',
  'CNPC',
  'Inner Mongolia (Ordos Basin; also spans parts of Shaanxi/Gansu/Ningxia via associated units), China',
  'China',
  'Inner Mongolia (Ordos Basin; also spans parts of Shaanxi/Gansu/Ningxia via associated units)',
  38.564,
  108.306,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Sulige Development Company (100%)',
  2500,
  30000,
  'million m³/y (natural gas)',
  299289.25,
  'million m³ (1P gas reserves; data year 2014)',
  parse_site_date('2006'),
  NULL,
  'natural gas (tight gas)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shaan-Jing Gas Pipeline (network; supplies from Jingbian/Changqing gas processing plant to Beijing/Tianjin)', 'Zhongwei-Jingbian Branch Pipeline (West–East Gas Pipeline interconnect)', 'Changqing Gas Field–Wuhai–Linhe Gas Pipeline (regional)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Changqing Oil Field / Changqing Oilfield (长庆油田)',
  'CNPC',
  'Shaanxi, Gansu, Ningxia, Inner Mongolia (Ordos Basin), China',
  'China',
  'Shaanxi, Gansu, Ningxia, Inner Mongolia (Ordos Basin)',
  37.5,
  108.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'CNPC',
  14160000,
  169920000,
  'bbl/y (crude oil; estimate derived from 472,000 bbl/d reported for field-level production)',
  7450,
  'million bbl (proved oil reserves; field-level compilation)',
  parse_site_date('1975'),
  NULL,
  'mixed (conventional + tight/shale)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shaan–Jing Gas Pipeline (Shaan-Jing 1; gas processing plant in Changqing gas field to Beijing)', 'Shaan-Jing parallel pipeline supplied from Sulige (via Yulin processing plant)', 'Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline', 'Zhongning–Yinchuan Oil Pipeline', 'Jing''an–Xianyang Oil Pipeline', 'Wuding Oil Pipeline', 'Jibai Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Qingcheng Shale Oil Field (庆城页岩油 / Qingcheng Oil Field)',
  'CNPC',
  'Gansu (Qingyang area, Ordos Basin), China',
  'China',
  'Gansu (Qingyang area, Ordos Basin)',
  36.5752,
  107.4443,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina/CNPC-operated Changqing Oilfield asset (100% PetroChina implied in Changqing structure; unit listed under Sulige complex)',
  0,
  0,
  'unknown (shale oil; field-level not publicly standardized)',
  0,
  'unknown',
  NULL,
  NULL,
  'shale oil (unconventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Heshui Shale Oil Field (合水页岩油)',
  'CNPC',
  'Gansu, China',
  'China',
  'Gansu',
  36.1175,
  108.6686,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  407500,
  4890000,
  'bbl/y (oil; data year 2023)',
  0,
  'unknown',
  parse_site_date('2023'),
  NULL,
  'shale oil (unconventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Jingma Oil Pipeline (Jing''an–Maling; connects Changqing network toward Gansu)', 'Zhongning–Lanzhou Oil Pipeline', 'Qingyang–Xianyang Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Xifeng Oil Field (西峰油田)',
  'CNPC',
  'Gansu, China',
  'China',
  'Gansu',
  36.2404,
  107.6109,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina/CNPC-operated Changqing Oilfield asset (listed under Sulige complex)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  NULL,
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Huaqing Oil Field (华庆油田)',
  'CNPC',
  'Gansu, China',
  'China',
  'Gansu',
  36.3,
  107.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  parse_site_date('2008'),
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  '环江 Oil Field (Huanjiang Oil Field)',
  'unknown',
  'Gansu, China',
  'China',
  'Gansu',
  36.957,
  107.0164,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'unknown',
  'state-owned',
  'Listed under Sulige complex; operator/owner not specified in the extracted field summary',
  0,
  0,
  'unknown',
  806.3,
  'million bbl (reserves; data year 2016)',
  NULL,
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Zhenbei Oil Field (镇北油田)',
  'CNPC',
  'Gansu, China',
  'China',
  'Gansu',
  37.0,
  107.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  parse_site_date('2006'),
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingyang–Xianyang Oil Pipeline', 'Zhongning–Lanzhou Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jing''an Oil Field (靖安油田)',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  38.0126,
  112.2033,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  2559167,
  30710000,
  'bbl/y (oil; data year 2010)',
  2199,
  'million bbl (1P oil reserves; data year 2019)',
  parse_site_date('1996'),
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Jing''an–Xianyang Oil Pipeline', 'Jingma Oil Pipeline (Jing''an–Maling)', 'Qingyang–Xianyang Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jiyuan Oil Field (姬塬油田)',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  37.2916,
  107.3466,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  1480.66,
  'million bbl (1P oil reserves; data year 2012)',
  parse_site_date('2007'),
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Jibai Oil Pipeline (Jiyuan, Dingbian → Baibao, Yan''an)', 'Jibai Oil Pipeline (capacity 1.5 mtpa)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Hujianshan Oil Field (胡尖山油田)',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  37.3056,
  108.2201,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown (historical points available; current not found)',
  0,
  'unknown (cumulative production reported in sources, remaining reserves not specified)',
  parse_site_date('2006'),
  NULL,
  'crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Wuding Oil Pipeline (Wuqi → Dingbian; Changqing export network)', 'Jibai Oil Pipeline', 'Jing''an–Xianyang Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Xin''anbian Tight Oil Field (新安边致密油)',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  37.4,
  108.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  parse_site_date('2015'),
  NULL,
  'tight oil (unconventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Wuding Oil Pipeline (Wuqi → Dingbian)', 'Jing''an–Xianyang Oil Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Changbei Tight I Gas Phase (长北致密气(一期))',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  38.0126,
  112.2033,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina (100%)',
  291.6666667,
  3500,
  'million m³/y (natural gas; data year 2017)',
  0,
  'unknown',
  parse_site_date('2007'),
  NULL,
  'tight gas (unconventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shaan-Jing Gas Pipeline network', 'Zhongwei-Jingbian Branch Pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Changbei Tight II Gas Phase (长北致密气(二期))',
  'Shell (China) Ltd',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  38.0126,
  112.2033,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Shell (China) Ltd',
  'JV',
  'PetroChina 51%; Shell (China) Ltd 49% (PSC/JV-style cooperation reported)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  NULL,
  NULL,
  'tight gas (unconventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shaan-Jing Gas Pipeline network (regional evacuation)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Shell',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Yichuan Gas Field (宜川气田)',
  'CNPC',
  'Shaanxi, China',
  'China',
  'Shaanxi',
  36.0,
  110.0,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  parse_site_date('2019'),
  NULL,
  'natural gas (conventional)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Shaan-Jing Gas Pipeline network (regional evacuation)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Qingshimao Gas Field (青石峁气田)',
  'CNPC',
  'Ningxia (Yanchi area, Ordos Basin), China',
  'China',
  'Ningxia (Yanchi area, Ordos Basin)',
  37.8,
  107.2,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'CNPC',
  'state-owned',
  'PetroChina Changqing Oilfield Company (100%)',
  0,
  0,
  'unknown',
  0,
  'unknown',
  parse_site_date('2022'),
  NULL,
  'natural gas (conventional/tight)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qingshimao Gas Field Qinggao Gas Pipeline (field trunk export; 1 bcm/y; 2024 start per network summary)', 'Changqing–Yinchuan Gas Pipeline (West–East Gas Pipeline 2 branch; regional)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Suizhong 36-1 Oilfield',
  'CNOOC',
  'Bohai Sea (Liaodong Bay / northern Bohai Bay), China',
  'China',
  'Bohai Sea (Liaodong Bay / northern Bohai Bay)',
  40.0,
  120.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated; equity/partners not clearly disclosed in cited public sources for SZ36-1 base field (separate Suizhong 36-1/Luda 5-2 Secondary Adjustment project is CNOOC-operated)',
  267000,
  3249100,
  'barrels (estimated from ~8,900 tonnes/day reported; converted using ~7.33 bbl/tonne; actual varies by density)',
  2190000000,
  'barrels (approx. from >300 million tonnes proven geological reserves reported; using ~7.33 bbl/tonne)',
  parse_site_date('1993'),
  NULL,
  'heavy crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Bohai oilfields subsea/offshore gathering network (field-specific line names not found in public sources reviewed)'],
  ARRAY['Tianjin (Binhai) industrial/receiving terminals for Bohai offshore crude (specific terminal/port link not found in sources reviewed)'],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Suizhong 36-1/Luda 5-2 Oilfield Secondary Adjustment and Development Project',
  'CNOOC',
  'Bohai Sea (Liaodong Bay), China',
  'China',
  'Bohai Sea (Liaodong Bay)',
  40.0,
  120.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in company announcement)',
  909000,
  11060000,
  'barrels (peak crude oil per day stated; annual/monthly derived from peak 30,300 bpd)',
  0,
  'barrels',
  parse_site_date('2024-02-05'),
  NULL,
  'crude oil (type not specified in CNOOC announcement for this project)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Uses adjacent producing projects to process/transport crude (specific pipeline names not disclosed in public announcement)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Suizhong 36-2 Oilfield (36-2 Block Development Project)',
  'CNOOC',
  'Bohai Sea (Liaodong Bay), China',
  'China',
  'Bohai Sea (Liaodong Bay)',
  40.05,
  120.55,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in company announcement)',
  291000,
  3538000,
  'barrels of oil equivalent (derived from peak 9,700 boe/d)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2024-12-23'),
  NULL,
  'light crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Relies on adjacent producing projects to process and transport crude (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Luda 6-2 Oilfield',
  'CNOOC',
  'Bohai Sea (Liaodong Bay), China',
  'China',
  'Bohai Sea (Liaodong Bay)',
  39.8,
  121.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC Limited holds 100% interest and is operator',
  300000,
  3650000,
  'barrels (derived from peak 10,000 bpd crude oil)',
  0,
  'barrels',
  parse_site_date('2021-08-23'),
  NULL,
  'crude oil (API not stated in announcement)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied into Suizhong 36-1 existing processing facilities (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Luda 5-2 North Oilfield (Phase II Development Project)',
  'CNOOC',
  'Bohai Sea (central Bohai; cited as ~30 m water depth), China',
  'China',
  'Bohai Sea (central Bohai; cited as ~30 m water depth)',
  39.9,
  120.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in the cited announcement)',
  201000,
  2446000,
  'barrels of oil equivalent (derived from peak 6,700 boe/d)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2025-02-21'),
  NULL,
  'heavy crude (super heavy oil thermal recovery)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore gathering/transport via Bohai network (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Penglai 19-3 Oilfield (Bohai Penglai / Block 11/05 PSC)',
  'CNOOC',
  'Bohai Sea (southern Bohai Sea), China',
  'China',
  'Bohai Sea (southern Bohai Sea)',
  38.5,
  120.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'PSC / JV (state-owned + foreign partner)',
  'CNOOC 51% / ConocoPhillips China 49% (PSC signed Dec 1994 for Block 11/05); operatorship transferred to CNOOC July 2014',
  0,
  0,
  'barrels (field-wide current production not found in public sources reviewed)',
  0,
  'barrels',
  parse_site_date('2002-12'),
  NULL,
  'crude oil (type varies across phases; not consistently stated in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2014-07'),
  NULL,
  ARRAY['Offshore platforms tied to Ming Zhu FPSO (FPSO named in public sources; specific export pipeline/landing terminal names not found in sources reviewed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Penglai 19-3 Oilfield Area 5/10 Development Project',
  'CNOOC',
  'Bohai Sea (south-central Bohai Sea), China',
  'China',
  'Bohai Sea (south-central Bohai Sea)',
  38.5,
  120.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'PSC / JV (state-owned + foreign partner)',
  'CNOOC Limited 51% and operator; ConocoPhillips China 49%',
  894000,
  10877000,
  'barrels (derived from peak 29,800 bpd crude oil)',
  0,
  'barrels',
  parse_site_date('2023-10-27'),
  NULL,
  'crude oil (API not stated in announcement)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied into existing Penglai 19-3 processing/export system (specific pipeline names not disclosed in announcement)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Penglai 19-3 Oilfield Area 4 Adjustment / Penglai 19-9 Oilfield Phase II Project',
  'CNOOC',
  'Bohai Sea, China',
  'China',
  'Bohai Sea',
  38.5,
  120.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'PSC / JV (state-owned + foreign partner)',
  'CNOOC Limited 51% and operator; ConocoPhillips China 49%',
  470430,
  5723570,
  'barrels (derived from peak 15,681 bpd crude oil)',
  0,
  'barrels',
  parse_site_date('2020-05-21'),
  NULL,
  'crude oil (API not stated in announcement)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Utilizes existing processing facilities of Penglai 19-3 (specific export pipeline/terminal not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Qinhuangdao 32-6 Oilfield (QHD 32-6)',
  'CNOOC',
  'Bohai Bay (central-northern Bohai Bay; ~130 km from Tianjin), China',
  'China',
  'Bohai Bay (central-northern Bohai Bay; ~130 km from Tianjin)',
  39.5,
  119.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'JV',
  'Initial ownership reported: CNOOC 51%, Texaco 24.5%, BP 24.5%; later comprehensive adjustment project reported: CNOOC 75.5% operator, Chevron China Energy 24.5%',
  1950000,
  23725000,
  'barrels (derived from designed peak capacity >65,000 bpd)',
  103000000,
  'barrels (recoverable, net to CNOOC as reported in 2001)',
  parse_site_date('2001-10-16'),
  NULL,
  'crude oil (type not stated in cited releases)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Field development included SPM and FPSO (specific export pipeline/terminal names not found in sources reviewed)'],
  ARRAY['Tianjin (nearest major coastal city referenced; specific receiving port/terminal not stated)'],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Caofeidian 6-4 Oilfield',
  'CNOOC',
  'Bohai Sea (western Bohai / Midwest Bohai), China',
  'China',
  'Bohai Sea (western Bohai / Midwest Bohai)',
  39.2,
  118.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in the cited press release)',
  450000,
  5475000,
  'barrels (derived from peak 15,000 bpd crude oil)',
  0,
  'barrels',
  parse_site_date('2021-03-15'),
  NULL,
  'crude oil (property not quantified in cited 2021 release)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Utilizes existing processing facilities of Nanpu 35-2 and Qinhuangdao 32-6 (tie-back; pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Caofeidian 6-4 Oilfield Comprehensive Adjustment Project',
  'CNOOC',
  'Bohai Sea (western Bohai Sea), China',
  'China',
  'Bohai Sea (western Bohai Sea)',
  39.2,
  118.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in announcement)',
  330000,
  4015000,
  'barrels of oil equivalent (derived from peak 11,000 boe/d)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2025-03-17'),
  NULL,
  'light crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Leverages adjacent existing facilities for development (specific pipeline/terminal names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Bozhong 19-2 Oilfield (Development Project)',
  'CNOOC',
  'Bohai Sea (central Bohai Bay), China',
  'China',
  'Bohai Sea (central Bohai Bay)',
  38.8,
  119.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in announcement)',
  564000,
  6862000,
  'barrels (derived from peak 18,800 bpd crude oil)',
  0,
  'barrels',
  parse_site_date('2024-10-08'),
  NULL,
  'heavy crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore processing platform + unmanned wellhead platforms; export via Bohai network (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Bozhong 26-6 Oilfield (Development Project Phase I)',
  'CNOOC',
  'Bohai Bay (central Bohai Bay), China',
  'China',
  'Bohai Bay (central Bohai Bay)',
  38.6,
  119.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in announcement)',
  669000,
  8139500,
  'barrels of oil equivalent (derived from peak 22,300 boe/d)',
  1258000000,
  'barrels of oil equivalent (approx. in-place; derived from >200 million cubic meters oil+gas in-place reported; rough conversion 1 m3 ~ 6.2898 bbl)',
  parse_site_date('2025-02-07'),
  NULL,
  'light crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore facilities; CCUS reinjection; export via Bohai network (specific pipeline/terminal names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Kenli 10-2 Oilfield (Development Project Phase I)',
  'CNOOC',
  'Bohai Sea (southern Bohai Sea), China',
  'China',
  'Bohai Sea (southern Bohai Sea)',
  38.0,
  118.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in CNOOC announcement; some secondary reporting states 100% stake)',
  582000,
  7081000,
  'barrels of oil equivalent (derived from peak 19,400 boe/d)',
  0,
  'barrels',
  parse_site_date('2025-07-22'),
  NULL,
  'heavy crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore processing/export via adjacent existing facilities (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Bozhong 19-6 Condensate Gas Field (Pilot Area Development Project)',
  'CNOOC',
  'Bohai Sea (central Bohai), China',
  'China',
  'Bohai Sea (central Bohai)',
  38.7,
  119.3,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC Limited holds 100% working interest and is operator',
  171600,
  2087800,
  'barrels condensate (derived from peak 5,720 bpd condensate; gas not converted here)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2020-10-22'),
  NULL,
  'condensate + natural gas',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Uses existing processing facilities of Bozhong 13-1 oilfield (tie-back)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Bozhong 19-6 Condensate Gas Field (Phase I Development Project)',
  'CNOOC',
  'Bohai Sea (central Bohai Sea), China',
  'China',
  'Bohai Sea (central Bohai Sea)',
  38.7,
  119.3,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (partners not stated in cited announcement)',
  1110000,
  13505000,
  'barrels of oil equivalent (derived from peak 37,000 boe/d)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2023-11-13'),
  NULL,
  'condensate + natural gas',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Includes gas process terminal; onshore power terminal referenced for Bozhong-Kenli onshore power project (specific export pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Bozhong 19-6 Gas Field 13-2 Block 5 Well Site Development Project',
  'CNOOC',
  'Bohai Sea (central Bohai Sea), China',
  'China',
  'Bohai Sea (central Bohai Sea)',
  38.7,
  119.3,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC Limited holds 100% interest and is operator',
  174000,
  2117000,
  'barrels of oil equivalent (derived from peak 5,800 boe/d)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2024-05-07'),
  NULL,
  'gas + liquids (boe; not further specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Wellhead platform tied into Bozhong 19-6 system (specific pipeline names not disclosed)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Qinhuangdao 29-6 Oilfield (Discovery; pre-development)',
  'CNOOC',
  'Bohai Sea (central Bohai Sea), China',
  'China',
  'Bohai Sea (central Bohai Sea)',
  39.3,
  119.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNOOC',
  'state-owned',
  'CNOOC-operated (discovery announcement; partners not stated)',
  76800,
  934400,
  'barrels (well test rate reported ~2,560 bpd; not field production)',
  0,
  'barrels of oil equivalent',
  parse_site_date('2025-12-24'),
  NULL,
  'medium-heavy crude',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2025-12-24'),
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNOOC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Fuman Oilfield (富满油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Aksu Prefecture, Shaya County), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Aksu Prefecture, Shaya County)',
  40.4,
  83.6,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by PetroChina (CNPC) Tarim Oilfield; no foreign JV/PSC terms identified in public sources for the core field development',
  333333.3333,
  4000000,
  'tonnes of oil and gas equivalent (planned/targeted; 2024 scale construction referenced)',
  7300000000,
  'boe (approximate; >1 billion tonnes cited as total oil & gas reserves; converted using 1 tonne oil ≈ 7.33 bbl for order-of-magnitude)',
  parse_site_date('2010-01-01'),
  NULL,
  'light crude (reported as mostly light crude, with associated gas)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)', 'West-to-East Gas Pipeline network (via Tarim gas transmission system / Lunnan hub)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Hade Oilfield / Hadedun Oilfield (哈德敦油田; Hade-Fuman bloc component)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Aksu Prefecture, Shaya County; Hadedun Town), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Aksu Prefecture, Shaya County; Hadedun Town)',
  40.7903,
  83.678,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by PetroChina (CNPC) Tarim Oilfield; associated gas recovery project located in Hadedun Town, Shaya County at listed coordinates',
  0,
  0,
  'unknown (public field-level production not found; part of Hade-Fuman production bloc)',
  0,
  'unknown',
  parse_site_date('2000-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)', 'West-to-East Gas Pipeline network (via Tarim gas transmission system / Lunnan hub)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Tahe Oilfield (塔河油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin, North Uplift / Akekule Arch area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin, North Uplift / Akekule Arch area)',
  41.1,
  82.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'State-owned CNPC/PetroChina system (no public PSC/JV terms identified for core development)',
  3000000,
  36500000,
  'barrels of oil (reported centered around ~100,000 bbl/d; converted to month/year)',
  4260000000,
  'barrels (proven reserves; widely cited summary figure)',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Tazhong Oil Field (塔中油田; Tazhong area development)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Bayingolin Mongol Autonomous Prefecture; Qiemo County / central Taklamakan area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Bayingolin Mongol Autonomous Prefecture; Qiemo County / central Taklamakan area)',
  40.5474,
  82.5783,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Primarily CNPC/PetroChina Tarim Oilfield operations; multiple oilfield service and operating units present in Tazhong area',
  0,
  0,
  'unknown (public field-level production not found in retrieved sources; major Tarim Basin producing area)',
  0,
  'unknown',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Lunnan Oilfield (轮南油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Bayangol/Aksu region interface; Luntai County area, northern Tarim / Tabei uplift margin), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Bayangol/Aksu region interface; Luntai County area, northern Tarim / Tabei uplift margin)',
  41.0,
  84.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by CNPC/PetroChina Tarim Oilfield; Lunnan also hosts the Lunnan Oil and Gas Reserve Center and the ‘first station’ of West-to-East gas pipelines (Lunnan Gas Station)',
  0,
  0,
  'unknown (field-level current oil output not found; historic capacity/production figures exist)',
  0,
  'unknown',
  parse_site_date('1989-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['137-km pipeline to Lunnan (historic CNPC build referenced)', 'West-to-East Gas Pipeline network (Lunnan Gas Station / Lunnan hub)'],
  ARRAY[]::TEXT[],
  ARRAY['Rail access serving the oilfield area (railway as primary transportation artery cited in technical literature)'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Sangtamu Oilfield (桑塔木油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; Tabei uplift / Lunnan slope area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; Tabei uplift / Lunnan slope area)',
  41.2,
  83.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated within CNPC/PetroChina Tarim Oilfield system (public field-level ownership breakdown not found)',
  0,
  0,
  'unknown (current production not found; listed historically among producing Tarim fields)',
  0,
  'unknown',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Donghetang Oilfield (东河塘油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area)',
  41.3,
  83.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated within CNPC/PetroChina Tarim Oilfield system (public field-level ownership breakdown not found)',
  0,
  0,
  'unknown (current production not found; listed historically among producing Tarim fields)',
  0,
  'unknown',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jilak Oilfield (吉拉克油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area)',
  41.15,
  83.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated within CNPC/PetroChina Tarim Oilfield system (public field-level ownership breakdown not found)',
  0,
  0,
  'unknown (current production not found; listed historically among producing Tarim fields)',
  0,
  'unknown',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jiefangqudong Oilfield (解放渠东油田)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; northern/central Tarim historic producing area)',
  41.1,
  83.7,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated within CNPC/PetroChina Tarim Oilfield system (public field-level ownership breakdown not found)',
  0,
  0,
  'unknown (current production not found; listed historically among producing Tarim fields)',
  0,
  'unknown',
  parse_site_date('1990-01-01'),
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['Tarim Oilfield internal gathering & transmission pipelines (field-level; names not consistently disclosed publicly)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Kela-2 Gas Field (克拉2气田; condensate associated)',
  'CNPC',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; Kuqa Depression area), China',
  'China',
  'Xinjiang Uyghur Autonomous Region (Tarim Basin; Kuqa Depression area)',
  41.8,
  83.2,
  'Energy',
  'Oil & Gas',
  'oil_and_gas_field',
  'active',
  'CNPC',
  'state-owned',
  'State-owned CNPC/PetroChina; no public PSC/JV terms identified for Kela-2 in retrieved sources',
  0,
  0,
  'unknown (primarily gas; oil/condensate volumes not found)',
  10082000000000,
  'cubic feet of gas (initial proven reserves widely cited)',
  parse_site_date('2004-01-01'),
  NULL,
  'condensate + natural gas (field produces gas and condensates)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('1900-01-01'),
  NULL,
  ARRAY['West-to-East Gas Pipeline network (Tarim gas transmission system)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Karamay Oilfield (Karamay Oil Field)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  45.5959,
  84.8892,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by CNPC/PetroChina; Xinjiang Oilfield is a CNPC upstream business unit.',
  8700000,
  104400000,
  'barrels',
  3000000000,
  'barrels',
  parse_site_date('1955'),
  NULL,
  'medium',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Karamay–Dushanzi crude pipeline (regional gathering/transfer system)'],
  ARRAY[]::TEXT[],
  ARRAY['Karamay rail connections (Xinjiang regional rail network)'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Mahu (Mahou) Tight Conglomerate Oilfield (Junggar Basin)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  46.6,
  85.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by CNPC/PetroChina Xinjiang Oilfield; onshore PRC state-owned upstream license.',
  2500000,
  30000000,
  'barrels',
  1000000000,
  'barrels',
  parse_site_date('2010'),
  NULL,
  'light',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Junggar Basin regional gathering pipelines (Mahu area)'],
  ARRAY[]::TEXT[],
  ARRAY['Karamay / regional Xinjiang rail logistics'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Jimsar (Jimusaer) Shale Oil Demonstration Zone (Junggar Basin)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  44.0,
  89.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'CNPC/PetroChina Xinjiang Oilfield as primary operator; national shale oil demonstration zone reported by regional media/state outlets.',
  610000,
  7320000,
  'barrels',
  1000000000,
  'barrels',
  parse_site_date('2019'),
  NULL,
  'light',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Xinjiang regional crude gathering/transfer system (Jimsar area)'],
  ARRAY[]::TEXT[],
  ARRAY['Urumqi–Jimusaer/Fukang regional rail logistics'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Tarim Oilfield (Tarim Basin – overall oilfield operations area)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  41.2,
  80.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by PetroChina (CNPC). 2023 petroleum liquids reported at 7.55 million tonnes.',
  3600000,
  43200000,
  'barrels',
  5000000000,
  'barrels',
  parse_site_date('1989'),
  NULL,
  'mixed',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['West–East Gas Pipeline (gas export; multiple lines)', 'Tarim Basin internal crude/gas gathering trunklines'],
  ARRAY[]::TEXT[],
  ARRAY['Korla rail connections (Xinjiang rail network)'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Fuman (Fuman 1 billion-ton ultra-deep oil area / Fuman Oilfield, Tarim Basin)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  40.4,
  83.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'Operated by PetroChina Tarim Oilfield (CNPC). Reported daily oil & gas production reaching ~10,000 tonnes (combined) and annual oil & gas output expected >4 million tonnes (oil & gas).',
  2400000,
  28800000,
  'barrels',
  1000000000,
  'tonnes (oil+gas resources)',
  parse_site_date('2016'),
  NULL,
  'ultra-deep crude (type not specified in public state-media reports)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Fuman area gathering pipelines (~200+ km reported in commissioning projects)', 'Tarim Basin trunk gathering/export system'],
  ARRAY[]::TEXT[],
  ARRAY['Korla rail logistics (via Tarim Basin facilities)'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Tahe Oilfield (Tarim Basin, Akekule Arch)',
  'Sinopec Northwest Oilfield Company (common operator for Tahe)',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  41.1,
  82.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sinopec Northwest Oilfield Company (common operator for Tahe)',
  'state-owned',
  'Widely reported as operated by Sinopec’s Northwest Oilfield; large onshore PRC state-owned upstream asset (no PSC/JV details found in accessible public sources).',
  3000000,
  36000000,
  'barrels',
  4260000000,
  'barrels',
  parse_site_date('1990'),
  NULL,
  'medium',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tarim Basin regional gathering/export pipelines'],
  ARRAY[]::TEXT[],
  ARRAY['Aksu/Korla rail logistics (Xinjiang rail network)'],
  'Sinopec',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
),
(
  'Tuha (Turpan–Hami) Oilfield (Tuha Oilfield)',
  'CNPC',
  'Xinjiang Uygur Autonomous Region, China',
  'China',
  'Xinjiang Uygur Autonomous Region',
  42.9,
  89.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'CNPC',
  'state-owned',
  'CNPC/PetroChina Tuha Oilfield. Reported as producing ~300,000 tonnes shale oil by 2025 plan (component of Jimsar zone plan) and conventional output historically in Turpan–Hami basin.',
  150000,
  1800000,
  'barrels',
  500000000,
  'barrels',
  parse_site_date('1970'),
  NULL,
  'mixed',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tuha basin gathering pipelines', 'West–East Gas Pipeline (regional tie-ins for gas where applicable)'],
  ARRAY[]::TEXT[],
  ARRAY['Turpan rail hub', 'Hami rail hub'],
  'CNPC',
  '{"source": "China_all_sites.json", "generated_date": "2026-01-21 22:43:46"}' ::JSONB
)
;


-- ============================================
-- STEP 6: VERIFICATION
-- ============================================

SELECT COUNT(*) as total_china_sites, 
       COUNT(CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN 1 END) as sites_with_coordinates,
       COUNT(CASE WHEN operational_status = 'active' THEN 1 END) as active_sites,
       COUNT(CASE WHEN operational_status != 'active' THEN 1 END) as inactive_sites
FROM public.commodity_locations 
WHERE country = 'China';
