-- ============================================
-- CONGO (REPUBLIC) OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:05:10.616357
-- Total sites: 35
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('Eni', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Murphy Oil', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Perenco', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Trident Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING CONGO (REPUBLIC) DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Congo (Republic)';

-- ============================================
-- STEP 5: INSERT CONGO (REPUBLIC) SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Moho Nord',
  'TotalEnergies',
  'Offshore (Pointe-Noire basin / Moho-Bilondo block)',
  'Congo (Republic)',
  'Offshore (Pointe-Noire basin / Moho-Bilondo block)',
  -4.48,
  11.05,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV',
  'TotalEnergies 63.5% (operator); Trident Energy 21.5%; SNPC 15%',
  3041666.7,
  36500000,
  'barrels (100% field, approx from 100 kboe/d)',
  0,
  'boe (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipelines to Alima FPU and Likouf FPU (Moho hub)'],
  ARRAY['Djéno Oil Terminal (Pointe-Noire area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Moho-Bilondo',
  'TotalEnergies',
  'Offshore (Pointe-Noire basin / Moho-Bilondo block)',
  'Congo (Republic)',
  'Offshore (Pointe-Noire basin / Moho-Bilondo block)',
  -4.5,
  11.08,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV',
  'TotalEnergies 63.5% (operator); Trident Energy 21.5%; SNPC 15%',
  3041666.7,
  36500000,
  'barrels (Moho license hub output; Moho-Bilondo + M',
  0,
  'boe (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipelines to Alima FPU and Likouf FPU (Moho hub)'],
  ARRAY['Djéno Oil Terminal (Pointe-Noire area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nkossa',
  'Trident Energy',
  'Offshore (Pointe-Noire basin)',
  'Congo (Republic)',
  'Offshore (Pointe-Noire basin)',
  -4.6,
  11.2,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV',
  'Trident Energy 85% (operator, per post-deal structure); SNPC 15% (post-deal structure)',
  456250,
  5475000,
  'barrels (Nkossa+Nsoko II combined ~15 kb/d, 100% f',
  0,
  'boe (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Djéno Oil Terminal (Pointe-Noire area)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nsoko II',
  'Trident Energy',
  'Offshore (Pointe-Noire basin)',
  'Congo (Republic)',
  'Offshore (Pointe-Noire basin)',
  -4.62,
  11.22,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV',
  'Trident Energy 85% (operator, per post-deal structure); SNPC 15% (post-deal structure)',
  456250,
  5475000,
  'barrels (Nkossa+Nsoko II combined ~15 kb/d, 100% f',
  0,
  'boe (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Djéno Oil Terminal (Pointe-Noire area)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nené Marine (Marine XII Block)',
  'Eni',
  'Offshore (Marine XII, ~17 km from coast)',
  'Congo (Republic)',
  'Offshore (Marine XII, ~17 km from coast)',
  -4.55,
  11.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Eni',
  'PSC JV',
  'Eni 65% (operator); LUKOIL Upstream Congo 25% (acquired from New Age); SNPC 10%',
  0,
  0,
  'barrels (not reliably sourced for current field-on',
  1500000000,
  'boe (resources cited attributable to Nené)',
  NULL,
  NULL,
  'light oil (low sulfur referenced as light/low sulfur for Marine XII output)',
  36,
  NULL,
  NULL,
  800000000,
  'USD',
  NULL,
  NULL,
  ARRAY['17 km subsea pipeline to Zatchi production platform (treatment)'],
  ARRAY['Djéno Oil Terminal (export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Litchendjili Marine (Marine XII Block)',
  'Eni',
  'Offshore (Marine XII)',
  'Congo (Republic)',
  'Offshore (Marine XII)',
  -4.52,
  11.55,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Eni',
  'PSC JV',
  'Eni 65% (operator); LUKOIL Upstream Congo 25%; SNPC 10%',
  0,
  0,
  'barrels (not reliably sourced for current field-on',
  0,
  'boe (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'mainly light, low-sulfur (Marine XII production described as mainly light and low sulfur)',
  NULL,
  NULL,
  NULL,
  800000000,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipeline(s) from Litchendjili to existing Marine XII production system'],
  ARRAY['Djéno Oil Terminal (export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Azurite (offshore oilfield)',
  'Murphy Oil',
  'Offshore (Pointe-Noire basin)',
  'Congo (Republic)',
  'Offshore (Pointe-Noire basin)',
  -4.7,
  11.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Murphy Oil',
  'private/JV (not reliably sourced)',
  'Not reliably sourced from primary operator/government documents in this pass',
  0,
  0,
  'barrels (not reliably sourced for current producti',
  0,
  'bbl (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Djéno Oil Terminal (likely export route for offshore crude; not field-specific sourced)'],
  ARRAY[]::text[],
  'Murphy Oil',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Lianzi (Unitized field, Congo/Angola)',
  'Trident Energy',
  'Offshore (border unitization area)',
  'Congo (Republic)',
  'Offshore (border unitization area)',
  -5.3,
  11.5,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV (not reliably sourced)',
  'Trident Energy operates/holds working interest (specific percentages not reliably sourced in this pass)',
  0,
  0,
  'barrels (not reliably sourced for current producti',
  0,
  'bbl (not reliably sourced for remaining reserves)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Yanga',
  'TotalEnergies',
  'Offshore (operated by TotalEnergies per country profile)',
  'Congo (Republic)',
  'Offshore (operated by TotalEnergies per country profile)',
  -4.75,
  11.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV (not reliably sourced)',
  'Not reliably sourced in this pass',
  0,
  0,
  'barrels (not reliably sourced)',
  0,
  'bbl (not reliably sourced)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Djéno Oil Terminal'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Sendji',
  'TotalEnergies',
  'Offshore (operated by TotalEnergies per country profile)',
  'Congo (Republic)',
  'Offshore (operated by TotalEnergies per country profile)',
  -4.72,
  11.32,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV (not reliably sourced)',
  'Not reliably sourced in this pass',
  0,
  0,
  'barrels (not reliably sourced)',
  0,
  'bbl (not reliably sourced)',
  NULL,
  NULL,
  'unknown (not reliably sourced)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Djéno Oil Terminal'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nzombo (permit area near Moho facilities)',
  'TotalEnergies',
  'Offshore (exploration permit ~100 km off Pointe-Noire)',
  'Congo (Republic)',
  'Offshore (exploration permit ~100 km off Pointe-Noire)',
  -4.49,
  11.06,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV (exploration permit)',
  'TotalEnergies 50% (operator); QatarEnergy 35%; SNPC 15%',
  0,
  0,
  'barrels (exploration permit; no production yet)',
  0,
  'bbl (prospective; not reliably sourced)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Moho-Bilondo (Moho Nord / Moho Phase 1bis)',
  'TotalEnergies',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.48,
  11.05,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV / PSC-style offshore license with NOC partner',
  'As of April 24, 2024 (announced): TotalEnergies EP Congo 63.5% (operator), Trident Energy 21.5%, SNPC 15% (subject to completion/approvals).',
  3041666.7,
  36500000,
  'bbl (oil equivalent); approx. 100,000 boe/d gross ',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (type varies by reservoir; public sources do not provide a single official fieldwide API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Moho export pipeline to Djéno onshore terminal (export via pipeline)'],
  ARRAY['Port of Djéno (onshore oil terminal, near Pointe-Noire)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nkossa Field',
  'TotalEnergies',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.6,
  11.2,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV / license with NOC partner',
  'Trident Energy 85% (operated), SNPC 15% (per Trident Energy).',
  228125,
  2737500,
  'bbl (oil equivalent); combined with Nsoko II appro',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (mature offshore; public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore export via existing Nkossa area infrastructure to Djéno terminal (exact pipeline names not consistently published)'],
  ARRAY['Port of Djéno (oil terminal)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nsoko II Field',
  'TotalEnergies',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.62,
  11.22,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV / license with NOC partner',
  'Trident Energy 85% (operated), SNPC 15% (per Trident Energy).',
  228125,
  2737500,
  'bbl (oil equivalent); combined with Nkossa approx.',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil / associated gas (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore export via existing Nkossa/Nsoko infrastructure to Djéno terminal (exact pipeline names not consistently published)'],
  ARRAY['Port of Djéno (oil terminal)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Lianzi Field (unitized Congo-Angola cross-border)',
  'Trident Energy',
  'Pointe-Noire Department (offshore, cross-border unitization zone)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore, cross-border unitization zone)',
  -5.3,
  11.5,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'Unitized cross-border JV',
  'Trident Energy 15.75% working interest (per Trident Energy). Other unit partners and operatorship split not fully detailed in the accessible public sources used here.',
  0,
  0,
  'bbl (not publicly and consistently disclosed at fi',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (deepwater; public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied into existing cross-border infrastructure (exact pipeline names not consistently published)'],
  ARRAY['Likely export via regional terminals (not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nené Marine Field (Marine XII Block)',
  'Eni',
  'Pointe-Noire Department (offshore, ~17 km from coast)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore, ~17 km from coast)',
  -4.55,
  11.58,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Eni',
  'PSC / JV (Marine XII)',
  'Eni 65% (operator), New Age 25%, SNPC 10% (per Eni press release).',
  0,
  0,
  'bbl (field current production not consistently dis',
  1500000000,
  'bbl (in place/resources estimate; Eni stated ~1.5 ',
  NULL,
  NULL,
  'light oil (36° API reported for test); associated gas',
  36,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['17 km subsea pipeline from Nené to Zatchi production platform (treatment/export chain thereafter not fully detailed in accessible sources)'],
  ARRAY['Pointe-Noire export chain via coastal facilities (specific terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Litchendjili Marine Field (Marine XII Block)',
  'Eni',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.52,
  11.55,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Eni',
  'PSC / JV (Marine XII)',
  'Eni 65% (operator), New Age 25%, SNPC 10% (by block terms referenced in Eni materials).',
  0,
  0,
  'bbl (not consistently disclosed publicly at field ',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'oil & gas (pre-salt; public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipeline directing production to Litchendjili / within Marine XII system (exact pipeline names/route details not consistently published)'],
  ARRAY['Pointe-Noire export chain via coastal facilities (specific terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Emeraude Field',
  'Perenco',
  'Pointe-Noire Department (offshore / coastal basin)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore / coastal basin)',
  -5.07,
  11.84,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license with NOC partner',
  'Perenco is operator; SNPC holds equity stakes in multiple Congo fields including Emeraude (stake cited in some compilations but not consistently confirmed with primary docs in accessible sources here).',
  0,
  0,
  'bbl (not consistently disclosed publicly at field ',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (shallow offshore; public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Connected into Perenco coastal/offshore infrastructure (specific pipeline names not consistently published)'],
  ARRAY['Pointe-Noire area export (exact terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Yombo Field',
  'Perenco',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.85,
  11.45,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license with NOC partner',
  'Perenco is operator (Yombo).',
  0,
  0,
  'bbl (not consistently disclosed publicly at field ',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Connected to Perenco’s Yombo FPSO/processing system (exact pipeline names not consistently published)'],
  ARRAY['Pointe-Noire area export (exact terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Likouala Field',
  'Perenco',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -5.22,
  11.71,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license with NOC partner',
  'Perenco is operator (took over operation in 2010 per widely cited summaries).',
  243333.3,
  2920000,
  'bbl (approx.; based on ~8,000 bpd cited in seconda',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Likouala area offshore gathering to coastal export chain (specific pipeline names not consistently published)'],
  ARRAY['Pointe-Noire area export (exact terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Boatou Field (marginal field; Boatou permit)',
  'Perenco',
  'Pointe-Noire Department (offshore, ~55 km off Pointe-Noire)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore, ~55 km off Pointe-Noire)',
  -5.15,
  11.65,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license with NOC partner',
  'Perenco (operator) with partners including SNPC (15%), Africa Oil & Gas Corporation (5%), PetroCongo (5%) as reported in 2023 industry coverage (full equity split beyond these not consistently disclosed in accessible sources here).',
  136875,
  1642500,
  'bbl (approx.; based on ~4,500 bpd startup output r',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Tie-in to existing Likouala infrastructure (~7 km from Likouala facilities per industry reporting)'],
  ARRAY['Pointe-Noire area export (exact terminal not consistently disclosed publicly at field level)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Yanga Field',
  'TotalEnergies',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.75,
  11.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV / PSC-style offshore license with NOC partner',
  'TotalEnergies lists Yanga as an operated offshore producing field in Congo; detailed equity split not consistently available in accessible primary sources here.',
  0,
  0,
  'bbl (not publicly and consistently disclosed at fi',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export via TotalEnergies Congo offshore-to-terminal system (specific pipeline names not consistently published)'],
  ARRAY['Port of Djéno (oil terminal, operated by TotalEnergies)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Sendji Field',
  'TotalEnergies',
  'Pointe-Noire Department (offshore)',
  'Congo (Republic)',
  'Pointe-Noire Department (offshore)',
  -4.72,
  11.32,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV / PSC-style offshore license with NOC partner',
  'TotalEnergies lists Sendji as an operated offshore producing field in Congo; detailed equity split not consistently available in accessible primary sources here.',
  0,
  0,
  'bbl (not publicly and consistently disclosed at fi',
  0,
  'bbl (remaining) - not reliably disclosed publicly ',
  NULL,
  NULL,
  'crude oil (public sources do not provide a single official API)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export via TotalEnergies Congo offshore-to-terminal system (specific pipeline names not consistently published)'],
  ARRAY['Port of Djéno (oil terminal, operated by TotalEnergies)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Yombo Oil Field (Marine I concession)',
  'Perenco',
  'Kouilou Department (offshore, ~NW of Pointe-Noire)',
  'Congo (Republic)',
  'Kouilou Department (offshore, ~NW of Pointe-Noire)',
  -4.85,
  11.45,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership (percentages changed over time)',
  'Historic (1991): Amoco 43.75%, Hydro-Congo 50%, Kuwait Foreign Petroleum Exploration Co. 6.25%. Current working interests not consistently published in open sources for the field-level; Marine I is operated by Perenco.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed for field-level in ope',
  NULL,
  NULL,
  'heavy crude (per OGJ description of Yombo crude)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipelines from platforms to Conkouati FPSO (two 18-inch lines reported historically)'],
  ARRAY['Offshore loading via Conkouati FPSO (shuttle tankers)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Masseko Oil Field (Marine I concession)',
  'Perenco',
  'Kouilou Department (offshore, Marine I area)',
  'Congo (Republic)',
  'Kouilou Department (offshore, Marine I area)',
  -4.82,
  11.42,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Marine I permit operated by Perenco; specific Masseko field-level WI splits not consistently published in open sources.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Marine I offshore gathering/export system (field tied into Marine I facilities; specifics not consistently published)'],
  ARRAY['Offshore export via Marine I facilities (field-level export point not consistently published)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Tchendo Oil Field (PNGF Sud / Tchendo II license)',
  'Perenco',
  'Kouilou Department (offshore/shallow water)',
  'Congo (Republic)',
  'Kouilou Department (offshore/shallow water)',
  -4.95,
  11.55,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Perenco-operated PNGF Sud complex includes Tchendo II license with multiple partners (SNPC, PetroNor/Hemla, Continent Congo, Africa Oil & Gas Corp, etc.) at license level; field-level splits not consistently published in open sources.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed for field-level in ope',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['PNGF Sud offshore gathering system (details not consistently published in open sources)'],
  ARRAY['Likely exported via Pointe-Noire area offshore terminals/FSO chain (field-level export point not consistently published)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Tchibouela East Oil Field (PNGF Sud)',
  'Perenco',
  'Kouilou Department (offshore/shallow water)',
  'Congo (Republic)',
  'Kouilou Department (offshore/shallow water)',
  -4.9,
  11.5,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Infill wells in Tchibouela East reported as part of PNGF Sud field complex operated by Perenco with multiple partners at license level; field-level splits not consistently published in open sources.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['PNGF Sud offshore gathering system (details not consistently published)'],
  ARRAY['Likely offshore export route via Pointe-Noire area terminals (not consistently published)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Tchibouela Oil Field (PNGF Sud / Tchibouela II license)',
  'Perenco',
  'Kouilou Department (offshore/shallow water)',
  'Congo (Republic)',
  'Kouilou Department (offshore/shallow water)',
  -4.9,
  11.5,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Perenco is operator of Tchibouela II license (PNGF Sud) with partners including PetroNor (via Hemla interest), SNPC, Hemla E&P Congo, Continent Congo, Africa Oil & Gas Corp, Petro Congo (license-level details reported; field-level split not consistently published).',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['PNGF Sud offshore gathering system (details not consistently published)'],
  ARRAY['Likely offshore export route via Pointe-Noire area terminals (not consistently published)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Tchibeli-Litanzi Oil Field (PNGF Sud / Tchibeli-Litanzi II license)',
  'Perenco',
  'Kouilou Department (offshore/shallow water)',
  'Congo (Republic)',
  'Kouilou Department (offshore/shallow water)',
  -4.88,
  11.48,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Perenco is operator of Tchibeli-Litanzi II license (PNGF Sud) with multiple partners at license level; field-level splits not consistently published.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['PNGF Sud offshore gathering system (details not consistently published)'],
  ARRAY['Likely offshore export route via Pointe-Noire area terminals (not consistently published)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Emeraude Oil Field (Emeraude permit / Emeraude Sud terminal area)',
  'Perenco',
  'Kouilou Department (offshore)',
  'Congo (Republic)',
  'Kouilou Department (offshore)',
  -5.0682,
  11.835,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Perenco-operated offshore field/permit; specific field-level ownership details not consistently published in open sources.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea export lines to Emeraude Sud Offshore Terminal (SPM/offshore terminal reported)'],
  ARRAY['Emeraude Sud Offshore Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Likouala Marine Oil Field',
  'Perenco',
  'Kouilou Department (offshore)',
  'Congo (Republic)',
  'Kouilou Department (offshore)',
  -5.2162,
  11.7078,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Open sources indicate Congorep (Perenco-SNPC JV) involvement; additional partners and exact field-level WIs not consistently published in open sources. Some listings note Eni involvement historically.',
  0,
  0,
  'bbl (crude oil)',
  80570000,
  'bbl (recoverable; reported as 80.57 Mmbbl crude & ',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore gathering/export tied to Likouala platform complex'],
  ARRAY['Likouala offshore terminal/port complex'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Likouala East Marine Oil Field',
  'Perenco',
  'Kouilou Department (offshore)',
  'Congo (Republic)',
  'Kouilou Department (offshore)',
  -5.1763,
  11.7022,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership',
  'Open listing indicates Eni and Congorep involvement; exact working interests not reliably disclosed in the listing.',
  0,
  0,
  'bbl (crude oil)',
  0,
  'bbl (not publicly confirmed)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore gathering/export tied to Likouala platform complex'],
  ARRAY['Likouala offshore terminal/port complex'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Boatou Oil Field (Boatou permit)',
  'Perenco',
  'Kouilou Department (offshore, ~55 km off Pointe-Noire)',
  'Congo (Republic)',
  'Kouilou Department (offshore, ~55 km off Pointe-Noire)',
  -5.15,
  11.65,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV / license partnership (state + private)',
  'Perenco 75% (operator), SNPC 15%, Africa Oil & Gas Corp (AOGC) 5%, PetroCongo 5%. New 20-year operating permit reported in 2023.',
  135000,
  1642500,
  'bbl (crude oil)',
  73000000,
  'bbl (estimated in-place; open source reporting)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Tie-back to Likouala platform complex (satellite development)'],
  ARRAY['Likouala offshore terminal/port complex'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Néné Marine Field (Marine XII)',
  'Eni',
  'Kouilou Department (offshore, Marine XII)',
  'Congo (Republic)',
  'Kouilou Department (offshore, Marine XII)',
  -4.5487,
  11.5845,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Eni',
  'PSC / JV',
  'Reported stake split: Eni 65%, Lukoil 25%, SNPC 10%.',
  0,
  0,
  'bbl (oil) and m3 (gas) (mixed; not separable from ',
  0,
  'boe (field-level not publicly confirmed in the ope',
  NULL,
  NULL,
  'gas-condensate / associated liquids (Marine XII LNG-linked; exact oil quality not in open listing)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Marine XII offshore subsea/pipeline network feeding FLNG Tango/Nguya system'],
  ARRAY['FLNG Tango (offshore LNG export)', 'FLNG Nguya (offshore LNG export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Litchendjili Field (Marine XII)',
  'Eni',
  'Kouilou Department (offshore, Marine XII)',
  'Congo (Republic)',
  'Kouilou Department (offshore, Marine XII)',
  -4.52,
  11.55,
  'Energy',
  'Natural Gas',
  'offshore_field',
  'active',
  'Eni',
  'PSC / JV',
  'Marine XII development stated to include Néné and Litchendjili fields; operator Eni. Public sources emphasize LNG development rather than field-level oil volumes.',
  0,
  0,
  'bbl (oil/condensate) and m3 (gas) (mixed; not sepa',
  0,
  'boe (field-level not publicly confirmed)',
  NULL,
  NULL,
  'gas field (LNG-linked; exact liquids quality not stated)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Marine XII offshore infrastructure system (platforms/subsea) feeding FLNG Tango and FLNG Nguya'],
  ARRAY['FLNG Tango (offshore LNG export)', 'FLNG Nguya (offshore LNG export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);
