-- ============================================
-- EGYPT OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:05:10.619765
-- Total sites: 49
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('Apache', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('BAPETCO', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('BP', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Cheiron', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Dana Gas', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('EGPC', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Energean', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Eni', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('GPC', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('GUPCO', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Gemsa Petroleum Company', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Khalda Petroleum', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Kuwait Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('PetroGulf Misr', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Petrobel', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Rashid Petroleum Company', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('SUCO', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Tharwa Petroleum Company', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Vegas Oil & Gas', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING EGYPT DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Egypt';

-- ============================================
-- STEP 5: INSERT EGYPT SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Obaiyed (Obayed) Gas & Condensate Field',
  'Cheiron',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.7,
  27.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Cheiron',
  'JV / Concession (PSC-style under EGPC)',
  'Operated by BAPETCO (EGPC JV); post-2021 Shell Western Desert assets held by Cheiron–Capricorn consortium; Capricorn reports Obaiyed concession at 50% working interest (WI) for Capricorn with operating partner Cheiron.',
  0,
  0,
  'bbl (liquids; monthly/yearly not found in reliable',
  1400000000,
  'scf (recoverable gas; legacy public estimate)',
  NULL,
  NULL,
  'gas & condensate (condensate quality not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  25,
  ARRAY['Obaiyed–Ameriya gas pipeline (~34-inch; ~315 km; to Ameriya petrochemicals / national grid)'],
  ARRAY['Sidi Kerir (SUMED terminal)'],
  ARRAY[]::text[],
  'Cheiron',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Badr El Din (BED) Fields / Integrated Badr El-Din Area (BED, BED-2, BED-3, BED-17, etc.)',
  'Cheiron',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.65,
  27.45,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Cheiron',
  'JV / Integrated concession (PSC-style under EGPC)',
  'Integrated Badr El-Din area consolidates multiple BAPETCO concessions; Cabinet-approved agreement involves EGPC, Cheiron Petroleum, and Capricorn (Capricorn reports BED concession at 50% WI).',
  105000,
  1260000,
  'barrels per month (oil target in integrated conces',
  0,
  'bbl (not found for integrated area in reliable pub',
  NULL,
  NULL,
  'oil & gas (varied by field; not found)',
  NULL,
  NULL,
  NULL,
  208000000,
  'USD',
  NULL,
  NULL,
  ARRAY['Western Desert national grid tie-ins (BAPETCO network; specific trunk lines not fully disclosed publicly)'],
  ARRAY['Sidi Kerir (SUMED terminal)'],
  ARRAY[]::text[],
  'Cheiron',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Badr-15 Development Area (BED 15-31 well area)',
  'BAPETCO',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.65,
  27.45,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'BAPETCO',
  'JV / Concession (PSC-style under EGPC)',
  'BAPETCO is EGPC JV; Western Desert assets operated by Cheiron with Capricorn as consortium partner in relevant concessions.',
  22500,
  273750,
  'bbl (condensate; computed from 750 bbl/d initial r',
  15000000000,
  'scf (gas; stated addition to reserves)',
  NULL,
  NULL,
  'gas & condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['National gas grid connection (immediate tie-in per ministry statements; specific line not named publicly)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'BAPETCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Alam El Shawish West (AESW) Concession / Fields',
  'Cheiron',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.6,
  27.4,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Cheiron',
  'JV / Concession (PSC-style under EGPC)',
  'Capricorn reports 20% WI in AESW; historical consortium (2010) Shell Egypt 40% (operator), Vegas 35%, GDF SUEZ 25% (later interests changed via 2021 Shell asset sale).',
  0,
  0,
  'bbl (not found)',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'oil & gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['BAPETCO/Cheiron Western Desert gathering system (specific pipeline names not found publicly)'],
  ARRAY['Sidi Kerir (SUMED terminal)'],
  ARRAY[]::text[],
  'Cheiron',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North East Abu Gharadig (NEAG) Concession (Tiba area / NEAG Extension)',
  'Apache',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  29.8,
  28.2,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Apache',
  'JV / Concession (PSC-style under EGPC)',
  'Capricorn reports 26% WI in NEAG (Tiba/Extension) with operating partner Cheiron; OGJ notes Shell interest historically in NEAG with Apache Abu Gharadig Corp. LDC as partner/operator context.',
  0,
  0,
  'bbl (not found)',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'oil & gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Abu Gharadig area gathering to El Hamra / Western Desert export system (specific trunk names not found in reliable public sources)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Apache',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Qarun Oil Field (Qarun Concession)',
  'Apache',
  'Faiyum / Giza desert margin (edge of Western Desert)',
  'Egypt',
  'Faiyum / Giza desert margin (edge of Western Desert)',
  29.5163,
  30.8578,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Apache',
  'JV / Concession (PSC-style under EGPC)',
  'Legacy reporting describes Qarun Petroleum Co. as EGPC JV with Apache and partners; specific current percentages not confirmed in latest public sources retrieved.',
  0,
  0,
  'bbl (current not found; historical design capacity',
  75000000,
  'bbl (proved; legacy estimate range 75–80 million b',
  NULL,
  NULL,
  'light oil',
  42.0,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Qarun-to-SUMED pipeline (~30 miles)', 'SUMED twin 42-inch oil pipelines (connection point)'],
  ARRAY['Sidi Kerir (SUMED terminal)'],
  ARRAY[]::text[],
  'Apache',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Abu Sennan Concession (multi-field area)',
  'Kuwait Energy',
  'Western Desert (likely Giza/Matrouh border region)',
  'Egypt',
  'Western Desert (likely Giza/Matrouh border region)',
  30.1,
  27.8,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Kuwait Energy',
  'Private partners under concession with EGPC (JV/PSC framework)',
  'Operator Kuwait Energy Egypt; partners reported: Kuwait Energy Egypt 25%, GlobalConnect 25%, United Oil & Gas 22%, Dover Investments 28%.',
  66000,
  803000,
  'bbl (oil; computed from 2,200 bpd initial commerci',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'oil & gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Abu Sennan area gathering and tie-ins (specific pipeline names not found in reliable public sources)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Kuwait Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'East Abu Sennan (EAS) Concession',
  'Tharwa Petroleum Company',
  'Western Desert (Alamein/Abu Sennan area)',
  'Egypt',
  'Western Desert (Alamein/Abu Sennan area)',
  30.1,
  27.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Tharwa Petroleum Company',
  'State-linked operator under EGPC framework (operator 100% WI stated by Tharwa for EAS concession)',
  'Tharwa states it is operator with 100% working interest in East Abu Sennan Concession; operations managed through Alamein Petroleum Company on behalf of EGPC and Tharwa.',
  45000,
  547500,
  'bbl (oil; computed from 1,500 bpd initial rate for',
  3500000,
  'bbl (proven reserves increase cited by company lea',
  NULL,
  NULL,
  'oil (Abu Roash E pay mentioned; quality not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['EAS tie-in to Western Desert production network (specific pipeline names not found publicly)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Tharwa Petroleum Company',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Matrouh Development Area (Khalda) - Sultan S-1X RC discovery area',
  'Khalda Petroleum',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.75,
  27.55,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Khalda Petroleum',
  'JV / PSC (EGPC–Apache JV)',
  'Khalda Petroleum Company is a joint venture between EGPC and Apache (APA Corp.).',
  22500,
  273750,
  'bbl (oil; allocated estimate assuming ~50% of >1,5',
  0,
  'bbl (testing/estimation ongoing; not found)',
  NULL,
  NULL,
  'oil & associated gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Khalda area gathering system (specific pipeline names not found publicly)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Khalda Petroleum',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Matrouh Development Area (Khalda) - Alex NW-1X discovery area',
  'Khalda Petroleum',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.75,
  27.55,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Khalda Petroleum',
  'JV / PSC (EGPC–Apache JV)',
  'Khalda Petroleum Company is a joint venture between EGPC and Apache (APA Corp.).',
  22500,
  273750,
  'bbl (oil; allocated estimate assuming ~50% of >1,5',
  0,
  'bbl (testing/estimation ongoing; not found)',
  NULL,
  NULL,
  'oil & associated gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Khalda area gathering system (specific pipeline names not found publicly)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Khalda Petroleum',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Kalabsha Development Area (Khalda) - West Fewebs-1 discovery',
  'Khalda Petroleum',
  'Western Desert (Kalabsha area)',
  'Egypt',
  'Western Desert (Kalabsha area)',
  30.75,
  27.55,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Khalda Petroleum',
  'JV / PSC (EGPC–Apache JV)',
  'Khalda Petroleum Company is a joint venture between EGPC and Apache (APA Corp.).',
  214950,
  2615225,
  'bbl (oil; computed from 7,165 bpd test rate; early',
  0,
  'bbl (not published; discovery test only)',
  NULL,
  NULL,
  'light oil',
  44.0,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Khalda/Western Desert gathering system; links toward export via Meleiha–El Hamra system (specific connection not confirmed for this well)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Khalda Petroleum',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Meleiha Oil Field (Agiba / Meleiha block)',
  'EGPC',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.55,
  27.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'EGPC',
  'JV (50/50 EGPC–IEOC/Eni)',
  'Agiba described as 50–50 JV of EGPC and Agip/IEOC (Eni).',
  0,
  0,
  'bbl (field-level current not found; legacy block-l',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'medium oil (API cited in legacy source)',
  31.6,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Meleiha–El Hamra export pipeline (regional export line referenced in legacy operator summaries)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'EGPC',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'West Razzaq Oil Field / Block (Agiba)',
  'EGPC',
  'Matrouh Governorate (Western Desert)',
  'Egypt',
  'Matrouh Governorate (Western Desert)',
  30.5,
  26.95,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'EGPC',
  'JV (50/50 EGPC–IEOC/Eni)',
  'Agiba described as 50–50 JV of EGPC and Agip/IEOC (Eni).',
  0,
  0,
  'bbl (field-level current not found)',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'oil (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Meleiha–El Hamra export pipeline (regional export line referenced in legacy operator summaries)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'EGPC',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Abu Gharadig Field (Abu Gharadig Basin)',
  'Apache',
  'Western Desert (Abu Gharadig Basin)',
  'Egypt',
  'Western Desert (Abu Gharadig Basin)',
  29.8,
  28.2,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Apache',
  'Concession/JV (PSC-style under EGPC)',
  'Large Western Desert producing area referenced across operator reports; specific current equity/reserves by field not found in sources retrieved.',
  0,
  0,
  'bbl (not found)',
  0,
  'bbl (not found)',
  NULL,
  NULL,
  'oil & gas (not found)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Abu Gharadig area gathering to El Hamra (specific pipeline names not found in reliable public sources)'],
  ARRAY['El Hamra (Mediterranean)'],
  ARRAY[]::text[],
  'Apache',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ras Budran Field (GOSE)',
  'SUCO',
  'South Sinai (Gulf of Suez East Concession)',
  'Egypt',
  'South Sinai (Gulf of Suez East Concession)',
  28.9333,
  33.1333,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SUCO',
  'JV (EGPC + foreign partner)',
  'Operated by SUCO (joint venture between EGPC and Dea/DEA Deutsche Erdoel AG; exact equity split not stated in available sources).',
  187500,
  2281250,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Ras Budran offshore-to-shore pipelines (field gathering)', 'PPC pipeline (as referenced by SUCO for crude loading)'],
  ARRAY['Ras Budran SBM (single buoy mooring)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ras Fanar Field (GOSW)',
  'SUCO',
  'Red Sea Governorate / Gulf of Suez West Concession',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez West Concession',
  28.45,
  33.25,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SUCO',
  'JV (EGPC + foreign partner)',
  'Operated by SUCO (joint venture between EGPC and Dea/DEA Deutsche Erdoel AG; exact equity split not stated in available sources). Field discovered 1974; production since 1984.',
  137250,
  1670125,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (Miocene reservoirs; type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Ras Fanar offshore-to-shore pipeline to SUCO facilities (as described by RWE/Offshore Energy)'],
  ARRAY['Zeit Bay area crude handling/export facilities (regional)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Zeit Bay Field incl. Ras El Behar (REB) onshore extension (GOSW)',
  'SUCO',
  'Red Sea Governorate / Gulf of Suez West Concession',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez West Concession',
  28.3,
  33.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'SUCO',
  'JV (EGPC + foreign partner)',
  'Operated by SUCO (joint venture between EGPC and Dea/DEA Deutsche Erdoel AG; exact equity split not stated in available sources). Includes onshore facilities at Ras El Behar Peninsula (REB) with directional wells and offshore platforms at Zeit Bay.',
  138333,
  1680417,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Zeit Bay field gathering pipelines (subsea/offshore-to-shore; not individually named in available sources)'],
  ARRAY['Zeit Bay crude processing/storage/shipping facilities (SUCO gas plant area)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Safa Field (Northeast Ramadan Concession)',
  'GUPCO',
  'Gulf of Suez (Northeast Ramadan area)',
  'Egypt',
  'Gulf of Suez (Northeast Ramadan area)',
  28.36,
  33.29,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'GUPCO',
  'JV (EGPC + foreign partner)',
  'Operated by GUPCO (EGPC joint venture with UAE’s Dragon Oil per Ministry/press reporting). Early production phase investments reported at about $125m for station + 10/11 km lines.',
  360000,
  4380000,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  125000000,
  'USD',
  NULL,
  NULL,
  ARRAY['North Safa production lines (10 km and 11 km; names not stated)'],
  ARRAY['Gulf of Suez export system (port/terminal not stated for this field in available sources)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Geisum & Tawila West Fields Complex (North Geisum / NE Geisum / South Geisum / Tawila-West / North-North Geisum)',
  'PetroGulf Misr',
  'Gulf of Suez (Central GoS, ~70 km north of Hurghada)',
  'Egypt',
  'Gulf of Suez (Central GoS, ~70 km north of Hurghada)',
  27.7,
  33.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'PetroGulf Misr',
  'PSC/JV (EGPC + foreign partners)',
  'Operated by Petrogulf Misr JV under Law No. 93/2007; EGPC 50% and partners (Cheiron/Pico + KUFPEC) 50% reported for the concession area. Five main fields: North Geisum, North-East Geisum, South Geisum, Tawila-West, and North-North Geisum (GNN).',
  699166,
  8508125,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'medium crude (composite export oil gravity reported ~28 API)',
  28,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea interconnecting pipelines gathering to CPS (Geisum Star)'],
  ARRAY['Gulf of Suez export system (specific terminal not stated in available sources)'],
  ARRAY[]::text[],
  'PetroGulf Misr',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Belayim Field (Belayim Marine)',
  'Eni',
  'Gulf of Suez',
  'Egypt',
  'Gulf of Suez',
  28.65,
  33.2,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Eni',
  'JV/PSC (state + IOC)',
  'Developed by Eni; operated via Petrobel JV structure (common Egypt JV model with EGPC). Specific equity percentages not confirmed in available sources used here.',
  2281250,
  27721375,
  'barrels of oil (bbl)',
  2780000000,
  'bbl (proven reserves; source is non-official compi',
  NULL,
  NULL,
  'black oil / medium-light crude (reported in secondary references)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Belayim Marine export pipeline system (not detailed in available sources)'],
  ARRAY['Belayim Marine/GoS export system (terminal not specified in available sources)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Morgan Field',
  'GUPCO',
  'Gulf of Suez',
  'Egypt',
  'Gulf of Suez',
  28.7,
  33.25,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'GUPCO',
  'JV (EGPC + foreign partner)',
  'Operated by GUPCO (EGPC joint venture; partner/percentages not confirmed in available sources used here).',
  1216667,
  14862500,
  'barrels of oil (bbl)',
  2700000000,
  'bbl (proven reserves; source is non-official compi',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Morgan offshore gathering/export system (not detailed in available sources)'],
  ARRAY['Gulf of Suez export system (terminal not specified in available sources)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'October Field (offshore)',
  'GUPCO',
  'Gulf of Suez',
  'Egypt',
  'Gulf of Suez',
  28.55,
  33.18,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (EGPC + foreign partner)',
  'Affiliated to/operated by GUPCO; major development works (new 18-inch pipelines and tie-ins) reported completed by Petroleum Marine Services (PMS) in 2024. Production volumes not stated in available sources.',
  0,
  0,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Two 18-inch offshore pipelines (installed/connected to OCTOBER-C, OCTOBER-A, OCTOBER H and OCTOBER-P platforms)'],
  ARRAY['Gulf of Suez export system (terminal not specified in available sources)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North-East Ramadan (Crystal Northeast Ramadan / NER-1X discovery)',
  'GUPCO',
  'Gulf of Suez (North-East Ramadan Concession area)',
  'Egypt',
  'Gulf of Suez (North-East Ramadan Concession area)',
  28.36,
  33.29,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'GUPCO',
  'JV (EGPC + foreign partner)',
  'Discovery announced by Ministry of Petroleum; made by GUPCO JV between EGPC and UAE’s Dragon Oil. Initial expected rate ~3,000 bbl/d.',
  91250,
  1110625,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['North-East Ramadan offshore production tie-in (not detailed in available sources)'],
  ARRAY['Gulf of Suez export system (terminal not specified in available sources)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Amer Field (GPC - GG83/3 well area)',
  'GPC',
  'Gulf of Suez',
  'Egypt',
  'Gulf of Suez',
  28.36,
  33.29,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'GPC',
  'State-owned (EGPC/Ministry sector company)',
  'Operated by GPC; exploratory well GG83/3 in the North Amer field added to production map (production volumes not stated).',
  0,
  0,
  'barrels of oil (bbl)',
  0,
  'bbl (remaining)',
  NULL,
  NULL,
  'crude oil (type not specified)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Not specified'],
  ARRAY['Not specified'],
  ARRAY[]::text[],
  'GPC',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'West Nile Delta (WND) Gas Development (Taurus, Libra, Giza, Fayoum, Raven)',
  'BP',
  'Mediterranean Sea (offshore Nile Delta, North Alexandria & West Mediterranean Deepwater concessions)',
  'Egypt',
  'Mediterranean Sea (offshore Nile Delta, North Alexandria & West Mediterranean Deepwater concessions)',
  31.7,
  29.5,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'BP',
  'JV / PSC',
  'West Nile Delta development: bp-operated; bp has published 82.75% stake (context: WND/Raven) with Harbour Energy 17.25% (stake details vary by concession/phase).',
  810000,
  9720000,
  'bbl condensate (approx; derived from 27,000 bbl/d ',
  0,
  'boe (not publicly consolidated at development leve',
  NULL,
  NULL,
  'gas-condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea tiebacks to onshore West Nile Delta processing facilities (North Alexandria / WND onshore reception and processing)', 'Connected to Egyptian national gas grid'],
  ARRAY['Alexandria area (regional export/import infrastructure; field gas exported to national grid)'],
  ARRAY[]::text[],
  'BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Nooros Gas & Condensate Field (Abu Madi West Development Lease)',
  'Petrobel',
  'Nile Delta (shallow waters, offshore Mediterranean)',
  'Egypt',
  'Nile Delta (shallow waters, offshore Mediterranean)',
  31.55,
  30.5,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Petrobel',
  'JV / PSC',
  'Abu Madi West development license: Eni (IEOC) 75%, bp 25%; Petrobel is jointly owned by IEOC (50%) and EGPC (50%).',
  0,
  0,
  'bbl (condensate not consistently disclosed in publ',
  0,
  'boe (not consistently disclosed in public sources)',
  NULL,
  NULL,
  'gas-condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Flowlines to Abu Madi treatment plant', 'Connected to Egyptian gas transmission / national grid'],
  ARRAY['Alexandria (regional export infrastructure)'],
  ARRAY[]::text[],
  'Petrobel',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Abu Qir Gas Field Hub (Abu Qir, North Abu Qir, West Abu Qir)',
  'Energean',
  'Mediterranean Sea (offshore north of Alexandria; Nile Delta region)',
  'Egypt',
  'Mediterranean Sea (offshore north of Alexandria; Nile Delta region)',
  31.45,
  30.05,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Energean',
  'PSC / JV with state participation',
  'Concession operated via JV with EGPC; concession agreement noted as 20-year duration extendable 10 years (Edison/EGPC agreement).',
  125000,
  1500000,
  'bbl (approx; oil/condensate referenced historicall',
  70,
  'bcm gas equivalent (historic estimate; translates ',
  NULL,
  NULL,
  'gas + condensate/oil',
  NULL,
  NULL,
  NULL,
  1405000000,
  'USD',
  NULL,
  20,
  ARRAY['Offshore pipelines linking platforms to onshore market / Egyptian national gas network'],
  ARRAY['Alexandria'],
  ARRAY[]::text[],
  'Energean',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North El Amriya & North Idku (NEA/NI) Development (includes Yazzi & Python fields within NEA/NI)',
  'Energean',
  'Mediterranean Sea (shallow-water offshore Nile Delta)',
  'Egypt',
  'Mediterranean Sea (shallow-water offshore Nile Delta)',
  28.36,
  33.29,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Energean',
  'PSC / JV with state entities',
  'Energean-operated; development is subsea tieback of 4 wells to North Abu Qir PIII platform; reported 2P reserves 39 MMboe (88% gas) at development level in operator-linked reporting.',
  0,
  0,
  'boe (peak production guidance exists; current liqu',
  39,
  'MMboe (2P)',
  NULL,
  NULL,
  'gas (with condensate potential)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea tieback to North Abu Qir PIII platform', 'Export via existing Abu Qir hub pipelines to domestic market / national grid'],
  ARRAY['Alexandria'],
  ARRAY[]::text[],
  'Energean',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Rosetta (Rashid) Gas Field / Rosetta Concession',
  'Rashid Petroleum Company',
  'Mediterranean Sea (offshore Nile Delta, east of Alexandria)',
  'Egypt',
  'Mediterranean Sea (offshore Nile Delta, east of Alexandria)',
  31.5,
  30.2,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Rashid Petroleum Company',
  'JV / PSC',
  'Rashid Petroleum Co. JV: EGPC 50%, BG 20%, Shell 20%, Edison 10% (historic structure; later partner changes occurred but not consistently available without paywalled sources). Gas sales agreement cited as 25-year (signed 1997-10).',
  0,
  0,
  'mcf (public sources emphasize gas rates; liquids n',
  0,
  'bcm (not consistently disclosed in accessible sour',
  NULL,
  NULL,
  'dry gas / gas-condensate (varies by reservoir)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  25,
  ARRAY['Pipeline to Egyptian national grid east of Alexandria'],
  ARRAY['Alexandria'],
  ARRAY[]::text[],
  'Rashid Petroleum Company',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Dana Gas / WASCO Onshore Nile Delta (El Manzala / West El Manzala / West El Qantara – consolidated as New El Manzala concession; includes El Basant and North El-Basant discoveries)',
  'Dana Gas',
  'Dakahlia / Port Said / Ismailia (onshore Nile Delta concession areas)',
  'Egypt',
  'Dakahlia / Port Said / Ismailia (onshore Nile Delta concession areas)',
  31.2,
  32.0,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Dana Gas',
  'Concession / PSC (100% working interest stated for consolidated concession)',
  'Dana Gas announced a new concession agreement (Dec 2024) consolidating 13 development leases into ''New El Manzala'' with 100% working interest; operated via WASCO JV with EGAS for operations.',
  46620,
  559440,
  'bbl (condensate; derived from 1,554 bbl/d disclose',
  22.1,
  'MMboe (2P, as of 2024-12-31 for Dana Gas Egypt por',
  NULL,
  NULL,
  'gas + condensate + LPG',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Connected to Egypt national gas grid (onshore tie-in)'],
  ARRAY['Damietta (regional LNG/export infrastructure; not necessarily dedicated to these fields)', 'Port Said (regional export infrastructure)'],
  ARRAY[]::text[],
  'Dana Gas',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'West El Burullus (West Burullus) Offshore Gas Field',
  'Cheiron',
  'Mediterranean Sea (western Nile Delta)',
  'Egypt',
  'Mediterranean Sea (western Nile Delta)',
  31.6,
  30.6,
  'Energy',
  'Natural Gas',
  'offshore_field',
  'active',
  'Cheiron',
  'JV / state partnership',
  'Developed through partnership between Egyptian petroleum sector and Cheiron Energy; Burullus Gas Company processing facilities referenced for handling gas.',
  0,
  0,
  'mcf (public sources emphasize gas rates; liquids n',
  0,
  'bcf (not disclosed in accessible sources)',
  NULL,
  NULL,
  'natural gas',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-in to existing processing facilities operated by Burullus Gas Company', 'Connected to Egyptian national gas grid'],
  ARRAY['Alexandria'],
  ARRAY[]::text[],
  'Cheiron',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ras Gharib Oilfields (Gharib Fields)',
  'GPC',
  'Red Sea Governorate (Eastern Desert / Gulf of Suez coastal plain)',
  'Egypt',
  'Red Sea Governorate (Eastern Desert / Gulf of Suez coastal plain)',
  28.349,
  33.078,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'GPC',
  'state-owned / EGPC operating company',
  'Operated by General Petroleum Company (GPC), an EGPC company; specific concession partner split not found in public sources for the Gharib fields.',
  270000,
  3285000,
  'bbl (crude oil)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown (mixed Gulf of Suez crude)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Local gathering/export pipeline network serving Gulf of Suez production (exact line names not publicly specified for Gharib)'],
  ARRAY['Ras Shukheir (Shukheir) terminal (regional export hub)'],
  ARRAY[]::text[],
  'GPC',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ras Budran Field',
  'SUCO',
  'South Sinai Governorate / Gulf of Suez (offshore, Eastern Desert region)',
  'Egypt',
  'South Sinai Governorate / Gulf of Suez (offshore, Eastern Desert region)',
  28.93,
  33.13,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'SUCO',
  'JV / PSC-style concession with EGPC',
  'Historically a SUCO JV between EGPC and Wintershall Dea/RWE Dea; EGPC acquired Wintershall Dea Egypt oil interests effective 2022-01-01 (concession share transfer).',
  180000,
  2190000,
  'bbl (crude oil)',
  0,
  'bbl (remaining not publicly stated)',
  NULL,
  NULL,
  'unknown (Ras Budran blend)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore-to-shore oil and gas pipelines (Ras Budran facilities)', 'PPC line (as referenced by SUCO loading operations)'],
  ARRAY['Ras Budran loading facility (SBM/terminal operations referenced by SUCO)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Zeit Bay Field (with Ras El Behar onshore extension)',
  'SUCO',
  'Red Sea Governorate / Gulf of Suez (offshore & onshore extension, Eastern Desert region)',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez (offshore & onshore extension, Eastern Desert region)',
  28.3,
  33.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'SUCO',
  'JV / PSC-style concession with EGPC',
  'Operated by SUCO; historically linked to EGPC and Wintershall Dea/RWE Dea participation; current detailed ownership by field not fully disclosed in public sources.',
  0,
  0,
  'bbl (crude oil, not separately disclosed)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['LPG 6-inch pipeline from Zeit Bay gas plant to GUPCO Ras Shukheir storage area (LPG export)', 'Offshore loading facility pipelines (field export system)'],
  ARRAY['Ras Shukheir storage area/terminal (for LPG distribution and regional exports)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ras Fanar Field',
  'SUCO',
  'Gulf of Suez (offshore, Eastern Desert region)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region)',
  28.45,
  33.25,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'SUCO',
  'JV / PSC-style concession with EGPC',
  'Operated by SUCO; specific field-level working interests not fully disclosed in public sources.',
  0,
  0,
  'bbl (crude oil, not separately disclosed)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore-to-shore export pipelines via SUCO network (names not publicly specified)'],
  ARRAY['Ras Shukheir (regional terminal)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Belayim (Belayim Marine) Field',
  'Eni',
  'Gulf of Suez (offshore, Eastern Desert region)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region)',
  28.65,
  33.2,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Eni',
  'JV / concession (state + foreign partner)',
  'Widely reported as developed/operated by Eni through its Egypt entities alongside EGPC; precise current JV/PSC percentages not consistently published in open sources.',
  2250000,
  27375000,
  'bbl (crude oil)',
  2780000000,
  'bbl',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore production/export pipeline network (field-specific names not found in open sources)'],
  ARRAY['Gulf of Suez oil terminals (commonly via Ras Shukheir region for exports)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Morgan (El Morgan) Field',
  'GUPCO',
  'Gulf of Suez (offshore, Eastern Desert region)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region)',
  28.7,
  33.25,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (operating company under EGPC + partner)',
  'GUPCO operates as a joint venture operating company; current partner mix varies by concession and has changed over time (e.g., Dragon Oil involvement in Gulf of Suez JV operations).',
  1200000,
  14600000,
  'bbl (crude oil)',
  2700000000,
  'bbl',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore pipeline network to regional processing/export (names not found in open sources)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'October Field (Offshore October)',
  'GUPCO',
  'Gulf of Suez (offshore, Eastern Desert region)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region)',
  28.55,
  33.18,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (operating company under EGPC + partner)',
  'Operated by GUPCO; field-level partner/interest splits not consistently published in open sources.',
  0,
  0,
  'bbl (crude oil, not separately disclosed)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Two 18-inch offshore pipelines connected to October platforms (October-C, October-A, October H, October-P)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Safa Field',
  'GUPCO',
  'Gulf of Suez (offshore, Eastern Desert region; Northeast Ramadan Concession)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region; Northeast Ramadan Concession)',
  28.3596,
  33.2946,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (EGPC + Dragon Oil/ENOC via operating company)',
  'Operated by GUPCO; Ministry statements describe GUPCO as joint operations company between EGPC and UAE''s Dragon Oil. Dragon Oil is a subsidiary of Emirates National Oil Company (ENOC).',
  67500,
  821250,
  'bbl (crude oil)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offshore production pipelines connected during 2024 development (names not publicly specified)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Safa Field - Al-Wasl-4 Development Well (site within field)',
  'GUPCO',
  'Gulf of Suez (offshore, Eastern Desert region; North Safa)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region; North Safa)',
  28.3596,
  33.2946,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (EGPC + Dragon Oil/ENOC via operating company)',
  'Development well brought onstream per Ministry/press statements; GUPCO is JV operator between EGPC and Dragon Oil in Gulf of Suez concessions.',
  67500,
  821250,
  'bbl (crude oil; based on 2,250 bpd initial rate)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['North Safa offshore production/export pipeline network (names not publicly specified)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North East Ramadan Crystal Discovery (NER-1X)',
  'GUPCO',
  'Gulf of Suez (offshore, Eastern Desert region; North-East Ramadan Concession)',
  'Egypt',
  'Gulf of Suez (offshore, Eastern Desert region; North-East Ramadan Concession)',
  28.36,
  33.29,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GUPCO',
  'JV (EGPC + Dragon Oil/ENOC via operating company)',
  'Announced as discovery achieved by GUPCO (joint operations company between EGPC and Dragon Oil).',
  90000,
  1095000,
  'bbl (crude oil; based on ~3,000 bpd estimated init',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back via existing offshore infrastructure (Al-Fanar platform referenced for drilling/early production)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'GUPCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Geisum & Tawila West Area (North Geisum, North-East Geisum, South Geisum, Tawila-West, GNN Geisum)',
  'PetroGulf Misr',
  'Red Sea Governorate / Central Gulf of Suez (offshore, Eastern Desert region; ~70 km NW of Hurghada)',
  'Egypt',
  'Red Sea Governorate / Central Gulf of Suez (offshore, Eastern Desert region; ~70 km NW of Hurghada)',
  27.7,
  33.5,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'PetroGulf Misr',
  'PSC / JV',
  'PetroGulf Misr operates under concession Law No. 93/2007 for Geisum & Tawila West Area between EGPC, Pico GOS Petroleum Company Limited and KUFPEC (Egypt) Limited (percentages not provided on public operator page).',
  690000,
  8395000,
  'bbl (crude oil; based on ~23,000 bopd target plan)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea pipeline network to central processing facilities (CPS ''Geisum Star'')'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'PetroGulf Misr',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Northwest Gemsa Concession (Al Amir Southeast Field / Al Ola extension; Geyad Field)',
  'Vegas Oil & Gas',
  'Red Sea Governorate / Gulf of Suez onshore west side (Eastern Desert region)',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez onshore west side (Eastern Desert region)',
  27.85,
  33.45,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Vegas Oil & Gas',
  'PSC / JV',
  'At start of commercial production (2009): Vegas 50% (operator), Circle Oil 40%, Premier Oil 10% (reported by industry press). Current ownership/operator may have changed; not confirmed in open sources here.',
  129000,
  1569500,
  'bbl (crude oil; based on ~4,300–4,500 bopd initial',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'light oil (reported by industry press)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Connected to Egyptian export pipeline network (name not specified in public report)'],
  ARRAY['Regional Gulf of Suez export terminals (commonly via Ras Shukheir/Ras Gharib area)'],
  ARRAY[]::text[],
  'Vegas Oil & Gas',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Gemsa Petroleum Company & Zaafarana Oil Company Areas (GEMPETCO/ZAFCO producing assets)',
  'Gemsa Petroleum Company',
  'Red Sea Governorate / Gulf of Suez (Eastern Desert region)',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez (Eastern Desert region)',
  27.85,
  33.45,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Gemsa Petroleum Company',
  'state-owned / EGPC sector companies with partners (details vary by development area)',
  'Combined production publicly reported for FY2023/24; North Zafarana Development Area amendments cite EGPC and Cheiron Zaafarana Petroleum Company Ltd., Oceaneer Zaafarana Ltd., and Sahara Oil & Gas Company (exact working interests not provided in open summary).',
  0,
  1700000,
  'bbl (crude oil; combined FY2023/24 total reported)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Regional Gulf of Suez gathering/export system (names not publicly specified)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'Gemsa Petroleum Company',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Zafarana Development Area',
  'Cheiron',
  'Red Sea Governorate / Gulf of Suez (Eastern Desert region)',
  'Egypt',
  'Red Sea Governorate / Gulf of Suez (Eastern Desert region)',
  28.36,
  33.29,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Cheiron',
  'PSC / JV',
  'Amended compliance agreement involves EGPC and Cheiron Zaafarana Petroleum Company Ltd., Oceaneer Zaafarana Ltd., and Sahara Oil & Gas Company; development period extended (duration not stated in open article summary).',
  0,
  0,
  'bbl (crude oil, not disclosed)',
  0,
  'bbl (not publicly stated)',
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Regional Gulf of Suez gathering/export system (names not publicly specified)'],
  ARRAY['Ras Shukheir terminal (regional export hub)'],
  ARRAY[]::text[],
  'Cheiron',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Abu Rudeis Oil Fields (Abu Rudeis Concession)',
  'Petrobel',
  'South Sinai Governorate (Sinai Peninsula)',
  'Egypt',
  'South Sinai Governorate (Sinai Peninsula)',
  28.85,
  33.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Petrobel',
  'JV (EGPC/IEOC Production under petroleum concession/PSC framework)',
  'Petrobel is an operating joint venture between Egyptian General Petroleum Corporation (EGPC) and Eni’s Egypt arm (IEOC Production). Specific equity split varies by agreement/concession and is not consistently disclosed publicly.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown; not publicly disclosed reliably at f',
  NULL,
  NULL,
  'crude oil (quality not publicly disclosed at field level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Regional Gulf of Suez crude gathering/export pipelines (specific line names not consistently disclosed publicly for Abu Rudeis onshore system)'],
  ARRAY['Suez Gulf export terminals (exact export point for Abu Rudeis streams varies; not consistently disclosed)'],
  ARRAY[]::text[],
  'Petrobel',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Sidrī Oilfield (Bir Sidri)',
  'Petrobel',
  'South Sinai Governorate (Sinai Peninsula)',
  'Egypt',
  'South Sinai Governorate (Sinai Peninsula)',
  28.88333,
  33.21667,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Petrobel',
  'JV (EGPC/IEOC Production under petroleum concession/PSC framework)',
  'Operated in the Abu Rudeis area by Petrobel (EGPC/Eni IEOC Production JV). Specific working interests not consistently disclosed publicly.',
  0,
  0,
  'bbl (unknown; not publicly disclosed)',
  0,
  'bbl (unknown; not publicly disclosed)',
  NULL,
  NULL,
  'crude oil (quality not publicly disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Local gathering pipelines to Abu Rudeis processing/export system (details not publicly disclosed)'],
  ARRAY['Suez Gulf export terminals (not consistently disclosed)'],
  ARRAY[]::text[],
  'Petrobel',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Zeit Bay Field (and Ras ElBehar onshore extension)',
  'SUCO',
  'South Sinai Governorate / Gulf of Suez (Sinai side)',
  'Egypt',
  'South Sinai Governorate / Gulf of Suez (Sinai side)',
  28.3,
  33.3,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'SUCO',
  'State-affiliated (EGPC sector company)',
  'SUCO states it operates Zeit Bay field (GOS West Concession) and associated facilities; detailed concession equity not publicly disclosed on SUCO site.',
  0,
  0,
  'bbl (unknown; not publicly disclosed)',
  0,
  'bbl (unknown; not publicly disclosed)',
  NULL,
  NULL,
  'crude oil and gas (quality not disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['6-inch LPG pipeline to GUPCO Ras Shukheir storage area (from Zeit Bay gas plant, per SUCO)'],
  ARRAY['Zeit Bay offshore loading facility (per SUCO third-party services description)', 'Ras Shukheir (GUPCO storage/export area for LPG, per SUCO)'],
  ARRAY[]::text[],
  'SUCO',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Muzhil Field (South Abu Zenima Concession)',
  'Eni',
  'South Sinai Governorate (Sinai Peninsula)',
  'Egypt',
  'South Sinai Governorate (Sinai Peninsula)',
  28.75,
  33.35,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Eni',
  'JV (EGPC + National Petroleum Company)',
  'PetroZenima is a joint venture between EGPC and National Petroleum Company (NPC) to develop the Muzhil Field in South Abu Zenima Concession.',
  0,
  0,
  'bbl (unknown; development/production details not r',
  7000000,
  'bbl (2P estimate reported)',
  NULL,
  NULL,
  'crude oil (quality not disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Two 10-inch pipelines (~13 km each) tying facilities to SUCO Ras Budran (planned/implemented per project description)', 'PPC pipeline (via Ras Budran export routing)'],
  ARRAY['Single Buoy Mooring (SBM) offshore loading (via Ras Budran facilities)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);
