-- ============================================
-- EQUATORIAL GUINEA OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:05:10.622085
-- Total sites: 18
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('GEPetrol', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Marathon Oil', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Trident Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING EQUATORIAL GUINEA DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Equatorial Guinea';

-- ============================================
-- STEP 5: INSERT EQUATORIAL GUINEA SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Zafiro Oil Field (Block B)',
  'GEPetrol',
  'Insular Region (offshore Bioko Island, Gulf of Guinea)',
  'Equatorial Guinea',
  'Insular Region (offshore Bioko Island, Gulf of Guinea)',
  3.8,
  8.07,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GEPetrol',
  'State-led PSC/JV',
  'Historic Block B participants reported as ExxonMobil/Mobil Equatorial Guinea 71.25%, Devon Energy 23.75%, Government of Equatorial Guinea 5% (older structure). GEPetrol purchased Devon''s 23.75% in 2008; PSC reportedly expired and operatorship transferred to GEPetrol in 2024; detailed current WI not publicly consolidated in one authoritative source.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'medium crude (Zafiro Blend)',
  30.2012,
  0.25101,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Zafiro offshore loading via FPU/FPSO (offshore)'],
  ARRAY[]::text[],
  'GEPetrol',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Alba Gas-Condensate Field (offshore north/northwest of Bioko Island; Alba Unit)',
  'Marathon Oil',
  'Insular Region (offshore Bioko Island, Gulf of Guinea)',
  'Equatorial Guinea',
  'Insular Region (offshore Bioko Island, Gulf of Guinea)',
  3.65,
  8.45,
  'Energy',
  'Oil & Gas',
  'offshore_field',
  'active',
  'Marathon Oil',
  'JV/PSC',
  'Working interests reported: Marathon 63% (operator), Noble 34%, GEPetrol 3%.',
  1950000,
  23725000,
  'bbl (condensate)',
  0,
  'bbl',
  NULL,
  NULL,
  'condensate (Alba)',
  53,
  0.02,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Alba offshore pipeline(s) to Punta Europa (Alba Plant/CPF)'],
  ARRAY['Punta Europa (Malabo area) product export terminal'],
  ARRAY[]::text[],
  'Marathon Oil',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ceiba Oil Field (Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea (often serviced via Bioko/Malabo logistics)',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea (often serviced via Bioko/Malabo logistics)',
  1.25,
  9.55,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Trident Energy operates Block G producing fields (Ceiba & Okume Complex) with 40.375% equity share (other partners not fully detailed in the cited asset page). Contract expires 2040-12-31.',
  0,
  0,
  'bbl (oil)',
  250000000,
  'bbl (minimum estimate cited historically)',
  NULL,
  NULL,
  'light crude (Ceiba crude)',
  31.2,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Subsea flowlines to Sendje Ceiba FPSO', 'Export pipeline to CALM buoy (Ceiba Marine Terminal)'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Okume Complex (Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea (often serviced via Bioko/Malabo logistics)',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea (often serviced via Bioko/Malabo logistics)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Okume Complex under Trident Energy operatorship since 2017 (acquired Hess Equatorial Guinea; contract expires 2040-12-31). The complex comprises multiple fields (Okume, Elon, Oveng, Akom North, Ebano).',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO (via subsea/field export system)', 'Export pipeline to CALM buoy (Ceiba Marine Terminal)'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Okume Field (within Okume Complex, Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Block G producing fields operated by Trident Energy; Okume discovered 2001; first oil 2006; contract expires 2040-12-31.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Elon Field (within Okume Complex, Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Named as one of five oil-producing fields comprising the Okume Complex under Trident Energy operatorship.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Oveng Field (within Okume Complex, Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Named as one of five oil-producing fields comprising the Okume Complex under Trident Energy operatorship.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Akom North Field (within Okume Complex, Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Named as one of five oil-producing fields comprising the Okume Complex under Trident Energy operatorship.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ebano Field (within Okume Complex, Block G)',
  'Trident Energy',
  'Río Muni offshore / Gulf of Guinea',
  'Equatorial Guinea',
  'Río Muni offshore / Gulf of Guinea',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'JV/PSC',
  'Named as one of five oil-producing fields comprising the Okume Complex under Trident Energy operatorship.',
  0,
  0,
  'bbl (oil)',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export to Sendje Ceiba FPSO'],
  ARRAY['Ceiba Marine Terminal (CALM buoy/FPSO export, offshore)'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ceiba Field (Block G, Rio Muni Basin)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.25,
  9.55,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Block G PSC extended to 2040. Trident Energy (operator) 40.375% equity; other JV partners include Kosmos Energy, Panoro Energy, GE Petrol (state), and the Ministry of Mines and Hydrocarbons / Government of Equatorial Guinea (state).',
  525000,
  6387500,
  'barrels (oil)',
  19900000,
  'barrels (remaining oil; estimate cited as remainin',
  NULL,
  NULL,
  'medium, sweet crude (Ceiba crude / Ceiba Blend)',
  31.2,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Ceiba subsea flowlines/manifolds to Sendje Ceiba FPSO (export via FPSO offloading system)'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Okume Complex (Block G, Rio Muni Basin)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Okume Complex comprises multiple fields tied to Block G PSC. Trident Energy (operator) 40.375% equity in Block G; JV includes Kosmos Energy, Panoro Energy, GE Petrol (state), and Government of Equatorial Guinea (state). PSC extended to 2040.',
  525000,
  6387500,
  'barrels (oil)',
  59100000,
  'barrels (remaining oil; estimate cited as remainin',
  NULL,
  NULL,
  'unknown (Ceiba Blend export stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['25 km, 12-inch pipeline from Okume CPF (Elon platform CPF) to Ceiba FPSO', 'Inter-field pipelines/flowlines to central processing facility (CPF)'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Okume Field (part of Okume Complex, Block G)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Under Block G PSC (extended to 2040). Trident Energy operates Ceiba and Okume Complex; JV includes Kosmos Energy, Panoro Energy, GE Petrol and Government of Equatorial Guinea.',
  525000,
  6387500,
  'barrels (oil; Block G total ~35 kbopd shared)',
  59100000,
  'barrels (remaining oil; Okume field-specific not i',
  NULL,
  NULL,
  'unknown (exported via Sendje Ceiba FPSO as Ceiba Blend stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Crude exported to Sendje Ceiba FPSO (tie-back export system)', '25 km, 12-inch pipeline from CPF to Ceiba FPSO'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Elon Field (part of Okume Complex, Block G)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Under Block G PSC (extended to 2040). CPF located at an Elon platform; JV includes Trident Energy, Kosmos Energy, Panoro Energy, GE Petrol and Government of Equatorial Guinea.',
  525000,
  6387500,
  'barrels (oil; Block G total ~35 kbopd shared)',
  59100000,
  'barrels (remaining oil; Elon-specific not isolated',
  NULL,
  NULL,
  'unknown (exported via Sendje Ceiba FPSO as Ceiba Blend stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Okume Complex CPF-to-Ceiba FPSO 25 km, 12-inch oil pipeline'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Oveng Field (part of Okume Complex, Block G)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Under Block G PSC (extended to 2040). JV includes Trident Energy, Kosmos Energy, Panoro Energy, GE Petrol and Government of Equatorial Guinea.',
  525000,
  6387500,
  'barrels (oil; Block G total ~35 kbopd shared)',
  59100000,
  'barrels (remaining oil; Oveng-specific not isolate',
  NULL,
  NULL,
  'unknown (exported via Sendje Ceiba FPSO as Ceiba Blend stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Okume Complex CPF-to-Ceiba FPSO 25 km, 12-inch oil pipeline'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ebano Field (part of Okume Complex, Block G)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Under Block G PSC (extended to 2040). JV includes Trident Energy, Kosmos Energy, Panoro Energy, GE Petrol and Government of Equatorial Guinea.',
  525000,
  6387500,
  'barrels (oil; Block G total ~35 kbopd shared)',
  59100000,
  'barrels (remaining oil; Ebano-specific not isolate',
  NULL,
  NULL,
  'unknown (exported via Sendje Ceiba FPSO as Ceiba Blend stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Okume Complex CPF-to-Ceiba FPSO 25 km, 12-inch oil pipeline'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Akom North Field (part of Okume Complex, Block G)',
  'Trident Energy',
  'Offshore Río Muni (Rio Muni Basin)',
  'Equatorial Guinea',
  'Offshore Río Muni (Rio Muni Basin)',
  1.3,
  9.58,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Trident Energy',
  'PSC / JV',
  'Under Block G PSC (extended to 2040). Okume Complex comprises Okume, Elon, Oveng, Akom North and Ebano. JV includes Trident Energy, Kosmos Energy, Panoro Energy, GE Petrol and Government of Equatorial Guinea.',
  525000,
  6387500,
  'barrels (oil; Block G total ~35 kbopd shared)',
  59100000,
  'barrels (remaining oil; Akom North-specific not is',
  NULL,
  NULL,
  'unknown (exported via Sendje Ceiba FPSO as Ceiba Blend stream)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Okume Complex CPF-to-Ceiba FPSO 25 km, 12-inch oil pipeline'],
  ARRAY['Offshore loading via Sendje Ceiba FPSO'],
  ARRAY[]::text[],
  'Trident Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Zafiro Field (Block B)',
  'GEPetrol',
  'Offshore Bioko / Gulf of Guinea (often grouped with Rio Muni offshore region in national production; Block B)',
  'Equatorial Guinea',
  'Offshore Bioko / Gulf of Guinea (often grouped with Rio Muni offshore region in national production;',
  3.8,
  8.0666666667,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GEPetrol',
  'PSC / JV',
  'Historic Block B participants included Mobil Equatorial Guinea Inc. (ExxonMobil subsidiary, operator, 71.25%), Devon Energy 23.75%, and Government of Equatorial Guinea 5% (per 2003 ExxonMobil release). Operatorship transferred to GEPetrol in 2024 per industry reporting; detailed current equity not confirmed in accessible primary sources.',
  0,
  0,
  'barrels (oil)',
  87000000,
  'barrels (remaining oil; estimate)',
  NULL,
  NULL,
  'light/medium sweet crude marketed as Zafiro Blend / New Zafiro Blend (includes Topacio and multiple ',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  5,
  ARRAY[]::text[],
  ARRAY['Serpentina FPSO / offshore loading location (Zafiro Blend load port)', 'Zafiro Terminal (UN/Locode GQZAF)'],
  ARRAY[]::text[],
  'GEPetrol',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Topacio Field (Block B; extension associated with Zafiro / New Zafiro Blend)',
  'GEPetrol',
  'Offshore Bioko / Gulf of Guinea (Block B)',
  'Equatorial Guinea',
  'Offshore Bioko / Gulf of Guinea (Block B)',
  3.8,
  8.0666666667,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'GEPetrol',
  'PSC / JV',
  'Topacio production merged with Zafiro in 2005 to create New Zafiro Blend (produced by MEGI, Ocean Equatorial Guinea Corp and Government of Equatorial Guinea per ExxonMobil crude trading note). Current Block B equity not confirmed in accessible primary sources.',
  0,
  0,
  'barrels (oil; blended as Zafiro Blend)',
  0,
  'barrels (unknown)',
  NULL,
  NULL,
  'medium crude (Topacio test oil gravity)',
  28.5,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Serpentina FPSO / Zafiro Blend load port'],
  ARRAY[]::text[],
  'GEPetrol',
  NULL
);
