-- ============================================
-- GABON OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:05:10.623493
-- Total sites: 50
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN
    RETURN NULL;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
    RETURN date_text::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN
    RETURN (date_text || '-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}$' THEN
    RETURN (date_text || '-01-01')::DATE;
  END IF;
  IF date_text ~ '^[0-9]{4}s$' THEN
    RETURN (SUBSTRING(date_text FROM 1 FOR 4) || '-01-01')::DATE;
  END IF;
  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('Assala Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('BW Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Perenco', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('VAALCO Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING GABON DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Gabon';

-- ============================================
-- STEP 5: INSERT GABON SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Dussafu (Tortue Field)',
  'BW Energy',
  'Offshore (Dussafu Marine Permit)',
  'Gabon',
  'Offshore (Dussafu Marine Permit)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'JV (PSC)',
  'BW Energy Gabon SA 73.5% (operator); Panoro Energy 17.5%; Gabon Oil Company 9%.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Dussafu MaBoMo-to-BW Adolo pipeline (approx. 20 km)'],
  ARRAY['FPSO BW Adolo (offloading to export tankers)'],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Dussafu (Hibiscus Field)',
  'BW Energy',
  'Offshore (Dussafu Marine Permit)',
  'Gabon',
  'Offshore (Dussafu Marine Permit)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'JV (PSC)',
  'BW Energy Gabon SA 73.5% (operator); Panoro Energy 17.5%; Gabon Oil Company 9%.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Hibiscus/Ruche to BW Adolo via MaBoMo-to-BW Adolo pipeline'],
  ARRAY['FPSO BW Adolo (offloading to export tankers)'],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Dussafu (Ruche Field)',
  'BW Energy',
  'Offshore (Dussafu Marine Permit)',
  'Gabon',
  'Offshore (Dussafu Marine Permit)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'JV (PSC)',
  'BW Energy Gabon SA 73.5% (operator); Panoro Energy 17.5%; Gabon Oil Company 9%.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Ruche to BW Adolo via MaBoMo-to-BW Adolo pipeline'],
  ARRAY['FPSO BW Adolo (offloading to export tankers)'],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Dussafu (Hibiscus South Field)',
  'BW Energy',
  'Offshore (Dussafu Marine Permit)',
  'Gabon',
  'Offshore (Dussafu Marine Permit)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'JV (PSC)',
  'BW Energy Gabon SA 73.5% (operator); Panoro Energy 17.5%; Gabon Oil Company 9%.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Hibiscus South to BW Adolo via MaBoMo-to-BW Adolo pipeline'],
  ARRAY['FPSO BW Adolo (offloading to export tankers)'],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Etame Field (Etame Marin Permit)',
  'VAALCO Energy',
  'Offshore (Etame Marin Block)',
  'Gabon',
  'Offshore (Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC consortium (JV)',
  'VAALCO operates Etame Marin block (working interest has varied; company states 58.8% working interest in 2024 corporate site; historical SEC filings show different WI in earlier years). Government back-in carried interest applies (7.5% historically, increasing to 10% in June 2026 per SEC filing).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (Gamba sandstone reservoirs; type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO/FPSO serving Etame Marin block (offloading to export tankers)'],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Avouma / South Tchibala Field Complex (Etame Marin Permit)',
  'VAALCO Energy',
  'Offshore (Etame Marin Block)',
  'Gabon',
  'Offshore (Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC consortium (JV)',
  'VAALCO operates Etame Marin block; consortium partners not fully enumerated in sources reviewed. Government back-in carried interest applies.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (Gamba sands)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO/FPSO serving Etame Marin block (offloading to export tankers)'],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ebouri Field (Etame Marin Permit)',
  'VAALCO Energy',
  'Offshore (Etame Marin Block)',
  'Gabon',
  'Offshore (Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC consortium (JV)',
  'VAALCO operates Etame Marin block; consortium partners not fully enumerated in sources reviewed. Government back-in carried interest applies.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (Gamba sands)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO/FPSO serving Etame Marin block (offloading to export tankers)'],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Southeast Etame Field (Etame Marin Permit)',
  'VAALCO Energy',
  'Offshore (Etame Marin Block)',
  'Gabon',
  'Offshore (Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC consortium (JV)',
  'VAALCO operates Etame Marin block; government back-in carried interest applies.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (Gamba sands)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO/FPSO serving Etame Marin block (offloading to export tankers)'],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Tchibala Field (Etame Marin Permit)',
  'VAALCO Energy',
  'Offshore (Etame Marin Block)',
  'Gabon',
  'Offshore (Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC consortium (JV)',
  'VAALCO operates Etame Marin block. Dentale formation production announced by VAALCO from North Tchibala 1-H.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (Dentale horizon; type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO/FPSO serving Etame Marin block (offloading to export tankers)'],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Hylia Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -1.1,
  8.9,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco is operator. TotalEnergies held 37.5% interest in Hylia prior to divestment; Perenco acquired TotalEnergies interests as part of 2021 closing (exact current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Hylia South West Field (Mono permit discovery tied to Hylia facilities)',
  'Perenco',
  'Offshore (Mono permit)',
  'Gabon',
  'Offshore (Mono permit)',
  -1.1,
  8.9,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco is operator (field produced through tie-in to Hylia platform infrastructure). Specific equity split not disclosed in sources reviewed.',
  180000,
  2190000,
  'bbl (computed from 6,000 bpd reported)',
  20000000,
  'bbl (oil in place estimate, low-end; sources cite ',
  NULL,
  NULL,
  'crude oil (NTO reservoir; also Madiela carbonate tested)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Hylia South West 10 km pipeline tie-in to Hylia facilities'],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Grondin Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.95,
  8.85,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Gonelle Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.98,
  8.87,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Barbier Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.92,
  8.82,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Mandaros Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.9,
  8.8,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Torpille Field (Perenco-operated mature asset included in 2021 divestment)',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.85,
  8.75,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Girelle Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.88,
  8.78,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Pageau Field',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.93,
  8.83,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco operator; TotalEnergies EP Gabon previously held 65.275% interest and divested to Perenco in deal closed 2021-12-09 (current split not fully specified in sources reviewed).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Simba Field (Becuna platform)',
  'Perenco',
  'Offshore',
  'Gabon',
  'Offshore',
  -1.02,
  8.92,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private + state participation (not fully specified)',
  'Perenco is operator (Becuna platform incident March 20, 2024; operations reported resumed August 2024 after approvals).',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Baudroie Mérou Marine II (License G5-143)',
  'TotalEnergies',
  'Offshore',
  'Gabon',
  'Offshore',
  -0.87,
  8.77,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'PSC (operator + state participation)',
  'TotalEnergies EP Gabon 75% (operator); Gabon Oil Company 15% (agreed sale signed 2024-10-15); Gabonese Republic 10%.',
  0,
  0,
  'bbl',
  0,
  'bbl',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Lucina Field',
  'Perenco',
  'Offshore (Block Lucina)',
  'Gabon',
  'Offshore (Block Lucina)',
  -1.05,
  8.95,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'inactive',
  'Perenco',
  'private + state participation (reported)',
  'Perenco Holdings and Societe Nationale Petroliere Gabonaise (as reported by Offshore-Technology/GlobalData).',
  0,
  0,
  'bbl',
  70000,
  'bbl (remaining recoverable reserve reported)',
  NULL,
  NULL,
  'crude oil (type not disclosed in sources reviewed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Anguille (Grand Anguille Marine concession)',
  'TotalEnergies',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.8,
  8.72,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'private (concession)',
  'Wholly owned by Total Gabon per historical disclosures (Grand Anguille Marine concession).',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Mandji/Anguille system; type not precisely specified in public sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  25,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Île Mandji (Onshore Île Mandji)',
  'TotalEnergies',
  'Ogooué-Maritime (Port-Gentil / Île Mandji)',
  'Gabon',
  'Ogooué-Maritime (Port-Gentil / Île Mandji)',
  -0.72,
  8.78,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TotalEnergies',
  'private (concession)',
  'Listed by Total as operated asset (100% op) in Île Mandji area; detailed partners not specified in available public source snippet.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Mandji quality marketed by TotalEnergies EP Gabon)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Torpille (Torpille sector)',
  'TotalEnergies',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.85,
  8.75,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'private (concession)',
  'TotalEnergies EP Gabon reports Torpille as a producing site with planned shutdowns in 2025; detailed partner split not provided in the cited quarterly note.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Torpille sector)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Torpille Nord Est',
  'TotalEnergies',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.85,
  8.75,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'private (concession)',
  'Listed by Total as an operated offshore asset in the Torpille area; partner details not provided in the referenced disclosure snippet.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Baudroie-Mérou',
  'TotalEnergies',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.87,
  8.77,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TotalEnergies',
  'JV (concession)',
  'Listed by Total as 50% operated asset; counterparty not specified in the referenced disclosure snippet.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Grondin',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.95,
  8.85,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field; TotalEnergies EP Gabon divested its 65.275% non-operated interest to Perenco with closing in 2021 (implying Perenco as owner/operator post-deal).',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Gonelle',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.98,
  8.87,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field; TotalEnergies EP Gabon divested its 65.275% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Barbier',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.92,
  8.82,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field; TotalEnergies EP Gabon divested its 65.275% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Mandaros',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.9,
  8.8,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field; TotalEnergies EP Gabon divested its 65.275% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Girelle',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.88,
  8.78,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field (part of Torpille area divestment package); TotalEnergies EP Gabon divested 65.275% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Pageau',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -0.93,
  8.83,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated mature offshore field (part of Torpille area divestment package); TotalEnergies EP Gabon divested 65.275% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Hylia',
  'Perenco',
  'Ogooué-Maritime (offshore Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil)',
  -1.1,
  8.9,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'JV',
  'Perenco-operated offshore field; TotalEnergies EP Gabon divested its 37.5% non-operated interest to Perenco with closing in 2021.',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  350000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Tortue (Dussafu Marin license)',
  'BW Energy',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'PSC',
  'Dussafu PSC: BW Energy 73.5% (operator), Panoro Energy 17.5%, Gabon Oil Company 9% (as disclosed for Dussafu). Production to FPSO BW Adolo adjacent to Tortue.',
  0,
  0,
  'bbl (license/field volumes vary; not specified per',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Gamba reservoir; type not specified in cited source)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Subsea pipelines to FPSO BW Adolo (Dussafu hub)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Hibiscus (Dussafu Marin license)',
  'BW Energy',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'PSC',
  'Dussafu PSC: BW Energy 73.5% (operator), Panoro Energy 17.5%, Gabon Oil Company 9%. Hibiscus produces via MaBoMo facility and pipelines to FPSO BW Adolo for processing/storage/offloading.',
  0,
  0,
  'bbl (varies; wells reported ~6,000–6,500 bpd each ',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Gamba sandstone reservoir)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Pipeline from MaBoMo facility to FPSO BW Adolo'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ruche (Dussafu Marin license)',
  'BW Energy',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  'Gabon',
  'Ogooué-Maritime (offshore Port-Gentil / Dussafu Marin)',
  -2.85,
  9.35,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'BW Energy',
  'PSC',
  'Dussafu PSC: BW Energy 73.5% (operator), Panoro Energy 17.5%, Gabon Oil Company 9%. Ruche is within the Ruche Exclusive Exploitation Area and tied into BW Adolo via the Dussafu hub.',
  0,
  0,
  'bbl (unknown/varies; part of Hibiscus/Ruche develo',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'crude oil (Gamba reservoir)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  20,
  ARRAY['Subsea/tie-back pipelines to FPSO BW Adolo (Dussafu hub)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'BW Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ompoyi',
  'Perenco',
  'Ogooué-Maritime (near Port-Gentil; onshore/offshore system south of Port-Gentil)',
  'Gabon',
  'Ogooué-Maritime (near Port-Gentil; onshore/offshore system south of Port-Gentil)',
  -1.15,
  8.95,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Perenco',
  'private/JV (license)',
  'Operated by Perenco; discovery well GSA-1 (2002) reported OOIP estimate publicly; detailed partner split not in cited source snippet.',
  0,
  0,
  'bbl (unknown/varies)',
  85000000,
  'bbl OOIP (public estimate)',
  NULL,
  NULL,
  '"dry" oil (as tested by discovery well)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Fernan Vaz FSO (export route for Perenco barrels - hub-level)', 'Mayumba/Banio FSO (export route for Perenco barrels - hub-level)', 'Cap Lopez Oil Terminal (Port-Gentil area)'],
  ARRAY[]::text[],
  'Perenco',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Gamba/Ivinga (Gamba Complex)',
  'Assala Energy',
  'Ogooué-Maritime (Ndougou Department / Gamba area)',
  'Gabon',
  'Ogooué-Maritime (Ndougou Department / Gamba area)',
  -2.689925,
  9.975681,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Field is owned by the Gabonese Republic; operated under the Gamba-Ivinga production licence (Assala Gabon historically; GOC acquired Assala Energy in 2024).',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Rabi-to-Gamba onshore pipeline system (export pipeline network to Gamba terminal)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Totou (satellite within Bende/M’Bassou/Totou licence)',
  'Assala Energy',
  'Ogooué-Maritime (Gamba region, onshore)',
  'Gabon',
  'Ogooué-Maritime (Gamba region, onshore)',
  -2.65,
  9.92,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Part of the Bende/M’Bassou/Totou production licence included in Shell’s onshore portfolio sold to Assala (2017) and later acquired by GOC (2024). Totou was shut-in in 1996 and brought back onstream in 2000.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline network to Gamba export terminal (via Shell/Assala/GOC infrastructure)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Bende (within Bende/M’Bassou/Totou licence)',
  'Assala Energy',
  'Ogooué-Maritime (Gamba region, onshore)',
  'Gabon',
  'Ogooué-Maritime (Gamba region, onshore)',
  -2.65,
  9.92,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Part of Shell’s onshore operated fields sold to Assala in 2017 as the Bende/M’Bassou/Totou operated field grouping; later acquired by GOC in 2024.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline network to Gamba export terminal (via Shell/Assala/GOC infrastructure)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'M’Bassou (within Bende/M’Bassou/Totou licence)',
  'Assala Energy',
  'Ogooué-Maritime (Gamba region, onshore)',
  'Gabon',
  'Ogooué-Maritime (Gamba region, onshore)',
  -2.65,
  9.92,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Part of Shell’s onshore operated fields sold to Assala in 2017 as the Bende/M’Bassou/Totou operated field grouping; later acquired by GOC in 2024.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline network to Gamba export terminal (via Shell/Assala/GOC infrastructure)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Rabi-Kounga (Rabi)',
  'Assala Energy',
  'Ogooué-Maritime (southern Gabon onshore; near Gamba region)',
  'Gabon',
  'Ogooué-Maritime (southern Gabon onshore; near Gamba region)',
  -2.0,
  9.95,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Discovered 1985; started production 1989. Included in Shell’s onshore operated fields sold to Assala (2017) and later acquired by GOC (2024). Historic partners reported include Total and Hess (historic). Proven reserves reported around 440 million bbl (historic).',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  440000000,
  'bbl (historic proven reserves reported)',
  NULL,
  NULL,
  'Conventional oil (reservoirs in Gamba and Dentale formations; crude commonly marketed as ''Rabi Ligh',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Rabi-to-Gamba onshore pipeline system'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Toucan/Robin',
  'Assala Energy',
  'Ogooué-Maritime (Gamba region, onshore)',
  'Gabon',
  'Ogooué-Maritime (Gamba region, onshore)',
  -2.55,
  9.85,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Part of Shell’s onshore operated fields sold to Assala in 2017 (Toucan/Robin), later acquired by GOC in 2024.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline network to Gamba export terminal (via Shell/Assala/GOC infrastructure)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Koula/Damier',
  'Assala Energy',
  'Ogooué-Maritime (Gamba region, onshore)',
  'Gabon',
  'Ogooué-Maritime (Gamba region, onshore)',
  -2.5,
  9.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Assala Energy',
  'State-owned resource with operator under production licence (historic private operator; now state-ow',
  'Part of Shell’s onshore operated fields sold to Assala in 2017 (Koula/Damier), later acquired by GOC in 2024.',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline network to Gamba export terminal (via Shell/Assala/GOC infrastructure)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'Assala Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Atora (Atora II licence)',
  'TotalEnergies',
  'Ogooué-Maritime (Gamba region / near Gamba terminal catchment)',
  'Gabon',
  'Ogooué-Maritime (Gamba region / near Gamba terminal catchment)',
  -2.45,
  9.75,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TotalEnergies',
  'JV / state-owned resource with multiple participants under production licence',
  'Reported as a non-operated field interest in Shell’s onshore portfolio transferred to Assala in 2017; Assala lists Atora II as a (non-operated) production licence in its portfolio. Third-party reporting indicates Atora field production exports via the Gamba terminal (historic).',
  0,
  0,
  'bbl (unknown; not publicly disclosed at field leve',
  0,
  'bbl (unknown)',
  NULL,
  NULL,
  'Conventional oil (type not publicly specified in accessible sources)',
  NULL,
  NULL,
  NULL,
  628000000,
  'USD',
  NULL,
  25,
  ARRAY['Onshore pipeline/terminal access to Gamba export terminal (exact line names not publicly specified in accessible sources)'],
  ARRAY['Gamba Southern export terminal (Gamba Sud)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Etame (Etame Marin Block)',
  'VAALCO Energy',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  'Gabon',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC / JV (percentages not fully confirmed in accessible sources for current year)',
  'Etame Marin Block is a PSC-operated offshore block with multiple producing fields; Etame is one of the producing fields. Block-level production since inception reported >120 million bbl; remaining reserves/resources ~113 million bbl (block-level).',
  0,
  0,
  'bbl (unknown; field-level volumes not reliably ava',
  113000000,
  'bbl (block-level remaining reserves/resources esti',
  NULL,
  NULL,
  'Conventional offshore crude (Dentale and Gamba formations referenced at block level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Avouma/South Tchibala (Etame Marin Block)',
  'VAALCO Energy',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  'Gabon',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC / JV (percentages not fully confirmed in accessible sources for current year)',
  'Producing fields in the Etame Marin Block include Avouma/South Tchibala. Block-level remaining reserves/resources ~113 million bbl (estimate).',
  0,
  0,
  'bbl (unknown; field-level volumes not reliably ava',
  113000000,
  'bbl (block-level remaining reserves/resources esti',
  NULL,
  NULL,
  'Conventional offshore crude (Dentale and Gamba formations referenced at block level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'North Tchibala (Etame Marin Block)',
  'VAALCO Energy',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  'Gabon',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC / JV (percentages not fully confirmed in accessible sources for current year)',
  'Producing fields in the Etame Marin Block include North Tchibala. Block-level remaining reserves/resources ~113 million bbl (estimate).',
  0,
  0,
  'bbl (unknown; field-level volumes not reliably ava',
  113000000,
  'bbl (block-level remaining reserves/resources esti',
  NULL,
  NULL,
  'Conventional offshore crude (Dentale and Gamba formations referenced at block level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Ebouri (Etame Marin Block)',
  'VAALCO Energy',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  'Gabon',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC / JV (percentages not fully confirmed in accessible sources for current year)',
  'Producing fields in the Etame Marin Block include Ebouri. Block-level remaining reserves/resources ~113 million bbl (estimate).',
  0,
  0,
  'bbl (unknown; field-level volumes not reliably ava',
  113000000,
  'bbl (block-level remaining reserves/resources esti',
  NULL,
  NULL,
  'Conventional offshore crude (Dentale and Gamba formations referenced at block level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  estimated_reserves,
  reserves_unit,
  start_date,
  closing_date,
  quality_type,
  api_gravity,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Southeast Etame (Etame Marin Block)',
  'VAALCO Energy',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  'Gabon',
  'Offshore Ogooué-Maritime (near Gamba region offshore; Etame Marin Block)',
  -1.95,
  9.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'VAALCO Energy',
  'PSC / JV (percentages not fully confirmed in accessible sources for current year)',
  'Producing fields in the Etame Marin Block include Southeast Etame. Block-level remaining reserves/resources ~113 million bbl (estimate).',
  0,
  0,
  'bbl (unknown; field-level volumes not reliably ava',
  113000000,
  'bbl (block-level remaining reserves/resources esti',
  NULL,
  NULL,
  'Conventional offshore crude (Dentale and Gamba formations referenced at block level)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'VAALCO Energy',
  NULL
);
