-- ============================================
-- COMPLETE ALGERIA OIL FIELDS IMPORT (39 sites)
-- Generated from: Algeria_all_sites.json
-- Generated date: 2026-01-21 21:43:45
-- ============================================

-- Helper function to parse date strings
CREATE OR REPLACE FUNCTION parse_site_date(date_str TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_str IS NULL OR date_str = 'unknown' OR date_str = '' THEN
    RETURN NULL;
  END IF;
  
  BEGIN
    RETURN date_str::DATE;
  EXCEPTION WHEN OTHERS THEN
    IF date_str ~ '^\d{4}$' THEN
      RETURN (date_str || '-01-01')::DATE;
    END IF;
    IF date_str ~ '^\d{4}-\d{2}$' THEN
      RETURN (date_str || '-01')::DATE;
    END IF;
    RETURN NULL;
  END;
END;
$$ LANGUAGE plpgsql;

-- Function to extract primary company name from operator string
CREATE OR REPLACE FUNCTION extract_primary_company(operator_text TEXT)
RETURNS TEXT AS $$
BEGIN
  IF operator_text IS NULL OR operator_text = '' THEN
    RETURN NULL;
  END IF;
  
  IF operator_text ILIKE '%Sonatrach%' THEN
    RETURN 'Sonatrach';
  END IF;
  IF operator_text ILIKE '%Cepsa%' THEN
    RETURN 'Cepsa';
  END IF;
  IF operator_text ILIKE '%Eni%' AND operator_text NOT ILIKE '%Groupement%' THEN
    RETURN 'Eni';
  END IF;
  IF operator_text ILIKE '%Occidental%' OR operator_text ILIKE '%Oxy%' OR operator_text ILIKE '%Anadarko%' THEN
    RETURN 'Occidental Petroleum';
  END IF;
  IF operator_text ILIKE '%Total%' OR operator_text ILIKE '%TotalEnergies%' THEN
    RETURN 'TotalEnergies';
  END IF;
  IF operator_text ILIKE '%Repsol%' THEN
    RETURN 'Repsol';
  END IF;
  IF operator_text ILIKE '%BP%' AND operator_text NOT ILIKE '%Groupement%' THEN
    RETURN 'BP';
  END IF;
  IF operator_text ILIKE '%PTTEP%' THEN
    RETURN 'PTTEP';
  END IF;
  IF operator_text ILIKE '%Petrovietnam%' THEN
    RETURN 'Petrovietnam';
  END IF;
  IF operator_text ILIKE '%Wintershall%' THEN
    RETURN 'Wintershall Dea';
  END IF;
  IF operator_text ILIKE '%Groupement Berkine%' THEN
    RETURN 'Groupement Berkine';
  END IF;
  IF operator_text ILIKE '%Organisation Ourhoud%' THEN
    RETURN 'Organisation Ourhoud';
  END IF;
  IF operator_text ILIKE '%Groupement Reggane Nord%' OR operator_text ILIKE '%GRN%' THEN
    RETURN 'Groupement Reggane Nord';
  END IF;
  IF operator_text ILIKE '%Groupement Isarene%' THEN
    RETURN 'Groupement Isarene';
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Insert/update companies from operators
INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('Sonatrach', 'producer', 'Algeria', ARRAY['Crude Oil', 'Natural Gas']),
  ('Cepsa', 'producer', 'Spain', ARRAY['Crude Oil', 'Natural Gas']),
  ('Eni', 'producer', 'Italy', ARRAY['Crude Oil', 'Natural Gas']),
  ('Occidental Petroleum', 'producer', 'United States', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'France', ARRAY['Crude Oil', 'Natural Gas']),
  ('Repsol', 'producer', 'Spain', ARRAY['Crude Oil', 'Natural Gas']),
  ('BP', 'producer', 'United Kingdom', ARRAY['Crude Oil', 'Natural Gas']),
  ('PTTEP', 'producer', 'Thailand', ARRAY['Crude Oil', 'Natural Gas']),
  ('Petrovietnam', 'producer', 'Vietnam', ARRAY['Crude Oil', 'Natural Gas']),
  ('Wintershall Dea', 'producer', 'Germany', ARRAY['Crude Oil', 'Natural Gas']),
  ('Groupement Berkine', 'producer', 'Algeria', ARRAY['Crude Oil']),
  ('Organisation Ourhoud', 'producer', 'Algeria', ARRAY['Crude Oil']),
  ('Groupement Reggane Nord', 'producer', 'Algeria', ARRAY['Natural Gas']),
  ('Groupement Isarene', 'producer', 'Algeria', ARRAY['Natural Gas'])
ON CONFLICT (name) DO UPDATE SET
  commodities_traded = EXCLUDED.commodities_traded;

-- Delete existing Algeria entries to avoid duplicates
DELETE FROM public.commodity_locations WHERE country = 'Algeria';

-- Insert all Algeria sites
INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  country,
  region,
  latitude,
  longitude,
  commodity_type,
  commodity_name,
  location_type,
  operational_status,
  operator,
  ownership_type,
  ownership_details,
  production_monthly,
  production_yearly,
  production_unit,
  current_production,
  reserves_estimate,
  reserves_unit,
  start_date,
  closing_date,
  api_gravity,
  quality_type,
  quality_sulfur_content,
  grade,
  last_transaction_value,
  last_transaction_currency,
  last_transaction_date,
  contract_duration_years,
  pipelines,
  ports,
  rail_connections,
  company,
  additional_info
) VALUES
(
  'Hassi Messaoud Oil Field',
  'Sonatrach',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Operated and owned by Sonatrach (national oil company).',
  10675000,
  129844000,
  'barrels (crude oil)',
  129844000,
  6400000000,
  'barrels',
  parse_site_date('1960'),
  NULL,
  44.5,
  'Light sweet (Saharan Blend typical)',
  NULL,
  'Light sweet',
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Hassi Messaoud crude pipeline network to coastal refineries/terminals (Algiers, Arzew, Béjaïa, Skikda)'],
  ARRAY['Arzew', 'Béjaïa', 'Skikda'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Hassi Berkine Complex (HB / HBNS area, Blocks 403/404)',
  'Groupement Berkine / Sonatrach (operatorship historically with Sonatrach and partners; assets associated with Blocks 404A and 208)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Groupement Berkine / Sonatrach (operatorship historically with Sonatrach and partners; assets associated with Blocks 404A and 208)',
  'JV / PSC-style partnership (Sonatrach majority, foreign minority)',
  'Public sources associate the greater Berkine system with Sonatrach plus Occidental (ex-Anadarko), TotalEnergies, Eni and others; one widely cited structure for the consortium is Sonatrach 51%, Anadarko/Oxy 24.5%, and two 12.25% partners (historically Maersk and Eni/Lasmo/Total depending on licence). Exact ownership varies by block/field and over time.',
  2281250,
  27750000,
  'barrels (crude oil)',
  27750000,
  0,
  'barrels',
  parse_site_date('2002-01-15'),
  NULL,
  NULL,
  'Crude oil (conventional)',
  NULL,
  NULL,
  4000000000,
  'USD',
  parse_site_date('2022-07-19'),
  NULL,
  ARRAY['Nezla pipeline (crude export line referenced for Berkine system exports)'],
  ARRAY['Arzew', 'Skikda', 'Béjaïa'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Rhourde El Baguel Oil Field (REB)',
  'Sonatrach (with historical BP participation under PSC)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach (with historical BP participation under PSC)',
  'JV / PSC (historical)',
  'Commonly cited participation: Sonatrach 70% and BP 30% (historical); PSC reported as 25 years signed in 1996 for EOR/redevelopment (public accounts vary; later disputes/arbitration reported).',
  608333,
  7400000,
  'barrels (crude oil)',
  7400000,
  3000000000,
  'barrels',
  parse_site_date('1963'),
  NULL,
  40.2,
  'Light (Cambrian reservoir crude)',
  NULL,
  'Light',
  1300000000,
  'USD',
  parse_site_date('1996-02-15'),
  25,
  ARRAY['Regional gathering/export pipelines via Hassi Messaoud hub (specific line names not consistently disclosed publicly)'],
  ARRAY['Arzew', 'Skikda', 'Béjaïa'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Rhourde El Khrouf Oil Field (RKF)',
  'Sonatrach-Cepsa (as commonly reported in field profiles)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach-Cepsa (as commonly reported in field profiles)',
  'JV',
  'Owned by Sonatrach and Compañía Española de Petróleos (Cepsa) per industry field profiles; percentages not consistently available in open sources.',
  0,
  0,
  'barrels (crude oil)',
  0,
  0,
  'barrels',
  parse_site_date('2002'),
  NULL,
  NULL,
  'Crude oil (conventional)',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Berkine basin export pipeline network (to Hassi Messaoud/coastal export system)'],
  ARRAY['Arzew', 'Skikda', 'Béjaïa'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'El Merk Field (Block 208 development cluster)',
  'Sonatrach (with Occidental/ex-Anadarko, Eni and other partners depending on block/field segment)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach (with Occidental/ex-Anadarko, Eni and other partners depending on block/field segment)',
  'JV / PSC-style partnership',
  'Public sources describe El Merk as part of the Sonatrach–Anadarko (now Oxy) partnership on Block 208, with other partners referenced historically including Eni and others; ownership percentages vary across licences/segments and over time.',
  3041667,
  37000000,
  'barrels (crude oil; approximate gross liquids basis derived from public bpd references)',
  37000000,
  120000000,
  'barrels',
  parse_site_date('2013'),
  NULL,
  NULL,
  'Crude oil + condensate/LPG system (liquids-rich development)',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export pipelines associated with Block 208/212 hub processing and Berkine export system'],
  ARRAY['Arzew', 'Skikda', 'Béjaïa'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Gassi Touil (oil and gas/condensate producing area)',
  'Sonatrach',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  30.516667,
  6.466667,
  'Energy',
  'Crude Oil',
  'oil_and_gas_field',
  'active',
  'Sonatrach',
  'state-owned (project history includes terminated foreign LNG development contract)',
  'Field operated by Sonatrach; LNG development contract by Repsol/Gas Natural was terminated in 2007 and Sonatrach pursued development.',
  0,
  0,
  'barrels (oil/condensate)',
  0,
  0,
  'barrels',
  parse_site_date('2009'),
  NULL,
  NULL,
  'Gas/condensate with associated oil (onshore)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2007'),
  NULL,
  ARRAY['Gas pipelines associated with Gassi Touil development toward processing/liquefaction projects (Djedid referenced in public descriptions)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Zemlet El Arbi Oil and Gas Field',
  'unknown',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  31.33,
  8.2,
  'Energy',
  'Crude Oil',
  'oil_and_gas_field',
  'active',
  'unknown',
  'unknown',
  'Listed in open extraction trackers with approximate coordinates; operator/owners not consistently disclosed in open sources.',
  0,
  0,
  'barrels (oil/condensate)',
  0,
  0,
  'barrels',
  NULL,
  NULL,
  NULL,
  'Conventional oil and gas (as classified in open extraction trackers)',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Regional gathering/export pipelines via Hassi Messaoud/Berkine hubs (not publicly specified for this field)'],
  ARRAY['Arzew', 'Skikda', 'Béjaïa'],
  ARRAY[]::TEXT[],
  NULL,
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Hassi R''Mel gas field (incl. oil rim/condensate system)',
  'Sonatrach',
  'Laghouat Province (Wilaya de Laghouat), Algeria',
  'Algeria',
  'Laghouat Province (Wilaya de Laghouat)',
  32.944117,
  3.260254,
  'Energy',
  'Natural Gas',
  'oil_and_gas_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Sonatrach (NOC) operated; no consistent public breakdown for Hassi R''Mel field equity reported in open sources.',
  0,
  0,
  'unknown (field produces gas + condensate; liquids not consistently reported as bbl)',
  0,
  7000000,
  'tonnes condensate (incremental recovery targeted by Boosting Project; not total remaining field reserves)',
  parse_site_date('1961'),
  NULL,
  NULL,
  'condensate/light liquids + natural gas (Triassic reservoirs)',
  NULL,
  'condensate/light liquids + natural gas',
  2300000000,
  'USD',
  parse_site_date('2024-05'),
  NULL,
  ARRAY['Hassi R’Mel–Arzew (condensate/LPG network via Sonatrach; specific line names not consistently published)', 'Hassi R’Mel–Arzew gas trunkline', 'Hassi R’Mel–Skikda gas trunkline', 'Hassi R’Mel–Algiers gas trunkline', 'Trans-Mediterranean (Transmed/Enrico Mattei) export pipeline system (feed)', 'Medgaz export pipeline system (feed)', 'Maghreb-Europe (GME) export pipeline system (feed)'],
  ARRAY['Arzew (LNG/export complex)', 'Skikda (LNG/export complex)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Oued Noumer Oil and Gas Field',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area / Oued Mya Basin), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area / Oued Mya Basin)',
  32.608,
  3.703,
  'Energy',
  'Crude Oil',
  'oil_and_gas_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Operated by Sonatrach; ownership structure not publicly detailed in open sources.',
  0,
  0,
  'unknown (public field-level liquids volumes not found in open sources)',
  0,
  0,
  'unknown',
  parse_site_date('1969'),
  NULL,
  NULL,
  'oil + associated gas / condensate (conventional)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Sonatrach Hassi R’Mel area gathering systems', 'Liquids/LPG/condensate pipelines linking Hassi R’Mel area to Arzew (network referenced by Sonatrach/industry summaries)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Aït Kheir (Ait Kheir) field (Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Listed as a major field operated by Sonatrach; detailed equity/contract terms not found in open sources.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  parse_site_date('1971'),
  NULL,
  NULL,
  'oil + gas/condensate (conventional)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Hassi R’Mel area gathering/processing system', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Sidi Merghich (Sidi Mezghich) field (Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Included in Hassi R’Mel area field lists; detailed ownership/contract terms not found in open sources.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  parse_site_date('1976'),
  NULL,
  NULL,
  'oil + gas/condensate (conventional)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Hassi R’Mel area gathering/processing system', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Matou Makouda field (Oued Noumer sector, Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Listed within the Oued Noumer sector under the Hassi R’Mel area; no public equity split found.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  parse_site_date('1975'),
  NULL,
  NULL,
  'oil + gas/condensate (conventional)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Oued Noumer sector processing/gathering (Hassi R’Mel area)', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Sidi Mezghich field (Oued Noumer sector, Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Listed within the Oued Noumer sector under the Hassi R’Mel area; no public equity split found.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  parse_site_date('1976'),
  NULL,
  NULL,
  'oil + gas/condensate (conventional)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Oued Noumer sector processing/gathering (Hassi R’Mel area)', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Djebel Bissa field (Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Included in Hassi R’Mel area field lists; no field-level ownership/contract terms found in open sources.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  NULL,
  NULL,
  NULL,
  'oil + gas/condensate (conventional; field-level crude specs not found)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Hassi R’Mel area gathering/processing system', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Makouda field (Hassi R’Mel area)',
  'Sonatrach',
  'Laghouat Province (Hassi R''Mel area), Algeria',
  'Algeria',
  'Laghouat Province (Hassi R''Mel area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Included in Hassi R’Mel area field lists; no field-level ownership/contract terms found in open sources.',
  0,
  0,
  'unknown',
  0,
  0,
  'unknown',
  NULL,
  NULL,
  NULL,
  'oil + gas/condensate (conventional; field-level crude specs not found)',
  NULL,
  NULL,
  NULL,
  'unknown',
  NULL,
  NULL,
  ARRAY['Connected to Hassi R’Mel area gathering/processing system', 'Liquids/LPG/condensate export network to Arzew (regional system)'],
  ARRAY['Arzew (via pipeline network)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Ourhoud Oil Field (ORD)',
  'Organisation Ourhoud (Sonatrach with partners incl. Cepsa)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  31.744302,
  6.042944,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Organisation Ourhoud (Sonatrach with partners incl. Cepsa)',
  'JV / PSC',
  'Consortium led with Sonatrach; Cepsa is operator in partnership with Sonatrach (exact current % varies by source/time; widely cited that Sonatrach and Cepsa are major partners).',
  0,
  0,
  'bbl (crude oil)',
  0,
  2300000000,
  'bbl',
  parse_site_date('2002-11-01'),
  NULL,
  40,
  'light crude oil',
  NULL,
  'light crude oil',
  NULL,
  'USD',
  parse_site_date('2018-03-08'),
  25,
  ARRAY['Field gathering/export system to regional processing/export network (Berkine Basin)'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Hassi Berkine South (HBNS) Oil Field',
  'Sonatrach / Anadarko (historic); today under Sonatrach with partners in Berkine PSC (incl. Oxy/Eni/TotalEnergies)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach / Anadarko (historic); today under Sonatrach with partners in Berkine PSC (incl. Oxy/Eni/TotalEnergies)',
  'PSC / JV',
  'Part of Berkine PSC area (Blocks 404a/208) operated with Sonatrach and partners (Occidental/Oxy, Eni, TotalEnergies).',
  0,
  0,
  'bbl (crude oil)',
  0,
  0,
  'bbl',
  parse_site_date('1998-05-05'),
  NULL,
  NULL,
  'crude oil (type not consistently published per-field)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-07-19'),
  25,
  ARRAY['HBNS Central Processing Facility (CPF) export facilities (field gathering, crude storage and export)'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Hassi Berkine (HBN) Oil Field',
  'Unitized between Block 404 (Sonatrach/Anadarko) and Block 403 (Sonatrach/Agip/Eni)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Unitized between Block 404 (Sonatrach/Anadarko) and Block 403 (Sonatrach/Agip/Eni)',
  'Unitized JV / PSC',
  'Unitized field across Blocks 404 and 403; historically Anadarko ~74.5% and Agip/Eni ~25.5% on the unitized field with Sonatrach participation per contractual terms.',
  0,
  0,
  'bbl (crude oil)',
  0,
  0,
  'bbl',
  parse_site_date('2002-01-15'),
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2002-01-15'),
  NULL,
  ARRAY['Processed through HBNS CPF production trains; crude storage and export facilities installed'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Hassi Berkine Complex (incl. Hassi Berkine/Hassi Berkine South/Satellites; Blocks 403/404/404a/208 perimeter)',
  'Groupement Berkine (Sonatrach with international partners)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Groupement Berkine (Sonatrach with international partners)',
  'PSC / JV',
  'Owned/participated by Sonatrach with Eni, Occidental (Oxy), TotalEnergies (per public sources). PSC extended 25 years in 2022 for Blocks 404a and 208.',
  0,
  0,
  'bbl (crude oil)',
  0,
  0,
  'bbl',
  parse_site_date('1998'),
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  4000000000,
  'USD',
  parse_site_date('2022-07-19'),
  25,
  ARRAY['Regional gathering and export system (Berkine Basin)'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'El Merk (El-Merk/EMK) Oil Field & Hub (Block 208 / Block 405a unitized portions)',
  'Groupement Berkine (Sonatrach with partners; historically Anadarko as key developer)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Groupement Berkine (Sonatrach with partners; historically Anadarko as key developer)',
  'JV / PSC / Unitized (multi-block)',
  'El Merk hub processes hydrocarbons from multiple Berkine Basin fields/blocks; developed/operated through Groupement Berkine with Sonatrach and international partners (commonly cited: Anadarko, Eni, Maersk, Talisman among participants depending on block/asset).',
  0,
  0,
  'bbl (crude oil; plus condensate/LPG associated with hub)',
  0,
  0,
  'bbl',
  parse_site_date('2013'),
  NULL,
  NULL,
  'crude oil and liquids from wet-gas processing',
  NULL,
  NULL,
  2226000000,
  'USD',
  parse_site_date('2013-01-06'),
  NULL,
  ARRAY['El Merk CPF: regional gathering pipelines for incoming field streams', 'Export pipelines from CPF to national export network (tie-in not consistently published in open sources)'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Menzel Ledjmet East (MLE) Wet Gas & Condensate Field (Block 405b)',
  'Eni / Sonatrach (jointly operated)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Eni / Sonatrach (jointly operated)',
  'JV / PSC',
  'Commonly reported as Eni majority with Sonatrach minority in Block 405b development (public sources often cite Eni 75% / Sonatrach 25%).',
  450000,
  5475000,
  'bbl (oil+condensate+LPG liquids, nameplate as of start-up)',
  5475000,
  1300000000000,
  'scf recoverable gas (plus associated liquids)',
  parse_site_date('2013-01-31'),
  NULL,
  NULL,
  'wet gas + condensate + LPG (+ some oil)',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2008-12-01'),
  NULL,
  ARRAY['Dry gas and liquids pipelines to tie-in on national pipeline grid ~140 km west of Block 405b'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Rhourde El Krouf (RKF) Oil Field (Rhourde Yacoub Block 406a)',
  'Cepsa / Sonatrach (per long-running JV/contract references)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Cepsa / Sonatrach (per long-running JV/contract references)',
  'JV / PSC',
  'Long-running Sonatrach–Cepsa association on Block 406a (Rhourde Yacoub perimeter); RKF discovered 1992 and brought on-stream 31 May 1996.',
  600000,
  7300000,
  'bbl (crude oil)',
  7300000,
  1500000000,
  'bbl recoverable (reported historical estimate)',
  parse_site_date('1996-05-31'),
  NULL,
  51,
  'light crude oil',
  NULL,
  'light crude oil',
  1200000000,
  'USD',
  parse_site_date('2018-01-01'),
  NULL,
  ARRAY['Field export via Berkine Basin gathering/export network'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Bir Seba Oil Field (Blocks 433a & 416b)',
  'PTTEP (with Sonatrach and Petrovietnam partners)',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'PTTEP (with Sonatrach and Petrovietnam partners)',
  'JV',
  'Joint venture partners: Sonatrach, PTTEP, and Petrovietnam (percentages not provided in cited open press release).',
  600000,
  7300000,
  'bbl (crude oil)',
  7300000,
  0,
  'bbl',
  parse_site_date('2015-10-27'),
  NULL,
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2015-10-27'),
  NULL,
  ARRAY['Central Processing Facility export system (Bir Seba project) tied to regional export network'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Zemoul El Kbar Contractual Perimeter (Berkine Basin)',
  'Sonatrach / Eni',
  'Ouargla Province, Algeria',
  'Algeria',
  'Ouargla Province',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach / Eni',
  'PSC',
  'Hydrocarbon production-sharing contract signed 7 July 2025 between Sonatrach and Eni; duration 30 years, extendable by 10 years; includes 7-year research period.',
  0,
  0,
  'boe (planned/expected over contract life)',
  0,
  415000000,
  'boe (expected production over contractual period)',
  parse_site_date('2025-07-07'),
  NULL,
  NULL,
  'oil and gas (contract area; detailed crude assay not published)',
  NULL,
  NULL,
  1350000000,
  'USD',
  parse_site_date('2025-07-07'),
  30,
  ARRAY['To be developed; expected tie-in to existing Berkine Basin gathering/export infrastructure'],
  ARRAY['Skikda (Mediterranean export terminal)', 'Arzew/Bethioua (Mediterranean export terminal)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Zarzaitine Oil Field',
  'Sonatrach',
  'Illizi Province (In Amenas District), Algeria',
  'Algeria',
  'Illizi Province (In Amenas District)',
  28.08333,
  9.75,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Sonatrach (operator/majority). Service contract reported with Sinopec (2002).',
  1380000,
  16800000,
  'barrels (estimated from ~2 million tonnes/year crude reported; conversion assumed ~7.3 bbl/tonne)',
  16800000,
  584000000,
  'barrels (estimated from 80 million tonnes ''primary reserves'' historical figure; conversion assumed ~7.3 bbl/tonne; remaining not disclosed)',
  parse_site_date('1960s'),
  NULL,
  NULL,
  'light sweet crude (regional typical; field-specific API not found)',
  NULL,
  'light sweet crude',
  525000000,
  'USD',
  parse_site_date('2002-01-01'),
  NULL,
  ARRAY['TRAPSA (Trapsa Oil Pipeline) (Zarzaitine–Edjeleh connection referenced)'],
  ARRAY['Skikda (likely via TRAPSA system; exact export route not fully confirmed for field)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Tin Fouye Tabankort (TFT) Field',
  'Sonatrach',
  'Illizi Province, Algeria',
  'Algeria',
  'Illizi Province',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Sonatrach',
  'JV/PSC',
  'Sonatrach with partners TotalEnergies and Repsol (percentages not found in accessible sources for TFT).',
  0,
  0,
  'bbl (oil not primary; gas/condensate field)',
  0,
  0,
  'bbl (oil reserves not applicable; gas reserves reported ~5.1 Tcf)',
  parse_site_date('1980'),
  NULL,
  NULL,
  'gas + condensate',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Connection into Algeria gas transmission system (via TFT hub referenced by Ain Tsila export plans)'],
  ARRAY['Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Ain Tsila Gas-Condensate Field',
  'Groupement Isarene (Sonatrach / Petroceltic / Enel JV)',
  'Illizi Basin (Isarene permit, Blocks 228 & 229a), Algeria',
  'Algeria',
  'Illizi Basin (Isarene permit, Blocks 228 & 229a)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Groupement Isarene (Sonatrach / Petroceltic / Enel JV)',
  'JV/PSC',
  'Reported interests: Petroceltic 56.625%, Sonatrach 25%, Enel 18.375% (project ownership).',
  0,
  0,
  'bbl (condensate not quantified in available sources; gas primary)',
  0,
  0,
  'bbl (oil reserves not applicable; gas reserves widely reported but uncertain)',
  parse_site_date('2021'),
  NULL,
  NULL,
  'gas-condensate',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Export pipeline planned/used to connect to main Algerian gas transmission system at Tin Fouye Tabankort (TFT) ~100 km away (as reported in project descriptions)'],
  ARRAY['Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Alrar Gas Field / Alrar Gas Complex (incl. Algerian portion of Wafa)',
  'Sonatrach',
  'Illizi Basin (near Libya border), Algeria',
  'Algeria',
  'Illizi Basin (near Libya border)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Sonatrach (operator/owner reported in multiple sources).',
  7770000,
  94600000,
  'm3 processed gas (target/maintained throughput referenced: 10 million m3/day)',
  94600000,
  0,
  'bbl (gas field; reserves not consolidated here)',
  parse_site_date('1984'),
  NULL,
  NULL,
  'gas + condensate/LPG',
  NULL,
  NULL,
  210000000,
  'USD',
  parse_site_date('2024-08-15'),
  NULL,
  ARRAY['Alrar field gathering/processing network (specific export pipeline names not confirmed in accessible sources)'],
  ARRAY['Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Tinrhert Gas Field (Ohanet II / Illizi Province)',
  'Sonatrach',
  'Illizi Province (Block Ohanet II), Algeria',
  'Algeria',
  'Illizi Province (Block Ohanet II)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Sonatrach',
  'state-owned',
  '100% owned and operated by Sonatrach (as reported at startup).',
  135000000,
  1642500000,
  'm3 gas (reported initial production 4.5 million m3/day)',
  1642500000,
  1059000000,
  'boe (expected recovery reported as 1,059 MMboe)',
  parse_site_date('2022-12-14'),
  NULL,
  NULL,
  'gas + condensate/LPG',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-in from Tinrhert wells to Ohanet field facilities (inlet separation and compression)'],
  ARRAY['Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Ohanet Conventional Gas Field (Ohanet II)',
  'Sonatrach',
  'Illizi Province (Ohanet II blocks 234p/239p/240p/244p), Algeria',
  'Algeria',
  'Illizi Province (Ohanet II blocks 234p/239p/240p/244p)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Sonatrach',
  'state-owned',
  'Sonatrach reported as owner/operator in field profile sources.',
  0,
  0,
  'bbl (gas primary; field-level bbl not available)',
  0,
  0,
  'bbl (gas field; oil reserves not applicable)',
  parse_site_date('2000'),
  NULL,
  NULL,
  'gas + associated liquids',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Connected into local Ohanet/Tinrhert gathering and compression system (exact trunk pipeline names not confirmed in accessible sources)'],
  ARRAY['Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'In Amenas Gas Project (Tiguentourine facility and associated fields)',
  'Sonatrach (jointly with partners)',
  'Illizi Province (near In Amenas; Tiguentourine), Algeria',
  'Algeria',
  'Illizi Province (near In Amenas; Tiguentourine)',
  27.926944,
  9.114722,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Sonatrach (jointly with partners)',
  'PSC/JV',
  'Originally a PSC with Sonatrach; historically operated with BP and Statoil (now Equinor). Eni acquired BP’s business in Algeria including In Amenas (2022 deal), implying Eni interest (exact current field-level WI split not fully specified in accessible sources here).',
  0,
  0,
  'bbl (field complex; liquids produced but not expressed in bbl/month in cited startup source)',
  0,
  0,
  'bbl (gas project; reserves not consolidated here)',
  parse_site_date('2006-05-27'),
  NULL,
  NULL,
  'gas + condensate/LPG',
  NULL,
  NULL,
  NULL,
  'USD',
  parse_site_date('2022-09-07'),
  NULL,
  ARRAY['In Amenas–Haoud El Hamra oil pipeline (origin at In Amenas)', 'In Amenas–Hassi Messaoud gas pipeline (origin at In Amenas)'],
  ARRAY['Skikda (via Haoud El Hamra/transport system; not fully confirmed for this specific project)', 'Arzew (via national gas system; not field-specific confirmed)'],
  ARRAY[]::TEXT[],
  'Sonatrach',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Sud-Est Illizi Block Gas Discovery Area (Tihalatine South)',
  'Repsol-led group (exploration)',
  'Illizi Basin (Sud-Est Illizi block), Algeria',
  'Algeria',
  'Illizi Basin (Sud-Est Illizi block)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Repsol-led group (exploration)',
  'PSC/JV',
  'Interests reported at time of discovery: Sonatrach 51%, Repsol 25.725%, Enel 13.475%, GDF Suez 9.8%.',
  0,
  0,
  'bbl (discovery test reported in gas rate; commercial production not confirmed in accessible sources)',
  0,
  0,
  'bbl (not disclosed)',
  parse_site_date('2012'),
  NULL,
  NULL,
  'gas (tested 3.7 MMcfd reported at discovery well)',
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Repsol',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Reggane (Reggane Nord gas field area)',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  27.213,
  0.338,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (post-Oct 2023 close)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; Reggane Nord project total)',
  2800000000,
  1500000000000,
  'scf_gas (project total; >1.5 Tcf reported for Reggane Nord complex)',
  parse_site_date('2017-12'),
  NULL,
  NULL,
  'dry gas (Paleozoic clastic reservoirs); condensate possible but not consistently reported',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline (new built connection)'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Kahlouche',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  27.213,
  0.338,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (field is part of Reggane Nord Blocks 351c/352c)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; allocated from Reggane Nord project total; field-level split not disclosed)',
  2800000000,
  1500000000000,
  'scf_gas (approx; share of Reggane Nord complex total reported >1.5 Tcf)',
  parse_site_date('2017'),
  NULL,
  NULL,
  'dry gas',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gathering network to Central Processing Facility (CPF)', 'Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Kahlouche Sud (South Kahlouche)',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (field is part of Reggane Nord Blocks 351c/352c)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; allocated from Reggane Nord project total; field-level split not disclosed)',
  2800000000,
  1500000000000,
  'scf_gas (approx; share of Reggane Nord complex total reported >1.5 Tcf)',
  parse_site_date('2017-12'),
  NULL,
  NULL,
  'dry gas',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gathering network to Central Processing Facility (CPF)', 'Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Azrafil Sud-Est (Southeast Azrafil)',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  NULL,
  NULL,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (field is part of Reggane Nord Blocks 351c/352c)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; allocated from Reggane Nord project total; field-level split not disclosed)',
  2800000000,
  1500000000000,
  'scf_gas (approx; share of Reggane Nord complex total reported >1.5 Tcf)',
  parse_site_date('2017-12'),
  NULL,
  NULL,
  'dry gas',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gathering network to Central Processing Facility (CPF)', 'Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Sali',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  26.34,
  -1.1,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (field is part of Reggane Nord Blocks 351c/352c)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; allocated from Reggane Nord project total; field-level split not disclosed)',
  2800000000,
  1500000000000,
  'scf_gas (approx; share of Reggane Nord complex total reported >1.5 Tcf)',
  parse_site_date('2017-12'),
  NULL,
  NULL,
  'dry gas',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gathering network to Central Processing Facility (CPF)', 'Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
),
(
  'Tiouliline',
  'Groupement Reggane Nord (GRN)',
  'Adrar Province (Wilaya d''Adrar), Algeria',
  'Algeria',
  'Adrar Province (Wilaya d''Adrar)',
  27.201,
  -0.8178,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Groupement Reggane Nord (GRN)',
  'JV / Production Sharing-style partnership with Sonatrach (national company)',
  'Sonatrach 40%; Repsol 36%; Wintershall Dea 24% (field is part of Reggane Nord Blocks 351c/352c)',
  233333333.33,
  2800000000,
  'm3_gas/year (approx; allocated from Reggane Nord project total; field-level split not disclosed)',
  2800000000,
  1500000000000,
  'scf_gas (approx; share of Reggane Nord complex total reported >1.5 Tcf)',
  parse_site_date('2017-12'),
  NULL,
  NULL,
  'dry gas',
  NULL,
  NULL,
  100000000,
  'USD',
  parse_site_date('2023-10-16'),
  25,
  ARRAY['Reggane Nord gathering network to Central Processing Facility (CPF)', 'Reggane Nord gas export pipeline (~74 km) to GR5 national gas transport pipeline'],
  ARRAY[]::TEXT[],
  ARRAY[]::TEXT[],
  'Groupement Reggane Nord',
  '{"source": "Algeria_all_sites.json", "generated_date": "2026-01-21 21:43:45"}'::JSONB
);
ON CONFLICT (title, country, commodity_name) 
DO UPDATE SET
  owner = EXCLUDED.owner,
  address = EXCLUDED.address,
  region = EXCLUDED.region,
  latitude = COALESCE(EXCLUDED.latitude, commodity_locations.latitude),
  longitude = COALESCE(EXCLUDED.longitude, commodity_locations.longitude),
  location_type = EXCLUDED.location_type,
  operational_status = EXCLUDED.operational_status,
  operator = EXCLUDED.operator,
  ownership_type = EXCLUDED.ownership_type,
  ownership_details = EXCLUDED.ownership_details,
  production_monthly = EXCLUDED.production_monthly,
  production_yearly = EXCLUDED.production_yearly,
  production_unit = EXCLUDED.production_unit,
  current_production = EXCLUDED.current_production,
  reserves_estimate = EXCLUDED.reserves_estimate,
  reserves_unit = EXCLUDED.reserves_unit,
  start_date = EXCLUDED.start_date,
  closing_date = EXCLUDED.closing_date,
  api_gravity = EXCLUDED.api_gravity,
  quality_type = EXCLUDED.quality_type,
  quality_sulfur_content = EXCLUDED.quality_sulfur_content,
  grade = EXCLUDED.grade,
  last_transaction_value = EXCLUDED.last_transaction_value,
  last_transaction_currency = EXCLUDED.last_transaction_currency,
  last_transaction_date = EXCLUDED.last_transaction_date,
  contract_duration_years = EXCLUDED.contract_duration_years,
  pipelines = EXCLUDED.pipelines,
  ports = EXCLUDED.ports,
  rail_connections = EXCLUDED.rail_connections,
  company = EXCLUDED.company,
  additional_info = EXCLUDED.additional_info,
  updated_at = NOW();

-- Clean up helper functions
DROP FUNCTION IF EXISTS parse_site_date(TEXT);
DROP FUNCTION IF EXISTS extract_primary_company(TEXT);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_commodity_locations_start_date ON public.commodity_locations(start_date);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_production_yearly ON public.commodity_locations(production_yearly);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_operator ON public.commodity_locations(operator);
CREATE INDEX IF NOT EXISTS idx_commodity_locations_status ON public.commodity_locations(operational_status);

-- Update companies RLS policy for open access
DROP POLICY IF EXISTS "Authenticated users can read companies" ON public.companies;
CREATE POLICY "Anyone can read companies" ON public.companies
  FOR SELECT USING (true);

-- Verification query
SELECT COUNT(*) as total_algeria_sites, 
       COUNT(CASE WHEN latitude IS NOT NULL AND longitude IS NOT NULL THEN 1 END) as sites_with_coordinates,
       COUNT(CASE WHEN operational_status = 'active' THEN 1 END) as active_sites,
       COUNT(CASE WHEN operational_status != 'active' THEN 1 END) as inactive_sites
FROM public.commodity_locations 
WHERE country = 'Algeria';
