-- ============================================================
-- Colombia, Ecuador & Peru — Oil Production Sites (UPSERT)
-- Run this in Supabase SQL Editor
-- Colombia: 21 sites | Ecuador: 12 sites | Peru: 11 sites
-- ============================================================

-- =====================
-- COLOMBIA — LLANOS BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rubiales Field', 'Ecopetrol', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 4.1333, -73.0333, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 12.00, 2.50, 60000, 100000000, 1800000, '{"start_year":1981,"production_bpd":60000,"quality":"Rubiales crude — Colombia''s heaviest commercial","note":"Ecopetrol 100%; Colombia''s largest field; acquired from Pacific Rubiales 2016","pipelines":"Rubiales → ODL → Coveñas Terminal","ports":"Coveñas Export Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Quifa Field', 'Ecopetrol', 'Meta Department — Llanos Basin, adjacent to Rubiales', NULL, 'Energy', 'Crude Oil', 4.2000, -73.1000, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 12.00, 2.20, 40000, 500000000, 1200000, '{"start_year":2010,"production_bpd":40000,"quality":"Extra heavy","note":"Ecopetrol 100%; developed by Pacific Rubiales","pipelines":"Quifa → Rubiales gathering → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Castilla Field', 'Ecopetrol', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 4.1667, -72.9500, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 14.00, 2.00, 70000, 200000000, 2100000, '{"start_year":1969,"production_bpd":70000,"quality":"Extra heavy","note":"Ecopetrol 100%; thermal steam injection EOR","pipelines":"Castilla → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chichimene Field', 'Ecopetrol + Hocol', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 4.3333, -73.2500, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Ecopetrol', 'joint_venture', 13.00, NULL, 40000, NULL, 1200000, '{"start_year":1998,"production_bpd":40000,"quality":"Extra heavy","note":"Ecopetrol 60%, Hocol (ExxonMobil) 40%","pipelines":"Chichimene → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Apiay Field', 'Ecopetrol + Repsol Colombia', 'Meta Department — Llanos Basin, historic', NULL, 'Energy', 'Crude Oil', 4.0667, -73.4667, 'Colombia', 'Llanos Basin', 'Apiay', 'oil_field', 'operational', 'Ecopetrol', 'joint_venture', 35.00, 0.30, 25000, NULL, 750000, '{"start_year":1981,"production_bpd":25000,"quality":"Light sweet","note":"Ecopetrol majority, Repsol minority; Colombia''s first Llanos commercial discovery","pipelines":"Apiay → Apiay Terminal → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Caño Limón Field', 'Occidental Petroleum Colombia + Ecopetrol', 'Arauca Department — northeastern Llanos, Venezuela border', NULL, 'Energy', 'Crude Oil', 6.9667, -71.3833, 'Colombia', 'Llanos Basin', 'Arauca', 'oil_field', 'operational', 'Occidental Petroleum Colombia', 'joint_venture', 30.00, 0.60, 30000, 50000000, 900000, '{"start_year":1986,"production_bpd":30000,"quality":"Medium light","note":"Ecopetrol 61%, Occidental 39%; guerrilla attacks on pipeline","pipelines":"Caño Limón → CLV (780km) → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('La Cira-Infantas (Llanos)', 'Ecopetrol', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 4.5000, -73.5000, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 15.00, NULL, 30000, NULL, 900000, '{"start_year":1998,"production_bpd":30000,"quality":"Extra heavy","note":"Ecopetrol 100%; mature heavy oil","pipelines":"La Cira-Infantas → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cusiana / Cupiagua Fields', 'Equion Energía + bp', 'Casanare Department — Llanos Basin foothills', NULL, 'Energy', 'Crude Oil', 5.3333, -72.6667, 'Colombia', 'Llanos Basin', 'Coveñas', 'oil_field', 'operational', 'Equion Energía', 'joint_venture', 40.00, 0.20, 60000, 100000000, 1800000, '{"start_year":1993,"production_bpd":60000,"quality":"Cusiana crude — premium Colombian light","note":"Equion (Ecopetrol 51.4% + Repsol 48.6%); BP discoveries 1990s","pipelines":"Cusiana/Cupiagua → Ocensa → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Volcaneras Field', 'Hocol + Ecopetrol', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 4.0833, -73.1667, 'Colombia', 'Llanos Basin', 'Puerto Gaitán', 'oil_field', 'operational', 'Hocol', 'joint_venture', 32.00, NULL, 20000, NULL, 600000, '{"start_year":2003,"production_bpd":20000,"quality":"Medium light","note":"Hocol (ExxonMobil) 70%, Ecopetrol 30%","pipelines":"Volcaneras → ODL → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Reforma / Acacías Area', 'Ecopetrol + GeoPark Colombia', 'Meta Department — Llanos Basin', NULL, 'Energy', 'Crude Oil', 3.9833, -73.7500, 'Colombia', 'Llanos Basin', 'Acacías', 'oil_field', 'operational', 'Ecopetrol', 'joint_venture', 33.00, NULL, 15000, NULL, 450000, '{"start_year":2010,"production_bpd":15000,"quality":"Medium light","note":"Ecopetrol, GeoPark Colombia","pipelines":"Reforma → ODL","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- COLOMBIA — MIDDLE MAGDALENA VALLEY
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('La Cira-Infantas (Middle Magdalena)', 'Ecopetrol', 'Santander Department — Middle Magdalena Valley', NULL, 'Energy', 'Crude Oil', 7.4000, -73.7833, 'Colombia', 'Middle Magdalena', 'Barrancabermeja', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 17.00, 1.80, 25000, 100000000, 750000, '{"start_year":1918,"production_bpd":25000,"quality":"Heavy","note":"Ecopetrol 100%; Colombia''s oldest continuously producing field; thermal EOR","pipelines":"La Cira-Infantas → Barrancabermeja refinery → OCENSA → Coveñas","ports":"Coveñas; Barrancabermeja","rail":"Barrancabermeja rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Teca / Tauramena / Recetor Fields', 'Ecopetrol + Hocol', 'Casanare Department — Middle Magdalena fringe / Llanos transition', NULL, 'Energy', 'Crude Oil', 5.0167, -72.7500, 'Colombia', 'Middle Magdalena', 'Coveñas', 'oil_field', 'operational', 'Ecopetrol', 'joint_venture', 35.00, NULL, 20000, NULL, 600000, '{"start_year":1999,"production_bpd":20000,"quality":"Light sweet","note":"Ecopetrol majority, Hocol minority","pipelines":"Teca/Tauramena → OCENSA → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Velásquez Field', 'Ecopetrol', 'Santander Department — Middle Magdalena', NULL, 'Energy', 'Crude Oil', 7.0833, -73.5000, 'Colombia', 'Middle Magdalena', 'Barrancabermeja', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 25.00, 1.20, 10000, NULL, 300000, '{"start_year":1941,"production_bpd":10000,"quality":"Medium heavy","note":"Ecopetrol 100%; mature","pipelines":"Velásquez → Barrancabermeja refinery gathering","ports":"Barrancabermeja; Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lisama Field', 'Ecopetrol', 'Santander Department — Middle Magdalena', NULL, 'Energy', 'Crude Oil', 7.2500, -73.4167, 'Colombia', 'Middle Magdalena', 'Barrancabermeja', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 23.00, NULL, 8000, NULL, 240000, '{"start_year":1939,"production_bpd":8000,"quality":"Medium heavy","note":"Ecopetrol 100%; mature","pipelines":"Lisama → Barrancabermeja gathering","ports":"Barrancabermeja","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- COLOMBIA — CATATUMBO BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tibú Field', 'Ecopetrol', 'Norte de Santander Department — Catatumbo Basin, Venezuela border', NULL, 'Energy', 'Crude Oil', 8.6333, -72.7333, 'Colombia', 'Catatumbo Basin', 'Tibú', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 28.00, 1.00, 15000, 100000000, 450000, '{"start_year":1939,"production_bpd":15000,"quality":"Medium light","note":"Ecopetrol 100%; security challenges from guerrilla","pipelines":"Tibú → CLV → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Río Zulia Field', 'Ecopetrol', 'Norte de Santander — Catatumbo Basin', NULL, 'Energy', 'Crude Oil', 8.4167, -72.5833, 'Colombia', 'Catatumbo Basin', 'Tibú', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 30.00, NULL, 8000, NULL, 240000, '{"start_year":1960,"production_bpd":8000,"quality":"Medium light","note":"Ecopetrol 100%","pipelines":"Río Zulia → Tibú gathering → Coveñas","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sardinata Field', 'Ecopetrol + Hocol', 'Norte de Santander — Catatumbo Basin', NULL, 'Energy', 'Crude Oil', 8.2500, -72.8333, 'Colombia', 'Catatumbo Basin', 'Tibú', 'oil_field', 'operational', 'Ecopetrol', 'joint_venture', 29.00, NULL, 6000, NULL, 180000, '{"start_year":1975,"production_bpd":6000,"quality":"Medium","note":"Ecopetrol, Hocol","pipelines":"Sardinata → Tibú gathering","ports":"Coveñas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- COLOMBIA — PUTUMAYO BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Orito Field', 'Ecopetrol', 'Putumayo Department — Putumayo Basin, southern Colombia Amazon', NULL, 'Energy', 'Crude Oil', 0.6667, -76.8833, 'Colombia', 'Putumayo Basin', 'Orito', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 26.00, 2.50, 25000, 300000000, 750000, '{"start_year":1963,"production_bpd":25000,"quality":"Medium heavy","note":"Ecopetrol 100%; historic Putumayo discovery","pipelines":"Orito → OTA → Tumaco Marine Terminal","ports":"Tumaco Marine Terminal (Pacific)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Costayaco Field', 'Ecopetrol', 'Putumayo Department — Putumayo Basin', NULL, 'Energy', 'Crude Oil', 0.5833, -77.0500, 'Colombia', 'Putumayo Basin', 'Orito', 'oil_field', 'operational', 'Ecopetrol', 'state_owned', 24.00, 2.80, 10000, NULL, 300000, '{"start_year":1969,"production_bpd":10000,"quality":"Medium heavy","note":"Ecopetrol 100%","pipelines":"Costayaco → OTA → Tumaco","ports":"Tumaco","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Guando / Cohembí Fields', 'Gran Tierra Energy + Ecopetrol', 'Putumayo Department', NULL, 'Energy', 'Crude Oil', 0.8333, -76.9167, 'Colombia', 'Putumayo Basin', 'Orito', 'oil_field', 'operational', 'Gran Tierra Energy', 'joint_venture', 27.00, NULL, 15000, NULL, 450000, '{"start_year":2009,"production_bpd":15000,"quality":"Medium heavy","note":"Gran Tierra 70%, Ecopetrol 30%","pipelines":"Guando → OTA → Tumaco","ports":"Tumaco","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Alea / Moqueta Area', 'GeoPark + Gran Tierra + Ecopetrol', 'Putumayo Department', NULL, 'Energy', 'Crude Oil', 0.7500, -77.1667, 'Colombia', 'Putumayo Basin', 'Orito', 'oil_field', 'operational', 'GeoPark', 'joint_venture', 26.00, NULL, 12000, NULL, 360000, '{"start_year":2013,"production_bpd":12000,"quality":"Medium heavy","note":"GeoPark (acquired Amerisur 2020), Gran Tierra, Ecopetrol","pipelines":"→ OTA → Tumaco","ports":"Tumaco","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ECUADOR — ORIENTE BASIN (AMAZON)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shushufindi Field', 'Petroecuador EP', 'Sucumbíos Province — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.1667, -76.6500, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 24.00, 1.80, 60000, 200000000, 1800000, '{"start_year":1972,"production_bpd":60000,"quality":"Oriente crude benchmark","note":"Petroecuador 100%; Ecuador''s largest field","pipelines":"Shushufindi → SOTE → Balao Terminal","ports":"Balao Terminal (Esmeraldas)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sacha Field', 'Petroecuador EP', 'Oriente Basin — Sucumbíos Province', NULL, 'Energy', 'Crude Oil', -0.2833, -76.8333, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 26.00, 1.50, 50000, 150000000, 1500000, '{"start_year":1972,"production_bpd":50000,"quality":"Medium heavy","note":"Petroecuador 100%; mature","pipelines":"Sacha → SOTE → Balao","ports":"Balao Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Libertador Field', 'Petroecuador EP', 'Sucumbíos Province — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.0833, -76.8833, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 25.00, NULL, 35000, NULL, 1050000, '{"start_year":1973,"production_bpd":35000,"quality":"Medium heavy","note":"Petroecuador 100%","pipelines":"Libertador → SOTE → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Auca Field', 'Petroecuador EP', 'Oriente Basin — Napo/Orellana Province', NULL, 'Energy', 'Crude Oil', -0.7500, -76.8667, 'Ecuador', 'Oriente Basin', 'Coca', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 23.00, 2.00, 30000, NULL, 900000, '{"start_year":1972,"production_bpd":30000,"quality":"Medium heavy","note":"Petroecuador 100%; mature","pipelines":"Auca → SOTE → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lago Agrio Field', 'Petroecuador EP', 'Sucumbíos Province — Oriente Basin, historic', NULL, 'Energy', 'Crude Oil', 0.0833, -76.8833, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 27.00, 1.40, 20000, 50000000, 600000, '{"start_year":1967,"production_bpd":20000,"quality":"Medium heavy","note":"Petroecuador 100%; Ecuador''s first commercial field","pipelines":"Lago Agrio → SOTE → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('ITT (Ishpingo-Tambococha-Tiputini) Field', 'Petroecuador EP', 'Yasuni National Park — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.6667, -75.8333, 'Ecuador', 'Oriente Basin', 'Coca', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 16.00, 2.50, 60000, 850000000, 1800000, '{"start_year":2016,"production_bpd":60000,"quality":"Heavy","note":"Petroecuador 100%; highly controversial — Yasuni National Park","pipelines":"ITT → SOTE → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pungarayacu Field', 'Petroecuador EP + PetroOriental', 'Pastaza Province — Oriente Basin heavy oil', NULL, 'Energy', 'Crude Oil', -1.5000, -77.8333, 'Ecuador', 'Oriente Basin', 'Puyo', 'oil_field', 'operational', 'Petroecuador EP', 'joint_venture', 11.00, 3.00, 10000, NULL, 300000, '{"start_year":2014,"production_bpd":10000,"quality":"Extra heavy — Ecuador''s heaviest crude","note":"Petroecuador 70%, PetroOriental (CNPC) 30%","pipelines":"Pungarayacu → OCP → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pañacocha Field', 'Andes Petroleum', 'Sucumbíos Province — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.3667, -75.8333, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Andes Petroleum', 'joint_venture', 24.00, NULL, 15000, NULL, 450000, '{"start_year":2006,"production_bpd":15000,"quality":"Medium heavy","note":"Andes Petroleum 100% (CNPC 55% + Sinopec 45%)","pipelines":"Pañacocha → OCP → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tarapoa Block', 'Andes Petroleum', 'Sucumbíos Province — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.1167, -76.3333, 'Ecuador', 'Oriente Basin', 'Lago Agrio', 'oil_field', 'operational', 'Andes Petroleum', 'joint_venture', 25.00, NULL, 20000, NULL, 600000, '{"start_year":2006,"production_bpd":20000,"quality":"Medium heavy","note":"Andes Petroleum 100% (CNPC-Sinopec JV)","pipelines":"Tarapoa → OCP → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Indillana / Coca-Payamino Area', 'Repsol Ecuador + Petroecuador', 'Orellana Province — Oriente Basin', NULL, 'Energy', 'Crude Oil', -0.4667, -77.0833, 'Ecuador', 'Oriente Basin', 'Coca', 'oil_field', 'operational', 'Repsol Ecuador', 'joint_venture', 27.00, NULL, 12000, NULL, 360000, '{"start_year":2000,"production_bpd":12000,"quality":"Medium heavy","note":"Repsol 35%, Petroecuador 65%","pipelines":"Coca-Payamino → SOTE → Balao","ports":"Balao","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ECUADOR — OFFSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Amistad Field', 'Petroecuador EP + EDC Ecuador', 'Offshore Gulf of Guayaquil — Pacific coast', NULL, 'Energy', 'Crude Oil', -3.2500, -80.3333, 'Ecuador', 'Offshore Ecuador', 'La Libertad', 'oil_field', 'operational', 'Petroecuador EP', 'joint_venture', 28.00, NULL, 5000, NULL, 150000, '{"start_year":1998,"production_bpd":5000,"quality":"Medium","note":"Petroecuador 70%, EDC Ecuador (CNPC) 30%; Ecuador''s only offshore","pipelines":"Amistad platform → subsea pipeline → La Libertad Terminal","ports":"La Libertad Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gustavo Galindo Velasco Field', 'Petroecuador EP', 'Offshore Gulf of Guayaquil', NULL, 'Energy', 'Crude Oil', -3.0000, -80.5000, 'Ecuador', 'Offshore Ecuador', 'La Libertad', 'oil_field', 'operational', 'Petroecuador EP', 'state_owned', 27.00, NULL, 3000, NULL, 90000, '{"start_year":2008,"production_bpd":3000,"quality":"Medium","note":"Petroecuador 100%; small offshore","pipelines":"→ La Libertad Terminal","ports":"La Libertad","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- PERU — TALARA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Talara Field', 'PetroPerú', 'Piura Department — Talara Basin, northwest Peru coast', NULL, 'Energy', 'Crude Oil', -4.5833, -81.2667, 'Peru', 'Talara Basin', 'Talara', 'oil_field', 'operational', 'PetroPerú', 'state_owned', 33.00, 0.80, 8000, 20000000, 240000, '{"start_year":1863,"production_bpd":8000,"quality":"Medium light","note":"PetroPerú 100%; Peru''s oldest producing area; South America''s first oil","pipelines":"Talara → Talara refinery → Bayóvar Terminal","ports":"Bayóvar Terminal; Talara Port","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lagunitas / La Brea-Pariñas Field', 'PetroPerú + GMP', 'Piura Department — Talara Basin', NULL, 'Energy', 'Crude Oil', -4.6667, -81.2000, 'Peru', 'Talara Basin', 'Talara', 'oil_field', 'operational', 'PetroPerú', 'state_owned', 32.00, NULL, 5000, NULL, 150000, '{"start_year":1900,"production_bpd":5000,"quality":"Medium light","note":"PetroPerú 100%; mature","pipelines":"Lagunitas → Talara refinery gathering","ports":"Bayóvar; Talara","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lobitos / Negritos Field', 'Olympic Peru', 'Piura Department — Talara Basin coast', NULL, 'Energy', 'Crude Oil', -4.4500, -81.2833, 'Peru', 'Talara Basin', 'Talara', 'oil_field', 'operational', 'Olympic Peru', 'private', 34.00, NULL, 3000, NULL, 90000, '{"start_year":1901,"production_bpd":3000,"quality":"Medium light","note":"Olympic Peru 100%; BPZ Energy legacy","pipelines":"Lobitos → Talara gathering","ports":"Talara","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- PERU — UCAYALI BASIN (GAS + CONDENSATE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Camisea Gas Field', 'Pluspetrol + Hunt Oil + SK Energy + Sonatrach + Repsol + Tecpetrol', 'Cusco Department — Ucayali Basin, Peruvian Amazon', NULL, 'Energy', 'Condensate', -12.3333, -72.8333, 'Peru', 'Ucayali Basin', 'Pisco', 'oil_field', 'operational', 'Pluspetrol', 'joint_venture', 55.00, NULL, 100000, 600000000, 3000000, '{"start_year":2004,"production_bpd":100000,"quality":"Ultra-light condensate sweet","note":"Pluspetrol 36%, Hunt Oil 36%, SK Energy 18%, Sonatrach 10%; gas-dominant mega-field","pipelines":"Camisea → 730km pipeline → Pisco → Peru LNG","ports":"Pisco Marine Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pagoreni / Cashiriari Area', 'Pluspetrol', 'Cusco Department — Ucayali Basin, Camisea area', NULL, 'Energy', 'Condensate', -12.5000, -72.6667, 'Peru', 'Ucayali Basin', 'Pisco', 'oil_field', 'operational', 'Pluspetrol', 'joint_venture', 52.00, NULL, 20000, NULL, 600000, '{"start_year":2010,"production_bpd":20000,"quality":"Condensate","note":"Pluspetrol consortium; gas + condensate satellites to Camisea","pipelines":"Pagoreni → Camisea gathering → Pisco","ports":"Pisco","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mipaya / Sepahua Area', 'Maple Gas (Hunt Oil)', 'Ucayali Department — Ucayali Basin', NULL, 'Energy', 'Condensate', -11.1667, -73.5000, 'Peru', 'Ucayali Basin', 'Pucallpa', 'oil_field', 'operational', 'Maple Gas', 'private', 50.00, NULL, 15000, NULL, 450000, '{"start_year":2014,"production_bpd":15000,"quality":"Condensate","note":"Maple Gas (Hunt Oil) 100%; gas + condensate","pipelines":"Mipaya → Aguaytía pipeline → Pucallpa","ports":"None (Amazon landlocked)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Aguaytía Field', 'Aguaytía Energy (Hunt Oil)', 'Ucayali Department — Ucayali Basin', NULL, 'Energy', 'Condensate', -9.0500, -75.5000, 'Peru', 'Ucayali Basin', 'Pucallpa', 'oil_field', 'operational', 'Aguaytía Energy', 'private', 48.00, NULL, 5000, NULL, 150000, '{"start_year":1998,"production_bpd":5000,"quality":"Condensate","note":"Aguaytía Energy (Hunt Oil) 100%; gas + condensate","pipelines":"Aguaytía → Pucallpa power plant; condensate road transport","ports":"None (Amazon interior)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- PERU — OFFSHORE & MARAÑÓN BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Corvina Field', 'Savia Perú (Ecopetrol Peru)', 'Offshore Tumbes Basin — northern Peru, near Ecuador border', NULL, 'Energy', 'Crude Oil', -4.0000, -81.3333, 'Peru', 'Offshore Peru', 'Zorritos', 'oil_field', 'operational', 'Savia Perú', 'state_owned', 28.00, 1.20, 8000, 50000000, 240000, '{"start_year":2009,"production_bpd":8000,"quality":"Medium","note":"Savia Perú (Ecopetrol subsidiary) 100%; Peru''s only offshore oil","pipelines":"Corvina platform → subsea pipeline → Zorritos Terminal","ports":"Zorritos Terminal (Tumbes)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Albacora Field (Peru)', 'Savia Perú (Ecopetrol Peru)', 'Offshore Tumbes Basin', NULL, 'Energy', 'Crude Oil', -3.8333, -81.4167, 'Peru', 'Offshore Peru', 'Zorritos', 'oil_field', 'operational', 'Savia Perú', 'state_owned', 27.00, NULL, 2000, NULL, 60000, '{"start_year":2015,"production_bpd":2000,"quality":"Medium heavy","note":"Savia Perú 100%; small offshore satellite to Corvina","pipelines":"Albacora → Corvina gathering → Zorritos","ports":"Zorritos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Marañón Basin / Trompeteros / Corrientes Area', 'PetroPerú', 'Loreto Department — Peruvian Amazon jungle', NULL, 'Energy', 'Crude Oil', -3.5000, -75.5000, 'Peru', 'Marañón Basin', 'Iquitos', 'oil_field', 'operational', 'PetroPerú', 'state_owned', 30.00, NULL, 10000, NULL, 300000, '{"start_year":1971,"production_bpd":10000,"quality":"Medium light","note":"PetroPerú 100%; acquired from Pluspetrol 2015; remote Amazon","pipelines":"Trompeteros → ONP (854km) → Bayóvar Terminal","ports":"Bayóvar Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pavayacu / Bretaña Area', 'GeoPark Peru + PetroPerú', 'Loreto Department — Marañón Basin', NULL, 'Energy', 'Crude Oil', -2.5000, -76.5000, 'Peru', 'Marañón Basin', 'Iquitos', 'oil_field', 'operational', 'GeoPark Peru', 'joint_venture', 32.00, NULL, 5000, NULL, 150000, '{"start_year":2008,"production_bpd":5000,"quality":"Medium light","note":"GeoPark Peru 75%, PetroPerú 25%; Lot 64 Loreto","pipelines":"Pavayacu → ONP → Bayóvar","ports":"Bayóvar","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();
