-- ============================================================
-- Netherlands Oil Production Sites — 10 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- GRONINGEN FIELD AREA / ONSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Schoonebeek Field', 'NAM (Shell/ExxonMobil 50/50)', 'Drenthe Province — Netherlands/Germany border', NULL, 'Energy', 'Crude Oil', 52.6500, 6.8833, 'Netherlands', 'Onshore', 'Emmen', 'oil_field', 'operational', 'NAM', 'joint_venture', 20.00, 1.00, 240000, 100000000, 240000, '{"start_year":1943,"production_bpd":8000,"quality":"Heavy — requires steam EOR; unique heavy crude for Western Europe","note":"Largest onshore oil field in Western Europe by OOIP; wartime German-controlled; NAM redevelopment 2011 using steam injection EOR; production suspended 2007–2011 for EOR conversion","last_transaction":"NAM redevelopment project 2011 (~€1B steam injection); Shell/ExxonMobil 50/50 NAM JV since 1947","contract_duration":"Dutch mining concession (Mijnbouwwet)","pipelines":"Schoonebeek → Twente crude pipeline (~75km) → Rotterdam/Terneuzen; steam injection from Emmen power plant","ports":"Rotterdam (Europoort); Terneuzen","rail":"Emmen–Zwolle rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rossum-Weerselo Field', 'NAM', 'Overijssel Province', NULL, 'Energy', 'Crude Oil', 52.3667, 6.8167, 'Netherlands', 'Onshore', 'Oldenzaal', 'oil_field', 'operational', 'NAM', 'joint_venture', 35.00, NULL, 15000, NULL, 15000, '{"start_year":1964,"production_bpd":500,"quality":"Light sweet","note":"Mature; NAM 100%","contract_duration":"Dutch mining concession","pipelines":"Overijssel → Dutch crude gathering → Rotterdam","ports":"Rotterdam","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wanneperveen Field', 'NAM', 'Overijssel/Drenthe', NULL, 'Energy', 'Crude Oil', 52.7500, 6.1833, 'Netherlands', 'Onshore', 'Meppel', 'oil_field', 'operational', 'NAM', 'joint_venture', 34.00, NULL, 12000, NULL, 12000, '{"start_year":1968,"production_bpd":400,"quality":"Medium light","note":"NAM 100%","contract_duration":"Dutch mining concession","pipelines":"Dutch onshore gathering → Rotterdam","ports":"Rotterdam","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Emlichheim Field (NL)', 'NAM', 'Drenthe — cross-border with Germany', NULL, 'Energy', 'Crude Oil', 52.6000, 6.8333, 'Netherlands', 'Onshore', 'Emmen', 'oil_field', 'operational', 'NAM', 'joint_venture', 34.00, NULL, 30000, NULL, 30000, '{"start_year":1944,"production_bpd":1000,"quality":"Medium light","note":"Dutch share of cross-border field; NAM 100% (Dutch sector)","contract_duration":"Dutch mining concession","pipelines":"Emlichheim → Dutch gathering → Rotterdam","ports":"Rotterdam","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NORTH SEA (DUTCH SECTOR)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rijn (Rhine) Field', 'Vermilion Energy + EBN', 'Dutch North Sea — Block P/Q', NULL, 'Energy', 'Crude Oil', 52.8333, 4.1667, 'Netherlands', 'Dutch North Sea', 'Den Helder', 'oil_field', 'operational', 'Vermilion Energy', 'joint_venture', 38.00, 0.20, 90000, 30000000, 90000, '{"start_year":1987,"production_bpd":3000,"quality":"Light sweet","note":"Vermilion Energy 52.6%, EBN (Dutch state) 40%, others 7.4%; Canadian independent with European focus","last_transaction":"Vermilion acquired Dutch North Sea assets ~2001","contract_duration":"Dutch offshore concession to 2030","pipelines":"Rijn → Den Helder onshore terminal (~100km subsea)","ports":"Den Helder; Rotterdam","rail":"Alkmaar–Den Helder rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Helm Field', 'Petrogas E&P + EBN', 'Dutch North Sea — Block K', NULL, 'Energy', 'Crude Oil', 53.3333, 4.5000, 'Netherlands', 'Dutch North Sea', 'Den Helder', 'oil_field', 'operational', 'Petrogas E&P', 'joint_venture', 37.00, NULL, 60000, NULL, 60000, '{"start_year":2002,"production_bpd":2000,"quality":"Light sweet","note":"Petrogas 60%, EBN 40%; Netherlands private","contract_duration":"Dutch offshore concession","pipelines":"Helm → Den Helder terminal","ports":"Den Helder","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Markham Field', 'Wintershall Dea + ConocoPhillips', 'Dutch North Sea — Block F3, shared with UK', NULL, 'Energy', 'Crude Oil', 54.1667, 3.2500, 'Netherlands', 'Dutch North Sea', 'Den Helder', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 38.00, NULL, 105000, 50000000, 105000, '{"start_year":1992,"production_bpd":3500,"quality":"Light sweet","note":"Cross-border UK/Netherlands; Dutch share; Wintershall Dea 50%, ConocoPhillips 50%","contract_duration":"Dutch/UK license","pipelines":"Markham → Dutch/UK pipeline systems → Den Helder / Teesside (UK)","ports":"Den Helder; Teesside (UK side)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Helder (P15 Block) Field', 'NAM', 'Dutch North Sea', NULL, 'Energy', 'Crude Oil', 52.5000, 4.0000, 'Netherlands', 'Dutch North Sea', 'Den Helder', 'oil_field', 'operational', 'NAM', 'joint_venture', 36.00, NULL, 75000, NULL, 75000, '{"start_year":1985,"production_bpd":2500,"quality":"Light sweet","note":"NAM (Shell 50%, ExxonMobil 50%)","contract_duration":"Dutch offshore concession","pipelines":"P15 → Den Helder terminal","ports":"Den Helder","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Luttelgeest (IJsselmeer) Field', 'Vermilion Energy Netherlands + EBN', 'Flevoland — reclaimed polder land', NULL, 'Energy', 'Crude Oil', 52.7000, 5.7333, 'Netherlands', 'Onshore', 'Lelystad', 'oil_field', 'operational', 'Vermilion Energy Netherlands', 'joint_venture', 37.00, NULL, 45000, NULL, 45000, '{"start_year":1988,"production_bpd":1500,"quality":"Light sweet","note":"Unique — oil field on reclaimed polder land; Vermilion 50%, EBN 40%, others 10%","contract_duration":"Dutch concession","pipelines":"Luttelgeest → Dutch onshore gathering → Rotterdam","ports":"Rotterdam","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Q8-A / Q10 Block Field', 'Oranje-Nassau Energie', 'Dutch North Sea — southern sector', NULL, 'Energy', 'Crude Oil', 52.2500, 4.3333, 'Netherlands', 'Dutch North Sea', 'Den Helder', 'oil_field', 'operational', 'Oranje-Nassau Energie', 'private', 36.00, NULL, 45000, NULL, 45000, '{"start_year":1997,"production_bpd":1500,"quality":"Light sweet","note":"ONE — private Dutch independent; 100% ownership","contract_duration":"Dutch offshore concession","pipelines":"Q8/Q10 → Den Helder","ports":"Den Helder","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Netherlands' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Netherlands' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
