-- ============================================================
-- Uzbekistan Oil Production Sites — 20 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- FERGANA VALLEY
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mingbulak Field', 'Uzbekneftegaz', 'Fergana Valley — Namangan Region', NULL, 'Energy', 'Crude Oil', 40.9167, 71.8333, 'Uzbekistan', 'Fergana Valley', 'Namangan', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 34.00, 0.60, 240000, 60000000, 240000, '{"start_year":1992,"production_bpd":8000,"quality":"Medium light","note":"Major blowout/spill 1992 — one of Central Asia''s worst environmental disasters; mature","contract_duration":"State license (perpetual)","pipelines":"Mingbulak → Fergana refinery pipeline (~80km)","ports":"None (landlocked)","rail":"Namangan–Fergana rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Andijan Field', 'Uzbekneftegaz', 'Fergana Valley — Andijan Region', NULL, 'Energy', 'Crude Oil', 40.7833, 72.3500, 'Uzbekistan', 'Fergana Valley', 'Andijan', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 33.00, 0.70, 90000, 50000000, 90000, '{"start_year":1908,"production_bpd":3000,"quality":"Medium","note":"Tsarist era — among Central Asia''s first oil fields; very mature","contract_duration":"State license","pipelines":"Andijan → Fergana refinery","ports":"None","rail":"Andijan–Tashkent main rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chimyon Field', 'Uzbekneftegaz', 'Fergana Valley — Fergana Region', NULL, 'Energy', 'Crude Oil', 40.5833, 71.9167, 'Uzbekistan', 'Fergana Valley', 'Fergana', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 35.00, NULL, 60000, 30000000, 60000, '{"start_year":1904,"production_bpd":2000,"quality":"Light sweet","note":"Colonial-era discovery; mature","contract_duration":"State license","pipelines":"Chimyon → Fergana refinery (~30km)","ports":"None","rail":"Fergana rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shorsu Field', 'Uzbekneftegaz', 'Fergana Valley — Fergana/Namangan border', NULL, 'Energy', 'Crude Oil', 40.5000, 71.5833, 'Uzbekistan', 'Fergana Valley', 'Fergana', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 34.00, NULL, 75000, NULL, 75000, '{"start_year":1956,"production_bpd":2500,"quality":"Medium light","contract_duration":"State license","pipelines":"Shorsu → Fergana refinery","ports":"None","rail":"Fergana rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Palgirchi Field', 'Uzbekneftegaz + Lukoil', 'Fergana Valley — deep carbonate', NULL, 'Energy', 'Crude Oil', 40.6667, 72.0833, 'Uzbekistan', 'Fergana Valley', 'Namangan', 'oil_field', 'operational', 'Uzbekneftegaz + Lukoil', 'joint_venture', 36.00, NULL, 120000, 100000000, 120000, '{"start_year":2002,"production_bpd":4000,"quality":"Light sweet","note":"Uzbekneftegaz 51%, Lukoil 49%; Paleozoy/Palgirchi; deep exploration development","last_transaction":"Lukoil PSA signed 2002; Fergana Valley deep carbonate exploration","contract_duration":"PSA to 2032","pipelines":"Palgirchi → Fergana gathering → Fergana refinery","ports":"None","rail":"Namangan rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kokdumalak Field', 'Uzbekneftegaz + Lukoil', 'Fergana Valley fringe — Kashkadarya Region', NULL, 'Energy', 'Crude Oil', 38.8333, 65.7500, 'Uzbekistan', 'Kashkadarya', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz + Lukoil', 'joint_venture', 38.00, 0.30, 450000, 500000000, 450000, '{"start_year":1990,"production_bpd":15000,"quality":"Light sweet","note":"Uzbekneftegaz 51%, Lukoil 49%; Kandym-Khauzak-Shady-Kungrad JV; Uzbekistan''s largest oil producer; oil + gas","last_transaction":"Lukoil JV agreement 1994; extended 2004 + 2017; ~$5B total Lukoil Uzbekistan investment","contract_duration":"PSA to 2035","pipelines":"Kokdumalak → Bukhara oil refinery; Central Asia–Centre pipeline (gas + associated oil)","ports":"None","rail":"Kashkadarya–Bukhara rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BUKHARA-KHIVA REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Uchkyr Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.5833, 63.5000, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 35.00, 0.40, 150000, 150000000, 150000, '{"start_year":1966,"production_bpd":5000,"quality":"Light sweet","contract_duration":"State license","pipelines":"Uchkyr → Bukhara refinery pipeline","ports":"None","rail":"Bukhara rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pamuk Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.7500, 63.7500, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 34.00, NULL, 120000, 100000000, 120000, '{"start_year":1960,"production_bpd":4000,"quality":"Medium light","note":"Mature","contract_duration":"State license","pipelines":"Pamuk → Bukhara refinery","ports":"None","rail":"Bukhara"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lyalikan Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.3333, 63.1667, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 34.00, NULL, 90000, NULL, 90000, '{"start_year":1972,"production_bpd":3000,"quality":"Medium light","contract_duration":"State license","pipelines":"Lyalikan → Bukhara gathering","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shurtan Field', 'Uzbekneftegaz + Lukoil', 'Kashkadarya Region — Bukhara-Khiva fringe', NULL, 'Energy', 'Crude Oil', 38.5000, 65.6667, 'Uzbekistan', 'Kashkadarya', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz + Lukoil', 'joint_venture', 37.00, 0.30, 240000, 200000000, 240000, '{"start_year":1980,"production_bpd":8000,"quality":"Light sweet","note":"Uzbekneftegaz 51%, Lukoil 49%; Shurtan Gas Chemical Complex; oil + gas","last_transaction":"Lukoil JV extension 2017; Shurtan Gas Chemical Complex ~$1.2B investment","contract_duration":"PSA to 2030","pipelines":"Shurtan → Kashkadarya → Bukhara refinery; gas → Central Asia–Centre pipeline","ports":"None","rail":"Kashkadarya rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mubarek Field', 'Uzbekneftegaz', 'Kashkadarya / Bukhara border', NULL, 'Energy', 'Crude Oil', 38.7500, 65.1667, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 36.00, NULL, 150000, NULL, 150000, '{"start_year":1968,"production_bpd":5000,"quality":"Light sweet","note":"Mature; major gas processing hub + oil","contract_duration":"State license","pipelines":"Mubarek → Mubarek Gas Processing Plant → Bukhara refinery","ports":"None","rail":"Mubarek–Bukhara rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Khazrabot Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.1667, 63.8333, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 35.00, NULL, 105000, NULL, 105000, '{"start_year":1975,"production_bpd":3500,"quality":"Light","contract_duration":"State license","pipelines":"Bukhara gathering → Bukhara refinery","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Adamtash Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.4167, 63.4167, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 34.00, NULL, 75000, NULL, 75000, '{"start_year":1978,"production_bpd":2500,"quality":"Medium light","contract_duration":"State license","pipelines":"Bukhara gathering system","ports":"None","rail":"Bukhara"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kyzylbayrak Field', 'Uzbekneftegaz', 'Khiva / Khorezm Region', NULL, 'Energy', 'Crude Oil', 41.3333, 60.5000, 'Uzbekistan', 'Khorezm', 'Khiva', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 33.00, NULL, 60000, NULL, 60000, '{"start_year":1980,"production_bpd":2000,"quality":"Medium","note":"Smaller field","contract_duration":"State license","pipelines":"Khorezm → Bukhara pipeline (~300km)","ports":"None","rail":"Khiva–Urgench rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Minglyar Field', 'Uzbekneftegaz', 'Bukhara Region', NULL, 'Energy', 'Crude Oil', 39.6667, 64.1667, 'Uzbekistan', 'Bukhara', 'Bukhara', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 35.00, NULL, 60000, NULL, 60000, '{"start_year":1985,"production_bpd":2000,"quality":"Light","contract_duration":"State license","pipelines":"Bukhara gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- USTYURT PLATEAU
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Surgil Field', 'Uzbekneftegaz + CNPC + KOGAS + SK Innovation', 'Ustyurt Plateau — Karakalpakstan', NULL, 'Energy', 'Crude Oil', 42.8333, 59.1667, 'Uzbekistan', 'Karakalpakstan', 'Nukus', 'oil_field', 'operational', 'Uzbekneftegaz + CNPC + KOGAS', 'joint_venture', 38.00, 0.20, 300000, 300000000, 300000, '{"start_year":2010,"production_bpd":10000,"quality":"Light sweet","note":"Uzbekneftegaz 24.5%, CNPC 50%, KOGAS 25%, SK Innovation 0.5%; Ustyurt Gas Chemical Complex; oil + gas","last_transaction":"CNPC + Korean consortium PSA signed 2006; Ustyurt GCC ~$4B investment (2010–2016); largest foreign investment in Uzbekistan energy at time","contract_duration":"PSA to 2040","pipelines":"Surgil → Ustyurt GCC → Central Asia–China gas pipeline; oil/condensate → Nukus → Bukhara","ports":"None (remote plateau — Aral Sea basin)","rail":"Nukus rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Akchalpak Field', 'Uzbekneftegaz', 'Ustyurt Plateau — Karakalpakstan', NULL, 'Energy', 'Crude Oil', 43.1667, 58.8333, 'Uzbekistan', 'Karakalpakstan', 'Nukus', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 36.00, NULL, 150000, 150000000, 150000, '{"start_year":1999,"production_bpd":5000,"quality":"Light sweet","contract_duration":"State license","pipelines":"Akchalpak → Nukus → Bukhara long-distance pipeline","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Berdakh Field', 'Uzbekneftegaz', 'Ustyurt Plateau', NULL, 'Energy', 'Crude Oil', 43.5000, 59.3333, 'Uzbekistan', 'Karakalpakstan', 'Nukus', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 35.00, NULL, 120000, NULL, 120000, '{"start_year":2003,"production_bpd":4000,"quality":"Light sweet","contract_duration":"State license","pipelines":"Ustyurt gathering → Nukus","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kokpatas Field', 'Uzbekneftegaz + Lukoil', 'Ustyurt Plateau — southwestern', NULL, 'Energy', 'Crude Oil', 42.5000, 58.5000, 'Uzbekistan', 'Karakalpakstan', 'Nukus', 'oil_field', 'operational', 'Uzbekneftegaz + Lukoil', 'joint_venture', 37.00, NULL, 180000, 120000000, 180000, '{"start_year":2006,"production_bpd":6000,"quality":"Light sweet","note":"Uzbekneftegaz 51%, Lukoil 49%","last_transaction":"Lukoil Ustyurt PSA signed 2004","contract_duration":"PSA to 2034","pipelines":"Kokpatas → Surgil → Central Asia pipeline system","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Surtanly Field', 'Uzbekneftegaz', 'Ustyurt Plateau', NULL, 'Energy', 'Crude Oil', 43.0000, 59.6667, 'Uzbekistan', 'Karakalpakstan', 'Nukus', 'oil_field', 'operational', 'Uzbekneftegaz', 'state_owned', 36.00, NULL, 75000, NULL, 75000, '{"start_year":2008,"production_bpd":2500,"quality":"Light sweet","note":"Smaller field","contract_duration":"State license","pipelines":"Ustyurt gathering → Nukus pipeline","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Uzbekistan' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Uzbekistan' AND commodity_name = 'Crude Oil' ORDER BY region, title;
