-- ============================================================
-- Vietnam Oil Production Sites — 21 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- OFFSHORE SOUTHERN VIETNAM / CUU LONG BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bach Ho Field', 'PetroVietnam + Zarubezhneft', 'Cuu Long Basin, Block 09-1', NULL, 'Energy', 'Crude Oil', 9.5000, 107.5833, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'Vietsovpetro (VSP)', 'joint_venture', 38.00, 0.04, 1350000, 150000000, 1350000, '{"start_year":1986,"production_bpd":45000,"quality":"Light sweet — Bach Ho crude Vietnam benchmark; fractured basement granite reservoir","note":"PetroVietnam 51%, Zarubezhneft 49%; Vietnam''s largest + most historic; first Vietnamese commercial oil export; peak ~280,000 bpd (1994)","last_transaction":"Vietsovpetro JV extended 2010 to 2030; ~$200M annual dividend to each side","contract_duration":"JV agreement to 2030","pipelines":"Bach Ho → FSO → tanker export; Bach Ho → Con Son gas pipeline","ports":"Vung Tau Port; Ho Chi Minh City (indirect)","rail":"None offshore"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rong Field', 'PetroVietnam + Zarubezhneft', 'Cuu Long Basin, Block 09-1', NULL, 'Energy', 'Crude Oil', 9.4167, 107.6667, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'Vietsovpetro (VSP)', 'joint_venture', 37.00, NULL, 240000, 80000000, 240000, '{"start_year":1994,"production_bpd":8000,"quality":"Light sweet (basement granite reservoir)","note":"Satellite to Bach Ho; PetroVietnam 51%, Zarubezhneft 49%","contract_duration":"JV to 2030","pipelines":"Rong → Bach Ho FSO → tanker export","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Su Tu Den Field', 'PVEP + ConocoPhillips + KNOC + SK Innovation', 'Cuu Long Basin, Block 15-1', NULL, 'Energy', 'Crude Oil', 9.7500, 107.8333, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'CUULONG JOC', 'joint_venture', 39.00, 0.03, 1650000, 300000000, 1650000, '{"start_year":2003,"production_bpd":55000,"quality":"Light sweet","note":"Vietnam''s second largest; PVEP 25%, ConocoPhillips 23.25%, KNOC 23.25%, SK Innovation 28.5%","last_transaction":"ConocoPhillips PSC Block 15-1 signed 1996; ConocoPhillips exploring Vietnam exit ~2022","contract_duration":"PSC to 2025 (renewal under negotiation)","pipelines":"Su Tu Den → Block 15-1 FSO (Armada Vencedor) → tanker export","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Su Tu Vang Field', 'PVEP + ConocoPhillips + KNOC + SK Innovation', 'Cuu Long Basin, Block 15-1', NULL, 'Energy', 'Crude Oil', 9.8333, 107.9167, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'CUULONG JOC', 'joint_venture', 38.00, NULL, 450000, 100000000, 450000, '{"start_year":2008,"production_bpd":15000,"quality":"Light sweet","note":"Su Tu Den satellite; PVEP/ConocoPhillips/KNOC/SK","contract_duration":"PSC to 2025","pipelines":"Su Tu Vang → Block 15-1 FSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Su Tu Trang Field', 'PVEP + ConocoPhillips + KNOC + SK Innovation', 'Cuu Long Basin, Block 15-1', NULL, 'Energy', 'Crude Oil', 9.6667, 107.7500, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'CUULONG JOC', 'joint_venture', 38.00, NULL, 300000, 80000000, 300000, '{"start_year":2015,"production_bpd":10000,"quality":"Light sweet","note":"PVEP/ConocoPhillips/KNOC/SK","contract_duration":"PSC to 2025","pipelines":"Su Tu Trang → Block 15-1 FSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Su Tu Nau Field', 'PVEP + ConocoPhillips + KNOC + SK Innovation', 'Cuu Long Basin, Block 15-1', NULL, 'Energy', 'Crude Oil', 9.9167, 107.8667, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'CUULONG JOC', 'joint_venture', 37.00, NULL, 240000, 60000000, 240000, '{"start_year":2018,"production_bpd":8000,"quality":"Light sweet","note":"PVEP/ConocoPhillips/KNOC/SK","contract_duration":"PSC to 2025","pipelines":"Su Tu Nau → Block 15-1 FSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Te Giac Trang Field', 'PVEP + Hess + PTTEP', 'Cuu Long Basin, Block 16-1', NULL, 'Energy', 'Crude Oil', 9.3333, 107.9167, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'Hoang Long JOC', 'joint_venture', 36.00, 0.05, 900000, 100000000, 900000, '{"start_year":2011,"production_bpd":30000,"quality":"Light sweet","note":"PVEP 35%, Hess 35%, PTTEP 30%; White Rhino","last_transaction":"Hess PSC Block 16-1 signed 1998; PTTEP joined 2008; Hess acquired by Chevron 2023","contract_duration":"PSC to 2029","pipelines":"Te Giac Trang → FPSO (Armada TGT1) → tanker export","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ca Ngu Vang Field', 'PVEP + Harvest Natural Resources', 'Cuu Long Basin, Block 9-2', NULL, 'Energy', 'Crude Oil', 9.1667, 107.7500, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Harvest Natural Resources', 'joint_venture', 37.00, NULL, 150000, 40000000, 150000, '{"start_year":2008,"production_bpd":5000,"quality":"Light sweet","note":"PVEP 50%, Harvest Natural Resources 50%; Golden Tuna; smaller field","contract_duration":"PSC","pipelines":"Ca Ngu Vang → FSO → tanker","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rang Dong Field', 'PVEP + MOECO + Idemitsu + Teikoku', 'Cuu Long Basin, Block 15-2', NULL, 'Energy', 'Crude Oil', 9.3500, 108.1667, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'JVPC (Japan Vietnam Petroleum Company)', 'joint_venture', 38.00, 0.04, 450000, 150000000, 450000, '{"start_year":1999,"production_bpd":15000,"quality":"Light sweet","note":"PVEP 35%, MOECO 35%, Idemitsu 15%, Teikoku Oil 15%; Dawn; longstanding Japanese consortium","last_transaction":"JVPC PSC signed 1992; one of Vietnam''s longest-running Japanese energy partnerships","contract_duration":"PSC to 2027","pipelines":"Rang Dong → FPSO (Rang Dong 1) → tanker export","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Phuong Dong Field', 'PVEP + MOECO + Idemitsu + Teikoku', 'Cuu Long Basin, Block 15-2', NULL, 'Energy', 'Crude Oil', 9.4167, 108.2500, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'JVPC', 'joint_venture', 37.00, NULL, 150000, NULL, 150000, '{"start_year":2009,"production_bpd":5000,"quality":"Light sweet","note":"Rang Dong satellite; East; same JVPC consortium","contract_duration":"PSC to 2027","pipelines":"Phuong Dong → Rang Dong FPSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ruby Field', 'PVEP + Petronas Carigali', 'Cuu Long Basin, Block 01', NULL, 'Energy', 'Crude Oil', 9.8333, 108.5833, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Petronas Carigali', 'joint_venture', 36.00, NULL, 300000, 100000000, 300000, '{"start_year":1998,"production_bpd":10000,"quality":"Light sweet","note":"PVEP 50%, Petronas Carigali 50%; mature","last_transaction":"PETRONAS PSC Block 01 signed 1992; longstanding Malaysia-Vietnam partnership","contract_duration":"PSC to 2028","pipelines":"Ruby → FSO → tanker","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Emerald Field', 'PVEP + Petronas Carigali', 'Cuu Long Basin, Block 01', NULL, 'Energy', 'Crude Oil', 9.7500, 108.6667, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Petronas Carigali', 'joint_venture', 36.00, NULL, 150000, NULL, 150000, '{"start_year":2004,"production_bpd":5000,"quality":"Light sweet","note":"Ruby satellite; PVEP 50%, PETRONAS 50%","contract_duration":"PSC to 2028","pipelines":"Emerald → Ruby FSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ca Rong Do Field', 'PetroVietnam', 'Cuu Long Basin, Block 07/09', NULL, 'Energy', 'Crude Oil', 9.5000, 108.3333, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'inactive', 'PetroVietnam', 'state_owned', 38.00, NULL, 0, 450000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Light sweet (estimated)","note":"Red Emperor; development stalled — South China Sea dispute; Repsol forced exit 2018 under Chinese pressure; Vietnam compensated Repsol ~$1B","last_transaction":"Repsol drilled discovery 2016; China pressured Vietnam to halt development; Repsol exited 2018; landmark South China Sea resource nationalism incident","contract_duration":"Development suspended","pipelines":"None (undeveloped)","ports":"Vung Tau (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NAM CON SON BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dai Hung Field', 'PVEP + Petronas + Harbour Energy', 'Nam Con Son Basin, Block 05-1a', NULL, 'Energy', 'Crude Oil', 7.6667, 109.0000, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Petronas + Harbour Energy', 'joint_venture', 37.00, 0.04, 300000, 200000000, 300000, '{"start_year":1994,"production_bpd":10000,"quality":"Light sweet","note":"Big Bear; PVEP 50%, Petronas 28.5%, Harbour Energy 21.5%; Vietnam''s first deepwater oil development","last_transaction":"Premier Oil → Harbour Energy acquisition 2021 ($5.3B)","contract_duration":"PSC to 2030","pipelines":"Dai Hung → FSO (Dai Hung Queen) → tanker export","ports":"Vung Tau (via tanker, ~400km)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chim Sao Field', 'Harbour Energy + PVEP + Petronas', 'Nam Con Son Basin, Block 12E', NULL, 'Energy', 'Crude Oil', 8.5000, 109.5000, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'Harbour Energy + PVEP + Petronas', 'joint_venture', 40.00, 0.03, 600000, 100000000, 600000, '{"start_year":2011,"production_bpd":20000,"quality":"Light sweet","note":"Star Bird; Harbour Energy 53.125%, PVEP 21.875%, Petronas 25%","last_transaction":"Premier Oil → Harbour Energy 2021; PSC Block 12E signed 2004","contract_duration":"PSC to 2034","pipelines":"Chim Sao → FPSO Lewek Emas → tanker export","ports":"Vung Tau (via tanker)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dua Field', 'Harbour Energy + PVEP + Petronas', 'Nam Con Son Basin, Block 12E', NULL, 'Energy', 'Crude Oil', 8.6667, 109.6667, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'Harbour Energy + PVEP + Petronas', 'joint_venture', 39.00, NULL, 240000, 50000000, 240000, '{"start_year":2014,"production_bpd":8000,"quality":"Light sweet","note":"Chim Sao satellite; same Harbour/PVEP/Petronas","contract_duration":"PSC to 2034","pipelines":"Dua → Chim Sao FPSO","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ca Tam Field', 'PVEP + ExxonMobil', 'Nam Con Son Basin, Block 05-2', NULL, 'Energy', 'Crude Oil', 7.5000, 109.1667, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + ExxonMobil', 'joint_venture', 38.00, NULL, 150000, NULL, 150000, '{"start_year":2002,"production_bpd":5000,"quality":"Light sweet","note":"PVEP 50%, ExxonMobil 50%","last_transaction":"ExxonMobil PSC Block 05-2 signed 1997","contract_duration":"PSC to 2032","pipelines":"Ca Tam → FSO → tanker","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rong Doi Field', 'PVEP + Santos + PTTEP', 'Nam Con Son Basin, Block 11-2', NULL, 'Energy', 'Crude Oil', 7.1667, 108.5833, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Santos + PTTEP', 'joint_venture', 37.00, NULL, 180000, 80000000, 180000, '{"start_year":2007,"production_bpd":6000,"quality":"Light sweet","note":"Twin Dragon; PVEP 35%, Santos 35%, PTTEP 30%; oil + gas","last_transaction":"Santos PSC signed 2002; PTTEP joined 2008","contract_duration":"PSC to 2032","pipelines":"Rong Doi → Nam Con Son Pipeline (gas + oil) → Ba Ria onshore","ports":"Vung Tau / Ba Ria onshore terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bunga Kekwa (PM3 CAA) Field', 'PVEP + Petronas Carigali', 'Block PM3 CAA — shared Vietnam/Malaysia', NULL, 'Energy', 'Crude Oil', 6.5000, 103.5000, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + PETRONAS Carigali', 'joint_venture', 38.00, NULL, 240000, NULL, 240000, '{"start_year":1999,"production_bpd":8000,"quality":"Light sweet","note":"Cai Nuoc; PETRONAS 50%, PVEP 50%; PM3 CAA joint Malaysia-Vietnam development zone; landmark maritime boundary solution","last_transaction":"PM3 CAA agreement signed 1992 — landmark joint development over overlapping claims","contract_duration":"CAA framework ongoing","pipelines":"PM3 CAA → Kerteh terminal (Malaysia) + Ba Ria (Vietnam)","ports":"Vung Tau; Kerteh (Malaysia)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Thang Long Field', 'PVEP + Rosneft Vietnam + Bitexco', 'Nam Con Son Basin, Block 01/10', NULL, 'Energy', 'Crude Oil', 8.1667, 108.8333, 'Vietnam', 'Nam Con Son Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Rosneft Vietnam', 'joint_venture', 37.00, NULL, 450000, 120000000, 450000, '{"start_year":2009,"production_bpd":15000,"quality":"Light sweet","note":"Dong Do; PVEP 35%, Rosneft Vietnam 35%, Bitexco 30%; TNK-BP historical","last_transaction":"TNK-BP passed to Rosneft via 2013 acquisition; Rosneft maintains presence despite 2022 Ukraine sanctions","contract_duration":"PSC to 2034","pipelines":"Thang Long → FPSO → tanker export","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hai Su Den Field', 'PVEP + Idemitsu + PTTEP', 'Block 15-2/01', NULL, 'Energy', 'Crude Oil', 9.1667, 108.0000, 'Vietnam', 'Cuu Long Basin', 'Vung Tau', 'oil_field', 'operational', 'PVEP + Idemitsu', 'joint_venture', 38.00, NULL, 360000, 80000000, 360000, '{"start_year":2014,"production_bpd":12000,"quality":"Light sweet","note":"Black/White Seahorse; PVEP 40%, Idemitsu 40%, PTTEP 20%","last_transaction":"Idemitsu PSC Block 15-2/01 signed 2008","contract_duration":"PSC to 2033","pipelines":"Hai Su → FSO → tanker","ports":"Vung Tau","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Vietnam' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Vietnam' AND commodity_name = 'Crude Oil' ORDER BY region, title;
