-- ============================================================
-- Pakistan Oil Production Sites — 45 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- SINDH PROVINCE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Khaskeli Field', 'OGDC', 'Sindh, Karachi District, Pakistan', NULL, 'Energy', 'Crude Oil', 25.1667, 67.7500, 'Pakistan', 'Sindh', 'Karachi', 'oil_field', 'operational', 'Oil & Gas Development Company (OGDC)', 'state_owned', 38.00, 0.10, 45000, 20000000, 45000, '{"start_year":1956,"production_bpd":1500,"quality":"Light sweet","contract_duration":"Development & Production Lease (DPL)","pipelines":"Karachi–Kotri crude gathering pipeline","ports":"Karachi Port / Keamari Oil Terminal","rail":"Karachi–Kotri main rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kotri / Lakhra Field', 'OGDC', 'Sindh, Jamshoro District, Pakistan', NULL, 'Energy', 'Crude Oil', 25.3667, 68.3000, 'Pakistan', 'Sindh', 'Jamshoro', 'oil_field', 'operational', 'OGDC', 'state_owned', 35.00, 0.12, 24000, 10000000, 24000, '{"start_year":1952,"production_bpd":800,"quality":"Light","note":"One of Pakistan''s oldest fields; mature, declining","pipelines":"Kotri–Karachi crude pipeline","ports":"Keamari Oil Terminal, Karachi","rail":"Kotri rail junction"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Badin Block', 'OMV / OGDC / PPL', 'Sindh, Badin District, Pakistan', NULL, 'Energy', 'Crude Oil', 24.6500, 68.8500, 'Pakistan', 'Sindh', 'Badin', 'oil_field', 'operational', 'OMV Pakistan (Austria) + OGDC + PPL', 'joint_venture', 42.00, 0.07, 300000, 150000000, 300000, '{"start_year":1985,"production_bpd":10000,"quality":"Light sweet","note":"Sindh''s largest oil cluster; OMV entered 1991","ownership_split":"OMV Pakistan 26.97%, OGDC 56.45%, PPL 16.58%","last_transaction":"OMV extended Badin PSA ~2015; partial stake sale discussions 2022","contract_duration":"PSA to 2030","pipelines":"Badin–Karachi crude pipeline (~200km); Badin gathering network","ports":"Keamari Oil Terminal, Karachi","rail":"Hyderabad–Kotri–Karachi rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tando Allah Yar Field', 'OGDC', 'Sindh, Hyderabad District, Pakistan', NULL, 'Energy', 'Crude Oil', 25.4333, 68.7167, 'Pakistan', 'Sindh', 'Hyderabad', 'oil_field', 'operational', 'OGDC', 'state_owned', 39.00, 0.08, 60000, 25000000, 60000, '{"start_year":1994,"production_bpd":2000,"quality":"Light sweet","pipelines":"Sindh gathering → Karachi pipeline","ports":"Keamari, Karachi","rail":"Hyderabad rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Naimat Basal Field', 'OGDC', 'Sindh, Pakistan', NULL, 'Energy', 'Crude Oil', 25.5833, 68.5000, 'Pakistan', 'Sindh', 'Naimat Basal', 'oil_field', 'operational', 'OGDC', 'state_owned', 37.00, 0.08, 45000, NULL, 45000, '{"start_year":1998,"production_bpd":1500,"quality":"Light sweet","pipelines":"Sindh crude gathering → Karachi","ports":"Karachi","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kunnar Pasakhi Deep (KPD) Field', 'OGDC / PPL', 'Sindh, Pakistan', NULL, 'Energy', 'Crude Oil', 24.9167, 68.6667, 'Pakistan', 'Sindh', 'Badin', 'oil_field', 'operational', 'OGDC + PPL', 'joint_venture', 40.00, 0.08, 150000, 60000000, 150000, '{"start_year":2004,"production_bpd":5000,"quality":"Light sweet","ownership_split":"OGDC 56%, PPL 44%","pipelines":"KPD → Badin pipeline → Karachi","ports":"Keamari, Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sono Field', 'PPL / OGDC', 'Sindh, Pakistan', NULL, 'Energy', 'Crude Oil', 24.7500, 68.9167, 'Pakistan', 'Sindh', 'Badin', 'oil_field', 'operational', 'Pakistan Petroleum Limited (PPL) + OGDC', 'joint_venture', 38.00, 0.08, 36000, NULL, 36000, '{"start_year":2002,"production_bpd":1200,"quality":"Light sweet","ownership_split":"PPL 60%, OGDC 40%","pipelines":"Sindh gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sinjhoro Field', 'OGDC', 'Sindh, Sanghar District, Pakistan', NULL, 'Energy', 'Crude Oil', 26.0000, 68.8667, 'Pakistan', 'Sindh', 'Sanghar', 'oil_field', 'operational', 'OGDC', 'state_owned', 41.00, 0.06, 90000, 35000000, 90000, '{"start_year":1996,"production_bpd":3000,"quality":"Light sweet","pipelines":"Sinjhoro → Sanghar → Karachi pipeline","ports":"Keamari, Karachi","rail":"Sanghar–Nawabshah rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Thatta / Gharo Field', 'OGDC', 'Sindh, Thatta District, Pakistan', NULL, 'Energy', 'Crude Oil', 24.7500, 67.9167, 'Pakistan', 'Sindh', 'Thatta', 'oil_field', 'operational', 'OGDC', 'state_owned', 36.00, 0.08, 24000, NULL, 24000, '{"start_year":1990,"production_bpd":800,"quality":"Light","note":"Small field","pipelines":"Thatta → Karachi (~60km)","ports":"Keamari, Karachi","rail":"Karachi–Hyderabad rail (Thatta station)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Indus East / Indus West Blocks', 'ENI / OGDC', 'Sindh offshore transition, Pakistan', NULL, 'Energy', 'Crude Oil', 24.5000, 68.5000, 'Pakistan', 'Sindh', 'Badin', 'oil_field', 'operational', 'ENI Pakistan + OGDC', 'joint_venture', 37.00, 0.07, 75000, NULL, 75000, '{"start_year":1999,"production_bpd":2500,"quality":"Light sweet","ownership_split":"ENI 40%, OGDC 60%","last_transaction":"ENI PSA signed 1995","contract_duration":"PSA to 2028","pipelines":"Indus blocks → Badin gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Miano Field', 'OMV / OGDC / PPL / MOL', 'Sindh, Khairpur District, Pakistan', NULL, 'Energy', 'Crude Oil', 27.0833, 68.5833, 'Pakistan', 'Sindh', 'Khairpur', 'oil_field', 'operational', 'OMV Pakistan + OGDC + PPL + MOL', 'joint_venture', 50.00, 0.04, 90000, 200000000, 90000, '{"start_year":1993,"production_bpd":3000,"quality":"Condensate, sweet","note":"Gas dominant + condensate","ownership_split":"OMV 26.67%, OGDC 33.33%, PPL 26.67%, MOL 13.33%","last_transaction":"PSA signed 1988; MOL Hungary entry 2005","contract_duration":"PSA to 2033","pipelines":"Miano gas → SSGC grid; condensate → Karachi","ports":"Karachi","rail":"Khairpur–Sukkur rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sawan Field', 'OMV / OGDC / PPL / MOL', 'Sindh, Khairpur District, Pakistan', NULL, 'Energy', 'Crude Oil', 27.2500, 68.9167, 'Pakistan', 'Sindh', 'Khairpur', 'oil_field', 'operational', 'OMV Pakistan (operator) + OGDC + PPL + MOL', 'joint_venture', 52.00, 0.03, 150000, 300000000, 150000, '{"start_year":1998,"production_bpd":5000,"quality":"Condensate, very light sweet","note":"Major gas + condensate","ownership_split":"OMV 26.67%, OGDC 33.33%, PPL 26.67%, MOL 13.33%","last_transaction":"PSA extended ~2018","contract_duration":"PSA to 2035","pipelines":"Sawan → SSGC main gas pipeline; condensate → Karachi","ports":"Karachi","rail":"Khairpur rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qadir Pur Field', 'OGDC / PPL', 'Sindh, Ghotki District, Pakistan', NULL, 'Energy', 'Crude Oil', 27.8333, 69.5000, 'Pakistan', 'Sindh', 'Ghotki', 'oil_field', 'operational', 'OGDC (operator) + PPL', 'joint_venture', 51.00, 0.04, 120000, 250000000, 120000, '{"start_year":1995,"production_bpd":4000,"quality":"Condensate sweet","note":"Gas + condensate","ownership_split":"OGDC 67.5%, PPL 32.5%","pipelines":"Qadir Pur → SNGPL/SSGC gas grid; condensate export pipeline","ports":"Karachi (via pipeline)","rail":"Ghotki–Rohri rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tando Muhammad Khan / Phulji Field', 'OGDC', 'Sindh, Pakistan', NULL, 'Energy', 'Crude Oil', 25.1167, 68.5333, 'Pakistan', 'Sindh', 'Tando Muhammad Khan', 'oil_field', 'operational', 'OGDC', 'state_owned', 36.00, 0.08, 30000, NULL, 30000, '{"start_year":2000,"production_bpd":1000,"quality":"Light sweet","pipelines":"Sindh gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BALOCHISTAN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sui Field', 'PPL', 'Balochistan, Dera Bugti District, Pakistan', NULL, 'Energy', 'Crude Oil', 28.6333, 69.1833, 'Pakistan', 'Balochistan', 'Dera Bugti', 'oil_field', 'operational', 'Pakistan Petroleum Limited (PPL)', 'state_owned', 48.00, 0.04, 60000, 30000000, 60000, '{"start_year":1952,"production_bpd":2000,"quality":"Condensate sweet — Sui condensate","note":"Pakistan''s largest gas field; primarily gas (~500 MMCFD), minor condensate","reserves_gas":"~15 TCF original; ~2 TCF remaining","ownership":"PPL 100% (state-owned; GoP 74.23%)","contract_duration":"DPL (perpetual state concession)","pipelines":"Sui–Multan–Karachi main gas pipeline (SSGC/SNGPL backbone); condensate via road tanker","ports":"Karachi (condensate by road)","rail":"Sibi–Quetta rail line (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Uch Field', 'OGDC / PPL / UCH Power', 'Balochistan, Dera Bugti District, Pakistan', NULL, 'Energy', 'Crude Oil', 29.0000, 69.9833, 'Pakistan', 'Balochistan', 'Dera Bugti', 'oil_field', 'operational', 'OGDC + PPL + UCH Power', 'joint_venture', 47.00, 0.04, 45000, 50000000, 45000, '{"start_year":1995,"production_bpd":1500,"quality":"Condensate sweet","note":"Gas + condensate; gas for power plant","reserves_gas":"~4 TCF","ownership_split":"OGDC 38.5%, PPL 38.5%, UCH Power (Engie) 23%","last_transaction":"BHP exited ~2003; GDF Suez took power/condensate rights","contract_duration":"PSA to 2035","pipelines":"Uch → Multan gas pipeline; condensate → Karachi","ports":"Karachi","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zarghun South Field', 'OGDC', 'Balochistan, Quetta District, Pakistan', NULL, 'Energy', 'Crude Oil', 30.3333, 67.1667, 'Pakistan', 'Balochistan', 'Quetta', 'oil_field', 'operational', 'OGDC', 'state_owned', 46.00, 0.04, 15000, NULL, 15000, '{"start_year":2004,"production_bpd":500,"quality":"Condensate sweet","note":"Gas + condensate","pipelines":"Zarghun → Quetta gas distribution; condensate by road","ports":"Karachi (by road)","rail":"Quetta–Sibi–Karachi rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Khetan Field', 'OGDC', 'Balochistan, Pakistan', NULL, 'Energy', 'Crude Oil', 29.5000, 68.3333, 'Pakistan', 'Balochistan', 'Khetan', 'oil_field', 'operational', 'OGDC', 'state_owned', 37.00, 0.08, 24000, NULL, 24000, '{"start_year":1999,"production_bpd":800,"quality":"Light sweet","pipelines":"Balochistan gathering → Karachi pipeline","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Loti Field', 'OGDC', 'Balochistan, Khuzdar District, Pakistan', NULL, 'Energy', 'Crude Oil', 28.5000, 66.5833, 'Pakistan', 'Balochistan', 'Khuzdar', 'oil_field', 'operational', 'OGDC', 'state_owned', 34.00, 0.10, 18000, NULL, 18000, '{"start_year":1983,"production_bpd":600,"quality":"Medium light","maturity":"Mature","pipelines":"Balochistan central gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pirkoh Field', 'OGDC', 'Balochistan, Dera Bugti — near Sui, Pakistan', NULL, 'Energy', 'Crude Oil', 28.8333, 68.9167, 'Pakistan', 'Balochistan', 'Dera Bugti', 'oil_field', 'operational', 'OGDC', 'state_owned', 45.00, 0.04, 30000, NULL, 30000, '{"start_year":1986,"production_bpd":1000,"quality":"Condensate sweet","note":"Gas + condensate","pipelines":"Pirkoh → Sui gas pipeline system; condensate → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zamzama Field', 'ENI / OGDC / PPL', 'Balochistan — Khuzdar/Jhal Magsi area, Pakistan', NULL, 'Energy', 'Crude Oil', 27.8333, 67.5000, 'Pakistan', 'Balochistan', 'Jhal Magsi', 'oil_field', 'operational', 'ENI Pakistan + OGDC + PPL', 'joint_venture', 50.00, 0.04, 90000, 80000000, 90000, '{"start_year":2002,"production_bpd":3000,"quality":"Condensate very light sweet","note":"Major gas + condensate (~350 MMCFD gas)","reserves_gas":"~3 TCF","ownership_split":"ENI 38.5%, OGDC 38.5%, PPL 20%, Government 3%","last_transaction":"BHP exited ~2004; ENI acquired operatorship; PSA extended 2020","contract_duration":"PSA to 2032","pipelines":"Zamzama → SSGC gas grid; condensate → Karachi via ENI pipeline","ports":"Keamari, Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chakar / Sujawal Field', 'OGDC / PPL', 'Balochistan/Sindh border, Pakistan', NULL, 'Energy', 'Crude Oil', 27.5000, 68.0833, 'Pakistan', 'Balochistan', 'Sujawal', 'oil_field', 'operational', 'OGDC + PPL', 'joint_venture', 38.00, 0.07, 45000, NULL, 45000, '{"start_year":2005,"production_bpd":1500,"quality":"Light sweet","ownership_split":"OGDC 56%, PPL 44%","pipelines":"Southern Balochistan → Sindh gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hala Block', 'MOL / OGDC', 'Balochistan/Sindh border area, Pakistan', NULL, 'Energy', 'Crude Oil', 26.7500, 68.4167, 'Pakistan', 'Balochistan', 'Hala', 'oil_field', 'operational', 'MOL Pakistan + OGDC', 'joint_venture', 39.00, 0.07, 60000, 30000000, 60000, '{"start_year":2006,"production_bpd":2000,"quality":"Light sweet","ownership_split":"MOL 40%, OGDC 60%","last_transaction":"MOL Hungary Block PSA signed 2003","contract_duration":"PSA to 2031","pipelines":"Hala → Sindh gathering → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Spud / Kirthar Block', 'OGDC', 'Balochistan — deep exploration, Pakistan', NULL, 'Energy', 'Crude Oil', 27.1667, 67.5833, 'Pakistan', 'Balochistan', 'Kirthar', 'oil_field', 'operational', 'OGDC', 'state_owned', 36.00, 0.08, 30000, NULL, 30000, '{"start_year":2010,"production_bpd":1000,"quality":"Light","note":"Active / Development","pipelines":"Kirthar → Balochistan → Karachi","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- PUNJAB
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Toot Field', 'OGDC', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.5500, 72.5833, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'OGDC', 'state_owned', 41.00, 0.07, 90000, 30000000, 90000, '{"start_year":1968,"production_bpd":3000,"quality":"Light sweet","note":"Pakistan''s first commercial oil field in Punjab","contract_duration":"DPL","pipelines":"Toot–Rawalpindi–Attock Refinery pipeline (~45km); direct refinery feed","ports":"None direct (landlocked Punjab, refinery-linked)","rail":"Attock–Rawalpindi rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dhurnal Field', 'OGDC / POL', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.4833, 72.4167, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'OGDC + Pakistan Oilfields Ltd (POL)', 'joint_venture', 44.00, 0.05, 150000, 50000000, 150000, '{"start_year":1984,"production_bpd":5000,"quality":"Light sweet — among Pakistan''s highest quality crudes","ownership_split":"OGDC 70%, POL 30%","pipelines":"Dhurnal → Attock Refinery pipeline","ports":"None direct","rail":"Attock–Rawalpindi rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pindori Field', 'POL', 'Punjab, Chakwal District, Pakistan', NULL, 'Energy', 'Crude Oil', 32.9333, 72.5667, 'Pakistan', 'Punjab', 'Chakwal', 'oil_field', 'operational', 'Pakistan Oilfields Ltd (POL)', 'private', 43.00, 0.05, 60000, 20000000, 60000, '{"start_year":1997,"production_bpd":2000,"quality":"Light sweet","ownership":"POL 100% (private listed company; Attock Group)","contract_duration":"DPL","pipelines":"Pindori → Attock Refinery pipeline (~30km)","ports":"None direct","rail":"Chakwal–Rawalpindi rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Minwal Field', 'POL', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.6167, 72.6667, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'Pakistan Oilfields Ltd (POL)', 'private', 42.00, 0.05, 45000, NULL, 45000, '{"start_year":1990,"production_bpd":1500,"quality":"Light sweet","ownership":"POL 100%","pipelines":"Minwal → Attock Refinery","ports":"None direct","rail":"Attock rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rajian Field', 'OGDC / POL', 'Punjab, Rawalpindi District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.2500, 72.9167, 'Pakistan', 'Punjab', 'Rawalpindi', 'oil_field', 'operational', 'OGDC + POL', 'joint_venture', 40.00, 0.06, 54000, NULL, 54000, '{"start_year":2001,"production_bpd":1800,"quality":"Light sweet","ownership_split":"OGDC 60%, POL 40%","pipelines":"Rajian → Attock Refinery pipeline","ports":"None","rail":"Rawalpindi–Attock rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Turkwal Field', 'POL / OGDC', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.7500, 72.4167, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'POL + OGDC', 'joint_venture', 41.00, 0.06, 24000, NULL, 24000, '{"start_year":2005,"production_bpd":800,"quality":"Light sweet","note":"Smaller field","ownership_split":"POL 50%, OGDC 50%","pipelines":"Attock district gathering → Attock Refinery","ports":"None","rail":"Attock rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Balkassar Field', 'AOC', 'Punjab, Chakwal District, Pakistan', NULL, 'Energy', 'Crude Oil', 32.8833, 72.6500, 'Pakistan', 'Punjab', 'Chakwal', 'oil_field', 'operational', 'Attock Oil Company (AOC)', 'private', 36.00, 0.15, 15000, 5000000, 15000, '{"start_year":1915,"production_bpd":500,"quality":"Light","note":"Colonial era — one of subcontinent''s oldest fields; very mature, symbolic significance","ownership":"AOC 100% (Attock Group private)","last_transaction":"Attock Group private ownership since colonial era","contract_duration":"Legacy concession (pre-independence)","pipelines":"Balkassar → Attock Refinery historical pipeline","ports":"None","rail":"Chakwal–Rawalpindi rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Adhi Field', 'OGDC / PPL / POL', 'Punjab, Rawalpindi District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.4667, 73.1667, 'Pakistan', 'Punjab', 'Rawalpindi', 'oil_field', 'operational', 'OGDC (operator) + PPL + POL', 'joint_venture', 43.00, 0.06, 165000, 80000000, 165000, '{"start_year":1978,"production_bpd":5500,"quality":"Light sweet","note":"Punjab''s largest producer; oil + gas + LPG","reserves_gas":"~1 TCF","ownership_split":"OGDC 56.45%, PPL 26.78%, POL 16.77%","contract_duration":"DPL renewable","pipelines":"Adhi → Attock Refinery pipeline (~40km); Adhi gas → SNGPL grid","ports":"None direct","rail":"Rawalpindi rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Meyal Field', 'POL / OGDC', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.6833, 72.2500, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'POL (operator) + OGDC', 'joint_venture', 40.00, 0.06, 75000, 25000000, 75000, '{"start_year":1968,"production_bpd":2500,"quality":"Light sweet","ownership_split":"POL 60%, OGDC 40%","pipelines":"Meyal → Attock Refinery (direct feed, ~15km)","ports":"None","rail":"Attock rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Joyamair Field', 'OGDC', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.5833, 72.3333, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'OGDC', 'state_owned', 39.00, 0.06, 30000, NULL, 30000, '{"start_year":1985,"production_bpd":1000,"quality":"Light sweet","maturity":"Mature","pipelines":"Attock gathering → Attock Refinery","ports":"None","rail":"Attock"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Fimkassar Field', 'OGDC / POL', 'Punjab, Attock District, Pakistan', NULL, 'Energy', 'Crude Oil', 32.8333, 72.0833, 'Pakistan', 'Punjab', 'Attock', 'oil_field', 'operational', 'OGDC + POL', 'joint_venture', 38.00, 0.06, 36000, NULL, 36000, '{"start_year":1993,"production_bpd":1200,"quality":"Light sweet","ownership_split":"OGDC 55%, POL 45%","pipelines":"Chakwal–Attock gathering → Attock Refinery","ports":"None","rail":"Attock rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chak Naurang Field', 'OGDC', 'Punjab, Mianwali District, Pakistan', NULL, 'Energy', 'Crude Oil', 32.5000, 71.6667, 'Pakistan', 'Punjab', 'Mianwali', 'oil_field', 'operational', 'OGDC', 'state_owned', 37.00, 0.07, 45000, 18000000, 45000, '{"start_year":1994,"production_bpd":1500,"quality":"Light sweet","pipelines":"Chak Naurang → Attock Refinery pipeline (~80km)","ports":"None","rail":"Mianwali rail station"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Nashpa Field', 'OGDC', 'Punjab/KPK border, Mianwali District, Pakistan', NULL, 'Energy', 'Crude Oil', 32.7500, 71.5000, 'Pakistan', 'Punjab', 'Mianwali', 'oil_field', 'operational', 'OGDC', 'state_owned', 42.00, 0.05, 225000, 75000000, 225000, '{"start_year":2007,"production_bpd":7500,"quality":"Light sweet","note":"One of Pakistan''s larger recent onshore discoveries","last_transaction":"Major OGDC domestic discovery announced 2007","contract_duration":"DPL","pipelines":"Nashpa → Attock Refinery pipeline (~100km)","ports":"None direct","rail":"Mianwali–Attock rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Makori East Field', 'OGDC', 'Punjab/KPK — Kohat District, Pakistan', NULL, 'Energy', 'Crude Oil', 33.5833, 71.5833, 'Pakistan', 'Punjab', 'Kohat', 'oil_field', 'operational', 'OGDC', 'state_owned', 40.00, 0.06, 90000, NULL, 90000, '{"start_year":2012,"production_bpd":3000,"quality":"Light sweet","pipelines":"Kohat → Attock Refinery pipeline","ports":"None","rail":"Kohat–Peshawar rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- OFFSHORE PAKISTAN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Indus Offshore Block G', 'ENI / OGDC', 'Arabian Sea, offshore Pakistan', NULL, 'Energy', 'Crude Oil', 23.5000, 66.5000, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'ENI Pakistan (operator) + OGDC', 'joint_venture', NULL, NULL, 0, 500000000, 0, '{"note":"Exploration / Pre-development — frontier deepwater","ownership_split":"ENI 60%, OGDC 40%","last_transaction":"ENI Block G PSA signed 1997","contract_duration":"PSA to 2030","pipelines":"Planned only","ports":"Karachi (planned offtake)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Offshore Block 2067-2', 'OGDC / GHPL', 'Arabian Sea — shallow, Pakistan', NULL, 'Energy', 'Crude Oil', 24.1667, 66.8333, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'OGDC + GHPL', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2008,"note":"Exploration stage","ownership_split":"OGDC 75%, GHPL 25%","pipelines":"Planned","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kekra-1 Well / Offshore Block 29', 'ExxonMobil / OGDC / PSO / PPL', 'Deep offshore Arabian Sea, Pakistan', NULL, 'Energy', 'Crude Oil', 23.3333, 65.5000, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'ExxonMobil (operator) + OGDC + PSO + PPL', 'joint_venture', NULL, NULL, 0, 1000000000, 0, '{"start_year":2019,"note":"Frontier deepwater exploration — Kekra-1 drilled at ~2,900m water depth; shows encountered, not commercial yet","potential_reserves":"1–3 billion barrels (frontier estimate)","ownership_split":"ExxonMobil 25%, OGDC 25%, PSO 25%, PPL 25%","last_transaction":"ExxonMobil PSA signed 2018 — ExxonMobil''s return to Pakistan after decades","contract_duration":"PSA to 2033","pipelines":"None yet","ports":"Karachi (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Offshore Block 28', 'ENI / OGDC', 'Arabian Sea — deepwater, Pakistan', NULL, 'Energy', 'Crude Oil', 23.0000, 64.8333, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'ENI Pakistan + OGDC', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2012,"note":"Exploration — deepwater frontier","ownership_split":"ENI 70%, OGDC 30%","pipelines":"None","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zarif Block', 'OGDC', 'Offshore Sindh — nearshore, Pakistan', NULL, 'Energy', 'Crude Oil', 24.3333, 67.3333, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'OGDC', 'state_owned', 36.00, 0.06, 15000, NULL, 15000, '{"start_year":2005,"production_bpd":500,"quality":"Light sweet","note":"Exploration / Early development — test production","pipelines":"Planned nearshore → Karachi","ports":"Keamari, Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Offshore Block 16', 'PPL / GHPL', 'Arabian Sea, shallow water, Pakistan', NULL, 'Energy', 'Crude Oil', 24.6667, 67.1667, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'Pakistan Petroleum Limited (PPL) + GHPL', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2010,"note":"Exploration stage","ownership_split":"PPL 65%, GHPL 35%","pipelines":"None yet","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('PEL Offshore Block', 'PEL', 'Arabian Sea, Pakistan', NULL, 'Energy', 'Crude Oil', 24.8333, 67.5000, 'Pakistan', 'Offshore', 'Karachi', 'oil_field', 'planned', 'Pakistan Exploration Ltd (PEL)', 'private', NULL, NULL, 0, NULL, 0, '{"start_year":2015,"note":"Exploration stage","ownership":"PEL 100% (private Pakistani company)","pipelines":"None","ports":"Karachi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- ============================================================
-- Verification
-- ============================================================
SELECT count(*) AS pakistan_oil_fields
FROM public.commodity_locations
WHERE country = 'Pakistan' AND commodity_name = 'Crude Oil';

SELECT count(*) AS total_locations
FROM public.commodity_locations;
