-- ============================================================
-- Zambia Sugar Mills — 3 mills (sugar_plants)
-- Run SUGAR_PLANTS_TABLE_SETUP.sql first. Then run this in Supabase SQL Editor.
-- Southern (Mazabuka/Kafue): 2 | Northern: 1
-- ============================================================

INSERT INTO public.sugar_plants (
  plant_id,
  mill_name,
  operator,
  country,
  iso_code,
  region,
  sugar_type,
  latitude,
  longitude,
  status,
  crushing_capacity_tcd,
  annual_output_tonnes,
  primary_grade,
  grades_available,
  icumsa_range,
  crushing_start,
  crushing_end,
  peak_months,
  export_terminal,
  distance_to_port_km,
  rail_access,
  storage_capacity_tonnes,
  price_benchmark,
  incoterms,
  typical_contract,
  major_buyers,
  export_markets,
  notes
) VALUES
  (
    'ZMB-SOU-001',
    'Nakambala Sugar Estate – Zambia Sugar Factory',
    'Zambia Sugar Plc — Illovo Sugar Africa / ABF Sugar (75%), LuSE public float (25%); listed on Lusaka Securities Exchange (ZSUG)',
    'Zambia',
    'ZMB',
    'Kafue Flats / Nakambala region – Southern Province (Mazabuka, ~150km south of Lusaka)',
    'sugarcane',
    -15.8667,
    27.7667,
    'operational',
    35000,
    450000,
    'Refined White Sugar / Raw Brown / VHP Raw',
    'Refined White Sugar (Whitespoon brand; 100,000 t/yr high-spec refinery commissioned 2016), Raw Sugar (VHP), Brown Granulated Sugar, Vitamin A-enriched direct consumption sugar, Syrup, Specialty Sugars, Molasses, Bagasse (cogen — supplies full factory + residential power during season)',
    '45–1200',
    'April',
    'December',
    'June, July, August, September',
    'Durban Sugar Terminal (via Zimbabwe/South Africa corridor, ~2,200km) or Dar es Salaam (TAZARA rail, ~2,000km)',
    2200,
    TRUE,
    300000,
    'ICE No. 11 / ICE No. 5 (refined) / EU ACP-EPA quota price / COMESA regional price',
    'FOB Durban; FOB Dar es Salaam; CIF regional',
    'Zambia domestic (Whitespoon brand primary); EU ACP quota; COMESA regional export; long-term supply agreements',
    'Zambia domestic market; COMESA region (DRC, Zimbabwe, Tanzania, Malawi, Mozambique); EU (ACP quota); institutional/industrial buyers',
    'COMESA Africa (~primary), EU (ACP/EPA quota), regional neighbouring countries',
    'Largest single-site cane sugar factory in Africa (per Illovo/Zambia Sugar annual reports). Founded 1964 by Tate & Lyle on south-east edge of Kafue Flats, Mazabuka. Nationalised 1972, reprivatised 1995. Tate & Lyle sold to Illovo 2001; Illovo (now ABF Sugar) now holds 75%. LuSE-listed since 1996. Factory expanded 2009–2010 (area from 11,000 to 17,000 ha) and again 2016 (new 100,000 t/yr high-spec refinery, ZMW 522M/$82M). Capacity: 450,000 t/yr sugar from ~3.5M t cane/yr (estate + 1.5M t from outgrowers and Nanga Farms). Own estate: ~17,000 ha irrigated; additional 3,500 ha agricultural expansion commissioned 2024 by President Hichilema. Whitespoon is Zambia''s leading retail sugar brand. Also administers 5 schools and provides bulk water supply to Mazabuka town (~250,000 residents). 6,385 direct + 4,774 indirect employees. 60th anniversary celebrated 2024.'
  ),
  (
    'ZMB-LUS-001',
    'Kafue Sugar – Consolidated Farming Ltd Mill',
    'Kafue Sugar / Consolidated Farming Limited (private Zambian/Zimbabwe-linked)',
    'Zambia',
    'ZMB',
    'Kafue Flats – Lusaka/Southern Province (Kafue area, along Kafue River)',
    'sugarcane',
    -15.7667,
    28.1833,
    'limited_operations',
    3000,
    25000,
    'Raw / Brown Sugar',
    'Raw Sugar, Brown Sugar, Molasses',
    '600–2000',
    'April',
    'November',
    'June, July, August',
    'Durban (via Zimbabwe/SA corridor)',
    2100,
    TRUE,
    20000,
    'ICE No. 11 / Zambian domestic price',
    'EXW Kafue',
    'Domestic supply (Lusaka market proximity)',
    'Zambia domestic market',
    'Zambia domestic only',
    'Second largest Zambia producer with ~5–7% national output. Located in Kafue area near Lusaka on Kafue River flats. Consolidated Farming Ltd is a private company; some links to Zimbabwean agricultural interests. Irrigated cane from Kafue River system. Proximity to Lusaka (Zambia''s capital and largest market) is a competitive advantage over Nakambala for local distribution. Capacity and output estimates based on USDA GAIN reports (contributes ~7.2% of national production historically).'
  ),
  (
    'ZMB-NOR-001',
    'Kalungwishi Sugar – Kasama Mill',
    'Kalungwishi Sugar / private operator (Northern Province)',
    'Zambia',
    'ZMB',
    'Eastern/Northern Province (Nakonde / Kasama area, Northern Zambia near Tanzania border)',
    'sugarcane',
    -10.2000,
    31.1667,
    'limited_operations',
    800,
    3000,
    'Raw Sugar',
    'Raw Sugar, Molasses',
    '600–2000',
    'May',
    'October',
    'June, July, August',
    'Dar es Salaam (via TAZARA railway through Tanzania)',
    2000,
    TRUE,
    5000,
    'EAC regional price / Zambian domestic price',
    'EXW Kasama',
    'Domestic supply (Northern Province)',
    'Zambia Northern Province domestic market',
    'Domestic only',
    'Very small operation — contributes ~0.3% of national Zambia sugar production historically. Located in Northern Province near the Tanzanian border (TAZARA rail corridor). Sub-industrial scale; included as the USDA-referenced third Zambia producer. Kalungwishi refers to the river system in Northern Province. Irrigated from small-scale river abstraction. Limited infrastructure; primarily serves local Northern Province market.'
  )
ON CONFLICT (mill_name, country) DO UPDATE SET
  plant_id = EXCLUDED.plant_id,
  operator = EXCLUDED.operator,
  iso_code = EXCLUDED.iso_code,
  region = EXCLUDED.region,
  sugar_type = EXCLUDED.sugar_type,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  status = EXCLUDED.status,
  crushing_capacity_tcd = EXCLUDED.crushing_capacity_tcd,
  annual_output_tonnes = EXCLUDED.annual_output_tonnes,
  primary_grade = EXCLUDED.primary_grade,
  grades_available = EXCLUDED.grades_available,
  icumsa_range = EXCLUDED.icumsa_range,
  crushing_start = EXCLUDED.crushing_start,
  crushing_end = EXCLUDED.crushing_end,
  peak_months = EXCLUDED.peak_months,
  export_terminal = EXCLUDED.export_terminal,
  distance_to_port_km = EXCLUDED.distance_to_port_km,
  rail_access = EXCLUDED.rail_access,
  storage_capacity_tonnes = EXCLUDED.storage_capacity_tonnes,
  price_benchmark = EXCLUDED.price_benchmark,
  incoterms = EXCLUDED.incoterms,
  typical_contract = EXCLUDED.typical_contract,
  major_buyers = EXCLUDED.major_buyers,
  export_markets = EXCLUDED.export_markets,
  notes = EXCLUDED.notes,
  updated_at = NOW();

