-- ============================================================
-- India Sugar Mills & Refineries — sugar_plants
-- Run SUGAR_PLANTS_TABLE_SETUP.sql first. Then run this in Supabase SQL Editor.
-- Representative large mills across UP, Maharashtra, Karnataka, TN, AP, Punjab/Haryana, Gujarat
-- ============================================================

INSERT INTO public.sugar_plants (
  plant_id,
  mill_name,
  operator,
  country,
  iso_code,
  region,
  sugar_type,
  latitude,
  longitude,
  status,
  crushing_capacity_tcd,
  annual_output_tonnes,
  primary_grade,
  grades_available,
  icumsa_range,
  crushing_start,
  crushing_end,
  peak_months,
  export_terminal,
  distance_to_port_km,
  rail_access,
  storage_capacity_tonnes,
  price_benchmark,
  incoterms,
  typical_contract,
  major_buyers,
  export_markets,
  notes
) VALUES
  (
    'IND-WUP-001',
    'Dhampur Sugar Mills Ltd — Dhampur Unit',
    'Dhampur Sugar Mills Ltd — private listed company (BSE: 500119); Goel family promoters',
    'India',
    'IND',
    'Uttar Pradesh — Western UP (Bijnor District)',
    'sugarcane',
    29.3060,
    78.5050,
    'operational',
    12000,
    180000,
    'M-30 Raw Sugar / S-30 Refined Sugar',
    'M-30 Raw Sugar, S-30 Refined Sugar, Refined White Sugar, Sulphitation Sugar, Molasses (A/B/C), Bagasse, Ethanol (distillery)',
    '150–600 (M-30); 45–100 (S-30/refined)',
    'October',
    'April',
    'November, December, January, February',
    'Kandla Port / JNPT Mumbai (~1,200–1,400km); Pipavav',
    1300,
    TRUE,
    120000,
    'NCDEX Futures (domestic); ICE No.11 (export); UP SAP (cane procurement)',
    'EXW Dhampur; FOB Kandla/JNPT',
    'Domestic bulk (trading companies, FMCG); export under OML quota; ethanol supply to OMCs (oil marketing companies)',
    'Domestic food industry; OMCs (IOCL, BPCL, HPCL) for ethanol; sugar traders',
    'Indonesia, Bangladesh, Sri Lanka, Africa (when export quota available)',
    'Dhampur Sugar Mills is one of western UP''s oldest and most established private mills, founded 1933. Multiple units: Dhampur (12,000 TCD), Asmoli (Sambhal), Mansurpur (Muzaffarnagar), and Rajpura — combined group capacity ~38,000 TCD. Vertically integrated: sugar → molasses → ethanol distillery (capacity ~150 KLPD). Dhampur unit has an ICUMSA 45 refinery. Western UP (Bijnor, Muzaffarnagar, Meerut, Hapur, Saharanpur, Bulandshahr, Moradabad districts) is India''s densest sugarcane belt — flat Gangetic plains, canal irrigation, high cane productivity (~80–85 t/ha). Sugar recovery in western UP ~10.5–11.5%. UP SAP FY2024-25: Rs 400/quintal (general variety).'
  ),
  (
    'IND-WUP-002',
    'Triveni Engineering & Industries Ltd — Khatauli Unit',
    'Triveni Engineering & Industries Ltd — private listed (NSE: TRIVENI); Thapar group',
    'India',
    'IND',
    'Uttar Pradesh — Western UP (Muzaffarnagar District)',
    'sugarcane',
    29.2760,
    77.7390,
    'operational',
    13000,
    200000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Refined White Sugar, Molasses, Ethanol, Power (co-gen)',
    '150–600 (M-30); 45–100 (refined)',
    'October',
    'April',
    'November, December, January, February',
    'Kandla / JNPT (~1,200km)',
    1200,
    TRUE,
    150000,
    'NCDEX; ICE No.11; UP SAP',
    'EXW Khatauli; FOB Kandla',
    'Domestic bulk; OML export quota; ethanol to OMCs',
    'Domestic food/beverage; OMCs; traders',
    'Indonesia, Bangladesh, UAE (when quota available)',
    'Triveni Engineering is one of India''s top 5 private sugar companies. 7 units across western and central UP: Khatauli (13,000 TCD), Muzaffarnagar (7,500 TCD), Deoband (10,000 TCD), Ramkola, Chandanpur, Rani Nangal, Milak Narayanpur — total group ~66,000 TCD. Also operates power turbine manufacturing (Triveni Turbine, separately listed). Khatauli unit has co-generation power plant (surplus to grid). Distillery capacity ~660 KLPD across group. Muzaffarnagar District is the highest cane density district in UP — sometimes called ''Sugar Bowl of India''. Western UP supplies ~50% of UP''s total cane.'
  ),
  (
    'IND-WUP-003',
    'Balrampur Chini Mills Ltd — Balrampur Unit',
    'Balrampur Chini Mills Ltd — private listed (NSE: BALRAMCHIN); Swarup family promoters',
    'India',
    'IND',
    'Uttar Pradesh — Western/Central UP (Balrampur District; group units across eastern and western UP)',
    'sugarcane',
    27.4300,
    82.1830,
    'operational',
    10000,
    150000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Refined Sugar, Molasses (A/B/C), Ethanol, Power',
    '150–600 (M-30); 45 (refined)',
    'October',
    'April',
    'November, December, January',
    'Kolkata Port / Kandla (~1,400km)',
    900,
    TRUE,
    100000,
    'NCDEX; UP SAP',
    'EXW Balrampur; FOB Kandla/Kolkata',
    'Domestic bulk; ethanol to OMCs; export OML',
    'Domestic; OMCs; traders',
    'Bangladesh, Indonesia, Africa (when quota)',
    'Balrampur Chini is India''s 2nd largest sugar company by capacity. 10 units across UP — Balrampur, Babhnan, Tulsipur, Haidergarh, Akbarpur, Mankapur, Rauzagaon, Gularia, Kumbhi, Maizapur — total ~1,30,000 TCD (approx). Distillery capacity ~1,100 KLPD across group, making it one of India''s largest ethanol producers. The ethanol business now contributes ~40–50% of group EBITDA, reducing dependency on cyclical sugar prices. Balrampur District is in eastern UP near the Nepal border; other units are in central and western UP.'
  ),
  (
    'IND-WUP-004',
    'Mawana Sugars Ltd — Mawana Unit',
    'Mawana Sugars Ltd — private listed (BSE: 500160); Siel Ltd / Budhiraja group',
    'India',
    'IND',
    'Uttar Pradesh — Western UP (Meerut District)',
    'sugarcane',
    29.1063,
    77.8950,
    'operational',
    8000,
    100000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Refined Sugar, Molasses, Ethanol',
    '150–600 (M-30); 45–150 (refined)',
    'October',
    'March',
    'November, December, January',
    'JNPT / Kandla (~1,250km)',
    1250,
    TRUE,
    80000,
    'NCDEX; UP SAP',
    'EXW Mawana',
    'Domestic supply; UP government procurement',
    'Domestic food industry; state agencies',
    'Limited — domestic focus',
    'Mawana is one of the oldest sugar mills in India, established ~1932. Located in Meerut District, core western UP cane belt. Also has Titawi unit (Muzaffarnagar). Western UP mills benefit from proximity to the Delhi NCR food & beverage manufacturing hub (~70km). Meerut–Muzaffarnagar–Saharanpur triangle is the most intensive cane farming zone in India.'
  ),
  (
    'IND-EUP-001',
    'Bajaj Hindusthan Sugar Ltd — Palia Kalan Unit',
    'Bajaj Hindusthan Sugar Ltd (BHSL) — private listed (NSE: BAJAJHIND); Bajaj family (Shishir Bajaj)',
    'India',
    'IND',
    'Uttar Pradesh — Eastern UP (Lakhimpur Kheri District)',
    'sugarcane',
    28.4430,
    80.5860,
    'operational',
    10000,
    130000,
    'M-30 Raw Sugar',
    'M-30, S-30, Molasses, Ethanol, Power (co-gen)',
    '150–600',
    'October',
    'April',
    'November, December, January',
    'Kolkata Port (~1,000km); Kandla (~1,400km)',
    1000,
    TRUE,
    100000,
    'NCDEX; UP SAP',
    'EXW Palia Kalan; FOB Kolkata',
    'Domestic bulk; ethanol to OMCs; export OML',
    'Domestic; OMCs; trading companies',
    'Bangladesh, Indonesia, Sri Lanka (when quota)',
    'Bajaj Hindusthan Sugar is India''s largest sugar company by installed capacity — 14 units, all in UP, combined ~1,36,000 TCD. Units in both eastern and western UP: Palia Kalan, Khambarkhera, Kinauni, Maqsoodapur, Pratappur, Rudauli, Gola, Kundarkhi, Budhana, Bilai, Barkheda, Gangnauli, Thanabhawan, Pooranpur. BHSL has historically been heavily indebted (cane arrears crisis of 2014–16 when UP mills owed Rs 10,000+ crore to farmers). Financial restructuring ongoing. Distillery capacity ~800 KLPD. Lakhimpur Kheri is eastern UP''s largest cane district — part of the Terai belt bordering Nepal.'
  ),
  (
    'IND-EUP-002',
    'Uttam Sugar Mills Ltd — Libberheri Unit',
    'Uttam Sugar Mills Ltd — private listed (NSE: UTTAMSUGAR); Uttam Group',
    'India',
    'IND',
    'Uttar Pradesh / Uttarakhand border (Libberheri — Haridwar District, near Muzaffarnagar)',
    'sugarcane',
    29.8200,
    78.0270,
    'operational',
    8500,
    100000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Refined Sugar, Molasses, Ethanol',
    '150–600 (M-30); 45–150 (refined)',
    'October',
    'April',
    'November, December, January',
    'Kandla / JNPT (~1,200km)',
    1200,
    TRUE,
    80000,
    'NCDEX; UP/Uttarakhand SAP',
    'EXW Libberheri',
    'Domestic supply; ethanol to OMCs',
    'Domestic food industry; OMCs',
    'Limited',
    'Uttam Sugar operates 5 units: Libberheri (Haridwar border, Uttarakhand/UP boundary), Khaikheri (Muzaffarnagar), Barkatpur (Bareilly), Hathras (western UP), and Sitapur (eastern UP). All UP/Uttarakhand operations. Group distillery capacity ~300 KLPD. Mid-size private operator. Haridwar–Muzaffarnagar corridor straddles the UP–Uttarakhand border; the Libberheri mill draws cane from both states.'
  ),
  (
    'IND-EUP-003',
    'Simbhaoli Sugars Ltd — Simbhaoli Unit',
    'Simbhaoli Sugars Ltd — private listed (BSE: 507998); Simbhaoli Group',
    'India',
    'IND',
    'Uttar Pradesh — Western UP (Hapur District — also supplies eastern markets)',
    'sugarcane',
    28.5670,
    77.9890,
    'operational',
    8000,
    90000,
    'Refined White Sugar / M-30',
    'Refined White Sugar (ICUMSA 45), M-30, Molasses, Ethanol, Power',
    '45–600',
    'October',
    'April',
    'November, December, January',
    'JNPT Mumbai (~1,250km); Kandla',
    1250,
    TRUE,
    80000,
    'NCDEX; UP SAP; ICE No.11 (refined export)',
    'EXW Simbhaoli; FOB JNPT',
    'Domestic branded sugar (Go Sugar brand); institutional; export OML',
    'Domestic retail (branded); food industry; OMCs',
    'UAE, Bangladesh, Sri Lanka (ICUMSA 45 refined)',
    'Simbhaoli Sugars, established 1933, is among India''s more consumer-facing sugar companies with branded retail operations (''Go Sugar''). Operates refinery producing ICUMSA 45 directly — less common for UP mills which mostly produce M-30. 3 units: Simbhaoli (Hapur), Chilwaria (Bahraich, eastern UP), Brijnathpur (Hapur). Has faced financial stress (debt restructuring 2019–21). Hapur is close to Ghaziabad / Delhi NCR — good logistics for branded FMCG supply.'
  ),
  (
    'IND-EUP-004',
    'UP Cooperative Sugar Factories — Basti / Gorakhpur Belt (Representative Entry)',
    'UP Cooperative Sugar Factories Federation (UPCSFED) — state government / cooperative',
    'India',
    'IND',
    'Uttar Pradesh — Eastern UP (Gorakhpur Division: Gorakhpur, Deoria, Basti, Sant Kabir Nagar, Kushinagar, Maharajganj)',
    'sugarcane',
    26.7606,
    83.3732,
    'operational',
    5000,
    50000,
    'M-30 Raw Sugar',
    'M-30, Molasses, Bagasse',
    '150–600',
    'November',
    'March',
    'December, January',
    'Kolkata Port (~900km)',
    900,
    TRUE,
    40000,
    'UP SAP; government procurement price',
    'EXW mill gate',
    'State government procurement; PDS (public distribution); domestic wholesale',
    'UP government PDS (ration system); domestic wholesale',
    'None — state distribution',
    'This entry represents the cluster of UP State Cooperative Sugar Factories in the Gorakhpur/Basti/Deoria belt of eastern UP. UPCSFED manages ~20+ cooperative mills in eastern UP, many financially distressed. Eastern UP mills typically smaller (3,000–7,000 TCD), lower recovery rates (~9–10%), older equipment. Key mills in this cluster: Siswa Bazar (Maharajganj), Padrauna (Kushinagar), Kaptanganj (Basti), Rudrapur (Deoria), Gauri Bazar (Deoria), Anandnagar (Sant Kabir Nagar). Eastern UP is India''s poorest cane-growing region — higher cane arrears default risk, greater dependence on UP government price support. Gorakhpur Division produces ~5–6 MT cane/season.'
  ),
  (
    'IND-MPU-001',
    'Shree Renuka Sugars Ltd — Maharashtra/Pune Region',
    'Shree Renuka Sugars Ltd — listed (NSE: RENUKA); Wilmar International major shareholder (~75%)',
    'India',
    'IND',
    'Maharashtra — Pune Region (Pune, Solapur, Satara, Ahmednagar districts; plus integrated with Karnataka units and refineries)',
    'sugarcane',
    18.5204,
    73.8567,
    'operational',
    8000,
    120000,
    'Refined White Sugar / Raw Sugar',
    'Refined White Sugar (ICUMSA 45), M-30, Raw VHP, Liquid Sugar, Molasses, Ethanol',
    '45–150 (refined); 600–1200 (VHP export)',
    'October',
    'April',
    'November, December, January, February',
    'JNPT Mumbai (~150km); Mormugao Goa (~300km)',
    150,
    TRUE,
    150000,
    'NCDEX/MCX; ICE No.11 (VHP export); FRP + Maharashtra state premium',
    'EXW mill; FOB JNPT/Mormugao',
    'Domestic bulk refined; VHP export to refiners (Indonesia, Bangladesh, Middle East); ethanol to OMCs',
    'Domestic FMCG (Wilmar group companies); international refiners; OMCs',
    'Indonesia, Bangladesh, UAE, Sri Lanka, Malaysia (VHP/ICUMSA 45)',
    'Shree Renuka Sugars is India''s largest sugar refiner and one of the largest exporters. 8 units across Maharashtra and Karnataka — total ~60,000 TCD. Became subsidiary of Wilmar International (Singapore) in 2020 after debt restructuring — Wilmar''s global sugar/agri network transforms Renuka into a strategic export platform. Key plants: Munoli (Karnataka, 13,000 TCD), Haveri (Karnataka), Bangalore Refinery; Maharashtra units in Pune/Solapur region. Also owns Brazil operations (Equipav/Vale do Ivai). Renuka Haldia refinery (West Bengal) processes imported raw sugar. Proximity to JNPT makes Maharashtra units India''s most cost-effective export platform. Maharashtra cane recovery: ~11–12%, among India''s highest.'
  ),
  (
    'IND-MPU-002',
    'Maharashtra Cooperative & Private Mills — Pune/Ahmednagar/Satara Cluster (Representative Entry)',
    'Various private and cooperative mills — Pune, Ahmednagar, Satara districts (including Bajaj group, Praj-linked mills, co-ops)',
    'India',
    'IND',
    'Maharashtra — Pune Region (Ahmednagar, Satara, Solapur districts)',
    'sugarcane',
    19.0728,
    74.7380,
    'operational',
    7500,
    100000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Molasses, Ethanol, Power',
    '150–600',
    'October',
    'March',
    'November, December, January',
    'JNPT Mumbai (~200km)',
    200,
    TRUE,
    80000,
    'NCDEX/MCX; FRP',
    'EXW mill; FOB JNPT',
    'Domestic supply; cooperative levy; Maharashtra state',
    'Maharashtra domestic market; state PDS; traders',
    'Export via JNPT (VHP when quota available)',
    'The Pune–Ahmednagar–Satara region is Maharashtra''s secondary cane belt (primary is Kolhapur). Key mills in this cluster include cooperative mills under Maharashtra State Co-op Sugar Factories Federation (MSCSFF) and private mills. Pune Division''s cane grows in rain-shadow areas requiring irrigation (Bhima, Godavari river command areas). Recovery ~10.5–11.5%. Major ethanol producers — Praj Industries (Pune-based) supplies distillery technology to most Maharashtra mills. Pune region has India''s highest concentration of second-generation ethanol R&D (Praj Matrix, partnerships with IISc etc.). Cane variety Co-86032 dominant in Maharashtra.'
  ),
  (
    'IND-MKO-001',
    'Dalmia Bharat Sugar / Kolhapur–Belgaum Cluster (Representative Entry)',
    'Various — Rajarambapu Patil SSK, Dalmia Bharat Sugar, Shree Datta Shetkari SSK and other co-ops/private mills',
    'India',
    'IND',
    'Maharashtra — Kolhapur Region (Kolhapur, Sangli, Satara districts — southern Maharashtra)',
    'sugarcane',
    16.7050,
    74.2433,
    'operational',
    10000,
    160000,
    'S-30 / M-30 Sugar',
    'S-30, M-30, Refined Sugar, Molasses, Ethanol, Power (co-gen)',
    '45–600',
    'October',
    'April',
    'November, December, January, February, March',
    'Mormugao Port Goa (~150km); JNPT Mumbai (~400km)',
    150,
    TRUE,
    120000,
    'NCDEX/MCX; FRP; Maharashtra SAP',
    'EXW Kolhapur; FOB Mormugao/JNPT',
    'Domestic Maharashtra/Karnataka supply; VHP/raw export via Mormugao',
    'Domestic food industry; traders; OMCs for ethanol; export traders via Goa',
    'Indonesia, Bangladesh, UAE, East Africa (VHP raw via Mormugao/JNPT)',
    'Kolhapur is Maharashtra''s — and arguably India''s — highest quality cane belt. Key advantages: perennial irrigation from Krishna river tributaries (Panchganga, Bhogavati), high sucrose content, among India''s best recovery rates (12–13%+), adsali (18-month ratoon) cane variety common. Kolhapur Division hosts ~45+ sugar factories, most cooperative. Key cooperative mills: Rajarambapu Patil SSK, Datta Shetkari SSK (Shirol), Warana SSK (Kolhapur/Sangli), Kumbhi-Kasari SSK. Private mills: Dalmia Bharat (acquired several units post-2015). Kolhapur sugar has premium pricing in domestic market. Mormugao (Goa) is India''s preferred export port for southern Maharashtra/Karnataka sugar — closer than JNPT. Maharashtra produces ~12–14 MT cane/season from Kolhapur division alone. Ethanol programme: Maharashtra co-ops leading B-heavy molasses diversion.'
  ),
  (
    'IND-MKO-002',
    'Warana Vibhag Sahakari Sakhar Karkhana (Warana Sugar Cooperative)',
    'Warana SSK — cooperative society; Tatyasaheb Kore family; Kolhapur / Sangli',
    'India',
    'IND',
    'Maharashtra — Kolhapur / Sangli border (Warana area — Peth Vadgaon, Kolhapur District)',
    'sugarcane',
    16.8910,
    74.1290,
    'operational',
    9000,
    130000,
    'S-30 / M-30 Sugar',
    'S-30, M-30, Refined Sugar, Molasses, Ethanol, Power',
    '45–600',
    'October',
    'April',
    'November, December, January, February',
    'Mormugao Port (~160km)',
    160,
    TRUE,
    100000,
    'NCDEX; FRP',
    'EXW Warana; FOB Mormugao',
    'Domestic cooperative levy; Maharashtra supply; export via Goa',
    'Maharashtra domestic; traders; state levy',
    'Indonesia, UAE (via Mormugao)',
    'Warana Cooperative is one of India''s most celebrated sugar cooperatives — founded by social reformer Tatyasaheb Kore in 1959 as part of Warana Nagar village development model (cooperative bank, dairy, education, sugar all integrated). Model for Maharashtra co-op movement. Warana area lies on Kolhapur–Sangli border, optimal cane agro-climatic zone. Recovery rate consistently among Maharashtra''s best. Also operates distillery and co-gen power. Warana Nagar complex includes school, college, hospital, bank — one of India''s rare cooperative village development success stories.'
  ),
  (
    'IND-KAR-001',
    'Shree Renuka Sugars Ltd — Munoli Unit (Belagavi)',
    'Shree Renuka Sugars Ltd / Wilmar International (~75% stake)',
    'India',
    'IND',
    'Karnataka — Belagavi (Belgaum) District (Munoli, Gokak area — northern Karnataka)',
    'sugarcane',
    16.2120,
    74.8300,
    'operational',
    13000,
    200000,
    'Refined White Sugar (ICUMSA 45) / VHP Raw',
    'ICUMSA 45 Refined, M-30, VHP Raw (export), Liquid Sugar, Molasses, Ethanol',
    '45–1200',
    'October',
    'April',
    'November, December, January, February',
    'Mormugao Port Goa (~150km); JNPT (~550km)',
    150,
    TRUE,
    200000,
    'NCDEX/MCX; ICE No.11 (VHP); Karnataka FRP',
    'EXW Munoli; FOB Mormugao',
    'Domestic bulk (Wilmar network); VHP export to SE Asia/Middle East; ethanol to OMCs',
    'Wilmar global sugar supply chain; Indonesian refiners; Middle East; OMCs',
    'Indonesia, Malaysia, UAE, Bangladesh, Sri Lanka (VHP + ICUMSA 45)',
    'Munoli is one of India''s largest sugar mills by crushing capacity. 13,000 TCD single-site; total Renuka Belagavi complex including refinery ~16,000 TCD equivalent. The Belagavi (formerly Belgaum) district straddles the Karnataka–Goa–Maharashtra border, with excellent cane agro-climatic conditions (Krishna river upstream, Malaprabha command area). Wilmar''s global network makes Munoli a key node in global sugar supply chains — particularly for SE Asia. The mill has advanced quality systems enabling consistent ICUMSA 45 production. Distillery capacity ~300 KLPD. Belagavi is the capital of Karnataka''s ''sugar belt'' — the district and adjoining Vijayapura, Bagalkote, Dharwad districts have ~50+ mills.'
  ),
  (
    'IND-KAR-002',
    'Nirani Sugars Ltd — Mudhol Unit',
    'Nirani Sugars Ltd — private; Murugesh Nirani (politician-industrialist, ex-Karnataka Minister)',
    'India',
    'IND',
    'Karnataka — Bagalkote District (Mudhol; also Bhalki, Bidar units in group)',
    'sugarcane',
    16.3520,
    75.2870,
    'operational',
    12000,
    170000,
    'M-30 / Refined Sugar',
    'M-30, Refined Sugar, Molasses, Ethanol, Power',
    '45–600',
    'October',
    'April',
    'November, December, January, February',
    'Mormugao (~200km); JNPT (~600km)',
    200,
    TRUE,
    150000,
    'NCDEX; Karnataka FRP',
    'EXW Mudhol; FOB Mormugao',
    'Domestic Karnataka/Maharashtra supply; export OML',
    'Domestic food industry; traders',
    'Indonesia, UAE (when export quota available)',
    'Nirani Sugars is one of Karnataka''s largest private sugar groups. Multiple units: Mudhol (Bagalkote), Bhalki (Bidar), and others — combined ~25,000+ TCD. Murugesh Nirani is a prominent BJP politician in Karnataka, and the mills have strong political connections affecting regulatory treatment. Bagalkote district is in the Malaprabha–Krishna command area — perennial irrigation, high cane productivity. Karnataka sugar industry is almost entirely private (unlike UP''s cooperative/state sector mix). Karnataka recovery rates: ~11–12%, comparable to Maharashtra.'
  ),
  (
    'IND-KAR-003',
    'EID Parry (India) Ltd — Karnataka Unit (Representative)',
    'EID Parry (India) Ltd — listed (NSE: EIDPARRY); Murugappa Group',
    'India',
    'IND',
    'Karnataka — Davangere / Chitradurga District (plus TN operations)',
    'sugarcane',
    14.4670,
    75.9220,
    'operational',
    8000,
    100000,
    'Refined White Sugar / M-30',
    'Refined White Sugar, M-30, Molasses, Ethanol, Power, Nutraceuticals (subsidiary)',
    '45–600',
    'October',
    'April',
    'November, December, January',
    'Chennai Port / Ennore (~350km); Mormugao (~400km)',
    350,
    TRUE,
    80000,
    'NCDEX; Karnataka/Tamil Nadu FRP',
    'EXW mill; FOB Chennai',
    'Domestic branded (Parry''s Sugar brand); institutional; export OML',
    'Domestic retail (branded Parry''s); food industry; OMCs',
    'Bangladesh, UAE, SE Asia (when quota)',
    'EID Parry is one of India''s oldest sugar companies, established 1788 by Thomas Parry (British merchant). Now part of the Murugappa Group conglomerate. Key mills: Karnataka (Davangere/Chitradurga), Tamil Nadu (Pugalur — see TN entry), Nellikuppam (Tamil Nadu). Also holds stake in Coromandel International (fertilisers) and nutraceuticals (Parry Nutraceuticals). ''Parry''s Sugar'' is a premium branded product in South India. EID Parry straddles the Karnataka–Tamil Nadu border cane belt.'
  ),
  (
    'IND-TNC-001',
    'EID Parry (India) Ltd — Pugalur Unit',
    'EID Parry (India) Ltd / Murugappa Group',
    'India',
    'IND',
    'Tamil Nadu — Coimbatore Region (Pugalur, Karur District; also Pettavaithalai, Nellikuppam)',
    'sugarcane',
    10.9670,
    77.9560,
    'operational',
    7500,
    90000,
    'Refined White Sugar',
    'Refined White Sugar, M-30, Molasses, Ethanol, Power',
    '45–150',
    'October',
    'March',
    'November, December, January',
    'Chennai Port / Ennore (~350km); Tuticorin (~300km)',
    300,
    TRUE,
    80000,
    'NCDEX; Tamil Nadu FRP',
    'EXW Pugalur; FOB Chennai/Tuticorin',
    'Domestic branded (Parry''s); South India institutional; export',
    'South India domestic; branded retail; OMCs',
    'Bangladesh, UAE, Malaysia (when quota)',
    'Pugalur (Karur District) is in the Coimbatore–Tirupur sugar belt of Tamil Nadu. TN''s cane belt runs from Coimbatore–Erode–Karur–Tiruchirappalli. Tamil Nadu sugar industry challenges: water scarcity (cane is water-intensive; TN faces recurrent drought), high cane cost, small mill sizes. TN produces ~600,000–800,000 t/yr sugar from ~40+ mills. Key TN mills: EID Parry (Pugalur, Nellikuppam), Ponni Sugars (Erode), TANCEM / TNSC (state mills). Coimbatore belt benefits from Bhavani river irrigation.'
  ),
  (
    'IND-TNC-002',
    'Ponni Sugars (Erode) Ltd',
    'Ponni Sugars (Erode) Ltd — private listed (BSE: 532460); A.R.M. Group',
    'India',
    'IND',
    'Tamil Nadu — Coimbatore Region (Erode District — Bhavani area)',
    'sugarcane',
    11.4100,
    77.7380,
    'operational',
    5500,
    65000,
    'S-30 / Refined Sugar',
    'S-30, Refined Sugar, Molasses, Ethanol, Power',
    '45–200',
    'October',
    'March',
    'November, December',
    'Chennai Port / Ennore (~350km); Tuticorin (~280km)',
    280,
    TRUE,
    50000,
    'NCDEX; Tamil Nadu FRP',
    'EXW Bhavani; FOB Tuticorin',
    'South India domestic supply; Tamil Nadu state PDS',
    'South India domestic; Tamil Nadu government',
    'Limited',
    'Ponni Sugars operates at Bhavani, Erode District — on the Bhavani river. Name ''Ponni'' refers to River Kaveri (Ponni = Kaveri in Tamil). Tamil Nadu sugar industry is chronically constrained by water — cane competes with paddy and vegetables for Bhavani/Kaveri river water. Erode is also India''s largest textile/fabric trading hub, so agri-processing competes for labour with garment industry. Small to mid-size mill; represents the typical TN mill profile.'
  ),
  (
    'IND-APK-001',
    'KCP Sugar & Industries Ltd — Vuyyuru Unit',
    'KCP Ltd — private listed (BSE: 590054); KCP Group (Hyderabad); Lakshmipathy family',
    'India',
    'IND',
    'Andhra Pradesh — Krishna District (Vuyyuru — Krishna river delta, coastal AP)',
    'sugarcane',
    16.3640,
    80.8460,
    'operational',
    8000,
    100000,
    'M-30 / S-30 / Refined Sugar',
    'M-30, S-30, Refined Sugar, Molasses, Alcohol/Ethanol, Power',
    '45–600',
    'October',
    'April',
    'November, December, January',
    'Krishnapatnam Port (~120km); Kakinada Port (~150km); Visakhapatnam (~250km)',
    120,
    TRUE,
    80000,
    'NCDEX; Andhra Pradesh FRP/SAP',
    'EXW Vuyyuru; FOB Krishnapatnam/Kakinada',
    'Domestic bulk; export VHP via Krishnapatnam/Kakinada; ethanol to OMCs',
    'Domestic AP/Telangana food industry; export traders; OMCs',
    'Indonesia, UAE, Bangladesh (VHP via east coast ports)',
    'KCP Sugar is one of Andhra Pradesh''s oldest and largest sugar companies (founded 1941). The Krishna River delta (Vuyyuru, Gudivada, Machilipatnam area) is AP''s primary cane belt — perennial irrigation via Krishna river canal system, high yields. KCP Group also makes cement and heavy engineering. Vuyyuru mill is well-regarded for quality. AP sugar is notable for east coast port access (Krishnapatnam, Kakinada) — competitive for Bangladesh and SE Asia export vs. west coast ports. AP produces ~1.0–1.5 MT sugar/yr from ~20 mills.'
  ),
  (
    'IND-APK-002',
    'Andhra Sugars Ltd — Tanuku Unit',
    'Andhra Sugars Ltd — private listed (BSE: 590006); Andhra-based promoters',
    'India',
    'IND',
    'Andhra Pradesh — West Godavari District (Tanuku; also Bhimadole, Kovvur)',
    'sugarcane',
    16.7600,
    81.6800,
    'operational',
    6000,
    75000,
    'M-30 / Refined Sugar',
    'M-30, Refined Sugar, Molasses, Alcohol, Chemicals (acetic acid, acetaldehyde from distillery)',
    '45–600',
    'October',
    'March',
    'November, December',
    'Kakinada Port (~100km); Visakhapatnam (~220km)',
    100,
    TRUE,
    60000,
    'NCDEX; AP FRP',
    'EXW Tanuku; FOB Kakinada',
    'Domestic AP supply; chemical products (industrial)',
    'AP domestic; industrial chemical buyers; OMCs',
    'Limited sugar export; chemical products regional',
    'Andhra Sugars is unusual in India''s sugar sector — the distillery produces industrial chemicals (acetic acid, acetaldehyde) from molasses, not just ethanol. Located in West Godavari District — part of the Godavari delta, AP''s other major river-canal irrigated cane belt (alongside Krishna). West Godavari (Eluru, Tanuku, Bhimavaram) and Krishna District together form AP''s coastal cane belt. Multiple units: Tanuku, Bhimadole, Kovvur. Kakinada is AP''s principal sugar export port.'
  ),
  (
    'IND-PUN-001',
    'Punjab Cooperative & Private Mills — Nakodar Cluster (Representative Entry)',
    'Punjab State Cooperative Sugar Mills Federation (PUNSUP) and private mills',
    'India',
    'IND',
    'Punjab (Jalandhar, Kapurthala, Gurdaspur, Hoshiarpur, Fatehgarh Sahib districts)',
    'sugarcane',
    31.1280,
    75.4760,
    'operational',
    5000,
    55000,
    'M-30 Sugar',
    'M-30, Molasses, Ethanol, Bagasse',
    '150–600',
    'October',
    'January',
    'November, December',
    'Mundra Port / Kandla (~1,000km); JNPT (~1,500km)',
    1000,
    TRUE,
    40000,
    'NCDEX; Punjab SAP (typically India''s highest SAP — ~Rs 391/quintal FY2024-25)',
    'EXW mill gate',
    'Punjab domestic supply; state PDS',
    'Punjab state government; domestic traders',
    'None — domestic only',
    'Punjab has ~15–16 sugar mills (mix of state co-ops and private), concentrated in Jalandhar–Kapurthala–Gurdaspur belt (sub-Himalayan foothills, well-irrigated by canal system). Punjab SAP is consistently India''s highest among major cane states, making Punjab sugar the most expensive to produce in India (~Rs 391/quintal vs. FRP Rs 340). Mills are uncompetitive vs. UP/Maharashtra on cost but survive due to state political support. Punjab cane: short season (~60–70 days), lower recovery (~9–10%) vs. peninsular India. Key mills: Nakodar (Jalandhar), Phagwara (Kapurthala), Batala (Gurdaspur), Morinda (Rupnagar), Fazilka.'
  ),
  (
    'IND-HAR-001',
    'Haryana State Cooperative Sugar Mills — Yamunanagar/Rohtak Cluster (Representative Entry)',
    'Haryana State Cooperative Sugar Mills Federation (HSCSMF) — state cooperative; also private mills',
    'India',
    'IND',
    'Haryana (Yamunanagar, Karnal, Rohtak, Panipat, Sonipat, Hisar districts)',
    'sugarcane',
    30.1290,
    77.3080,
    'operational',
    5500,
    60000,
    'M-30 Sugar',
    'M-30, Molasses, Ethanol, Bagasse, Power',
    '150–600',
    'October',
    'January',
    'November, December',
    'Mundra / Kandla (~1,100km); JNPT (~1,400km)',
    1100,
    TRUE,
    50000,
    'NCDEX; Haryana SAP',
    'EXW mill gate',
    'Haryana state PDS; domestic traders',
    'Haryana/Delhi NCR domestic market; state agencies',
    'None',
    'Haryana has ~11 sugar mills. Yamunanagar is the state''s main sugar town (northernmost UP-border belt). Key mills: Yamunanagar Cooperative, Shahabad Cooperative (Kurukshetra), Rohtak Cooperative, Panipat Cooperative, and some private units. Haryana SAP: ~Rs 362/quintal FY2024-25. Similar issues to Punjab: high cane cost, short season, declining cane acreage as farmers switch to paddy/wheat/vegetables (more profitable with MSP support). Delhi NCR proximity creates strong demand for molasses-based industrial alcohol.'
  ),
  (
    'IND-GUJ-001',
    'South Gujarat Sugar Mills — Surat Belt (Representative Entry)',
    'Gujarat cooperative and private mills (e.g., Surat District Co-op Union, Narmada Co-op, Gandevi, etc.)',
    'India',
    'IND',
    'Gujarat — Surat / South Gujarat (Surat, Narmada, Bharuch, Navsari, Valsad districts)',
    'sugarcane',
    21.2500,
    72.8500,
    'operational',
    7000,
    90000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Refined Sugar, Molasses, Ethanol',
    '45–600',
    'October',
    'March',
    'November, December',
    'Hazira Port / Surat (~20km); Mundra (~250km); Kandla (~300km)',
    20,
    TRUE,
    80000,
    'NCDEX; Gujarat SAP',
    'EXW mill; FOB Hazira/Mundra',
    'Domestic Gujarat/Maharashtra supply; export via Hazira/Mundra when quota',
    'Gujarat domestic; Surat textile/food industry; traders',
    'Indonesia, UAE (via Mundra/Hazira when quota)',
    'Gujarat produces ~1.0–1.3 MT sugar/yr from ~20 mills. South Gujarat (Surat–Bharuch–Narmada–Navsari–Valsad) is the primary belt — fertile Tapi/Narmada river plains, sub-tropical climate. Key mills: Surat District Co-op Union, Narmada Co-op, Gandevi (Navsari). Surat is India''s diamond/textile capital — high local demand for sugar in food processing. Gujarat''s proximity to Mundra/Kandla (major export ports) gives it competitive export logistics. Average recovery ~10–11%. Gujarat mills also produce significant ethanol (supply to Reliance, Gujarat OMCs).'
  ),
  (
    'IND-GUJ-002',
    'Mid/North Gujarat Sugar Mills — Vadodara/Anand/Banaskantha Cluster (Representative Entry)',
    'Kothari Sugars & Chemicals and various co-ops/private mills',
    'India',
    'IND',
    'Gujarat — Vadodara / Anand / North Gujarat (Sabarkantha, Banaskantha, Mehsana)',
    'sugarcane',
    22.4500,
    73.2000,
    'operational',
    5000,
    60000,
    'M-30 / S-30 Sugar',
    'M-30, S-30, Molasses, Ethanol',
    '150–600',
    'October',
    'February',
    'November, December',
    'Mundra (~200km); Kandla (~220km)',
    200,
    TRUE,
    50000,
    'NCDEX; Gujarat SAP',
    'EXW mill',
    'Gujarat/Maharashtra domestic supply; export OML when viable',
    'Gujarat domestic; traders',
    'Limited',
    'Represents mid-Gujarat/north Gujarat cane belt. Vadodara–Anand area has both cane and dairy farming (Amul dairy co-op origin in Anand). North Gujarat (Sabarkantha, Mehsana, Banaskantha) grows cane under irrigation (Sardar Sarovar canal command area). Gujarat cane acreage has expanded post-Narmada canal completion. North Gujarat mills smaller than south Gujarat. Also included in this belt: Mahuva and Modasa area co-op mills.'
  )
ON CONFLICT (mill_name, country) DO UPDATE SET
  plant_id = EXCLUDED.plant_id,
  operator = EXCLUDED.operator,
  iso_code = EXCLUDED.iso_code,
  region = EXCLUDED.region,
  sugar_type = EXCLUDED.sugar_type,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  status = EXCLUDED.status,
  crushing_capacity_tcd = EXCLUDED.crushing_capacity_tcd,
  annual_output_tonnes = EXCLUDED.annual_output_tonnes,
  primary_grade = EXCLUDED.primary_grade,
  grades_available = EXCLUDED.grades_available,
  icumsa_range = EXCLUDED.icumsa_range,
  crushing_start = EXCLUDED.crushing_start,
  crushing_end = EXCLUDED.crushing_end,
  peak_months = EXCLUDED.peak_months,
  export_terminal = EXCLUDED.export_terminal,
  distance_to_port_km = EXCLUDED.distance_to_port_km,
  rail_access = EXCLUDED.rail_access,
  storage_capacity_tonnes = EXCLUDED.storage_capacity_tonnes,
  price_benchmark = EXCLUDED.price_benchmark,
  incoterms = EXCLUDED.incoterms,
  typical_contract = EXCLUDED.typical_contract,
  major_buyers = EXCLUDED.major_buyers,
  export_markets = EXCLUDED.export_markets,
  notes = EXCLUDED.notes,
  updated_at = NOW();

