-- ============================================================
-- Mexico Oil Production Sites — 18 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- OFFSHORE GULF OF MEXICO
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cantarell Complex', 'Pemex E&P', 'Bay of Campeche — offshore Campeche', NULL, 'Energy', 'Crude Oil', 19.6667, -92.3500, 'Mexico', 'Gulf of Mexico', 'Ciudad del Carmen', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 22.00, 3.50, 4800000, 1500000000, 4800000, '{"start_year":1979,"production_bpd":160000,"quality":"Heavy — Maya crude blend contributor","note":"Severely declining; was world''s second-largest 2003; discovered 1976; collapsed from peak ~2.1M bpd (2004); Pemex 100%","last_transaction":"Nitrogen injection ~$5B (2000–2006) — world''s largest nitrogen EOR; catastrophic 75% decline 2004–2024","contract_duration":"Pemex state concession (perpetual)","pipelines":"Cantarell platforms → Dos Bocas terminal (~200km subsea); Dos Bocas → Salina Cruz, Minatitlán refineries","ports":"Dos Bocas Marine Terminal; Cayo Arcas offshore loading","rail":"None offshore"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ku-Maloob-Zaap (KMZ) Complex', 'Pemex E&P', 'Bay of Campeche — offshore', NULL, 'Energy', 'Crude Oil', 19.5000, -92.5000, 'Mexico', 'Gulf of Mexico', 'Ciudad del Carmen', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 22.00, 3.30, 19500000, 3000000000, 19500000, '{"start_year":1981,"production_bpd":650000,"quality":"Heavy — Maya crude","note":"Mexico''s current largest producing field; ~40% of national production; Ku 1981, Maloob 1996, Zaap 2007; Pemex 100%","last_transaction":"KMZ expansion ~$10B (2010–2020); nitrogen injection EOR ongoing","contract_duration":"Pemex state concession","pipelines":"KMZ → Dos Bocas terminal; → Cayo Arcas offshore loading","ports":"Dos Bocas; Cayo Arcas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Abkatún-Pol-Chuc Complex', 'Pemex E&P', 'Bay of Campeche', NULL, 'Energy', 'Crude Oil', 19.7500, -92.2500, 'Mexico', 'Gulf of Mexico', 'Ciudad del Carmen', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 21.00, NULL, 4500000, 3000000000, 4500000, '{"start_year":1980,"production_bpd":150000,"quality":"Heavy sour Maya blend","note":"Mature; Pemex 100%","contract_duration":"Pemex state concession","pipelines":"Abkatún-Pol-Chuc → Dos Bocas","ports":"Dos Bocas; Cayo Arcas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Litoral de Tabasco (Ixtal-Manik)', 'Pemex E&P', 'Offshore Tabasco coast — shallow water', NULL, 'Energy', 'Crude Oil', 18.6667, -92.5000, 'Mexico', 'Gulf of Mexico', 'Villahermosa', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 20.00, NULL, 1500000, NULL, 1500000, '{"start_year":2005,"production_bpd":50000,"quality":"Heavy sour","note":"Pemex 100%","contract_duration":"Pemex state concession","pipelines":"Litoral → Dos Bocas terminal (short offshore)","ports":"Dos Bocas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ayatsil-Tekel-Utsil (ATU) Complex', 'Pemex E&P', 'Bay of Campeche', NULL, 'Energy', 'Crude Oil', 19.4167, -92.6667, 'Mexico', 'Gulf of Mexico', 'Ciudad del Carmen', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 23.00, NULL, 2400000, 2000000000, 2400000, '{"start_year":2015,"production_bpd":80000,"quality":"Heavy sour","note":"Newer development; Ayatsil 2015, Tekel 2017; Pemex 100%","last_transaction":"ATU development ~$3B (2010–2017); Pemex''s last major successful deepwater project before fiscal crisis","contract_duration":"Pemex state concession","pipelines":"ATU → KMZ infrastructure → Dos Bocas","ports":"Dos Bocas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tsimin-Xux Field', 'Pemex E&P', 'Bay of Campeche — deepwater fringe', NULL, 'Energy', 'Crude Oil', 19.8333, -92.8333, 'Mexico', 'Gulf of Mexico', 'Ciudad del Carmen', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 24.00, NULL, 600000, NULL, 600000, '{"start_year":2019,"production_bpd":20000,"quality":"Heavy","note":"Smaller deepwater; Pemex 100%","contract_duration":"Pemex state concession","pipelines":"Tsimin → KMZ → Dos Bocas","ports":"Dos Bocas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Trion (Perdido Fold Belt) Field', 'Pemex + BHP', 'Deep Gulf of Mexico — US/Mexico maritime boundary', NULL, 'Energy', 'Crude Oil', 25.3333, -96.3333, 'Mexico', 'Gulf of Mexico', 'Matamoros', 'oil_field', 'planned', 'BHP', 'joint_venture', 28.00, NULL, 0, 500000000, 0, '{"start_year":null,"production_bpd":100000,"quality":"Medium (estimated)","note":"Pre-development; discovered 2012; FID pending (delayed multiple times); Pemex 60%, BHP 40% (operator)","last_transaction":"BHP + Pemex partnership 2017; FID repeatedly delayed 2019–2024 due to Pemex financial crisis + AMLO focus on onshore; project in limbo","contract_duration":"Mexico Round 2 license (post-2013 energy reform)","pipelines":"Planned subsea → US Gulf Coast (cross-border)","ports":"Planned export via US Gulf Coast","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zama Field', 'Pemex (forced operator)', 'Bay of Campeche — deepwater, cross-border', NULL, 'Energy', 'Crude Oil', 25.8333, -96.5833, 'Mexico', 'Gulf of Mexico', 'Matamoros', 'oil_field', 'planned', 'Pemex', 'joint_venture', 30.00, NULL, 0, 670000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Medium light (estimated)","note":"Development stalled — unitization dispute; discovered 2017 by Talos Energy; Pemex forced 51% + operatorship 2021; Talos 17.35%, Harbour 17.35%","last_transaction":"Talos discovered Zama 2017 — first post-reform private Gulf discovery; Pemex asserted cross-border; forced unitization; development stalled 2021–2024; arbitration ongoing; symbol of AMLO re-nationalization","contract_duration":"Mexico Round 1 license (disputed)","pipelines":"Planned subsea","ports":"Planned Dos Bocas or US Gulf Coast","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CHICONTEPEC BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chicontepec Basin', 'Pemex E&P', 'Veracruz / Puebla — onshore tight oil', NULL, 'Energy', 'Crude Oil', 20.8333, -97.8333, 'Mexico', 'Chicontepec', 'Poza Rica', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 28.00, 1.50, 1200000, 3000000000, 1200000, '{"start_year":1926,"production_bpd":40000,"quality":"Medium light","note":"Massive underperforming tight oil; Pemex estimated 500k+ bpd potential; ~139B bbl OOIP (disputed); Pemex 100%","last_transaction":"Pemex fiscal black hole — ~$20B+ spent (2005–2020) with minimal increase; reservoir far tighter than projected; AMLO largely abandoned Chicontepec 2018–2024","contract_duration":"Pemex state","pipelines":"Chicontepec → Tula refinery; → Poza Rica gathering","ports":"Veracruz (indirect)","rail":"Mexico City–Veracruz rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Poza Rica Field', 'Pemex E&P', 'Veracruz — Golden Lane / Faja de Oro', NULL, 'Energy', 'Crude Oil', 20.5333, -97.4500, 'Mexico', 'Chicontepec', 'Poza Rica', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 32.00, 1.20, 450000, 50000000, 450000, '{"start_year":1930,"production_bpd":15000,"quality":"Medium light","note":"Very mature; Golden Lane discovery 1908 — Mexico''s first major oil boom; Pemex 100%","last_transaction":"Nationalized 1938 (Lázaro Cárdenas expropriation — created Pemex)","contract_duration":"Pemex state","pipelines":"Poza Rica → Tula refinery; → Tuxpan port pipeline","ports":"Tuxpan Oil Terminal (Veracruz)","rail":"Poza Rica–Mexico City rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Furbero-Paleocanal Field', 'Pemex E&P', 'Veracruz — Chicontepec area', NULL, 'Energy', 'Crude Oil', 20.6667, -97.6667, 'Mexico', 'Chicontepec', 'Poza Rica', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 27.00, NULL, 150000, NULL, 150000, '{"start_year":2000,"production_bpd":5000,"quality":"Medium","note":"Chicontepec play; Pemex 100%","contract_duration":"Pemex state","pipelines":"Furbero → Chicontepec gathering → Poza Rica","ports":"Tuxpan (indirect)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BURGOS BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Burgos Basin Onshore', 'Pemex E&P', 'Tamaulipas / Nuevo León — northern Mexico', NULL, 'Energy', 'Crude Oil', 25.5000, -99.0000, 'Mexico', 'Burgos', 'Reynosa', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 40.00, NULL, 900000, 500000000, 900000, '{"start_year":1940,"production_bpd":30000,"quality":"Light sweet condensate; API ~35° light oil","note":"Gas-condensate dominant + light oil; mature conventional; Pemex 100%","last_transaction":"2014 energy reform opened Burgos to private; AMLO reversed 2018 — forced Pemex re-consolidation; most private operators exited","contract_duration":"Pemex state; some private contracts suspended","pipelines":"Burgos → Reynosa gathering → Texas export (cross-border)","ports":"Corpus Christi, Texas (export)","rail":"Monterrey–Reynosa rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Arenque Field', 'Lewis Energy Group', 'Burgos Basin — Tamaulipas onshore', NULL, 'Energy', 'Crude Oil', 25.3333, -98.6667, 'Mexico', 'Burgos', 'Reynosa', 'oil_field', 'operational', 'Lewis Energy Group', 'private', 38.00, NULL, 150000, NULL, 150000, '{"start_year":2016,"production_bpd":5000,"quality":"Light sweet","note":"Lewis Energy (Texas independent) 100% under service contract; Mexico retains mineral rights; Round 1 award 2015","last_transaction":"Lewis won Burgos Block 2015; AMLO pressure 2018+ but Lewis maintained operations","contract_duration":"Service contract","pipelines":"Arenque → Reynosa gathering → Texas","ports":"Corpus Christi, Texas (export)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Misión Field', 'Pemex E&P', 'Burgos Basin', NULL, 'Energy', 'Crude Oil', 25.6667, -99.1667, 'Mexico', 'Burgos', 'Reynosa', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 37.00, NULL, 240000, NULL, 240000, '{"start_year":2001,"production_bpd":8000,"quality":"Light sweet","note":"Pemex 100%","contract_duration":"Pemex state","pipelines":"Misión → Burgos gathering → Reynosa","ports":"Texas Gulf Coast","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ONSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Veracruz-Tampico Onshore Belt', 'Pemex E&P', 'Veracruz/Tamaulipas — Isthmian Salt Basin', NULL, 'Energy', 'Crude Oil', 21.5000, -97.5000, 'Mexico', 'Onshore', 'Tampico', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 30.00, NULL, 1500000, NULL, 1500000, '{"start_year":1950,"production_bpd":50000,"quality":"Medium light","note":"Mature onshore cluster; multiple small fields; Pemex 100%","contract_duration":"Pemex state","pipelines":"Tampico–Veracruz gathering → Madero refinery; → Tula refinery","ports":"Tampico Oil Terminal; Tuxpan","rail":"Tampico–Mexico City rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Samaria-Luna Field', 'Pemex E&P', 'Tabasco onshore', NULL, 'Energy', 'Crude Oil', 17.9167, -92.7500, 'Mexico', 'Onshore', 'Villahermosa', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 19.00, NULL, 900000, NULL, 900000, '{"start_year":2007,"production_bpd":30000,"quality":"Heavy","note":"Pemex 100%","contract_duration":"Pemex state","pipelines":"Samaria → Dos Bocas terminal (short onshore)","ports":"Dos Bocas","rail":"Tabasco rail (limited)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ek-Balam Field', 'Pemex E&P', 'Campeche onshore', NULL, 'Energy', 'Crude Oil', 19.5000, -91.5000, 'Mexico', 'Onshore', 'Campeche', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 18.00, NULL, 450000, NULL, 450000, '{"start_year":2017,"production_bpd":15000,"quality":"Heavy sour","note":"Pemex 100%","contract_duration":"Pemex state","pipelines":"Ek-Balam → Dos Bocas terminal","ports":"Dos Bocas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Quesqui Field', 'Pemex E&P', 'Tabasco onshore', NULL, 'Energy', 'Crude Oil', 18.1667, -92.9167, 'Mexico', 'Onshore', 'Villahermosa', 'oil_field', 'operational', 'Pemex E&P', 'state_owned', 20.00, NULL, 300000, NULL, 300000, '{"start_year":2010,"production_bpd":10000,"quality":"Heavy","note":"Pemex 100%","contract_duration":"Pemex state","pipelines":"Quesqui → Dos Bocas","ports":"Dos Bocas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Mexico' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Mexico' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
