-- ============================================================
-- Hungary Oil Production Sites — 14 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- GREAT HUNGARIAN PLAIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Algyő Field', 'MOL Hungarian Oil and Gas', 'Csongrád-Csanád County — Great Plain', NULL, 'Energy', 'Crude Oil', 46.3833, 20.1667, 'Hungary', 'Great Hungarian Plain', 'Szeged', 'oil_field', 'operational', 'MOL', 'public', 38.00, 0.40, 240000, 80000000, 240000, '{"start_year":1965,"production_bpd":8000,"quality":"Light sweet — Hungarian crude benchmark","note":"Hungary''s largest oil field; discovered 1964; peak ~40,000 bpd (1985); MOL 100%","last_transaction":"MOL privatized 1995–2000; Surgutneftegaz acquired 21.2% 2009 (hostile); Hungary forced Russia to sell back 2011 under EU pressure","contract_duration":"Hungarian federal mining concession (Bányatörvény)","pipelines":"Algyő → MOL Algyő processing plant → Százhalombatta refinery (~160km); Algyő → Druzhba pipeline","ports":"None (landlocked); crude exported via Druzhba pipeline","rail":"Szeged–Budapest rail line (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hajdúszoboszló Field', 'MOL', 'Hajdú-Bihar County — northeastern Great Plain', NULL, 'Energy', 'Crude Oil', 47.4500, 21.3833, 'Hungary', 'Great Hungarian Plain', 'Debrecen', 'oil_field', 'operational', 'MOL', 'public', 36.00, NULL, 45000, 15000000, 45000, '{"start_year":1925,"production_bpd":1500,"quality":"Light sweet","note":"Historic — one of Hungary''s oldest; discovered drilling for water; primarily gas + oil; MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Hajdúszoboszló → Debrecen → MOL pipeline network → Százhalombatta","ports":"None","rail":"Debrecen–Budapest rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pusztaföldvár Field', 'MOL', 'Békés County — southeastern Great Plain', NULL, 'Energy', 'Crude Oil', 46.7667, 20.8333, 'Hungary', 'Great Hungarian Plain', 'Békéscsaba', 'oil_field', 'operational', 'MOL', 'public', 37.00, NULL, 60000, 50000000, 60000, '{"start_year":1958,"production_bpd":2000,"quality":"Light sweet","note":"Mature; MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Békés County → Algyő → Százhalombatta","ports":"None","rail":"Békéscsaba rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Battonya Field', 'MOL', 'Békés County — near Romanian border', NULL, 'Energy', 'Crude Oil', 46.2667, 21.0000, 'Hungary', 'Great Hungarian Plain', 'Békéscsaba', 'oil_field', 'operational', 'MOL', 'public', 37.00, NULL, 45000, NULL, 45000, '{"start_year":1960,"production_bpd":1500,"quality":"Light sweet","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Battonya → Algyő gathering","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Üllés Field', 'MOL', 'Csongrád County — Great Plain', NULL, 'Energy', 'Crude Oil', 46.3833, 19.9333, 'Hungary', 'Great Hungarian Plain', 'Szeged', 'oil_field', 'operational', 'MOL', 'public', 36.00, NULL, 36000, NULL, 36000, '{"start_year":1962,"production_bpd":1200,"quality":"Light","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Üllés → Algyő gathering → Százhalombatta","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Szeghalom Field', 'MOL', 'Békés County', NULL, 'Energy', 'Crude Oil', 47.0333, 21.1667, 'Hungary', 'Great Hungarian Plain', 'Békéscsaba', 'oil_field', 'operational', 'MOL', 'public', 37.00, NULL, 30000, NULL, 30000, '{"start_year":1965,"production_bpd":1000,"quality":"Light sweet","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Szeghalom → Pusztaföldvár → Algyő","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Endrőd Field', 'MOL', 'Békés County', NULL, 'Energy', 'Crude Oil', 46.9000, 20.7833, 'Hungary', 'Great Hungarian Plain', 'Békéscsaba', 'oil_field', 'operational', 'MOL', 'public', 36.00, NULL, 24000, NULL, 24000, '{"start_year":1967,"production_bpd":800,"quality":"Light sweet","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Békés County gathering → Algyő","ports":"None","rail":"Gyoma rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Szank Field', 'MOL', 'Bács-Kiskun County — central Great Plain', NULL, 'Energy', 'Crude Oil', 46.6833, 19.7000, 'Hungary', 'Great Hungarian Plain', 'Kecskemét', 'oil_field', 'operational', 'MOL', 'public', 38.00, NULL, 75000, 60000000, 75000, '{"start_year":1969,"production_bpd":2500,"quality":"Light sweet","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Szank → Algyő → Százhalombatta","ports":"None","rail":"Kecskemét rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kiskunhalas Field', 'MOL', 'Bács-Kiskun County', NULL, 'Energy', 'Crude Oil', 46.4333, 19.4833, 'Hungary', 'Great Hungarian Plain', 'Kecskemét', 'oil_field', 'operational', 'MOL', 'public', 37.00, NULL, 45000, NULL, 45000, '{"start_year":1971,"production_bpd":1500,"quality":"Light sweet","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Kiskunhalas → Szank → Algyő","ports":"None","rail":"Kiskunhalas–Budapest rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ZALA REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lovászi Field', 'MOL', 'Zala County — western Hungary, near Croatia/Slovenia border', NULL, 'Energy', 'Crude Oil', 46.5833, 16.5667, 'Hungary', 'Zala Region', 'Nagykanizsa', 'oil_field', 'operational', 'MOL', 'public', 34.00, 0.60, 36000, 5000000, 36000, '{"start_year":1937,"production_bpd":1200,"quality":"Medium light","note":"Hungary''s oldest producing field — Hungarian oil cradle; Magyar Kőolajipari Rt.; WWII strategic; very mature; MOL 100%","contract_duration":"Hungarian mining concession (perpetual state production)","pipelines":"Lovászi → Letenye crude gathering → Százhalombatta pipeline (~250km)","ports":"None (landlocked)","rail":"Nagykanizsa–Budapest rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Budafa Field', 'MOL', 'Zala County', NULL, 'Energy', 'Crude Oil', 46.4667, 16.7167, 'Hungary', 'Zala Region', 'Nagykanizsa', 'oil_field', 'operational', 'MOL', 'public', 33.00, NULL, 24000, NULL, 24000, '{"start_year":1940,"production_bpd":800,"quality":"Medium light","note":"Mature; historic field; MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Budafa → Lovászi → Letenye gathering","ports":"None","rail":"Nagykanizsa rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hahót Field', 'MOL', 'Zala County', NULL, 'Energy', 'Crude Oil', 46.5333, 17.0000, 'Hungary', 'Zala Region', 'Zalaegerszeg', 'oil_field', 'operational', 'MOL', 'public', 34.00, NULL, 18000, NULL, 18000, '{"start_year":1942,"production_bpd":600,"quality":"Medium light","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Zala gathering → Letenye → Százhalombatta","ports":"None","rail":"Zalaegerszeg rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kiscsehi Field', 'MOL', 'Zala County', NULL, 'Energy', 'Crude Oil', 46.6000, 16.9167, 'Hungary', 'Zala Region', 'Zalaegerszeg', 'oil_field', 'operational', 'MOL', 'public', 33.00, NULL, 12000, NULL, 12000, '{"start_year":1948,"production_bpd":400,"quality":"Medium light","note":"Small; MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Zala gathering → MOL network","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Oltárc Field', 'MOL', 'Zala County — near Croatian border', NULL, 'Energy', 'Crude Oil', 46.4833, 16.5000, 'Hungary', 'Zala Region', 'Nagykanizsa', 'oil_field', 'operational', 'MOL', 'public', 35.00, NULL, 15000, NULL, 15000, '{"start_year":1952,"production_bpd":500,"quality":"Light","note":"MOL 100%","contract_duration":"Hungarian mining concession","pipelines":"Lovászi cluster → Letenye","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Hungary' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Hungary' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
