-- ============================================================
-- Timor-Leste Oil Production Sites — 7 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- OFFSHORE TIMOR SEA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bayu-Undan Field', 'Santos + INPEX + Eni + TIMOR GAP', 'Timor Sea — JPDA Zone, offshore', NULL, 'Energy', 'Crude Oil', -11.1667, 127.3500, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'inactive', 'Santos', 'joint_venture', 42.00, 0.04, 0, 400000000, 0, '{"start_year":2004,"production_bpd":0,"quality":"Light sweet","note":"Santos 56.7%, INPEX 11.4%, Eni 11%, Tokyo Gas 6.1%, TEPCO 6.1%, Toho Gas 1.9%, TIMOR GAP 6.8%; peak ~110,000 bpd oil+condensate (2005–2008); closed/decommissioning 2023","last_transaction":"Santos acquired ConocoPhillips Australia/JPDA assets 2023 for ~$1.65B — inherited decommissioning liability","contract_duration":"JPDA PSC expired with field life","pipelines":"Bayu-Undan → Darwin LNG Pipeline (502km subsea); condensate → tanker export","ports":"Darwin Port (Australia); Dili received royalties only","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kitan Field', 'ENI + INPEX + TIMOR GAP', 'Timor Sea — Block JPDA 06-105', NULL, 'Energy', 'Crude Oil', -11.6667, 128.5000, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'inactive', 'ENI', 'joint_venture', 39.00, 0.05, 0, 45000000, 0, '{"start_year":2011,"production_bpd":0,"quality":"Light sweet","note":"ENI 40%, INPEX 35%, TIMOR GAP 25%; peak ~40,000 bpd (2012); closed 2016; total ~25M bbl produced","last_transaction":"ENI decommissioned 2016; FPSO Montara Spirit released; ~$800M total development","contract_duration":"JPDA PSC expired with depletion","pipelines":"Kitan FPSO (Montara Spirit) → direct tanker offloading (no pipeline)","ports":"Darwin (Australia); Singapore (condensate trading)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Elang-Kakatua-Kakatua North (EKKN) Field', 'Santos + TIMOR GAP', 'Timor Sea — Block AC/P8', NULL, 'Energy', 'Crude Oil', -12.0000, 127.5000, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'inactive', 'Santos', 'joint_venture', 40.00, 0.04, 0, 60000000, 0, '{"start_year":1998,"production_bpd":0,"quality":"Light sweet","note":"Santos 60%, TIMOR GAP 40%; peak ~25,000 bpd; closed 2007; total ~50M bbl produced","last_transaction":"Santos decommissioned 2007; field depleted faster than expected","pipelines":"EKKN FPSO → tanker offloading","ports":"Darwin (Australia)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Laminaria-Corallina Field', 'Santos', 'Timor Sea — Block AC/P8, Australian waters', NULL, 'Energy', 'Crude Oil', -11.5000, 127.6667, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'inactive', 'Santos', 'joint_venture', 38.00, 0.05, 0, 200000000, 0, '{"start_year":1999,"production_bpd":0,"quality":"Light sweet","note":"Peak ~80,000 bpd (2000); total ~100M bbl; closed 2012; Woodside historical operator","last_transaction":"Woodside operated until exit; Santos decommissioned 2012","pipelines":"Laminaria FPSO (Gail Explorer) → tanker offloading","ports":"Darwin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chuditch Field', 'TIMOR GAP + Santos', 'Timor Sea — Block JPDA 03-19', NULL, 'Energy', 'Crude Oil', -10.8333, 126.1667, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'planned', 'TIMOR GAP + Santos', 'joint_venture', 37.00, NULL, 0, 150000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Light sweet (estimated)","note":"TIMOR GAP 75%, Santos 25%; discovery 2000; pre-development/appraisal; development stalled","last_transaction":"TIMOR GAP took controlling stake ~2018 as part of Timor-Leste resource nationalism push","contract_duration":"JPDA framework","pipelines":"Planned → Tasi Mane onshore pipeline (Timor-Leste south coast)","ports":"Planned Beaço Terminal (south coast Timor-Leste)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- GREATER SUNRISE FIELD
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sunrise Field', 'Woodside + ConocoPhillips + Shell + TIMOR GAP', 'Greater Sunrise — Timor Sea, JPDA/CMATS zone', NULL, 'Energy', 'Crude Oil', -10.7500, 126.9167, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'planned', 'Woodside Energy', 'joint_venture', 52.00, NULL, 0, 225000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Condensate very light sweet (associated with gas)","note":"Woodside 33.44%, ConocoPhillips 30%, Shell 26.56%, TIMOR GAP 10%; discovered 1974; ~5.1 Tcf gas + ~225M bbl condensate; one of Southeast Asia''s largest undeveloped fields; major geopolitical dispute","last_transaction":"Timor-Leste terminated CMATS 2017; new maritime boundary 2018; Woodside vs Timor-Leste deadlocked over pipeline route (Tasi Mane vs Darwin vs FLNG); development stalled since 2018","contract_duration":"New PSC framework under negotiation post-2018 boundary","pipelines":"Disputed — Timor-Leste wants 270km to Tasi Mane; Woodside prefers FLNG or 890km to Darwin; $30B+ cost difference","ports":"Planned Beaço Terminal (Timor-Leste) vs Darwin (Australia) — central dispute","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Troubadour Field', 'Woodside + ConocoPhillips + Shell + TIMOR GAP', 'Greater Sunrise — adjacent structure', NULL, 'Energy', 'Crude Oil', -10.6667, 127.0833, 'Timor-Leste', 'Timor Sea', 'Dili', 'oil_field', 'planned', 'Woodside Energy', 'joint_venture', 50.00, NULL, 0, 50000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Condensate sweet","note":"Same ownership as Sunrise; Woodside 33.44%, ConocoPhillips 30%, Shell 26.56%, TIMOR GAP 10%; discovered 1990s; ~1.2 Tcf gas + ~50M bbl condensate; tied to Sunrise development decision","last_transaction":"Troubadour development contingent on Sunrise FID (still pending)","contract_duration":"Same dispute as Sunrise","pipelines":"Same dispute as Sunrise — Tasi Mane vs Darwin vs FLNG","ports":"Planned with Sunrise","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Timor-Leste' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Timor-Leste' AND commodity_name = 'Crude Oil' ORDER BY operational_status, title;
