-- ============================================================
-- Botswana Coal Mines — 3 Sites (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================
-- If ON CONFLICT fails, run this first to add the unique constraint:
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_commodity_locations_title_country_commodity
--   ON public.commodity_locations (title, country, commodity_name);
-- ============================================================

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  commodity_type,
  commodity_name,
  latitude,
  longitude,
  country,
  region,
  city,
  location_type,
  operational_status,
  operator,
  company,
  ownership_type,
  grade,
  production_capacity,
  current_production,
  additional_info
) VALUES
(
  'Mmamabula Coalfield',
  'Jindal Steel and Power',
  'Mmamabula, Central Botswana',
  'Energy',
  'Coal',
  -23.5946,
  26.5756,
  'Botswana',
  'Central District',
  'Mmamabula',
  'mine',
  'operational',
  'Jindal Steel and Power',
  'Jindal Steel and Power',
  'private',
  'Sub-bituminous',
  NULL,
  NULL,
  '{
    "coal_type": "Sub-bituminous",
    "mining_method": "Surface and Underground",
    "original_owner": "CIC Energy",
    "ownership_changes": [{"year": 2012, "previous_owner": "CIC Energy", "new_owner": "Jindal Steel and Power"}],
    "major_milestones": [
      {"year": 2009, "event": "Contract signed with Shanghai Electric for Mmamabula Energy Project"},
      {"year": 2012, "event": "Jindal Steel and Power acquired CIC Energy for $116 million"}
    ],
    "estimated_mine_life_remaining_years": 30,
    "nearest_port": "Maputo Port, Mozambique (~900 km)",
    "nearest_railway": "Botswana Railway - Mahalapye Station",
    "loading_port": "Maputo Port, Mozambique",
    "transport_modes": ["Rail", "Truck"],
    "price_basis": "FOB",
    "contract_types": "Long-term",
    "export_license": true
  }'::jsonb
)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET
  owner = EXCLUDED.owner,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  region = EXCLUDED.region,
  city = EXCLUDED.city,
  location_type = EXCLUDED.location_type,
  operational_status = EXCLUDED.operational_status,
  operator = EXCLUDED.operator,
  company = EXCLUDED.company,
  ownership_type = EXCLUDED.ownership_type,
  grade = EXCLUDED.grade,
  production_capacity = EXCLUDED.production_capacity,
  current_production = EXCLUDED.current_production,
  additional_info = EXCLUDED.additional_info,
  updated_at = NOW();

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  commodity_type,
  commodity_name,
  latitude,
  longitude,
  country,
  region,
  city,
  location_type,
  operational_status,
  operator,
  company,
  ownership_type,
  grade,
  production_capacity,
  current_production,
  additional_info
) VALUES
(
  'Morupule Coalfield',
  'Debswana',
  'Palapye, Central Botswana',
  'Energy',
  'Coal',
  -22.5071,
  27.0264,
  'Botswana',
  'Central District',
  'Palapye',
  'mine',
  'operational',
  'Debswana',
  'Debswana',
  'joint_venture',
  'Sub-bituminous (No. 1 Seam)',
  877000,
  877000,
  '{
    "coal_type": "Sub-bituminous",
    "grade": "No. 1 Seam",
    "calorific_value_kcal_kg": 5614,
    "mining_method": "Underground (bord and pillar)",
    "annual_capacity_tonnes": 877000,
    "founded_year": 1971,
    "years_in_operation": 54,
    "original_owner": "Bamangwato Concessions Ltd",
    "ownership_changes": [{"year": 1971, "previous_owner": "Bamangwato Concessions Ltd", "new_owner": "Debswana"}],
    "major_milestones": [
      {"year": 1971, "event": "Founded to supply the Bamangwato copper and nickel mine"},
      {"year": 1980, "event": "Mining lease extension granted"},
      {"year": 2008, "event": "Wash plant commissioned at 120 tonnes/hour capacity"}
    ],
    "nearest_port": "Maputo Port, Mozambique (~700 km)",
    "nearest_railway": "Botswana Railway - Palapye Station",
    "loading_port": "Maputo Port, Mozambique",
    "transport_modes": ["Rail", "Truck"],
    "price_basis": "FOB",
    "contract_types": "Long-term",
    "export_license": true,
    "note": "Debswana = Botswana Government & De Beers JV"
  }'::jsonb
)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET
  owner = EXCLUDED.owner,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  region = EXCLUDED.region,
  city = EXCLUDED.city,
  location_type = EXCLUDED.location_type,
  operational_status = EXCLUDED.operational_status,
  operator = EXCLUDED.operator,
  company = EXCLUDED.company,
  ownership_type = EXCLUDED.ownership_type,
  grade = EXCLUDED.grade,
  production_capacity = EXCLUDED.production_capacity,
  current_production = EXCLUDED.current_production,
  additional_info = EXCLUDED.additional_info,
  updated_at = NOW();

INSERT INTO public.commodity_locations (
  title,
  owner,
  address,
  commodity_type,
  commodity_name,
  latitude,
  longitude,
  country,
  region,
  city,
  location_type,
  operational_status,
  operator,
  company,
  ownership_type,
  grade,
  production_capacity,
  current_production,
  additional_info
) VALUES
(
  'Sese Coalfield',
  'African Energy Resources / First Quantum Minerals',
  'Sese, North-East Botswana',
  'Energy',
  'Coal',
  -21.5855,
  27.2109,
  'Botswana',
  'Central District (near Francistown)',
  'Sese',
  'mine',
  'operational',
  'African Energy Resources / First Quantum Minerals',
  'African Energy Resources',
  'joint_venture',
  'Sub-bituminous / Coking coal',
  NULL,
  NULL,
  '{
    "coal_type": "Sub-bituminous / Coking coal",
    "mining_method": "Surface",
    "license_number": "Large-Scale Mining Licence (25-year)",
    "original_owner": "African Energy Resources",
    "estimated_mine_life_remaining_years": 30,
    "major_milestones": [
      {"year": 2017, "event": "Government granted tax holiday to First Quantum Minerals and African Energy Resources"},
      {"year": 2018, "event": "ESIA updated to include up to 500 MW power generation"},
      {"year": 2020, "event": "Generation licence awarded for 225 MW by Botswana Energy Regulatory Authority"},
      {"year": 2021, "event": "Large-scale mining licence secured for 51 km² containing 650Mt of coal resources"}
    ],
    "nearest_port": "Maputo Port, Mozambique (~600 km)",
    "nearest_railway": "Botswana Railway - Francistown Station",
    "loading_port": "Maputo Port, Mozambique",
    "transport_modes": ["Rail", "Truck"],
    "price_basis": "FOB",
    "contract_types": "Long-term",
    "export_license": true,
    "certifications": ["ESIA approved", "Water extraction rights (Shashe Dam)", "50-year Land Lease"]
  }'::jsonb
)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET
  owner = EXCLUDED.owner,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  region = EXCLUDED.region,
  city = EXCLUDED.city,
  location_type = EXCLUDED.location_type,
  operational_status = EXCLUDED.operational_status,
  operator = EXCLUDED.operator,
  company = EXCLUDED.company,
  ownership_type = EXCLUDED.ownership_type,
  grade = EXCLUDED.grade,
  production_capacity = EXCLUDED.production_capacity,
  current_production = EXCLUDED.current_production,
  additional_info = EXCLUDED.additional_info,
  updated_at = NOW();
