-- ============================================================
-- Uranium Production Sites — Africa (UPSERT)
-- Run this in Supabase SQL Editor
-- Niger: 5 | Namibia: 3 | South Africa: 5 | Tanzania: 3 | Zambia: 1 | Zimbabwe: 2 | CAR: 1 | DRC: 1
-- Madagascar: 2 | Malawi: 1 | Morocco: 2 | Egypt: 4 | Somalia: 1 | Gabon: 1 = 32 sites total
-- ============================================================

-- =====================
-- NIGER
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('SOMAÏR (Arlit Mine)', 'State of Niger (nationalized)', 'Agadez Region', NULL, 'Energy', 'Uranium', 18.7603, 7.3303, 'Niger', 'Agadez Region', 'Arlit', 'mine', 'inactive', 'SOMAÏR', 'state_owned', 0.28, 0, 42200, 0, '{"mining_method":"open-pit","start_date":"1971","closing_date":"2024-10","production_unit":"tU/year","note":"Nationalized by Niger June 2025; formerly Orano 63.4%, Sopamin 36.6%","processing_mill":["SOMAÏR on-site mill (Arlit)","Heap leach pad SOMAIR Lixi"],"transport_routes":["Uranium Highway truck 1600 km to Parakou (Benin)","Rail 400 km Parakou to Cotonou port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('COMINAK (Akouta Underground Mine)', 'Orano + Sopamin + Enusa', 'Agadez Region', NULL, 'Energy', 'Uranium', 18.6751, 7.3099, 'Niger', 'Agadez Region', 'Akokan', 'mine', 'inactive', 'COMINAK', 'joint_venture', 0.40, 0, 0, 0, '{"mining_method":"underground","start_date":"1978","closing_date":"2021-03-31","production_unit":"tU/year","note":"Orano 59%, Sopamin 31%, Enusa 10%; reserves exhausted; rehabilitation ongoing","processing_mill":["COMINAK on-site mill (Akokan)"],"transport_routes":["Uranium Highway truck to Parakou (Benin)","Rail to Cotonou port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('SOMINA (Azelik / Teguidda Mine)', 'CNNC Intl / Sopamin / ZXJoy / KOMIR', 'Agadez Region', NULL, 'Energy', 'Uranium', 17.7700, 6.9000, 'Niger', 'Agadez Region', 'Azelik', 'mine', 'inactive', 'SOMINA', 'joint_venture', 0.20, 0, 15600, 0, '{"mining_method":"open-pit","start_date":"2010","production_unit":"tU/year","note":"CNNC 37.2%, Sopamin 33%, ZXJoy 24.8%, KOMIR 5%; care-and-maintenance; CNNC announced restart May 2024","processing_mill":["SOMINA on-site mill (Azelik)"],"transport_routes":["Road to Agadez then Niamey"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Imouraren Deposit', 'Imouraren SA', 'Agadez Region', NULL, 'Energy', 'Uranium', 18.0820, 7.3630, 'Niger', 'Agadez Region', NULL, 'mine', 'planned', 'Imouraren SA', 'joint_venture', 0.06, 0, 174000, 0, '{"mining_method":"open-pit (planned); ISR under study","production_unit":"tU/year","note":"Formerly Orano 63.52%, Sopamin 33.35%, KHNP 3.13%; permit revoked June 2024; Orano in ICSID arbitration","processing_mill":["No mill built — planned on-site ISR facility"],"transport_routes":["Uranium Highway to Cotonou (planned)"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dasa Project (Global Atomic)', 'Global Atomic + SOPAMIN', 'Agadez Region — Tim Mersoi Basin', NULL, 'Energy', 'Uranium', 17.6500, 7.5500, 'Niger', 'Agadez Region', NULL, 'mine', 'planned', 'SOMIDA', 'joint_venture', 0.29, 0, 43582, 0, '{"mining_method":"underground","production_unit":"tU/year","note":"Global Atomic 90%, Niger/SOPAMIN 10%; excavation began 2022; first deliveries expected 2025","processing_mill":["Planned on-site mill at Dasa"],"transport_routes":["Road to Arlit or Agadez, then Uranium Highway south"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NAMIBIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rössing Uranium Mine', 'CNUC / IFIC / IDC / Gov Namibia', 'Erongo Region', NULL, 'Energy', 'Uranium', -22.4780, 15.0600, 'Namibia', 'Erongo Region', 'Arandis', 'mine', 'operational', 'Rössing Uranium', 'joint_venture', 0.03, 2350, 27000, 2350, '{"mining_method":"open-pit","start_date":"1976","production_unit":"tonnes U3O8/year","note":"CNUC 68.6%, Iranian 15%, IDC 10%, Gov Namibia 3%; Rio Tinto sold to CNUC 2019; life extended to 2036","processing_mill":["Rössing on-site sulphuric acid leach plant (Arandis)"],"transport_routes":["B2 highway 45 km to Walvis Bay port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Husab Mine (Swakop Uranium)', 'Taurus Minerals + Epangelo Mining', 'Erongo Region', NULL, 'Energy', 'Uranium', -22.5200, 15.0800, 'Namibia', 'Erongo Region', NULL, 'mine', 'operational', 'Swakop Uranium', 'joint_venture', 0.04, 4200, 137500, 4200, '{"mining_method":"open-pit","start_date":"2016","production_unit":"tonnes U3O8/year","note":"Taurus (CGN 60% + China-Africa Development Fund 40%) 90%, Epangelo 10%; ~USD 5.2B investment","processing_mill":["Husab on-site agitated acid leach plant (15 Mtpa)","Heap leach pilot July 2024"],"transport_routes":["B2 highway 45 km to Walvis Bay port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Langer Heinrich Mine', 'Paladin Energy + CNNC Overseas', 'Erongo Region', NULL, 'Energy', 'Uranium', -23.0500, 15.3000, 'Namibia', 'Erongo Region', NULL, 'mine', 'operational', 'Langer Heinrich Uranium', 'joint_venture', 0.043, 1400, 57000, 1400, '{"mining_method":"open-pit","start_date":"2007","production_unit":"tonnes U3O8/year","note":"Paladin 75%, CNNC 25%; care-and-maintenance 2018; restart 2024; guidance 3.0-3.6 Mlbs U3O8 FY2025","processing_mill":["Langer Heinrich on-site alkaline leach plant"],"transport_routes":["Road 85 km to Walvis Bay port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- SOUTH AFRICA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Moab Khotsong (Vaal River Ops)', 'Harmony Gold', 'North West Province / Free State — Klerksdorp Goldfield', NULL, 'Energy', 'Uranium', -26.9700, 26.7300, 'South Africa', 'North West Province', 'Klerksdorp', 'mine', 'operational', 'Harmony Gold', 'private', 0.0125, 280, NULL, 280, '{"mining_method":"underground (by-product of gold)","start_date":"1968","production_unit":"tU/year (by-product)","note":"100% Harmony Gold; acquired from AngloGold Ashanti 2018; uranium via South Uranium Plant at Great Noligwa","processing_mill":["Great Noligwa Gold Plant (South Uranium Plant circuit)"],"transport_routes":["Road to Pelindaba; export via Durban port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sibanye Witwatersrand Tailings', 'Sibanye-Stillwater', 'Gauteng / North West Province', NULL, 'Energy', 'Uranium', -26.3700, 27.4500, 'South Africa', 'Gauteng', 'Johannesburg', 'mine', 'operational', 'Sibanye-Stillwater', 'private', 0.005, 100, NULL, 100, '{"mining_method":"tailings retreatment (by-product)","note":"100% Sibanye-Stillwater; Cooke, Driefontein, West Rand tailings; uranium from historic gold tailings","processing_mill":["Various gold plants with uranium circuit"],"transport_routes":["Road to Pelindaba; export via Durban or Richards Bay"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Henkries Uranium Project', 'Neo Energy Metals', 'Northern Cape — Namaqualand district, 80 km N of Springbok', NULL, 'Energy', 'Uranium', -29.0000, 17.9700, 'South Africa', 'Northern Cape', 'Springbok', 'mine', 'planned', 'Neo Energy Metals', 'private', 0.0399, 0, 2130, 0, '{"mining_method":"open-pit (planned ISR / shallow paleochannel)","production_unit":"tU/year","note":"100% Neo Energy Metals via NURSA; 4.7 Mlbs U3O8 at 399 ppm; Henkries South acquisition 2024","processing_mill":["Not yet built"],"transport_routes":["N7 road to Cape Town port (planned)"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Karoo Uranium Province', 'Peninsula Energy + Lukisa JV', 'Western Cape / Northern Cape / Eastern Cape — Karoo', NULL, 'Energy', 'Uranium', -32.3600, 22.5700, 'South Africa', 'Western Cape', 'Beaufort West', 'mine', 'planned', 'Tasman RSA Mines', 'joint_venture', 0.10, 0, 25000, 0, '{"mining_method":"open-pit (sandstone; planned)","production_unit":"tU/year","note":"Peninsula Energy + Pala Investments; Lukisa JV; EIA under review; ~25,000 tU at 0.1%","processing_mill":["Planned Central Processing Plant near Beaufort West"],"transport_routes":["N1 highway to Cape Town port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Beisa Uranium-Gold Mine', 'Neo Energy Metals', 'Free State — Welkom Goldfield, Witwatersrand Basin', NULL, 'Energy', 'Uranium', -27.9800, 26.7200, 'South Africa', 'Free State', 'Welkom', 'mine', 'planned', 'Neo Energy Metals', 'private', 0.078, 0, 53000, 0, '{"mining_method":"underground (narrow reef)","production_unit":"tU/year","note":"100% Neo Energy Metals via NURB; ~117 Mlbs U3O8 and ~5.4 Mozs gold; acquired from Sibanye + Sunshine 2024","processing_mill":["Beatrix 4 Shaft processing plant (existing)"],"transport_routes":["Road to Pelindaba; export Durban port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- TANZANIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mkuju River Project (Nyota Deposit)', 'Uranium One (Rosatom)', 'Ruvuma Region — Namtumbo District', NULL, 'Energy', 'Uranium', -10.3700, 36.5500, 'Tanzania', 'Ruvuma Region', NULL, 'mine', 'planned', 'Mantra Tanzania', 'state_owned', 0.025, 0, 58500, 0, '{"mining_method":"open-pit (planned); ISL pilot July 2025","production_unit":"tU/year","note":"100% Uranium One (Rosatom); Special Mining Licence 2013; partly inside Mwalimu Nyerere National Park","processing_mill":["On-site mill planned; ISL pilot plant 2025"],"transport_routes":["Road ~470 km to Dar es Salaam"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bahi Deposit', 'AuKing Mining', 'Dodoma Region — 80 km west of Dodoma', NULL, 'Energy', 'Uranium', -6.0000, 35.3000, 'Tanzania', 'Dodoma Region', 'Dodoma', 'mine', 'planned', 'AuKing Mining', 'private', NULL, 0, 9477, 0, '{"mining_method":"open-pit / ISR (surficial playa lake; planned)","production_unit":"tU/year","note":"Mining approval 2009; AuKing holds tenements; Manyoni adjacent 9,477 tU inferred","processing_mill":["None built"],"transport_routes":["Road to Dodoma then Dar es Salaam port (planned)"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Likuyu North Deposit', 'Gladiator Resources', 'Ruvuma Region — Tunduru Basin, near Mkuju River', NULL, 'Energy', 'Uranium', -10.5000, 36.4000, 'Tanzania', 'Ruvuma Region', NULL, 'mine', 'planned', 'Gladiator Resources', 'private', NULL, 0, 2350, 0, '{"mining_method":"ISR (in-situ recovery; positive analysis 2024)","production_unit":"tU/year","note":"Gladiator Resources 6 licences ~1,814 km²; similar geology to Nyota; acquired Zeus Resources 2022","processing_mill":["None built — ISR on-site planned"],"transport_routes":["Road to Dar es Salaam port (planned)"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ZAMBIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Muntanga Project', 'Atomic Eagle', 'Southern Province — Siavonga and Chirundu Districts', NULL, 'Energy', 'Uranium', -16.1200, 28.7100, 'Zambia', 'Southern Province', 'Siavonga', 'mine', 'planned', 'Atomic Eagle', 'private', 0.028, 0, 20363, 0, '{"mining_method":"open-pit (planned; 2 pits: Muntanga 750x550m, Dibwe 1500x300m, acid heap leach)","start_date":"2028 (forecast)","production_unit":"tU/year (FS avg 12-year LOM)","note":"100% Atomic Eagle (merged GoviEx + Tombador Iron 2025); 719 km² ML + 1,136 km² total; ESIA filed ZEMA Sept 2025; forecast 846 tU/year avg over 12-year LOM","processing_mill":["Central processing plant planned on-site, 3.5 Mtpa, weak H2SO4 + H2O2 heap leach"],"transport_routes":["26 km road to Siavonga Highway","Livingstone 560 km to Namibia/Walvis Bay port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ZIMBABWE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kanyemba-1 Uranium Deposit', 'Afri-Sino Mining + ZMDC', 'Mashonaland Central — Guruve District, Zambezi Valley', NULL, 'Energy', 'Uranium', -16.3300, 30.4000, 'Zimbabwe', 'Mashonaland Central Province', 'Guruve', 'mine', 'planned', 'Afri-Sino / ZMDC', 'joint_venture', 0.60, 0, 1800, 0, '{"mining_method":"open-pit (planned; 1991 feasibility: 350 tU/year capacity)","production_unit":"tU/year","note":"Afri-Sino 42% (China Uranium Corp), ZMDC balance; Iran-Zimbabwe MOU 2010; Russian MoUs 2021/2023; no active production","processing_mill":["None built — on-site mill planned in 1991 feasibility"],"transport_routes":["~300 km north of Harare via Zambezi Valley road"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Karoi Uranium (Lomagundi Belt)', 'Zimbabwe Geological Survey', 'Mashonaland West — Karoi District', NULL, 'Energy', 'Uranium', -16.8200, 29.6800, 'Zimbabwe', 'Mashonaland West Province', 'Karoi', 'mine', 'planned', 'Zimbabwe Geological Survey', 'state_owned', NULL, 0, NULL, 0, '{"mining_method":"exploration only","production_unit":"tU/year","note":"Lomagundi Precambrian Copperbelt-type sediments; ~0.77 tU produced historically 1950s; no JORC/NI 43-101 resource; national resource quantification 2022","processing_mill":["None"],"transport_routes":["~200 km NW of Harare via A1 highway to Karoi"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CENTRAL AFRICAN REPUBLIC
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bakouma Uranium Project', 'Orano + CAR Government', 'Mbomou Prefecture — Bakouma Sub-Prefecture', NULL, 'Energy', 'Uranium', 5.6900, 22.8000, 'Central African Republic', 'Mbomou Prefecture', 'Bakouma', 'mine', 'inactive', 'Orano', 'joint_venture', 1.27, 0, 36500, 0, '{"mining_method":"open-pit (planned; suspended 2012)","closing_date":"2012-06","production_unit":"tU/year","note":"Orano 90%, CAR 10%; armed attack June 2012; UraMin acquired 2007 USD 2.5B; Patricia 11,512 tU at 0.138%U","processing_mill":["Pilot opened 2010, abandoned 2012"],"transport_routes":["~870 km SE of Bangui","Planned: road to Bangui then export"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- DEMOCRATIC REPUBLIC OF CONGO
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shinkolobwe Mine', 'DRC Government', 'Haut-Katanga — Kambove Territory', NULL, 'Energy', 'Uranium', -11.0550, 26.5470, 'Democratic Republic of Congo', 'Haut-Katanga Province', 'Likasi', 'mine', 'inactive', 'None', 'state_owned', 0.30, 0, 1400, 0, '{"mining_method":"underground/open-pit (historic); closed, artisanal incursions","start_date":"1921","closing_date":"2004","production_unit":"tU/year","note":"Manhattan Project source; ore up to 65% U3O8; sealed 1960; Presidential Decree closure 2004; part of 400 km Katanga uraniferous belt (Luiswishi, Kambove, Musonoi); Orano exploration 2009","processing_mill":["Historic: Olen Belgium, US AEC facilities"],"transport_routes":["20 km W of Likasi","145 km NW of Lubumbashi","TAZARA rail to Dar es Salaam","Lobito Corridor to Angola coast"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- MADAGASCAR
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Morondava Basin Uranium Exploration', 'OMNIS (state agency)', 'Menabe Region — western Madagascar', NULL, 'Energy', 'Uranium', -20.3000, 44.3000, 'Madagascar', 'Menabe Region', 'Morondava', 'mine', 'planned', 'None', 'state_owned', NULL, 0, NULL, 0, '{"mining_method":"exploration only — open-pit likely (sandstone-type, Karoo formation)","production_unit":"tU/year","note":"Folakara/North Morondava prospects; Cline/URAMAD permits expired 2015-2016; 2024 MDPI Grade I-II target; no JORC resource","processing_mill":["None"],"transport_routes":["Morondava town ~320 km from Antananarivo","Morondava port for coastal export"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Toliara / Fort Dauphin Mineral Sands', 'Energy Fuels', 'Atsimo-Andrefana Region — southwestern Madagascar', NULL, 'Energy', 'Uranium', -23.3500, 43.6700, 'Madagascar', 'Atsimo-Andrefana Region', 'Toliara', 'mine', 'planned', 'Energy Fuels', 'private', NULL, 29, NULL, 29, '{"mining_method":"open-pit dredge (primary: ilmenite/zircon/monazite); uranium by-product from monazite at White Mesa Mill USA","start_date":"2025","production_unit":"tU/year (~75,000 lbs U3O8/year by-product)","note":"100% Energy Fuels (acquired Base Resources Oct 2024); suspension lifted Nov 2024; monazite to White Mesa Utah for REE+U recovery","processing_mill":["Monazite to White Mesa Mill Utah USA"],"transport_routes":["Toliara port","Sea freight to USA White Mesa Mill"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- MALAWI
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kayelekera Uranium Mine', 'Lotus Resources + Gov Malawi', 'Northern Region — Karonga District', NULL, 'Energy', 'Uranium', -9.8400, 33.5100, 'Malawi', 'Northern Region', 'Karonga', 'mine', 'operational', 'Lotus Resources', 'joint_venture', 0.085, 923, 19655, 923, '{"mining_method":"open-pit (SAG mill, acid leach, RIP, peroxide precipitation)","start_date":"2009-04","production_unit":"tU/year (ramp-up target 2.4 Mlbs U3O8/year Q1 2026)","note":"Lotus 85%, Malawi Govt 15%; acquired from Paladin 2020; re-inaugurated Aug 2025; first yellowcake Sept 2025","processing_mill":["Kayelekera on-site mill"],"transport_routes":["52 km east to Karonga","Road to Dar es Salaam port for export"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- MOROCCO
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('OCP Phosphate Uranium', 'URANEXT / OCP Group', 'Khouribga (Oulad Abdoun), Youssoufia (Gantour), Essaouira (Meskala), El Jadida', NULL, 'Energy', 'Uranium', 32.8800, -6.9100, 'Morocco', 'Khouribga', 'El Jadida', 'mine', 'planned', 'URANEXT', 'state_owned', 0.012, 0, 6900000, 0, '{"mining_method":"by-product from wet-process phosphoric acid (ion exchange/solvent extraction)","start_date":"2025","production_unit":"tU/year (target TBD; Belgium recovered 686 tU 1985-1998)","note":"OCP phosphate; ~6.9 MtU in phosphate rock; URANEXT $100M plant at El Jadida announced May 2025","processing_mill":["URANEXT plant at El Jadida/Jorf Lasfar (under construction)"],"transport_routes":["El Jadida/Jorf Lasfar port","Slurry pipeline Khouribga 235 km to Jorf Lasfar"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tarfaya Phosphate Uranium', 'ONHYM', 'Guelmim-Oued Noun — Tarfaya Province, SW Morocco', NULL, 'Energy', 'Uranium', 27.9400, -12.9300, 'Morocco', 'Guelmim-Oued Noun Region', 'Tarfaya', 'mine', 'planned', 'ONHYM', 'state_owned', 0.015, 0, NULL, 0, '{"mining_method":"exploration only (phosphate-uranium in Cretaceous marinites)","production_unit":"tU/year","note":"U3O8 up to ~150 ppm; oil shale deposit 86 Gt; IUREP 1983 speculative 70,000-100,000 tU nationwide","processing_mill":["None"],"transport_routes":["Tarfaya port","Road to Agadir 350 km or Laayoune 120 km"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- EGYPT
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Missikat / El Erediya', 'NMA Egypt', 'Red Sea Governorate — Central Eastern Desert ~200 km S of Hurghada', NULL, 'Energy', 'Uranium', 25.5500, 33.1800, 'Egypt', 'Red Sea Governorate', NULL, 'mine', 'planned', 'NMA Egypt', 'state_owned', 0.05, 0, 5000, 0, '{"mining_method":"exploratory adits/trenching; open-pit or underground planned","production_unit":"tU/year","note":"100% NMA/EAEA; vein-type pitchblende in younger granites; El Erediya discovered 1970; Egypt ~5,000 tU inferred to $260/kgU","processing_mill":["None built"],"transport_routes":["Desert road from Hurghada ~200 km","Qena–Safaga road from Nile Valley"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gabal Gattar Uranium Deposit', 'NMA Egypt', 'Red Sea Governorate — ~35 km W of Hurghada', NULL, 'Energy', 'Uranium', 27.2000, 33.4000, 'Egypt', 'Red Sea Governorate', 'Hurghada', 'mine', 'planned', 'NMA Egypt', 'state_owned', NULL, 0, NULL, 0, '{"mining_method":"trenching and shallow drilling; open-pit targeted","production_unit":"tU/year","note":"100% NMA/EAEA; vein-type F-Mo-U in granite; discovered 1985; ~27,000 t mineralization identified","processing_mill":["None"],"transport_routes":["~35 km desert road W of Hurghada","Hurghada Red Sea port and airport"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Allouga Uranium Mine', 'NMA Egypt', 'South Sinai Governorate — southwestern Sinai Peninsula', NULL, 'Energy', 'Uranium', 29.0300, 33.1200, 'Egypt', 'South Sinai Governorate', NULL, 'mine', 'operational', 'NMA Egypt', 'state_owned', 0.108, 0, NULL, 0, '{"mining_method":"open-pit and underground; crushing, H2SO4 leach, IX, NaOH precipitation","start_date":"1957","production_unit":"tU/year (small-scale; figures not disclosed)","note":"100% NMA/EAEA; Egypt''s only operating uranium mine; Carboniferous host; environmental concerns documented","processing_mill":["On-site processing plant"],"transport_routes":["Southwestern Sinai roads","Road to Suez/Ismailia for NMA transfer"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wadi Nasieb Uranium Occurrence', 'NMA Egypt', 'South Sinai Governorate — west-central Sinai Peninsula', NULL, 'Energy', 'Uranium', 29.4200, 33.0800, 'Egypt', 'South Sinai Governorate', NULL, 'mine', 'planned', 'NMA Egypt', 'state_owned', NULL, 0, NULL, 0, '{"mining_method":"exploration only","production_unit":"tU/year","note":"100% NMA/EAEA; uranium in carbonaceous marls and Carboniferous dolomites; economic potential not assessed","processing_mill":["None"],"transport_routes":["Sinai road network"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- SOMALIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Alio Ghelle Uranium Deposit', 'Gov of Somalia', 'Galmudug State — Galgaduud-Mudug region, Bur Massif', NULL, 'Energy', 'Uranium', 4.2000, 46.1000, 'Somalia', 'Galmudug State', NULL, 'mine', 'planned', 'None', 'state_owned', 0.07, 0, 5000, 0, '{"mining_method":"exploration only — security prevents access","production_unit":"tU/year","note":"Carnotite in Neoproterozoic Bur Massif; 1984 Red Book ~5,000 tU RAR; Al-Shabaab controls parts; exploration suspended since 1991","processing_mill":["None"],"transport_routes":["No viable access; Mogadishu ~600 km S, Bosaso ~500 km N"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- GABON
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, concentration_level, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mounana–Oklo Mining District', 'Gov of Gabon', 'Haut-Ogooué Province — ~80 km NW of Franceville', NULL, 'Energy', 'Uranium', -1.4100, 13.1600, 'Gabon', 'Haut-Ogooué Province', 'Mounana', 'mine', 'inactive', 'None (historically COMUF)', 'state_owned', 0.37, 0, 4800, 0, '{"mining_method":"open-pit and underground — ALL CLOSED 1999","start_date":"1961","closing_date":"1999","production_unit":"tU/year","note":"Franceville Basin; Mounana, Oklo, Boyindzi, Okélobondo, Mikouloungou; Oklo fossil reactors; ~28,000 tU total production; remediated 2004","processing_mill":["Mounana mill (closed 1999, dismantled)"],"transport_routes":["N3 Mounana→Franceville 80 km","Trans-Gabon Railway to Libreville port"]}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, concentration_level=EXCLUDED.concentration_level, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();
