-- ============================================================
-- Germany Oil Production Sites — 14 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- LOWER SAXONY
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mittelplate Field', 'Wintershall Dea + Harbour Energy', 'Lower Saxony / Schleswig-Holstein — Wadden Sea, tidal flat', NULL, 'Energy', 'Crude Oil', 54.0000, 8.6667, 'Germany', 'Lower Saxony', 'Heide', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 30.00, 0.80, 480000, 90000000, 480000, '{"start_year":1987,"production_bpd":16000,"quality":"Medium","note":"Germany''s largest producing oil field; ~40% of total German production; artificial island in UNESCO Wadden Sea; Wintershall Dea 50%, Harbour Energy 50%","last_transaction":"Harbour Energy acquired DEA from LetterOne 2021 for $2.2B; LetterOne acquired DEA from RWE 2015 for €5.1B","contract_duration":"German federal mining license (Bundesberggesetz) to 2041","pipelines":"Mittelplate island → Dieksand terminal (9km subsea + 7km onshore); Dieksand → Hamburg refinery (~100km)","ports":"Hamburg Port; Brunsbüttel (Elbe estuary)","rail":"Heide–Hamburg rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rühle Field', 'Wintershall Dea', 'Lower Saxony — Emsland District', NULL, 'Energy', 'Crude Oil', 52.7500, 7.1667, 'Germany', 'Lower Saxony', 'Lingen', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 36.00, 0.30, 75000, 30000000, 75000, '{"start_year":1949,"production_bpd":2500,"quality":"Light sweet","note":"Mature; Wintershall Dea 100%","last_transaction":"Wintershall Dea formed 2019 (BASF Wintershall + DEA merger)","contract_duration":"German federal mining license","pipelines":"Rühle → Emsland gathering → Lingen refinery (~50km); or → Hamburg","ports":"Hamburg (indirect via pipeline)","rail":"Lingen–Osnabrück rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Georgsdorf Field', 'Wintershall Dea', 'Lower Saxony — Emsland', NULL, 'Energy', 'Crude Oil', 52.5833, 7.0000, 'Germany', 'Lower Saxony', 'Lingen', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 35.00, NULL, 60000, 25000000, 60000, '{"start_year":1944,"production_bpd":2000,"quality":"Light sweet","note":"Mature; WWII-era strategic production; Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Georgsdorf → Lingen refinery gathering","ports":"Hamburg (indirect)","rail":"Lingen rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Emlichheim Field', 'Wintershall Dea', 'Lower Saxony — Emsland, Netherlands border', NULL, 'Energy', 'Crude Oil', 52.6167, 6.8500, 'Germany', 'Lower Saxony', 'Lingen', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 34.00, 0.40, 90000, 50000000, 90000, '{"start_year":1944,"production_bpd":3000,"quality":"Medium light","note":"Cross-border field with Netherlands; German side; Wintershall Dea 100% (German sector)","contract_duration":"German federal mining license","pipelines":"Emlichheim → Lingen refinery pipeline","ports":"Hamburg; Rotterdam (via Netherlands pipeline, cross-border)","rail":"Nordhorn–Lingen rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rühlermoor Field', 'Wintershall Dea', 'Lower Saxony — Emsland', NULL, 'Energy', 'Crude Oil', 52.7167, 7.1000, 'Germany', 'Lower Saxony', 'Lingen', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 35.00, NULL, 45000, NULL, 45000, '{"start_year":1950,"production_bpd":1500,"quality":"Light sweet","note":"Mature; Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Rühlermoor → Lingen gathering","ports":"Hamburg","rail":"Lingen rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Scheerhorn Field', 'Wintershall Dea', 'Lower Saxony — Emsland', NULL, 'Energy', 'Crude Oil', 52.5333, 7.2500, 'Germany', 'Lower Saxony', 'Lingen', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 34.00, NULL, 30000, NULL, 30000, '{"start_year":1955,"production_bpd":1000,"quality":"Medium light","note":"Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Emsland gathering → Lingen","ports":"Hamburg","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hänigsen Field', 'Wintershall Dea', 'Lower Saxony — Hanover region', NULL, 'Energy', 'Crude Oil', 52.4833, 9.9833, 'Germany', 'Lower Saxony', 'Hanover', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 33.00, 0.50, 36000, 15000000, 36000, '{"start_year":1950,"production_bpd":1200,"quality":"Medium light","note":"Germany''s first major postwar field; mature; Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Hänigsen → Hanover oil pipeline → Hamburg refinery","ports":"Hamburg","rail":"Hanover rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Steinfelde Field', 'Wintershall Dea', 'Lower Saxony — Cloppenburg', NULL, 'Energy', 'Crude Oil', 52.8333, 8.0000, 'Germany', 'Lower Saxony', 'Cloppenburg', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 34.00, NULL, 24000, NULL, 24000, '{"start_year":1962,"production_bpd":800,"quality":"Medium light","note":"Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Steinfelde → Lower Saxony gathering → Hamburg","ports":"Hamburg","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vorhop-Knesebeck Field', 'Wintershall Dea', 'Lower Saxony — Gifhorn District', NULL, 'Energy', 'Crude Oil', 52.7167, 10.7333, 'Germany', 'Lower Saxony', 'Gifhorn', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 35.00, NULL, 45000, NULL, 45000, '{"start_year":1958,"production_bpd":1500,"quality":"Light sweet","note":"Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Gifhorn → Hanover → Hamburg gathering","ports":"Hamburg","rail":"Wolfsburg–Hanover rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Plesse (Söhlingen) Field', 'Wintershall Dea + ExxonMobil', 'Lower Saxony — Rotenburg', NULL, 'Energy', 'Crude Oil', 52.9167, 9.5000, 'Germany', 'Lower Saxony', 'Rotenburg', 'oil_field', 'operational', 'Wintershall Dea + ExxonMobil', 'joint_venture', 36.00, NULL, 60000, NULL, 60000, '{"start_year":1957,"production_bpd":2000,"quality":"Light sweet","note":"Wintershall Dea 60%, ExxonMobil Germany 40%; legacy Mobil Germany","contract_duration":"German federal mining license","pipelines":"Söhlingen → Hamburg gathering system","ports":"Hamburg","rail":"Bremen–Hamburg rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Landwehren Field', 'Wintershall Dea', 'Lower Saxony — Nienburg', NULL, 'Energy', 'Crude Oil', 52.6667, 9.2500, 'Germany', 'Lower Saxony', 'Nienburg', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 34.00, NULL, 21000, NULL, 21000, '{"start_year":1964,"production_bpd":700,"quality":"Medium light","note":"Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Nienburg gathering → Hamburg","ports":"Hamburg","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Breitbrunn-Eggstätt Field', 'Wintershall Dea', 'Bavaria — Upper Bavaria, Chiemsee area', NULL, 'Energy', 'Crude Oil', 47.9833, 12.3667, 'Germany', 'Bavaria', 'Rosenheim', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 42.00, NULL, 15000, NULL, 15000, '{"start_year":1956,"production_bpd":500,"quality":"Light sweet","note":"Bavaria''s only producing field; very small — mostly gas with oil; legacy Mobil/ExxonMobil; Wintershall Dea 100%","contract_duration":"German federal mining license","pipelines":"Breitbrunn → Bavaria gathering → Ingolstadt refinery","ports":"None direct (landlocked Bavaria)","rail":"Rosenheim–Munich rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NORTH SEA / OTHER
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mittelplate Offshore Extension', 'Wintershall Dea + Harbour Energy', 'German North Sea sector — shallow Wadden Sea', NULL, 'Energy', 'Crude Oil', 54.0167, 8.6500, 'Germany', 'North Sea', 'Heide', 'oil_field', 'operational', 'Wintershall Dea', 'joint_venture', 30.00, 0.80, 0, NULL, 0, '{"start_year":1987,"production_bpd":0,"quality":"Medium","note":"Offshore directional drilling component of Mittelplate; production included in main Mittelplate total; drills from artificial island into German North Sea sector","contract_duration":"To 2041","pipelines":"Part of Mittelplate system","ports":"Hamburg; Brunsbüttel","rail":"Heide–Hamburg rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Römerberg Field', 'Engie E&P Deutschland', 'Rhineland-Palatinate — far western Germany', NULL, 'Energy', 'Crude Oil', 49.3500, 8.4333, 'Germany', 'Rhineland-Palatinate', 'Karlsruhe', 'oil_field', 'operational', 'Engie E&P Deutschland', 'state_owned', 38.00, NULL, 12000, NULL, 12000, '{"start_year":1978,"production_bpd":400,"quality":"Light sweet","note":"Small, Rhine Valley; Palatina RWE → GDF Suez → Engie; French state ownership","contract_duration":"German federal mining license","pipelines":"Römerberg → Karlsruhe refinery (MiRO) pipeline (~50km)","ports":"None direct (Rhine River, landlocked)","rail":"Karlsruhe rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Germany' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Germany' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
