-- ============================================================
-- Suriname & Venezuela — Oil Production Sites (UPSERT)
-- Run this in Supabase SQL Editor
-- Suriname: 5 sites | Venezuela: 20 sites
-- Note: Trinidad and Tobago already covered in INSERT_TRINIDAD_TOBAGO_OIL.sql
-- ============================================================

-- =====================
-- SURINAME — ONSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tambaredjo Field', 'Staatsolie', 'Saramacca District — onshore coastal Suriname', NULL, 'Energy', 'Crude Oil', 5.8333, -55.1667, 'Suriname', 'Onshore Suriname', 'Paramaribo', 'oil_field', 'operational', 'Staatsolie', 'state_owned', 22.00, 2.00, 15000, 100000000, 450000, '{"start_year":1982,"production_bpd":15000,"quality":"Heavy","note":"Staatsolie 100%; Suriname''s only producing field until offshore","pipelines":"Tambaredjo → Tout Lui Faut refinery (Paramaribo)","ports":"Paramaribo Port","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Calcutta Field', 'Staatsolie', 'Saramacca District — onshore Suriname', NULL, 'Energy', 'Crude Oil', 5.9167, -55.2500, 'Suriname', 'Onshore Suriname', 'Paramaribo', 'oil_field', 'operational', 'Staatsolie', 'state_owned', 21.00, NULL, 1000, NULL, 30000, '{"start_year":1985,"production_bpd":1000,"quality":"Heavy","note":"Staatsolie 100%; small onshore satellite","pipelines":"Calcutta → Tambaredjo gathering → Tout Lui Faut refinery","ports":"Paramaribo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- SURINAME — OFFSHORE (GUYANA-SURINAME BASIN)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 58 (Sapakara / Krabdagu)', 'TotalEnergies + APA Corporation', 'Offshore Suriname — Guyana-Suriname Basin deep water', NULL, 'Energy', 'Crude Oil', 7.0000, -56.0000, 'Suriname', 'Offshore Suriname', NULL, 'oil_field', 'planned', 'TotalEnergies', 'joint_venture', 30.00, NULL, 0, 2000000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Medium light (estimated)","note":"TotalEnergies 50%, APA 50%; discoveries 2020-2022; FID pending; targeting ~200,000 bpd","pipelines":"Planned FPSO → shuttle tanker export","ports":"Planned offshore export","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 52 (Dikkop)', 'Petronas + ExxonMobil', 'Offshore Suriname — Guyana-Suriname Basin', NULL, 'Energy', 'Crude Oil', 7.5000, -55.5000, 'Suriname', 'Offshore Suriname', NULL, 'oil_field', 'planned', 'Petronas', 'joint_venture', NULL, NULL, 0, 400000000, 0, '{"start_year":null,"production_bpd":0,"quality":"TBD","note":"Petronas 50%, ExxonMobil 50%; Dikkop discovery 2022; appraisal ongoing","pipelines":"None (exploration stage)","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 53', 'Equinor', 'Offshore Suriname — Guyana-Suriname Basin', NULL, 'Energy', 'Crude Oil', 8.0000, -55.0000, 'Suriname', 'Offshore Suriname', NULL, 'oil_field', 'planned', 'Equinor', 'private', NULL, NULL, 0, NULL, 0, '{"start_year":null,"production_bpd":0,"quality":"Unknown","note":"Equinor 100%; exploration — no commercial discoveries announced","pipelines":"None","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VENEZUELA — MARACAIBO BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lagunillas Field', 'PDVSA', 'Zulia State — Lake Maracaibo, western shore', NULL, 'Energy', 'Crude Oil', 10.1333, -71.2667, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 17.00, 2.50, 30000, 200000000, 900000, '{"start_year":1926,"production_bpd":30000,"quality":"Heavy","note":"PDVSA 100%; Venezuela''s oldest major lake field; nationalized 1976","pipelines":"Lagunillas → Lake Maracaibo gathering → Paraguaná CRP","ports":"Maracaibo Port; La Salina Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bachaquero Field', 'PDVSA', 'Zulia State — Lake Maracaibo, eastern shore', NULL, 'Energy', 'Crude Oil', 9.6667, -71.1167, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 16.00, 2.80, 40000, 150000000, 1200000, '{"start_year":1931,"production_bpd":40000,"quality":"Heavy","note":"PDVSA 100%; mature; Creole Petroleum legacy","pipelines":"Bachaquero → Lake Maracaibo gathering → Paraguaná / Bajo Grande","ports":"Bajo Grande Terminal; Maracaibo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tía Juana Field', 'PDVSA', 'Zulia State — Lake Maracaibo, northwest', NULL, 'Energy', 'Crude Oil', 10.2500, -71.4667, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 18.00, 2.40, 25000, NULL, 750000, '{"start_year":1928,"production_bpd":25000,"quality":"Heavy","note":"PDVSA 100%; mature","pipelines":"Tía Juana → Lake Maracaibo gathering → Paraguaná","ports":"La Salina; Maracaibo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('La Paz Field', 'PDVSA', 'Zulia State — Lake Maracaibo, central', NULL, 'Energy', 'Crude Oil', 9.9167, -71.3333, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 19.00, NULL, 20000, NULL, 600000, '{"start_year":1930,"production_bpd":20000,"quality":"Heavy","note":"PDVSA 100%; mature","pipelines":"La Paz → Lake Maracaibo gathering","ports":"Maracaibo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Boscán Field', 'Chevron Venezuela + PDVSA', 'Zulia State — western Maracaibo Basin, onshore', NULL, 'Energy', 'Crude Oil', 10.0000, -72.2500, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'Chevron Venezuela', 'joint_venture', 10.00, 5.50, 60000, 8000000000, 1800000, '{"start_year":1946,"production_bpd":60000,"quality":"Extra heavy — Venezuela''s highest sulfur crude","note":"PDVSA 60%, Chevron 40% (operator); OFAC licensed; one of few foreign-operated fields","pipelines":"Boscán → San Lorenzo Terminal","ports":"San Lorenzo Terminal (Gulf of Venezuela)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ceuta Field', 'PDVSA', 'Zulia State — Lake Maracaibo', NULL, 'Energy', 'Crude Oil', 9.7500, -71.2833, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 20.00, NULL, 15000, NULL, 450000, '{"start_year":1926,"production_bpd":15000,"quality":"Heavy","note":"PDVSA 100%; mature","pipelines":"Ceuta → Lake Maracaibo gathering","ports":"Maracaibo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cabimas Field', 'PDVSA', 'Zulia State — Lake Maracaibo, historic', NULL, 'Energy', 'Crude Oil', 10.3833, -71.4500, 'Venezuela', 'Maracaibo Basin', 'Maracaibo', 'oil_field', 'operational', 'PDVSA', 'state_owned', 21.00, NULL, 10000, NULL, 300000, '{"start_year":1917,"production_bpd":10000,"quality":"Heavy","note":"PDVSA 100%; Lake Maracaibo''s first major field; Los Barroso 1922","pipelines":"Cabimas → Lake Maracaibo gathering","ports":"Maracaibo","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VENEZUELA — ORINOCO BELT
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cerro Negro', 'PDVSA', 'Orinoco Belt — Monagas State, Boyacá Area', NULL, 'Energy', 'Crude Oil', 8.7500, -64.3333, 'Venezuela', 'Orinoco Belt', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 8.00, 3.00, 20000, 30000000000, 600000, '{"start_year":2001,"production_bpd":20000,"quality":"Extra heavy bitumen","note":"PDVSA 100%; expropriated from ExxonMobil 2007; severely curtailed","pipelines":"Cerro Negro → Jose Terminal → upgrader","ports":"Jose Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Petropiar / Hamaca', 'PDVSA + Chevron', 'Orinoco Belt — Anzoátegui State, Boyacá Area', NULL, 'Energy', 'Crude Oil', 8.5000, -64.0000, 'Venezuela', 'Orinoco Belt', 'Jose', 'oil_field', 'operational', 'PDVSA', 'joint_venture', 8.00, NULL, 40000, 30000000000, 1200000, '{"start_year":2004,"production_bpd":40000,"quality":"Extra heavy bitumen — upgraded to Merey synthetic","note":"PDVSA 70%, Chevron 30%; Chevron-operated; OFAC licensed","pipelines":"Hamaca upgrader → Jose Terminal","ports":"Jose Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Petrocedeño / Sincor', 'PDVSA', 'Orinoco Belt — Anzoátegui State, Machete Area', NULL, 'Energy', 'Crude Oil', 9.0000, -63.5000, 'Venezuela', 'Orinoco Belt', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 8.00, NULL, 10000, NULL, 300000, '{"start_year":1997,"production_bpd":10000,"quality":"Extra heavy","note":"PDVSA 100%; nationalized from TotalEnergies/Equinor 2007; collapsed","pipelines":"Sincor upgrader (idle) → Jose Terminal","ports":"Jose Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Petromonagas', 'PDVSA', 'Orinoco Belt — Monagas State, Carabobo/Junín Area', NULL, 'Energy', 'Crude Oil', 8.8333, -64.5000, 'Venezuela', 'Orinoco Belt', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 8.00, NULL, 5000, NULL, 150000, '{"start_year":2009,"production_bpd":5000,"quality":"Extra heavy","note":"PDVSA 100%; bp exited 2010; collapsed","pipelines":"→ Jose Terminal (non-operational)","ports":"Jose","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Carabobo / Junín Blocks', 'PDVSA + various partners', 'Orinoco Belt — mega-projects stalled', NULL, 'Energy', 'Crude Oil', 8.6667, -64.7500, 'Venezuela', 'Orinoco Belt', 'Jose', 'oil_field', 'operational', 'PDVSA', 'joint_venture', 9.00, NULL, 20000, 200000000000, 600000, '{"start_year":2010,"production_bpd":20000,"quality":"Extra heavy","note":"PDVSA majority; Chevron, Rosneft, CNPC, Repsol, ENI — most suspended; largely undeveloped","pipelines":"Planned upgraders → Jose (mostly not built)","ports":"Jose (if developed)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VENEZUELA — EASTERN VENEZUELA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Oficina Field', 'PDVSA', 'Anzoátegui State — Eastern Venezuela Basin', NULL, 'Energy', 'Crude Oil', 8.7500, -64.7500, 'Venezuela', 'Eastern Venezuela', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 32.00, 0.80, 50000, 300000000, 1500000, '{"start_year":1938,"production_bpd":50000,"quality":"Mesa 30 benchmark — Eastern Venezuela light","note":"PDVSA 100%; historic Creole/Shell field; mature conventional","pipelines":"Oficina → Jose Terminal; → Barcelona refinery","ports":"Jose Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Santa Rosa / Temblador Area', 'PDVSA', 'Monagas State — Eastern Venezuela', NULL, 'Energy', 'Crude Oil', 9.3333, -62.9167, 'Venezuela', 'Eastern Venezuela', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 34.00, 0.60, 30000, NULL, 900000, '{"start_year":1929,"production_bpd":30000,"quality":"Light sweet","note":"PDVSA 100%; mature conventional","pipelines":"Santa Rosa → Eastern Venezuela gathering → Jose","ports":"Jose Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Quiriquire Field', 'PDVSA', 'Monagas State — Eastern Venezuela', NULL, 'Energy', 'Crude Oil', 9.6667, -63.2333, 'Venezuela', 'Eastern Venezuela', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 31.00, NULL, 20000, NULL, 600000, '{"start_year":1928,"production_bpd":20000,"quality":"Medium light","note":"PDVSA 100%; mature","pipelines":"Quiriquire → Eastern Venezuela gathering","ports":"Jose","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Furrial Field', 'PDVSA', 'Monagas State — Eastern Venezuela Basin', NULL, 'Energy', 'Crude Oil', 9.5000, -63.0000, 'Venezuela', 'Eastern Venezuela', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 26.00, 1.00, 80000, 200000000, 2400000, '{"start_year":1986,"production_bpd":80000,"quality":"Medium","note":"PDVSA 100%; Venezuela''s last major conventional discovery","pipelines":"Furrial → Jose Terminal","ports":"Jose","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Acema / Morichal / Pilón Area', 'PDVSA', 'Monagas State — Eastern Venezuela', NULL, 'Energy', 'Crude Oil', 9.2500, -62.7500, 'Venezuela', 'Eastern Venezuela', 'Jose', 'oil_field', 'operational', 'PDVSA', 'state_owned', 30.00, NULL, 40000, NULL, 1200000, '{"start_year":1960,"production_bpd":40000,"quality":"Medium light","note":"PDVSA 100%","pipelines":"→ Jose Terminal gathering","ports":"Jose","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VENEZUELA — OFFSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Plataforma Deltana', 'PDVSA + Chevron (historical)', 'Offshore Orinoco River Delta — Gulf of Paria', NULL, 'Energy', 'Condensate', 10.0000, -61.5000, 'Venezuela', 'Offshore Venezuela', NULL, 'oil_field', 'inactive', 'PDVSA', 'joint_venture', 40.00, NULL, 0, 500000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Condensate (estimated)","note":"Offshore gas + condensate; development halted by sanctions; Chevron, Shell, Repsol suspended","pipelines":"None operational","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mariscal Sucre / Cardón IV Project', 'PDVSA + ENI', 'Offshore northern Venezuela — Caribbean', NULL, 'Energy', 'Crude Oil', 11.5000, -68.5000, 'Venezuela', 'Offshore Venezuela', NULL, 'oil_field', 'inactive', 'PDVSA', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":null,"production_bpd":0,"quality":"Gas project","note":"Offshore gas project; Perla discovery 2009; development suspended indefinitely","pipelines":"None","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Corocoro Field', 'PDVSA', 'Offshore Falcón State — northwestern Venezuela Caribbean', NULL, 'Energy', 'Crude Oil', 11.0000, -69.5000, 'Venezuela', 'Offshore Venezuela', 'Paraguaná', 'oil_field', 'operational', 'PDVSA', 'state_owned', 28.00, NULL, 3000, NULL, 90000, '{"start_year":1970,"production_bpd":3000,"quality":"Medium","note":"PDVSA 100%; small offshore mature","pipelines":"Corocoro → Paraguaná gathering","ports":"Paraguaná Peninsula","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();
