-- ============================================================
-- Nigeria Sugar Mills — 5 mills (sugar_plants)
-- Run SUGAR_PLANTS_TABLE_SETUP.sql first. Then run this in Supabase SQL Editor.
-- Adamawa: 1 | Niger: 1 | Kwara: 2 | Jigawa: 1
-- ============================================================

INSERT INTO public.sugar_plants (
  plant_id,
  mill_name,
  operator,
  country,
  iso_code,
  region,
  sugar_type,
  latitude,
  longitude,
  status,
  crushing_capacity_tcd,
  annual_output_tonnes,
  primary_grade,
  grades_available,
  icumsa_range,
  crushing_start,
  crushing_end,
  peak_months,
  export_terminal,
  distance_to_port_km,
  rail_access,
  storage_capacity_tonnes,
  price_benchmark,
  incoterms,
  typical_contract,
  major_buyers,
  export_markets,
  notes
) VALUES
  ('NGA-ADM-001', 'Savannah Sugar Company – Numan Integrated Sugar Complex', 'Dangote Sugar Refinery Plc (DSR) / Dangote Group', 'Nigeria', 'NGA', 'Numan region – Adamawa State (Benue River valley, Numan LGA)', 'sugarcane', 9.4667, 12.0333, 'operational', 3000, 50000, 'Raw / Mill White Sugar', 'Raw Sugar, Mill White Sugar, Molasses, Bagasse (fuel), 90MW power (planned)', '600–1200', 'November', 'April', 'December, January, February', 'Apapa Port, Lagos (domestic supply only currently)', 850, FALSE, 35000, 'ICE No. 11 / Nigerian domestic regulated price', 'DDP Lagos (domestic); Ex-Works Numan', 'Domestic supply to DSR Lagos refinery; tied to BIP import quota', 'DSR Lagos refinery (internal); Nigerian domestic market via Dangote Sugar distribution network', 'Domestic only; no current exports', 'Originally state-owned Savannah Sugar Company Ltd (SSCL), established 1981 with 50,000 t/yr installed capacity. Privatised 2004 to Dangote. Mill was at 3,000 TCD as of 2022; Dangote announced $700M BIP investment in Nov 2022 to expand to 6,000 → 9,800 → 15,000 TCD over 7 years. Plantation area to grow from 8,700 ha to 24,200 ha. 90MW cogeneration planned. Estate on Benue River alluvial soils. Dangote also developing a second large site at Tunga, Nasarawa State (60,000 ha, 430,000 t/yr target — under_construction, not listed here). Dangote DSR controls ~70% of Nigerian refined sugar market and was allocated 864,000 MT import quota in 2022.'),
  ('NGA-NIG-001', 'Sunti Golden Sugar Estate – Sugar Factory', 'Golden Sugar Company (subsidiary of Flour Mills of Nigeria Plc / FMN)', 'Nigeria', 'NGA', 'Sunti region – Niger State (Niger River, Borgu LGA / Mashegu LGA)', 'sugarcane', 10.2000, 4.7500, 'operational', 3000, 30000, 'Raw / Mill White Sugar', 'Raw Sugar, Mill White Sugar, Molasses', '600–1200', 'November', 'April', 'December, January, February', 'Apapa Port, Lagos (domestic supply only)', 700, FALSE, 20000, 'ICE No. 11 / Nigerian domestic price', 'Ex-Works Sunti', 'Domestic supply to FMN Lagos refinery; tied to BIP import quota', 'FMN Golden Sugar Lagos refinery (internal); Nigerian domestic market', 'Domestic only', 'Commissioned in phases; formally opened by President Buhari. FMN invested over NGN 73 billion at Sunti. Total estate area: 22,000 ha with 15,000 ha under development; currently 3,500 ha irrigated cane. Factory capacity: 3,000 TCD operational; planned expansion to match estate development. Located on Niger River alluvial soils, Borgu LGA. FMN also signed MoU with Nasarawa State Government for further expansion. FMN was allocated 400,000 MT raw sugar import quota (2022) tied to BIP compliance. Golden Sugar Company also manages import refinery operations at Apapa.'),
  ('NGA-KWA-001', 'BUA Lafiagi Sugar Company (LASUCO) – Lafiagi Sugar Mill', 'BUA Group (BUA International / BUA Foods Plc)', 'Nigeria', 'NGA', 'Lafiagi / Bacita region – Kwara State (Niger River, Edu LGA)', 'sugarcane', 8.8667, 5.4167, 'operational', 10000, 220000, 'White Granulated Sugar', 'White Granulated Sugar, Raw Sugar, Ethanol, Molasses, Power (grid-connected)', '45–600', 'November', 'April', 'December, January, February', 'Apapa Port, Lagos', 550, FALSE, 120000, 'ICE No. 11 / Nigerian domestic price', 'Ex-Works Lafiagi; DDP Lagos', 'Domestic supply to BUA Lagos refinery (internal); direct sales to industrial buyers', 'Nigerian domestic market; BUA Sugar Refinery Lagos; food/beverage manufacturers', 'Primarily domestic; potential West Africa exports', 'BUA''s Lafiagi Sugar Company (LASUCO) is the most advanced integrated sugar complex in Nigeria. $300M+ investment; 20,000 ha estate. 10,000 TCD fully integrated: mill + ethanol plant + refinery + power plant (grid-connected). Africa Finance Corporation provided $200M investment in Dec 2021. Refining capacity: 220,000 MT/yr white sugar. BUA was allocated 386,000 MT import quota (2022); BIP compliance improving. Located adjacent to old Nigerian Sugar Company Bacita site (now KIA Group). BUA Foods Plc listed on Nigerian Stock Exchange (NGX). BUA also has major refined sugar operations in Apapa, Lagos.'),
  ('NGA-KWA-002', 'Nigerian Sugar Company (NSC) – Bacita Sugar Mill', 'KIA Africa Group Limited (acquired 2022–2024)', 'Nigeria', 'NGA', 'Bacita region – Kwara State (Niger River, Edu LGA, adjacent to Lafiagi)', 'sugarcane', 8.9000, 5.3833, 'limited_operations', 4500, 40000, 'Raw / Mill White Sugar', 'Raw Sugar, Mill White Sugar, Molasses', '600–1200', 'November', 'April', 'December, January, February', 'Apapa Port, Lagos (domestic supply only)', 550, FALSE, 25000, 'ICE No. 11 / Nigerian domestic price', 'Ex-Works Bacita', 'Domestic supply; BIP import quota (50,000 MT allocated 2022)', 'Nigerian domestic market; Lagos import refineries', 'Domestic only', 'Nigeria''s oldest sugar mill — established by federal government in 1961 with 40,000 MT installed capacity. Privatised 2004. Acquired by KIA Africa Group Limited (2022–2024); target of reaching 176,000 MT output. Currently limited_operations pending KIA rehabilitation investment. Located adjacent to BUA''s new Lafiagi LASUCO complex. 8,500 ha potential estate area; 4,500 TCD design capacity per NSDC data. BIP import quota allocation of 50,000 MT in 2022 is lowest of major operators, reflecting limited BIP progress.'),
  ('NGA-JIG-001', 'Jigawa Sugar Company – Hadejia Sugar Estate', 'Jigawa Sugar Company (state/private partnership)', 'Nigeria', 'NGA', 'Jigawa State – Hadejia River Basin (Hadejia LGA)', 'sugarcane', 12.4500, 10.0500, 'idle', 4000, 0, 'Raw Sugar', 'Raw Sugar (design); Molasses', '600–1200', NULL, NULL, NULL, 'Apapa Port, Lagos (domestic only when operational)', 1200, FALSE, 20000, 'ICE No. 11 / Nigerian domestic price', 'Ex-Works Hadejia', 'Domestic supply (when operational)', 'Nigerian domestic market', 'Domestic only', 'NSDC-listed potential/small-scale site. 7,000 ha potential area; 4,000 TCD design capacity per NSDC master plan. Located in Hadejia-Jama''are River Basin Development Authority (HJRBD) zone, Jigawa State. Currently idle — listed in NSDC records as needing development/rehabilitation investment. Region has security challenges (Boko Haram/banditry in wider NE Nigeria). Not part of the three main BIP operators (Dangote, BUA, FMN). Included for completeness as NSDC-registered site.')
ON CONFLICT (mill_name, country) DO UPDATE SET
  plant_id = EXCLUDED.plant_id,
  operator = EXCLUDED.operator,
  iso_code = EXCLUDED.iso_code,
  region = EXCLUDED.region,
  sugar_type = EXCLUDED.sugar_type,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  status = EXCLUDED.status,
  crushing_capacity_tcd = EXCLUDED.crushing_capacity_tcd,
  annual_output_tonnes = EXCLUDED.annual_output_tonnes,
  primary_grade = EXCLUDED.primary_grade,
  grades_available = EXCLUDED.grades_available,
  icumsa_range = EXCLUDED.icumsa_range,
  crushing_start = EXCLUDED.crushing_start,
  crushing_end = EXCLUDED.crushing_end,
  peak_months = EXCLUDED.peak_months,
  export_terminal = EXCLUDED.export_terminal,
  distance_to_port_km = EXCLUDED.distance_to_port_km,
  rail_access = EXCLUDED.rail_access,
  storage_capacity_tonnes = EXCLUDED.storage_capacity_tonnes,
  price_benchmark = EXCLUDED.price_benchmark,
  incoterms = EXCLUDED.incoterms,
  typical_contract = EXCLUDED.typical_contract,
  major_buyers = EXCLUDED.major_buyers,
  export_markets = EXCLUDED.export_markets,
  notes = EXCLUDED.notes,
  updated_at = NOW();
