-- ============================================================
-- Botswana Coal Mines — 3 Sites (full column-by-column INSERT)
-- Run AFTER COAL_MINES_TABLE_SETUP.sql
-- ============================================================

INSERT INTO public.coal_mines (
  mine_name,
  operator,
  license_number,
  contact_email,
  contact_phone,
  country,
  region,
  address,
  latitude,
  longitude,
  nearest_port,
  nearest_railway,
  founded_year,
  years_in_operation,
  original_owner,
  ownership_changes,
  major_milestones,
  notable_incidents,
  estimated_mine_life_remaining_years,
  coal_type,
  grade,
  calorific_value_kcal_kg,
  moisture_percent,
  ash_percent,
  sulfur_percent,
  size_mm,
  annual_capacity_tonnes,
  available_stock_tonnes,
  mining_method,
  price_per_tonne_usd,
  price_basis,
  minimum_order_tonnes,
  payment_terms,
  contract_types,
  loading_port,
  transport_modes,
  lead_time_days,
  export_license,
  certifications
) VALUES
(
  'Mmamabula Coalfield',
  'Jindal Steel and Power',
  NULL,
  NULL,
  NULL,
  'Botswana',
  'Central District',
  'Mmamabula, Central Botswana',
  -23.5946,
  26.5756,
  'Maputo Port, Mozambique (~900 km)',
  'Botswana Railway - Mahalapye Station',
  NULL,
  NULL,
  'CIC Energy',
  '[{"year": 2012, "previous_owner": "CIC Energy", "new_owner": "Jindal Steel and Power"}]'::jsonb,
  '[
    {"year": 2009, "event": "Contract signed with Shanghai Electric for Mmamabula Energy Project"},
    {"year": 2012, "event": "Jindal Steel and Power acquired CIC Energy for $116 million"}
  ]'::jsonb,
  '[]'::jsonb,
  30,
  'Sub-bituminous',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Surface and Underground',
  NULL,
  'FOB',
  NULL,
  NULL,
  'Long-term',
  'Maputo Port, Mozambique',
  '["Rail", "Truck"]'::jsonb,
  NULL,
  true,
  '[]'::jsonb
),
(
  'Morupule Coalfield',
  'Debswana (Botswana Government & De Beers)',
  NULL,
  NULL,
  NULL,
  'Botswana',
  'Central District',
  'Palapye, Central Botswana',
  -22.5071,
  27.0264,
  'Maputo Port, Mozambique (~700 km)',
  'Botswana Railway - Palapye Station',
  1971,
  54,
  'Bamangwato Concessions Ltd',
  '[{"year": 1971, "previous_owner": "Bamangwato Concessions Ltd", "new_owner": "Debswana"}]'::jsonb,
  '[
    {"year": 1971, "event": "Founded to supply the Bamangwato copper and nickel mine"},
    {"year": 1980, "event": "Mining lease extension granted"},
    {"year": 2008, "event": "Wash plant commissioned at 120 tonnes/hour capacity"}
  ]'::jsonb,
  '[]'::jsonb,
  NULL,
  'Sub-bituminous',
  'No. 1 Seam',
  5614,
  NULL,
  NULL,
  NULL,
  NULL,
  877000,
  NULL,
  'Underground (bord and pillar)',
  NULL,
  'FOB',
  NULL,
  NULL,
  'Long-term',
  'Maputo Port, Mozambique',
  '["Rail", "Truck"]'::jsonb,
  NULL,
  true,
  '[]'::jsonb
),
(
  'Sese Coalfield',
  'African Energy Resources / First Quantum Minerals (JV)',
  'Large-Scale Mining Licence (25-year)',
  NULL,
  NULL,
  'Botswana',
  'Central District (near Francistown)',
  'Sese, North-East Botswana',
  -21.5855,
  27.2109,
  'Maputo Port, Mozambique (~600 km)',
  'Botswana Railway - Francistown Station',
  NULL,
  NULL,
  'African Energy Resources',
  '[]'::jsonb,
  '[
    {"year": 2017, "event": "Government granted tax holiday to First Quantum Minerals and African Energy Resources"},
    {"year": 2018, "event": "ESIA updated to include up to 500 MW power generation"},
    {"year": 2020, "event": "Generation licence awarded for 225 MW by Botswana Energy Regulatory Authority"},
    {"year": 2021, "event": "Large-scale mining licence secured for 51 km² containing 650Mt of coal resources"}
  ]'::jsonb,
  '[]'::jsonb,
  30,
  'Sub-bituminous / Coking coal',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Surface',
  NULL,
  'FOB',
  NULL,
  NULL,
  'Long-term',
  'Maputo Port, Mozambique',
  '["Rail", "Truck"]'::jsonb,
  NULL,
  true,
  '["ESIA approved", "Water extraction rights (Shashe Dam)", "50-year Land Lease"]'::jsonb
)
ON CONFLICT (mine_name, country) DO UPDATE SET
  operator = EXCLUDED.operator,
  license_number = EXCLUDED.license_number,
  contact_email = EXCLUDED.contact_email,
  contact_phone = EXCLUDED.contact_phone,
  region = EXCLUDED.region,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  nearest_port = EXCLUDED.nearest_port,
  nearest_railway = EXCLUDED.nearest_railway,
  founded_year = EXCLUDED.founded_year,
  years_in_operation = EXCLUDED.years_in_operation,
  original_owner = EXCLUDED.original_owner,
  ownership_changes = EXCLUDED.ownership_changes,
  major_milestones = EXCLUDED.major_milestones,
  notable_incidents = EXCLUDED.notable_incidents,
  estimated_mine_life_remaining_years = EXCLUDED.estimated_mine_life_remaining_years,
  coal_type = EXCLUDED.coal_type,
  grade = EXCLUDED.grade,
  calorific_value_kcal_kg = EXCLUDED.calorific_value_kcal_kg,
  moisture_percent = EXCLUDED.moisture_percent,
  ash_percent = EXCLUDED.ash_percent,
  sulfur_percent = EXCLUDED.sulfur_percent,
  size_mm = EXCLUDED.size_mm,
  annual_capacity_tonnes = EXCLUDED.annual_capacity_tonnes,
  available_stock_tonnes = EXCLUDED.available_stock_tonnes,
  mining_method = EXCLUDED.mining_method,
  price_per_tonne_usd = EXCLUDED.price_per_tonne_usd,
  price_basis = EXCLUDED.price_basis,
  minimum_order_tonnes = EXCLUDED.minimum_order_tonnes,
  payment_terms = EXCLUDED.payment_terms,
  contract_types = EXCLUDED.contract_types,
  loading_port = EXCLUDED.loading_port,
  transport_modes = EXCLUDED.transport_modes,
  lead_time_days = EXCLUDED.lead_time_days,
  export_license = EXCLUDED.export_license,
  certifications = EXCLUDED.certifications,
  updated_at = NOW();
