-- ============================================================
-- Thailand Oil Production Sites — 15 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- GULF OF THAILAND (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tantawan Field', 'PTTEP', 'Gulf of Thailand — Block B5', NULL, 'Energy', 'Crude Oil', 11.5000, 101.5000, 'Thailand', 'Gulf of Thailand', 'Rayong', 'oil_field', 'operational', 'PTTEP', 'state_owned', 42.00, 0.05, 240000, 80000000, 240000, '{"start_year":1997,"production_bpd":8000,"quality":"Light sweet","note":"Block B5","last_transaction":"PTTEP assumed full ownership ~2010","contract_duration":"PSC to 2027","pipelines":"Tantawan → FSO → tanker export → Map Ta Phut refinery","ports":"Map Ta Phut (Rayong) via FSO tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Benchamas Field', 'PTTEP', 'Gulf of Thailand — Block B5', NULL, 'Energy', 'Crude Oil', 11.3333, 101.6667, 'Thailand', 'Gulf of Thailand', 'Rayong', 'oil_field', 'operational', 'PTTEP', 'state_owned', 41.00, 0.05, 150000, 50000000, 150000, '{"start_year":2002,"production_bpd":5000,"quality":"Light sweet","note":"Block B5","contract_duration":"PSC to 2027","pipelines":"Benchamas → Tantawan FSO → tanker export","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jasmine Field', 'Mubadala Petroleum + PTTEP', 'Gulf of Thailand — Block B5/B9', NULL, 'Energy', 'Crude Oil', 11.1667, 101.8333, 'Thailand', 'Gulf of Thailand', 'Rayong', 'oil_field', 'operational', 'Mubadala Petroleum + PTTEP', 'joint_venture', 40.00, 0.04, 300000, 80000000, 300000, '{"start_year":2010,"production_bpd":10000,"quality":"Light sweet","note":"Mubadala 45%, PTTEP 55%","last_transaction":"Mubadala entry 2014 ($200M acquisition from Pearl Oil)","contract_duration":"PSC to 2031","pipelines":"Jasmine → FSO Benchamas II → tanker export","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Nang Nuan Field', 'Mubadala Petroleum + PTTEP', 'Gulf of Thailand — Block B9A', NULL, 'Energy', 'Crude Oil', 10.9167, 102.0000, 'Thailand', 'Gulf of Thailand', 'Rayong', 'oil_field', 'operational', 'Mubadala Petroleum + PTTEP', 'joint_venture', 39.00, 0.05, 180000, 40000000, 180000, '{"start_year":2013,"production_bpd":6000,"quality":"Light sweet","note":"Mubadala 45%, PTTEP 55%","last_transaction":"Mubadala acquisition ~2014","contract_duration":"PSC to 2031","pipelines":"Nang Nuan → Jasmine FSO → tanker export","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Trat Field', 'PTTEP', 'Gulf of Thailand — Block G4/43', NULL, 'Energy', 'Crude Oil', 11.0000, 103.0000, 'Thailand', 'Gulf of Thailand', 'Trat', 'oil_field', 'operational', 'PTTEP', 'state_owned', 38.00, 0.05, 240000, 60000000, 240000, '{"start_year":1999,"production_bpd":8000,"quality":"Light sweet","note":"Block G4/43","last_transaction":"PTTEP full ownership ~2010","contract_duration":"PSC to 2028","pipelines":"Trat → FSO → tanker export → Map Ta Phut","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Manora Field', 'Mubadala Petroleum + PTTEP', 'Gulf of Thailand — Block G1/48', NULL, 'Energy', 'Crude Oil', 9.5833, 100.3333, 'Thailand', 'Gulf of Thailand', 'Nakhon Si Thammarat', 'oil_field', 'operational', 'Mubadala Petroleum + PTTEP', 'joint_venture', 37.00, 0.06, 90000, 20000000, 90000, '{"start_year":2014,"production_bpd":3000,"quality":"Light sweet","note":"Mubadala 75%, PTTEP 25%","last_transaction":"Tap Oil sold to Mubadala ~2015 for ~$45M","contract_duration":"PSC to 2033","pipelines":"Manora FSO → tanker export (no pipeline)","ports":"Khanom / Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wassana Field', 'PTTEP', 'Gulf of Thailand — Block G6/27', NULL, 'Energy', 'Crude Oil', 9.8333, 101.3333, 'Thailand', 'Gulf of Thailand', 'Surat Thani', 'oil_field', 'operational', 'PTTEP', 'state_owned', 34.00, 0.10, 90000, 25000000, 90000, '{"start_year":2016,"production_bpd":3000,"quality":"Medium light","note":"Thailand''s first FPSO-based oil development; acquired from KrisEnergy 2020","last_transaction":"KrisEnergy liquidation 2020; PTTEP acquired ~$50M","contract_duration":"PSC to 2034","pipelines":"Wassana FPSO → tanker export","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Apus Field', 'PTTEP', 'Gulf of Thailand — Block B8/38', NULL, 'Energy', 'Crude Oil', 10.5000, 101.5000, 'Thailand', 'Gulf of Thailand', 'Rayong', 'oil_field', 'operational', 'PTTEP', 'state_owned', 38.00, 0.05, 105000, 25000000, 105000, '{"start_year":2015,"production_bpd":3500,"quality":"Light sweet","note":"Block B8/38","contract_duration":"PSC to 2035","pipelines":"Apus → FSO → tanker → Map Ta Phut","ports":"Map Ta Phut via tanker","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kaphong Field', 'PTTEP', 'Gulf of Thailand — Block G1/61', NULL, 'Energy', 'Crude Oil', 9.3333, 100.5000, 'Thailand', 'Gulf of Thailand', 'Nakhon Si Thammarat', 'oil_field', 'operational', 'PTTEP', 'state_owned', 36.00, 0.07, 75000, 15000000, 75000, '{"start_year":2008,"production_bpd":2500,"quality":"Light sweet","note":"Acquired from KrisEnergy 2020","last_transaction":"KrisEnergy liquidation 2020; PTTEP acquired Thailand portfolio ~$50M bundle","contract_duration":"PSC to 2032","pipelines":"Kaphong → Khanom nearshore terminal (short pipeline, ~30km)","ports":"Khanom terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ONSHORE THAILAND
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sirikit Field', 'PTTEP', 'Kamphaeng Phet / Phitsanulok — Central Plains', NULL, 'Energy', 'Crude Oil', 16.1833, 100.0500, 'Thailand', 'Central Plains', 'Phitsanulok', 'oil_field', 'operational', 'PTTEP', 'state_owned', 37.00, 0.05, 600000, 200000000, 600000, '{"start_year":1983,"production_bpd":20000,"quality":"Light sweet","note":"Thailand''s largest onshore oil field; L13/48 + L15/43 blocks","last_transaction":"Chevron exited 2021; PTTEP acquired for ~$480M — end of Chevron''s 50-year Thailand presence","contract_duration":"PSC to 2041","pipelines":"Sirikit → Lang Suan crude pipeline (~300km) → Map Ta Phut Rayong refinery complex","ports":"Map Ta Phut Industrial Estate (Rayong) via pipeline","rail":"Phitsanulok–Bangkok rail line (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pratu Tao Field', 'PTTEP', 'Phitsanulok Basin — L15/43', NULL, 'Energy', 'Crude Oil', 16.3333, 100.3333, 'Thailand', 'Central Plains', 'Phitsanulok', 'oil_field', 'operational', 'PTTEP', 'state_owned', 36.00, 0.06, 90000, 25000000, 90000, '{"start_year":1988,"production_bpd":3000,"quality":"Light sweet","note":"Sirikit satellite field","last_transaction":"Transferred with Chevron exit package 2021","contract_duration":"PSC to 2041","pipelines":"Pratu Tao → Sirikit gathering → Map Ta Phut pipeline","ports":"Map Ta Phut via Sirikit pipeline","rail":"Phitsanulok rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wichian Buri Field', 'PTTEP', 'Phetchabun Province — L33/43', NULL, 'Energy', 'Crude Oil', 15.6500, 101.1167, 'Thailand', 'Central Plains', 'Phetchabun', 'oil_field', 'operational', 'PTTEP', 'state_owned', 38.00, 0.04, 150000, 50000000, 150000, '{"start_year":1996,"production_bpd":5000,"quality":"Light sweet","note":"L33/43","contract_duration":"PSC to 2033","pipelines":"Wichian Buri → Sirikit gathering → Map Ta Phut","ports":"Map Ta Phut","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Si Thep Field', 'PTTEP', 'Phetchabun Province — L33/43', NULL, 'Energy', 'Crude Oil', 15.5000, 101.0000, 'Thailand', 'Central Plains', 'Phetchabun', 'oil_field', 'operational', 'PTTEP', 'state_owned', 37.00, 0.05, 105000, 30000000, 105000, '{"start_year":2001,"production_bpd":3500,"quality":"Light sweet","note":"L33/43","contract_duration":"PSC to 2033","pipelines":"Si Thep → Wichian Buri → Map Ta Phut","ports":"Map Ta Phut","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Nong Yao Field', 'PTTEP', 'Chai Nat Province — L44/43', NULL, 'Energy', 'Crude Oil', 15.1667, 100.5000, 'Thailand', 'Central Plains', 'Chai Nat', 'oil_field', 'operational', 'PTTEP', 'state_owned', 36.00, 0.06, 45000, 12000000, 45000, '{"start_year":2006,"production_bpd":1500,"quality":"Light sweet","note":"L44/43","contract_duration":"PSC to 2030","pipelines":"Nong Yao → Sirikit gathering → Map Ta Phut","ports":"Map Ta Phut","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Fang Oilfield', 'PTT (Thailand Oil Co.)', 'Chiang Mai Province — Northern Thailand', NULL, 'Energy', 'Crude Oil', 19.9167, 99.2167, 'Thailand', 'Northern Thailand', 'Chiang Mai', 'oil_field', 'operational', 'PTT', 'state_owned', 40.00, 0.08, 15000, 5000000, 15000, '{"start_year":1955,"production_bpd":500,"quality":"Light sweet","note":"Thailand''s oldest producing oilfield; discovery 1921; very mature","contract_duration":"State concession perpetual","pipelines":"Fang → Chiang Mai by road tanker (too small for pipeline)","ports":"None direct (northern Thailand landlocked)","rail":"Chiang Mai–Bangkok rail line (nearby)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Thailand' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Thailand' AND commodity_name = 'Crude Oil' ORDER BY region, title;
