-- ============================================================
-- Austria Oil Production Sites — 12 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- VIENNA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Matzen Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.4167, 16.7500, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 34.00, 0.80, 240000, 50000000, 240000, '{"start_year":1949,"production_bpd":8000,"quality":"Medium light — Vienna Basin crude","note":"Largest Austrian field; Europe''s most productive onshore oil basin per km²; discovered 1938; peak ~60,000 bpd (1955)","last_transaction":"OMV listed Vienna Stock Exchange; Austrian government ~31.5% via ÖBIB","contract_duration":"OMV federal mining concession (Bergbauberechtigungen)","pipelines":"Matzen → Schwechat refinery (~40km); Matzen → TAL pipeline (Trans-Alpine); OMV Vienna Basin gathering","ports":"None direct (landlocked); crude exported via pipeline to Germany/Italy","rail":"Vienna–Gänserndorf rail line (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Prottes Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.3667, 16.6500, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 33.00, NULL, 45000, 10000000, 45000, '{"start_year":1951,"production_bpd":1500,"quality":"Medium light","note":"Mature","contract_duration":"Federal mining concession","pipelines":"Prottes → Matzen → Schwechat gathering","ports":"None","rail":"Gänserndorf rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zistersdorf Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.5333, 16.7667, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 32.00, NULL, 15000, 5000000, 15000, '{"start_year":1930,"production_bpd":500,"quality":"Medium","note":"Austria''s first commercial oil field; very mature; Austrian Naphtha Company; WWII strategic for German Reich","contract_duration":"Federal mining concession","pipelines":"Zistersdorf → Matzen gathering → Schwechat","ports":"None","rail":"Zistersdorf–Gänserndorf rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Schönkirchen-Reyersdorf Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.3333, 16.5833, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 34.00, NULL, 36000, NULL, 36000, '{"start_year":1953,"production_bpd":1200,"quality":"Medium light","contract_duration":"Federal mining concession","pipelines":"Schönkirchen → Matzen → Schwechat","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Aderklaa Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.2833, 16.5667, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 33.00, NULL, 24000, NULL, 24000, '{"start_year":1955,"production_bpd":800,"quality":"Medium","note":"Mature","contract_duration":"Federal mining concession","pipelines":"Aderklaa → Vienna Basin gathering → Schwechat","ports":"None","rail":"Vienna Airport nearby (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Obersiebenbrunn Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.2167, 16.7833, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 33.00, NULL, 18000, NULL, 18000, '{"start_year":1958,"production_bpd":600,"quality":"Medium light","contract_duration":"Federal mining concession","pipelines":"Obersiebenbrunn → Matzen gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Spannberg Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.4500, 16.8333, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 34.00, NULL, 21000, NULL, 21000, '{"start_year":1959,"production_bpd":700,"quality":"Medium light","contract_duration":"Federal mining concession","pipelines":"Spannberg → Matzen → Schwechat","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mühlberg Field', 'OMV', 'Lower Austria — Vienna Basin', NULL, 'Energy', 'Crude Oil', 48.3833, 16.9167, 'Austria', 'Vienna Basin', 'Gänserndorf', 'oil_field', 'operational', 'OMV', 'public', 32.00, NULL, 15000, NULL, 15000, '{"start_year":1961,"production_bpd":500,"quality":"Medium","contract_duration":"Federal mining concession","pipelines":"Mühlberg → Vienna Basin gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- MOLASSE BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Voitsdorf Field', 'RAG Austria', 'Upper Austria — Molasse Basin', NULL, 'Energy', 'Crude Oil', 47.9667, 14.0833, 'Austria', 'Molasse Basin', 'Linz', 'oil_field', 'operational', 'RAG Austria', 'private', 36.00, NULL, 30000, 20000000, 30000, '{"start_year":1956,"production_bpd":1000,"quality":"Light sweet","note":"Oil + gas; RAG Austria (Energie AG Oberösterreich + EDF + others); OMV divested RAG 2007","last_transaction":"OMV sold RAG Austria to consortium 2007 for ~€800M","contract_duration":"Austrian federal mining license","pipelines":"Voitsdorf → Linz refinery pipeline","ports":"None","rail":"Linz rail hub (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Edt-Fraham Field', 'RAG Austria', 'Upper Austria — Molasse Basin', NULL, 'Energy', 'Crude Oil', 48.0333, 13.9167, 'Austria', 'Molasse Basin', 'Linz', 'oil_field', 'operational', 'RAG Austria', 'private', 35.00, NULL, 18000, NULL, 18000, '{"start_year":1962,"production_bpd":600,"quality":"Light sweet","contract_duration":"Federal mining license","pipelines":"Edt-Fraham → Upper Austria gathering → Linz","ports":"None","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Geinberg Field', 'RAG Austria', 'Upper Austria — Molasse Basin', NULL, 'Energy', 'Crude Oil', 48.2167, 13.4833, 'Austria', 'Molasse Basin', 'Linz', 'oil_field', 'operational', 'RAG Austria', 'private', 34.00, NULL, 12000, NULL, 12000, '{"start_year":1971,"production_bpd":400,"quality":"Medium light","note":"Smaller field","contract_duration":"Federal mining license","pipelines":"Geinberg → Upper Austria gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Taufkirchen Field', 'RAG Austria + Genol', 'Bavaria border area — Molasse Basin, Austrian side', NULL, 'Energy', 'Crude Oil', 48.0667, 13.7500, 'Austria', 'Molasse Basin', 'Linz', 'oil_field', 'operational', 'RAG Austria + Genol', 'joint_venture', 35.00, NULL, 15000, NULL, 15000, '{"start_year":1968,"production_bpd":500,"quality":"Light","note":"RAG Austria 50%, Genol 50%","contract_duration":"Federal mining license","pipelines":"Taufkirchen → Molasse gathering → Austria pipeline network","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Austria' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Austria' AND commodity_name = 'Crude Oil' ORDER BY region, title;
