-- ============================================================
-- South Africa Sugar Mills — 12 mills (sugar_plants)
-- Run SUGAR_PLANTS_TABLE_SETUP.sql first. Then run this in Supabase SQL Editor.
-- KwaZulu-Natal: 10 | Mpumalanga: 2
-- ============================================================

INSERT INTO public.sugar_plants (
  plant_id,
  mill_name,
  operator,
  country,
  iso_code,
  region,
  sugar_type,
  latitude,
  longitude,
  status,
  crushing_capacity_tcd,
  annual_output_tonnes,
  primary_grade,
  grades_available,
  icumsa_range,
  crushing_start,
  crushing_end,
  peak_months,
  export_terminal,
  distance_to_port_km,
  rail_access,
  storage_capacity_tonnes,
  price_benchmark,
  incoterms,
  typical_contract,
  major_buyers,
  export_markets,
  notes
) VALUES
  ('ZAF-KZN-001', 'Sezela Sugar Mill', 'Illovo Sugar (South Africa) Pty Ltd / ABF Sugar', 'South Africa', 'ZAF', 'KwaZulu-Natal South Coast (Sezela, Scottburgh area)', 'sugarcane', -30.3667, 30.6500, 'operational', 19000, 250000, 'Raw Sugar / Refined Specialty', 'Raw Sugar (VHP), Refined White Sugar, Specialty Sugars, Furfural (20,000 t/yr), Furfuryl Alcohol, Ethyl Alcohol, Molasses, Bagasse', '45–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 65, TRUE, 180000, 'ICE No. 11 / SASA Recoverable Value (RV) price', 'FOB Durban', 'SACU domestic; FOB Durban world market; US TRQ; SACUM-UK EPA', 'SACU domestic; EU buyers; UK buyers (SACUM-UK EPA); US refiners (TRQ); world market', 'SACU (~70%); EU, UK, USA, world market', 'Illovo''s largest South African mill. Opened 1915 (Reynolds Brothers). Processes ~2.37 million t cane/year. World-class bio-refinery: produces 20,000 t/yr furfural from bagasse hemicellulose — one of world''s most advanced furfural operations.'),
  ('ZAF-KZN-002', 'Eston Sugar Mill', 'Illovo Sugar (South Africa) Pty Ltd / ABF Sugar', 'South Africa', 'ZAF', 'KwaZulu-Natal Midlands / South (Eston, Umbumbulu area)', 'sugarcane', -29.8833, 30.5667, 'operational', 11000, 135000, 'Raw Sugar', 'Raw Sugar (VHP), Molasses, Bagasse', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 50, TRUE, 90000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market', 'SACU domestic; world market via Durban terminal', 'SACU (~70%); world market', 'Processes ~1.35 million t cane/year. KZN Midlands rainfed dryland cane area. Raw sugar mill, no on-site refinery; raw sugar routes to Durban terminal for export or Durban standalone refinery.'),
  ('ZAF-KZN-003', 'Noodsberg Sugar Mill', 'Illovo Sugar (South Africa) Pty Ltd / ABF Sugar', 'South Africa', 'ZAF', 'KwaZulu-Natal Midlands (Noodsberg, New Hanover area)', 'sugarcane', -29.3667, 30.5500, 'operational', 13000, 155000, 'Raw Sugar / Specialty', 'Raw Sugar, Specialty Sugars, Syrup products, Molasses, Bagasse', '300–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 80, TRUE, 110000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market', 'SACU domestic market; world market', 'SACU (~70%); world market', 'Processes ~1.48 million t cane/year. KZN Midlands rainfed area. Illovo SA produces specialty sugars (syrups, amber sugars) alongside raw sugar at this site.'),
  ('ZAF-KZN-004', 'UCL Sugar Mill (Umzimkulu / Sezela area)', 'UCL Company (Pty) Ltd', 'South Africa', 'ZAF', 'KwaZulu-Natal South Coast (Umzimkulu / Harding area)', 'sugarcane', -30.2833, 29.9667, 'operational', 7500, 85000, 'Raw Sugar', 'Raw Sugar (VHP), Molasses, Bagasse', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 120, TRUE, 60000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market', 'SACU domestic; world market via Durban terminal', 'SACU (~70%); world market', 'UCL Company is a relatively small independent miller on KZN South Coast. Raw sugar only — no refinery. Raw sugar output routes to Durban terminal.'),
  ('ZAF-KZN-005', 'Maidstone Sugar Mill', 'Tongaat Hulett Sugar Ltd (under business rescue; SEP: Kagara Sugar Ltd, Tanzania)', 'South Africa', 'ZAF', 'KwaZulu-Natal North Coast (Maidstone / Tongaat, near Durban)', 'sugarcane', -29.5667, 31.1167, 'limited_operations', 10000, 115000, 'Raw Sugar', 'Raw Sugar (VHP), Molasses, Bagasse; refined sugar via Durban central refinery', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 35, TRUE, 80000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market; UK EPA', 'SACU domestic (Huletts brand via Durban refinery); world market', 'SACU (~70%); EU, UK, USA, world market', 'KZN North Coast. Earliest mill in KZN (1903). Tongaat Hulett entered voluntary business rescue Oct 2022; Kagara Sugar Ltd (Tanzania) selected as strategic equity partner (SEP) July 2023. Operations continued during restructuring but flagged limited_operations due to financial uncertainty and grower payment defaults.'),
  ('ZAF-KZN-006', 'Amatikulu Sugar Mill', 'Tongaat Hulett Sugar Ltd (under business rescue; SEP: Kagara Sugar Ltd)', 'South Africa', 'ZAF', 'KwaZulu-Natal North Coast (Amatikulu, KwaDukuza LM)', 'sugarcane', -29.0500, 31.5333, 'limited_operations', 8500, 95000, 'Raw Sugar', 'Raw Sugar (VHP), Molasses, Bagasse', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 100, TRUE, 65000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market', 'SACU domestic; world market', 'SACU (~70%); world market', 'Opened 1907. KZN North Coast rainfed zone. Part of Tongaat Hulett''s 3-mill SA portfolio (Maidstone, Amatikulu, Felixton). Raw sugar routes to Tongaat Hulett''s central Durban refinery (Huletts brand).'),
  ('ZAF-KZN-007', 'Felixton Sugar Mill', 'Tongaat Hulett Sugar Ltd (under business rescue; SEP: Kagara Sugar Ltd)', 'South Africa', 'ZAF', 'KwaZulu-Natal North Coast (Felixton / Empangeni, uMhlatuze LM)', 'sugarcane', -28.7667, 31.8833, 'limited_operations', 13000, 165000, 'Raw Sugar', 'Raw Sugar (VHP), Molasses, Bagasse; refined via Durban refinery', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 170, TRUE, 115000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market', 'SACU domestic; world market', 'SACU (~70%); world market', 'Tongaat Hulett''s largest mill. KZN North Coast rainfed zone. Together Tongaat''s three mills crush over 4.8 million t cane/year.'),
  ('ZAF-KZN-008', 'Gledhow Sugar Mill', 'Gledhow Sugar Company (Pty) Ltd — in business rescue since March 2023', 'South Africa', 'ZAF', 'KwaZulu-Natal North Coast (Gledhow / Stanger / KwaDukuza area)', 'sugarcane', -29.3333, 31.2667, 'limited_operations', 7000, 70000, 'Refined White Sugar (EC2)', 'Refined White Sugar (EC2, 35 t/hr refinery), Raw Sugar, Molasses, Bagasse', '45–600', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 70, TRUE, 50000, 'ICE No. 5 (refined) / ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic (refined); FOB Durban world market', 'SACU domestic refined sugar; world market', 'SACU (~70%); world market', 'Gledhow Sugar Company is a ''white-end'' mill (on-site 35 t/hr refinery producing EC2 refined white sugar). Entered business rescue March 2023. Operations continued through restructuring but financial stability uncertain.'),
  ('ZAF-KZN-009', 'Umfolozi Sugar Mill', 'Umfolozi Sugar Mill (Pty) Ltd — independent grower-owned cooperative', 'South Africa', 'ZAF', 'KwaZulu-Natal North Coast (Umfolozi flats, uMhlatuze / Mtubatuba area)', 'sugarcane', -28.5667, 32.0667, 'operational', 9500, 120000, 'VHP Brown Sugar', 'VHP Brown Sugar, Raw Sugar, Molasses', '600–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 185, TRUE, 85000, 'ICE No. 11 / SASA RV price', 'FOB Durban', 'SACU domestic; FOB Durban world market; SACU regional', 'SACU domestic; world market via Durban terminal; regional Africa', 'SACU (~70%); world market VHP brown sugar', 'Independent grower-cooperative mill; BEE transformation achieved 2009. Located in Umfolozi flats — unique narrow-gauge rail system for cane extraction from wetlands. Produces high-quality VHP brown sugar for domestic and export.'),
  ('ZAF-MPU-001', 'Malelane Sugar Mill + Refinery (RCL Foods / Selati)', 'RCL Foods Sugar & Milling (Pty) Ltd (formerly TSB Sugar RSA Ltd; owned by Remgro via RCL)', 'South Africa', 'ZAF', 'Mpumalanga Lowveld (Malelane, Nkomazi LM — Komati Valley)', 'sugarcane', -25.4833, 31.5333, 'operational', 14500, 320000, 'Refined White Sugar / Specialty', 'Refined White Sugar (Selati brand), Special Sugars, Raw Sugar, Molasses, Animal Feed (Molatek), Bagasse', '45–1200', 'March', 'December', 'May, June, July, August', 'Port of Maputo, Mozambique (balance of raw sugar from Komati) / Durban Sugar Terminal', 85, TRUE, 220000, 'ICE No. 5 (refined) / ICE No. 11; SACUM-UK EPA', 'FOB Maputo; FOB Durban', 'SACU domestic (Selati brand primary); FOB Maputo/Durban export', 'SACU domestic (Selati #1 SA brand); UK buyers (EPA); US TRQ; world market', 'SACU (~70%); UK (SACUM-UK EPA, 13% of SA exports in MY 2022/23); USA (TRQ); world market', 'RCL''s white-end flagship refinery — Selati, South Africa''s #1 selling sugar brand. 1.9 million t/yr cane capacity. Mpumalanga is 100% irrigated (centre-pivots, canal system). RCL total production capacity: ~720,000 t/yr across 3 mills.'),
  ('ZAF-MPU-002', 'Komati Sugar Mill (RCL Foods / Selati)', 'RCL Foods Sugar & Milling (Pty) Ltd', 'South Africa', 'ZAF', 'Mpumalanga Lowveld (Komatipoort / Nkomazi LM — near Mozambique border)', 'sugarcane', -25.5333, 32.0167, 'operational', 19000, 320000, 'VHP Raw Sugar', 'VHP Raw Sugar, Molasses, Bagasse', '600–1200', 'March', 'December', 'May, June, July, August', 'Port of Maputo, Mozambique (balance export) / via Malelane refinery (internal)', 60, TRUE, 200000, 'ICE No. 11 / SASA RV price', 'FOB Maputo', 'Internal transfer to Malelane refinery; balance FOB Maputo export', 'Internal (Malelane refinery) + world market via Maputo', 'World market (VHP raw sugar FOB Maputo); balance refined via Malelane', 'Most modern mill in South Africa — commissioned 1994. 2.6 million t cane crushed per 38-week season at ~500 t/hr. Recognized as most cost-efficient mill in southern Africa. 100% irrigated using centre pivots and canal system fed by Komati and Lomati Rivers.'),
  ('ZAF-KZN-010', 'Pongola Sugar Mill (RCL Foods / Selati)', 'RCL Foods Sugar & Milling (Pty) Ltd', 'South Africa', 'ZAF', 'Pongola region – KwaZulu-Natal North (Pongola, uPhongolo LM)', 'sugarcane', -27.3833, 31.6167, 'operational', 10500, 140000, 'Raw Sugar / Refined', 'Raw Sugar (VHP), Refined White Sugar, Molasses, Bagasse', '45–1200', 'April', 'December', 'June, July, August', 'Durban Sugar Terminal (Maydon Wharf)', 280, TRUE, 95000, 'ICE No. 11 / ICE No. 5 (refined) / SASA RV price', 'FOB Durban', 'SACU domestic (Selati); FOB Durban world market', 'SACU domestic (Selati brand); world market', 'SACU (~70%); world market', 'Established 1954; acquired by RCL Foods (then TSB Sugar) in 2009. Normal 39-week crop capacity: 1.4 million t cane. Pongola area irrigated. Has refinery on-site. RCL group total SA capacity: ~720,000 t/yr.')
ON CONFLICT (mill_name, country) DO UPDATE SET
  plant_id = EXCLUDED.plant_id,
  operator = EXCLUDED.operator,
  iso_code = EXCLUDED.iso_code,
  region = EXCLUDED.region,
  sugar_type = EXCLUDED.sugar_type,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  status = EXCLUDED.status,
  crushing_capacity_tcd = EXCLUDED.crushing_capacity_tcd,
  annual_output_tonnes = EXCLUDED.annual_output_tonnes,
  primary_grade = EXCLUDED.primary_grade,
  grades_available = EXCLUDED.grades_available,
  icumsa_range = EXCLUDED.icumsa_range,
  crushing_start = EXCLUDED.crushing_start,
  crushing_end = EXCLUDED.crushing_end,
  peak_months = EXCLUDED.peak_months,
  export_terminal = EXCLUDED.export_terminal,
  distance_to_port_km = EXCLUDED.distance_to_port_km,
  rail_access = EXCLUDED.rail_access,
  storage_capacity_tonnes = EXCLUDED.storage_capacity_tonnes,
  price_benchmark = EXCLUDED.price_benchmark,
  incoterms = EXCLUDED.incoterms,
  typical_contract = EXCLUDED.typical_contract,
  major_buyers = EXCLUDED.major_buyers,
  export_markets = EXCLUDED.export_markets,
  notes = EXCLUDED.notes,
  updated_at = NOW();
