-- ============================================================
-- Ukraine Oil Production Sites — 16 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- BLACK SEA (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Subbotina Field', 'Chornomornaftogaz (Ukraine)', 'Black Sea — offshore Odesa region', NULL, 'Energy', 'Crude Oil', 45.5833, 31.5833, 'Ukraine', 'Black Sea', 'Odesa', 'oil_field', 'inactive', 'Chornomornaftogaz', 'state_owned', 37.00, NULL, 0, NULL, 0, '{"start_year":2012,"production_bpd":0,"quality":"Light sweet","note":"Seized — Russia occupied Ukrainian Black Sea platforms Feb–Mar 2022; ~1,000 bpd pre-war; Boyko Towers seized; ICC arbitration filed by Ukraine vs Russia (~$10B damages claimed)","last_transaction":"Russia seized Boyko Towers and offshore platforms February 2022","contract_duration":"Ukrainian state; Russia de facto post-2022","pipelines":"Planned → Odesa offshore terminal (inactive)","ports":"Odesa (inactive — Black Sea blockaded 2022–2023)","rail":"None offshore"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Odeska Field', 'Chornomornaftogaz (Ukraine)', 'Black Sea — Odesa shelf', NULL, 'Energy', 'Crude Oil', 45.7500, 31.3333, 'Ukraine', 'Black Sea', 'Odesa', 'oil_field', 'inactive', 'Chornomornaftogaz', 'state_owned', 36.00, NULL, 0, NULL, 0, '{"start_year":2011,"production_bpd":0,"quality":"Light sweet","note":"Seized by Russia 2022; ~500 bpd pre-war; Ukraine legally; Russia occupied","contract_duration":"Ukrainian state; Russia occupied","pipelines":"None operational","ports":"Odesa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Herodot Field', 'NAK Naftogaz Ukraine', 'Black Sea — deeper water exploration', NULL, 'Energy', 'Crude Oil', 44.8333, 32.0000, 'Ukraine', 'Black Sea', 'Odesa', 'oil_field', 'inactive', 'Naftogaz', 'state_owned', NULL, NULL, 0, 500000000, 0, '{"start_year":2014,"production_bpd":0,"quality":"TBD","note":"Exploration suspended (conflict); ~500M bbl potential; Naftogaz 100%","contract_duration":"Ukrainian state","pipelines":"None","ports":"Odesa (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- DNIPRO-DONETSK BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lelyakivske Field', 'Ukrnafta', 'Chernihiv Oblast — northern Dnipro-Donetsk', NULL, 'Energy', 'Crude Oil', 51.1667, 32.5000, 'Ukraine', 'Dnipro-Donetsk Basin', 'Nizhyn', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 38.00, 0.30, 90000, 50000000, 90000, '{"start_year":1975,"production_bpd":3000,"quality":"Light sweet","note":"Ukrainian government-controlled area; Ukrnafta 50%+ (Naftogaz majority; Kolomoisky Privat Group historical minority); state control reasserted; Kolomoisky sanctioned 2023","last_transaction":"Government-Kolomoisky dispute over Ukrnafta 2015–2022","contract_duration":"Ukrainian subsoil use license","pipelines":"Dnipro-Donetsk fields → Kremenchuk refinery; → Odesa pipeline","ports":"Odesa (via pipeline — export route disrupted by war)","rail":"Nizhyn–Kyiv rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gnidyntsivske Field', 'Ukrnafta', 'Chernihiv Oblast', NULL, 'Energy', 'Crude Oil', 51.0833, 32.6667, 'Ukraine', 'Dnipro-Donetsk Basin', 'Nizhyn', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 37.00, NULL, 60000, NULL, 60000, '{"start_year":1971,"production_bpd":2000,"quality":"Light sweet","note":"Ukrnafta","contract_duration":"Ukrainian subsoil license","pipelines":"Chernihiv cluster → Kremenchuk pipeline","ports":"Odesa (indirect)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Prylutske Field', 'Ukrnafta', 'Chernihiv Oblast', NULL, 'Energy', 'Crude Oil', 50.5833, 32.3833, 'Ukraine', 'Dnipro-Donetsk Basin', 'Pryluky', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 38.00, NULL, 45000, NULL, 45000, '{"start_year":1977,"production_bpd":1500,"quality":"Light sweet","note":"Ukrnafta","contract_duration":"Ukrainian subsoil license","pipelines":"→ Kremenchuk","ports":"Odesa","rail":"Pryluky–Kyiv rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rybalske Field', 'Ukrnafta + JKX Oil & Gas', 'Poltava Oblast — central Dnipro-Donetsk', NULL, 'Energy', 'Crude Oil', 49.8333, 33.8333, 'Ukraine', 'Dnipro-Donetsk Basin', 'Poltava', 'oil_field', 'operational', 'Ukrnafta', 'joint_venture', 39.00, NULL, 60000, NULL, 60000, '{"start_year":1994,"production_bpd":2000,"quality":"Light sweet","note":"Ukrnafta 50%, JKX Oil & Gas (UK-listed) 50%; partially war disruption; JKX continued operations amid difficulties","last_transaction":"JKX longstanding Ukraine operator; nationalization fears post-2022","contract_duration":"PSA to 2028","pipelines":"Poltava → Kremenchuk pipeline","ports":"Odesa","rail":"Poltava rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Zakhidno-Khrestyshchenske Field', 'Poltava Petroleum Company', 'Poltava Oblast', NULL, 'Energy', 'Crude Oil', 49.6667, 33.5000, 'Ukraine', 'Dnipro-Donetsk Basin', 'Poltava', 'oil_field', 'operational', 'Poltava Petroleum Company', 'joint_venture', 38.00, NULL, 45000, NULL, 45000, '{"start_year":1997,"production_bpd":1500,"quality":"Light sweet","note":"JKX/Ukrnafta JV; JKX 50%, Ukrnafta 50%","contract_duration":"Ukrainian subsoil license","pipelines":"Poltava → Kremenchuk","ports":"Odesa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bugruvativske Field', 'Ukrnafta', 'Poltava Oblast', NULL, 'Energy', 'Crude Oil', 49.5000, 33.6667, 'Ukraine', 'Dnipro-Donetsk Basin', 'Poltava', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 37.00, NULL, 36000, NULL, 36000, '{"start_year":1989,"production_bpd":1200,"quality":"Light sweet","note":"Ukrnafta","contract_duration":"Ukrainian subsoil license","pipelines":"→ Kremenchuk pipeline","ports":"Odesa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Radchenkivske Field', 'Ukrnafta', 'Poltava Oblast', NULL, 'Energy', 'Crude Oil', 49.3333, 33.5000, 'Ukraine', 'Dnipro-Donetsk Basin', 'Poltava', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 38.00, NULL, 30000, NULL, 30000, '{"start_year":1983,"production_bpd":1000,"quality":"Light sweet","note":"Ukrnafta","contract_duration":"Ukrainian subsoil license","pipelines":"→ Kremenchuk","ports":"Odesa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kharkiv Oblast Fields Cluster', 'Ukrnafta', 'Kharkiv Oblast — frontline/occupied', NULL, 'Energy', 'Crude Oil', 49.7500, 36.9167, 'Ukraine', 'Dnipro-Donetsk Basin', 'Kharkiv', 'oil_field', 'inactive', 'Ukrnafta', 'state_owned', 36.00, NULL, 0, NULL, 0, '{"start_year":1960,"production_bpd":0,"quality":"Light sweet","note":"Severely disrupted — Kharkiv Oblast frontline 2022–2024; ~3,000 bpd pre-war; minimal/disrupted; some areas recaptured; pipeline route disrupted","contract_duration":"Ukrainian state; contested operationally","pipelines":"Kharkiv → Kremenchuk pipeline (disrupted)","ports":"Odesa (pipeline route disrupted)","rail":"Kharkiv rail hub (frontline city)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yuliivske Field', 'Ukrnafta / DTEK', 'Kharkiv Oblast', NULL, 'Energy', 'Crude Oil', 49.1667, 37.0000, 'Ukraine', 'Dnipro-Donetsk Basin', 'Kharkiv', 'oil_field', 'inactive', 'Ukrnafta', 'joint_venture', 37.00, NULL, 0, NULL, 0, '{"start_year":1982,"production_bpd":0,"quality":"Light sweet","note":"Disrupted — Kharkiv Oblast conflict zone; ~2,000 bpd pre-war; Ukrnafta/DTEK (Akhmetov) contested","contract_duration":"Ukrainian state","pipelines":"Disrupted","ports":"Odesa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CARPATHIAN REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Boryslav Field', 'Ukrnafta', 'Lviv Oblast — Ukrainian Carpathians', NULL, 'Energy', 'Crude Oil', 49.2833, 23.4500, 'Ukraine', 'Carpathian', 'Boryslav', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 32.00, 0.50, 15000, 2000000, 15000, '{"start_year":1853,"production_bpd":500,"quality":"Medium light","note":"World''s oldest continuously producing oil region alongside Pennsylvania; artisanal pre-dates Bóbrka; commercial well 1872 — Galician oil rush Austrian Empire; very mature; Ukrnafta 100%","contract_duration":"State concession (perpetual historic)","pipelines":"Boryslav → Drohobych refinery (~15km, historic refinery now Naftohaz Ukrayiny)","ports":"None direct (landlocked western Ukraine)","rail":"Boryslav–Drohobych–Lviv rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Stryi Field', 'Ukrnafta', 'Lviv Oblast — Carpathian', NULL, 'Energy', 'Crude Oil', 49.2583, 23.8583, 'Ukraine', 'Carpathian', 'Stryi', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 31.00, NULL, 12000, NULL, 12000, '{"start_year":1882,"production_bpd":400,"quality":"Medium","note":"Mature; Austro-Hungarian era; Ukrnafta 100%","contract_duration":"Ukrainian state concession","pipelines":"Stryi → Drohobych gathering","ports":"None","rail":"Stryi–Lviv rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dolyna Field', 'Ukrnafta', 'Ivano-Frankivsk Oblast — Carpathian', NULL, 'Energy', 'Crude Oil', 48.9667, 24.0167, 'Ukraine', 'Carpathian', 'Dolyna', 'oil_field', 'operational', 'Ukrnafta', 'state_owned', 33.00, NULL, 18000, NULL, 18000, '{"start_year":1939,"production_bpd":600,"quality":"Medium light","note":"Ukrnafta 100%","contract_duration":"Ukrainian state concession","pipelines":"Dolyna → Nadvirna refinery → Drohobych → Lviv","ports":"None","rail":"Dolyna–Ivano-Frankivsk rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bitkov Field', 'Ukrnafta + Naftogazvydobuvannya', 'Ivano-Frankivsk Oblast', NULL, 'Energy', 'Crude Oil', 48.5000, 24.2500, 'Ukraine', 'Carpathian', 'Nadvirna', 'oil_field', 'operational', 'Ukrnafta', 'joint_venture', 34.00, NULL, 24000, NULL, 24000, '{"start_year":1959,"production_bpd":800,"quality":"Medium light","note":"Ukrnafta 70%, Naftogazvydobuvannya 30%","contract_duration":"Ukrainian state concession","pipelines":"Bitkov → Nadvirna → Drohobych","ports":"None","rail":"None direct (Carpathian mountains)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Ukraine' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Ukraine' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
