-- ============================================================
-- Eswatini (Swaziland) Coal Mines — 1 Site
-- Single-row INSERT to avoid VALUES length mismatch
-- Run AFTER COAL_MINES_TABLE_SETUP.sql
-- ============================================================

INSERT INTO public.coal_mines (mine_name, operator, license_number, contact_email, contact_phone, country, region, address, latitude, longitude, nearest_port, nearest_railway, founded_year, years_in_operation, original_owner, ownership_changes, major_milestones, notable_incidents, estimated_mine_life_remaining_years, coal_type, grade, calorific_value_kcal_kg, moisture_percent, ash_percent, sulfur_percent, size_mm, annual_capacity_tonnes, available_stock_tonnes, mining_method, price_per_tonne_usd, price_basis, minimum_order_tonnes, payment_terms, contract_types, loading_port, transport_modes, lead_time_days, export_license, certifications)
VALUES ('Maloma Coalfield', 'Maloma Colliery (historically operated by the Swaziland Railway and private entities; current operator status unclear)', NULL, NULL, NULL, 'Eswatini', 'Lubombo District', 'Near the town of Siteki, eastern Eswatini, close to the border with Mozambique', -26.45, 31.95, 'Maputo Port (Mozambique) — via rail and road', 'Swaziland Railway (connects to Goba, Mozambique, and South African rail network)', 1960, 60, 'Swaziland Railway and private investors', '[{"year": 1980, "event": "Swaziland Railway transferred to private entities (exact details unclear)"}]'::jsonb, '[{"year": 1960, "event": "Discovery and initial development of the Maloma Coalfield"}, {"year": 1980, "event": "Peak production period, supplying coal to local and regional markets"}]'::jsonb, '[]'::jsonb, NULL, 'Bituminous (low-grade)', 'Seams of varying thickness, primarily used for local industry and power generation', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Opencast (historically)', NULL, NULL, NULL, NULL, NULL, 'Maputo Port (Mozambique) — via Swaziland Railway and road transport', '["Rail (Swaziland Railway)", "Truck"]'::jsonb, NULL, false, '[]'::jsonb)
ON CONFLICT (mine_name, country) DO UPDATE SET operator = EXCLUDED.operator, license_number = EXCLUDED.license_number, contact_email = EXCLUDED.contact_email, contact_phone = EXCLUDED.contact_phone, region = EXCLUDED.region, address = EXCLUDED.address, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, nearest_port = EXCLUDED.nearest_port, nearest_railway = EXCLUDED.nearest_railway, founded_year = EXCLUDED.founded_year, years_in_operation = EXCLUDED.years_in_operation, original_owner = EXCLUDED.original_owner, ownership_changes = EXCLUDED.ownership_changes, major_milestones = EXCLUDED.major_milestones, notable_incidents = EXCLUDED.notable_incidents, estimated_mine_life_remaining_years = EXCLUDED.estimated_mine_life_remaining_years, coal_type = EXCLUDED.coal_type, grade = EXCLUDED.grade, calorific_value_kcal_kg = EXCLUDED.calorific_value_kcal_kg, moisture_percent = EXCLUDED.moisture_percent, ash_percent = EXCLUDED.ash_percent, sulfur_percent = EXCLUDED.sulfur_percent, size_mm = EXCLUDED.size_mm, annual_capacity_tonnes = EXCLUDED.annual_capacity_tonnes, available_stock_tonnes = EXCLUDED.available_stock_tonnes, mining_method = EXCLUDED.mining_method, price_per_tonne_usd = EXCLUDED.price_per_tonne_usd, price_basis = EXCLUDED.price_basis, minimum_order_tonnes = EXCLUDED.minimum_order_tonnes, payment_terms = EXCLUDED.payment_terms, contract_types = EXCLUDED.contract_types, loading_port = EXCLUDED.loading_port, transport_modes = EXCLUDED.transport_modes, lead_time_days = EXCLUDED.lead_time_days, export_license = EXCLUDED.export_license, certifications = EXCLUDED.certifications, updated_at = NOW();
