-- ============================================================
-- Trinidad and Tobago Oil Production Sites — 12 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- OFFSHORE TRINIDAD
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Angostura Field', 'bp Trinidad and Tobago', 'East Coast Marine Area — ECMA, offshore east Trinidad', NULL, 'Energy', 'Crude Oil', 10.4167, -60.9167, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'bp Trinidad and Tobago', 'joint_venture', 26.00, 1.50, 900000, 400000000, 900000, '{"start_year":2014,"production_bpd":30000,"quality":"Medium heavy","note":"T&T''s largest offshore oil field; FID 2010, discovered 1996; bp 50% (operator), Shell 50%","last_transaction":"bp + Shell partnership $4B Angostura development (2010–2014); T&T''s largest offshore oil investment","contract_duration":"T&T production sharing contract to 2040s","pipelines":"Angostura subsea → Mahogany B platform hub → Point Fortin terminal (~50km subsea)","ports":"Point Fortin Oil Terminal; Brighton La Brea","rail":"None (Trinidad has no railway)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mahogany Field', 'Heritage Petroleum', 'East Coast Marine Area — offshore east Trinidad', NULL, 'Energy', 'Crude Oil', 10.3333, -61.0833, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 28.00, 1.20, 300000, 100000000, 300000, '{"start_year":1968,"production_bpd":10000,"quality":"Medium","note":"Mature; Amoco era; Heritage Petroleum 100% (Govt of T&T — formed 2018 from Petrotrin)","last_transaction":"Petrotrin collapsed 2018; government closed refinery, created Heritage Petroleum; Mahogany transferred to Heritage 2018","contract_duration":"State concession","pipelines":"Mahogany → Point Fortin terminal","ports":"Point Fortin; Brighton","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Teak Field', 'Heritage Petroleum', 'East Coast Marine Area', NULL, 'Energy', 'Crude Oil', 10.2500, -61.1500, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 27.00, NULL, 150000, NULL, 150000, '{"start_year":1972,"production_bpd":5000,"quality":"Medium heavy","note":"Mature; Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Teak → Mahogany hub → Point Fortin","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Samaan Field', 'Heritage Petroleum', 'East Coast Marine Area', NULL, 'Energy', 'Crude Oil', 10.3833, -61.0500, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 28.00, NULL, 90000, NULL, 90000, '{"start_year":1975,"production_bpd":3000,"quality":"Medium","note":"Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Samaan → Mahogany → Point Fortin","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Poui Field', 'bp Trinidad and Tobago', 'East Coast Marine Area', NULL, 'Energy', 'Crude Oil', 10.4500, -60.9500, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'bp Trinidad and Tobago', 'joint_venture', 25.00, NULL, 240000, NULL, 240000, '{"start_year":2016,"production_bpd":8000,"quality":"Heavy","note":"Part of Angostura infrastructure; bp 50%, Shell 50%","contract_duration":"T&T PSC","pipelines":"Poui → Angostura subsea → Point Fortin","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cashima (Savonetta) Offshore', 'Heritage Petroleum', 'West Coast Marine Area — offshore west Trinidad', NULL, 'Energy', 'Crude Oil', 10.6500, -61.6500, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 29.00, NULL, 150000, NULL, 150000, '{"start_year":1965,"production_bpd":5000,"quality":"Medium light","note":"Mature shallow water; Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Cashima → Point Fortin terminal (short offshore)","ports":"Point Fortin; Pt. Lisas Industrial Estate (petrochemical complex nearby)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Soldado Field', 'Heritage Petroleum', 'West Coast Marine Area — offshore southwest Trinidad', NULL, 'Energy', 'Crude Oil', 10.0833, -61.7833, 'Trinidad and Tobago', 'Offshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 28.00, NULL, 60000, NULL, 60000, '{"start_year":1954,"production_bpd":2000,"quality":"Medium","note":"Very mature; one of T&T''s oldest offshore; British Petroleum era; Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Soldado → Point Fortin terminal","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ONSHORE TRINIDAD
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Serrette Field', 'Heritage Petroleum', 'Onshore Trinidad — southern Trinidad', NULL, 'Energy', 'Crude Oil', 10.2500, -61.5000, 'Trinidad and Tobago', 'Onshore Trinidad', 'Point Fortin', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 30.00, NULL, 90000, NULL, 90000, '{"start_year":1920,"production_bpd":3000,"quality":"Medium light","note":"Mature onshore; colonial-era Trinidad Leaseholds Ltd; Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Serrette → Point Fortin refinery site (closed 2018; pipeline to terminal)","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Forest Reserve Onshore', 'Heritage Petroleum', 'South Trinidad — Brighton La Brea area', NULL, 'Energy', 'Crude Oil', 10.2333, -61.6167, 'Trinidad and Tobago', 'Onshore Trinidad', 'Brighton', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 27.00, NULL, 120000, NULL, 120000, '{"start_year":1910,"production_bpd":4000,"quality":"Medium heavy","note":"Mature onshore near Pitch Lake; Trinidad''s first commercial oil production (1908–1910); fully nationalized via Petrotrin → Heritage 2018","last_transaction":"Historic area — Forest Reserve first commercial oil; Heritage 2018","contract_duration":"State concession","pipelines":"Forest Reserve → Brighton terminal","ports":"Brighton La Brea Terminal (historic)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Parrylands (Fyzabad) Onshore', 'Heritage Petroleum', 'South Trinidad', NULL, 'Energy', 'Crude Oil', 10.1667, -61.5000, 'Trinidad and Tobago', 'Onshore Trinidad', 'Fyzabad', 'oil_field', 'operational', 'Heritage Petroleum', 'state_owned', 28.00, NULL, 150000, NULL, 150000, '{"start_year":1930,"production_bpd":5000,"quality":"Medium","note":"Heritage Petroleum 100%","contract_duration":"State concession","pipelines":"Parrylands → Point Fortin gathering","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- OFFSHORE TOBAGO / EASTERN VENEZUELA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pelican Field', 'BHP Trinidad and Tobago', 'East Tobago Basin — offshore between Trinidad & Tobago', NULL, 'Energy', 'Crude Oil', 11.2500, -60.5000, 'Trinidad and Tobago', 'Offshore Tobago', 'Scarborough', 'oil_field', 'operational', 'BHP Trinidad and Tobago', 'joint_venture', 30.00, 0.80, 300000, 80000000, 300000, '{"start_year":2012,"production_bpd":10000,"quality":"Medium light","note":"Smaller offshore; BHP 68.46% (operator), Heritage Petroleum 31.54%","last_transaction":"BHP developed Pelican ~$1B (2009–2012); BHP''s only Trinidad oil asset","contract_duration":"T&T PSC to 2030s","pipelines":"Pelican subsea → Point Fortin terminal (~100km subsea)","ports":"Point Fortin","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Loran-Manatee Field', 'Shell Trinidad and Tobago + bp', 'Eastern Venezuela Basin — disputed Trinidad/Venezuela maritime border', NULL, 'Energy', 'Crude Oil', 10.6667, -60.0833, 'Trinidad and Tobago', 'Offshore Tobago', 'Scarborough', 'oil_field', 'inactive', 'Shell Trinidad and Tobago', 'joint_venture', 45.00, NULL, 0, 300000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Condensate sweet (estimated)","note":"Development stalled — maritime boundary dispute with Venezuela; discovered 2011–2012; Shell 70% (Loran — Trinidad), bp 50% (Manatee — Venezuela); disputed ownership","last_transaction":"Trinidad and Venezuela failed to agree on unitization 2013–2024; Venezuela awarded PDVSA + Chevron Manatee 2023; Trinidad protested; field in legal limbo","contract_duration":"T&T PSC (disputed)","pipelines":"Planned subsea → Point Fortin (Trinidad) or Venezuela (disputed)","ports":"Planned Point Fortin or Venezuela","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Trinidad and Tobago' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Trinidad and Tobago' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
