-- ============================================================
-- DRC Coal Mines — 2 Sites
-- Same structure as INSERT_BOTSWANA_COAL_MINES_FULL.sql
-- Run AFTER COAL_MINES_TABLE_SETUP.sql
-- ============================================================

INSERT INTO public.coal_mines (
  mine_name,
  operator,
  license_number,
  contact_email,
  contact_phone,
  country,
  region,
  address,
  latitude,
  longitude,
  nearest_port,
  nearest_railway,
  founded_year,
  years_in_operation,
  original_owner,
  ownership_changes,
  major_milestones,
  notable_incidents,
  estimated_mine_life_remaining_years,
  coal_type,
  grade,
  calorific_value_kcal_kg,
  moisture_percent,
  ash_percent,
  sulfur_percent,
  size_mm,
  annual_capacity_tonnes,
  available_stock_tonnes,
  mining_method,
  price_per_tonne_usd,
  price_basis,
  minimum_order_tonnes,
  payment_terms,
  contract_types,
  loading_port,
  transport_modes,
  lead_time_days,
  export_license,
  certifications
) VALUES
(
  'Makala Coal Mine (Lukuga Coalfield)',
  'Gécamines',
  NULL,
  NULL,
  NULL,
  'Democratic Republic of Congo',
  'Tanganyika Province (formerly Katanga Province)',
  'Near Kalemie (formerly Albertville), eastern DRC, along Lukuga River tributaries',
  -5.95,
  29.18,
  'Kalemie Port (Lake Tanganyika) — connects to Kigoma (Tanzania) and then Dar es Salaam seaport',
  'SNCC Railway — Kalemie station (connects to Lubumbashi, ~4-7 days by rail)',
  1914,
  111,
  'Belgian Colonial Administration',
  '[{"year": 1916, "previous_owner": "Belgian Colonial Administration", "new_owner": "Coalworks opened at Greinerville (now Moluba) under colonial operation"}, {"year": 1966, "previous_owner": "Union Minière du Haut Katanga (UMHK)", "new_owner": "Gécamines (state-owned, post-independence nationalisation)"}]'::jsonb,
  '[{"year": 1914, "event": "Mining operations began on the northwestern part of the deposit following coal seam outcrops"}, {"year": 1915, "event": "Railway reached Albertville (now Kalemie), connecting the coalfield to broader transport network"}, {"year": 1916, "event": "Coalworks at Greinerville (now Moluba) officially opened"}, {"year": 1966, "event": "Nationalisation — Gécamines took over operations"}, {"year": 2006, "event": "Cailteux assessment estimated total basin reserves at over 75 million tonnes"}]'::jsonb,
  '[{"year": 1990, "event": "Coal production curtailed by ethnic conflicts in Shaba Province (noted in DRC geological records)"}]'::jsonb,
  NULL,
  'Sub-bituminous (low-grade)',
  'Seam 1 (primary, ~2m thickness), Seam 2 (secondary, 1-1.5m thickness)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Underground (Room-and-pillar)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Kalemie Port (Lake Tanganyika) → Kigoma, Tanzania → Dar es Salaam (ocean port)',
  '["Rail (SNCC)", "Lake Tanganyika barge", "Truck"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
),
(
  'Walikale Region — Coal Deposit (Unverified / Prospective)',
  NULL,
  NULL,
  NULL,
  NULL,
  'Democratic Republic of Congo',
  'North Kivu Province — Walikale Territory',
  'Walikale, ~135 km west of Goma, Lowa River valley',
  -1.4167,
  28.0333,
  'Goma (Lake Kivu) → Bukavu → Dar es Salaam (very long route)',
  'No direct railway. Access via National Road No. 3 only (Bukavu–Lubutu).',
  NULL,
  NULL,
  NULL,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"year": 2010, "event": "President Kabila banned all artisanal mining in Walikale territory (September 2010)"}, {"year": 2010, "event": "All mining and mineral exports from North Kivu suspended — ongoing instability"}]'::jsonb,
  NULL,
  'Unknown — unconfirmed deposit',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '["Truck (very poor road conditions)", "Small aircraft (airstrip on local road)"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
)
ON CONFLICT (mine_name, country) DO UPDATE SET
  operator = EXCLUDED.operator,
  license_number = EXCLUDED.license_number,
  contact_email = EXCLUDED.contact_email,
  contact_phone = EXCLUDED.contact_phone,
  region = EXCLUDED.region,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  nearest_port = EXCLUDED.nearest_port,
  nearest_railway = EXCLUDED.nearest_railway,
  founded_year = EXCLUDED.founded_year,
  years_in_operation = EXCLUDED.years_in_operation,
  original_owner = EXCLUDED.original_owner,
  ownership_changes = EXCLUDED.ownership_changes,
  major_milestones = EXCLUDED.major_milestones,
  notable_incidents = EXCLUDED.notable_incidents,
  estimated_mine_life_remaining_years = EXCLUDED.estimated_mine_life_remaining_years,
  coal_type = EXCLUDED.coal_type,
  grade = EXCLUDED.grade,
  calorific_value_kcal_kg = EXCLUDED.calorific_value_kcal_kg,
  moisture_percent = EXCLUDED.moisture_percent,
  ash_percent = EXCLUDED.ash_percent,
  sulfur_percent = EXCLUDED.sulfur_percent,
  size_mm = EXCLUDED.size_mm,
  annual_capacity_tonnes = EXCLUDED.annual_capacity_tonnes,
  available_stock_tonnes = EXCLUDED.available_stock_tonnes,
  mining_method = EXCLUDED.mining_method,
  price_per_tonne_usd = EXCLUDED.price_per_tonne_usd,
  price_basis = EXCLUDED.price_basis,
  minimum_order_tonnes = EXCLUDED.minimum_order_tonnes,
  payment_terms = EXCLUDED.payment_terms,
  contract_types = EXCLUDED.contract_types,
  loading_port = EXCLUDED.loading_port,
  transport_modes = EXCLUDED.transport_modes,
  lead_time_days = EXCLUDED.lead_time_days,
  export_license = EXCLUDED.export_license,
  certifications = EXCLUDED.certifications,
  updated_at = NOW();
