-- ============================================================
-- Syria Oil Production Sites — 32 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- DEIR EZ-ZOR REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Omar Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 34.9167, 40.4167, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF (de facto)', 'state_owned', 36.00, 0.50, 300000, 400000000, 300000, '{"start_year":1989,"production_bpd":10000,"quality":"Light sweet","note":"Largest Syrian field; conflict-damaged; SDF controls eastern bank; pre-war peak ~30,000 bpd","ooip":"1.5 billion barrels","last_transaction":"Shell PSC terminated ~2011 (EU sanctions); ISIS seized 2014–2017; SDF recaptured 2017","pipelines":"Omar → Deir ez-Zor → T2 → Banias (pipeline damaged/inactive)","ports":"Banias Crude Oil Terminal (Mediterranean — inactive due to conflict)","rail":"Deir ez-Zor–Damascus rail (war damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tanak Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 34.8333, 40.5000, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF (de facto)', 'state_owned', 37.00, 0.40, 90000, 300000000, 90000, '{"start_year":1991,"production_bpd":3000,"quality":"Light sweet","note":"Pre-war ~8,000 bpd; Gulfsands PSC suspended 2011; ISIS seized 2014–2017","pipelines":"Tanak → Omar → Deir ez-Zor pipeline","ports":"Banias (pipeline inactive)","rail":"Deir ez-Zor rail (damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jafra Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 34.8500, 40.6167, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF (de facto)', 'state_owned', 36.00, 0.50, 60000, 150000000, 60000, '{"start_year":1993,"production_bpd":2000,"quality":"Light sweet","note":"Pre-war ~5,000 bpd","pipelines":"Jafra → Omar field gathering → Deir ez-Zor pipeline","ports":"Banias (inactive)","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ward Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 35.0000, 40.3333, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF', 'state_owned', 35.00, 0.50, 24000, NULL, 24000, '{"start_year":1995,"production_bpd":800,"quality":"Light sweet","note":"Small field; pre-war ~2,000 bpd","pipelines":"Ward → Deir ez-Zor gathering system","ports":"Banias (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rasafa / Al-Rasafah Field', 'Syrian Petroleum Company', 'Deir ez-Zor / Raqqa border', NULL, 'Energy', 'Crude Oil', 35.6333, 38.9333, 'Syria', 'Deir ez-Zor', 'Rasafa', 'oil_field', 'operational', 'SPC', 'state_owned', 34.00, 0.80, 15000, 100000000, 15000, '{"start_year":1987,"production_bpd":"minimal current","quality":"Medium light","note":"Contested (government vs SDF border area); pre-war ~3,000 bpd","pipelines":"Rasafa → T3 pumping station → Banias pipeline","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kharata Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 34.7500, 40.7500, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF', 'state_owned', 35.00, 0.50, 45000, NULL, 45000, '{"start_year":1994,"production_bpd":1500,"quality":"Light","note":"Limited activity","pipelines":"Eastern Deir ez-Zor gathering","ports":"Banias (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Isba Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 35.0833, 40.2500, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC', 'state_owned', 34.00, 0.60, 36000, NULL, 36000, '{"start_year":1990,"production_bpd":1200,"quality":"Medium light","note":"Limited / damaged","pipelines":"Western Deir ez-Zor gathering → T2 station","ports":"Banias","rail":"Deir ez-Zor rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hamdan Field', 'Syrian Petroleum Company', 'Deir ez-Zor Governorate', NULL, 'Energy', 'Crude Oil', 34.9833, 40.4833, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF', 'state_owned', 36.00, 0.50, 45000, 120000000, 45000, '{"start_year":1988,"production_bpd":1500,"quality":"Light sweet","note":"Pre-war ~4,000 bpd","pipelines":"Hamdan → Omar → Deir ez-Zor pipeline","ports":"Banias (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Maleh / Al-Maleh Field', 'Syrian Petroleum Company', 'Deir ez-Zor, eastern bank', NULL, 'Energy', 'Crude Oil', 34.7000, 40.5833, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF', 'state_owned', 35.00, 0.50, 30000, NULL, 30000, '{"start_year":1992,"production_bpd":1000,"quality":"Light","note":"Limited activity","pipelines":"Eastern bank gathering → Omar hub","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Conoco / Al-Tabiya Field', 'Syrian Petroleum Company', 'Deir ez-Zor — near US military base', NULL, 'Energy', 'Crude Oil', 35.0500, 40.3667, 'Syria', 'Deir ez-Zor', 'Conoco', 'oil_field', 'operational', 'SDF + US Military', 'state_owned', 36.00, 0.50, 150000, NULL, 150000, '{"start_year":"1990s","production_bpd":5000,"quality":"Light sweet","note":"Conoco plant — now US military garrison Mission Support Site Conoco; SDF revenue stream; ISIS held 2014–2017","last_transaction":"Conoco evacuated ~2005; site repurposed; geopolitically significant","pipelines":"Local gathering → eastern Syria SDF network","ports":"None operational","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Azraq Field', 'Syrian Petroleum Company', 'Deir ez-Zor border area', NULL, 'Energy', 'Crude Oil', 34.8833, 40.8333, 'Syria', 'Deir ez-Zor', 'Deir ez-Zor', 'oil_field', 'operational', 'SPC / SDF', 'state_owned', 35.00, 0.50, 24000, NULL, 24000, '{"start_year":1993,"production_bpd":800,"quality":"Light","note":"Limited","pipelines":"Eastern gathering system","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NORTHEAST SYRIA (Al-Hasakah)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rumailan / Rmeilan Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 37.0500, 42.0333, 'Syria', 'Al-Hasakah', 'Rumailan', 'oil_field', 'operational', 'SPC / AANES (SDF)', 'state_owned', 33.00, 0.80, 825000, 500000000, 825000, '{"start_year":1968,"production_bpd":27500,"quality":"Medium light","note":"Largest in NE Syria; Syria''s most active field currently; SDF primary revenue source; pre-war ~40,000 bpd","last_transaction":"Gulfsands PSC suspended 2011; SDF operational control since 2012","pipelines":"Rumailan → Qamishli → Hasaka gathering (limited; trucks dominate); pre-war → Banias (inactive)","ports":"Banias (pre-war; inactive); oil by road tanker to Iraq border (Al-Waleed/Fish Khabur)","rail":"Qamishli–Ras al-Ayn rail (war damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Suwaydiyah / Al-Suwaidiyah Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 37.1333, 42.1833, 'Syria', 'Al-Hasakah', 'Qamishli', 'oil_field', 'operational', 'SPC / AANES (SDF)', 'state_owned', 34.00, 0.70, 240000, 300000000, 240000, '{"start_year":1959,"production_bpd":8000,"quality":"Medium light","note":"One of Syria''s first fields; mature; significant gas also; pre-war ~15,000 bpd","pipelines":"Suwaydiyah → Qamishli gathering → northern Syria pipeline (partially active)","ports":"Banias (pre-war pipeline, inactive)","rail":"Qamishli rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Karatchuk Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate — far northeast', NULL, 'Energy', 'Crude Oil', 37.2667, 42.5000, 'Syria', 'Al-Hasakah', 'Karatchuk', 'oil_field', 'operational', 'SPC / AANES (SDF)', 'state_owned', 32.00, 0.90, 60000, 100000000, 60000, '{"start_year":1956,"production_bpd":2000,"quality":"Medium","note":"Syria''s first commercial oil discovery; near Iraq/Turkey border; pre-war ~5,000 bpd","pipelines":"Karatchuk → Suwaydiyah → Qamishli gathering","ports":"Banias (pre-war; inactive)","rail":"Qamishli–Nusaybin (Turkey) rail (closed)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jabisah Gas + Condensate Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 36.8333, 41.5000, 'Syria', 'Al-Hasakah', 'Al-Hasakah', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 48.00, 0.30, 30000, NULL, 30000, '{"start_year":1987,"production_bpd":1000,"quality":"Condensate sweet","note":"Major gas field; gas + condensate; condensate ~1,000 bpd current","pipelines":"Jabisah gas → Al-Hasakah power plants; condensate → road tanker","ports":"None operational","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tishrin Field', 'Syrian Petroleum Company', 'Al-Hasakah / Deir ez-Zor border', NULL, 'Energy', 'Crude Oil', 36.5000, 41.2500, 'Syria', 'Al-Hasakah', 'Tishrin', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 35.00, 0.50, 36000, NULL, 36000, '{"start_year":1985,"production_bpd":1200,"quality":"Light sweet","note":"Pre-war ~3,500 bpd","pipelines":"Tishrin → Deir ez-Zor pipeline (damaged)","ports":"Banias (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hawl / Al-Hawl Field', 'Syrian Petroleum Company', 'Al-Hasakah — near Iraq border', NULL, 'Energy', 'Crude Oil', 36.5000, 41.8333, 'Syria', 'Al-Hasakah', 'Al-Hawl', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 34.00, 0.70, 60000, NULL, 60000, '{"start_year":1991,"production_bpd":2000,"quality":"Medium light","note":"Limited activity","pipelines":"Al-Hawl → Rumailan gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tel Adis Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 37.0000, 41.5833, 'Syria', 'Al-Hasakah', 'Tel Adis', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 33.00, 0.80, 45000, NULL, 45000, '{"start_year":1982,"production_bpd":1500,"quality":"Medium","note":"Limited","pipelines":"Al-Hasakah gathering network","ports":"Banias (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qashibah Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 36.7500, 41.0833, 'Syria', 'Al-Hasakah', 'Qashibah', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 34.00, 0.70, 30000, NULL, 30000, '{"start_year":1989,"production_bpd":1000,"quality":"Medium light","note":"Limited","pipelines":"NE Syria gathering → Rumailan hub","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kheshman Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 36.9167, 41.3333, 'Syria', 'Al-Hasakah', 'Kheshman', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 33.00, 0.80, 24000, NULL, 24000, '{"start_year":1990,"production_bpd":800,"quality":"Medium light","note":"Limited","pipelines":"NE gathering system","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dubaysan Field', 'Syrian Petroleum Company', 'Al-Hasakah Governorate', NULL, 'Energy', 'Crude Oil', 37.1667, 41.7500, 'Syria', 'Al-Hasakah', 'Dubaysan', 'oil_field', 'operational', 'SPC / AANES', 'state_owned', 34.00, 0.70, 36000, NULL, 36000, '{"start_year":1988,"production_bpd":1200,"quality":"Medium light","note":"Limited","pipelines":"NE gathering → Rumailan","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 26 — Gulfsands Petroleum Area', 'Syrian Petroleum Company', 'Al-Hasakah, Block 26', NULL, 'Energy', 'Crude Oil', 36.8333, 41.8333, 'Syria', 'Al-Hasakah', 'Block 26', 'oil_field', 'inactive', 'Gulfsands Petroleum (suspended) / AANES de facto', 'state_owned', 35.00, 0.50, 30000, 200000000, 30000, '{"start_year":2007,"production_bpd":"minimal now","quality":"Light sweet","note":"Gulfsands PSC suspended 2011 (EU sanctions); wrote off ~$350M Syria assets; delisted LSE 2020","last_transaction":"Gulfsands suspended all Syria operations 2011; SDF de facto","pipelines":"Block 26 → Rumailan hub → NE Syria gathering","ports":"Banias (pre-war; inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- PALMYRA REGION (Homs Governorate)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Palmyra / Tadmur Block', 'Syrian Petroleum Company', 'Homs Governorate — central Syria', NULL, 'Energy', 'Crude Oil', 34.5500, 38.2667, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'inactive', 'SPC / Al-Furat Petroleum Company (AFPC)', 'state_owned', 33.00, 1.00, 0, 400000000, 0, '{"start_year":1986,"production_bpd":"minimal/nil current","quality":"Medium light","note":"ISIS held 2015–2016; significant infrastructure destruction; Shell + CNPC exited AFPC 2011","last_transaction":"Shell + CNPC exited AFPC 2011; ISIS destroyed major infrastructure 2015; Russian airstrikes recapture 2016","pipelines":"Palmyra → T3 pumping station → Banias pipeline (severely damaged)","ports":"Banias Crude Oil Terminal (Mediterranean — pipeline damaged/inactive)","rail":"Palmyra–Damascus rail (damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ash-Shaer / Al-Sha''er Gas Field', 'Syrian Petroleum Company', 'Homs Governorate — near Palmyra', NULL, 'Energy', 'Crude Oil', 34.6667, 38.0833, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'inactive', 'SPC', 'state_owned', 46.00, 0.30, 15000, 100000000, 15000, '{"start_year":1989,"production_bpd":"minimal now","quality":"Condensate sweet","note":"Major gas field; feeds Syrian gas grid; ISIS seized June 2014 — executed ~270 soldiers/workers; ISIS seized again May 2016","reserves_gas":"~5 TCF gas","pipelines":"Ash-Shaer gas → Syrian gas pipeline network → Homs; condensate → Homs refinery","ports":"Banias (gas processed, not direct export)","rail":"Palmyra–Homs rail (damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Furat / Euphrates Block', 'Syrian Petroleum Company', 'AFPC area — Deir ez-Zor/Palmyra border', NULL, 'Energy', 'Crude Oil', 35.0000, 38.8333, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'operational', 'Al-Furat Petroleum Company (AFPC)', 'state_owned', 35.00, 0.50, 150000, 800000000, 150000, '{"start_year":1988,"production_bpd":5000,"quality":"Light sweet","note":"AFPC total blocks; peak ~140,000 bpd 2002 (Syria''s peak output); Shell + CNPC exited 2011","last_transaction":"Shell PSC suspended 2011 ($1.5B+ write-off); CNPC exited 2011 (~$500M write-off); AFPC now SPC-only but dysfunctional","pipelines":"AFPC blocks → T2/T3 pumping stations → Banias (severely compromised)","ports":"Banias","rail":"Deir ez-Zor–Palmyra–Damascus (damaged throughout)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jihar Field', 'Syrian Petroleum Company', 'Homs Governorate — Palmyra area', NULL, 'Energy', 'Crude Oil', 34.3333, 38.5000, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'inactive', 'SPC', 'state_owned', 34.00, 0.70, 15000, NULL, 15000, '{"start_year":1990,"production_bpd":"minimal now","quality":"Medium light","note":"Pre-war ~3,000 bpd","pipelines":"Jihar → T3 → Banias pipeline (damaged)","ports":"Banias","rail":"Homs–Palmyra rail (damaged)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bishri / Jabal Bishri Block', 'Syrian Petroleum Company', 'Deir ez-Zor / Raqqa / Palmyra tri-border', NULL, 'Energy', 'Crude Oil', 35.5000, 39.5000, 'Syria', 'Homs', 'Bishri', 'oil_field', 'operational', 'SPC', 'state_owned', 33.00, 0.80, 60000, NULL, 60000, '{"start_year":1992,"production_bpd":2000,"quality":"Medium","note":"Minimal / conflict zone; highly contested militarily","pipelines":"Bishri → T3 station → Banias","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qahar Field', 'Syrian Petroleum Company', 'Palmyra area, Homs Governorate', NULL, 'Energy', 'Crude Oil', 34.2500, 38.7500, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'operational', 'SPC', 'state_owned', 34.00, 0.70, 45000, NULL, 45000, '{"start_year":1988,"production_bpd":1500,"quality":"Medium light","note":"Minimal","pipelines":"Palmyra gathering → T3 → Banias","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Taym Field', 'Syrian Petroleum Company', 'Deir ez-Zor / Palmyra border', NULL, 'Energy', 'Crude Oil', 35.1667, 39.5000, 'Syria', 'Homs', 'Al-Taym', 'oil_field', 'operational', 'SPC', 'state_owned', 35.00, 0.50, 75000, NULL, 75000, '{"start_year":1986,"production_bpd":2500,"quality":"Light","note":"Minimal / contested","pipelines":"Al-Taym → Deir ez-Zor → T2 → Banias","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kawkab Field', 'Syrian Petroleum Company', 'Homs Governorate — near Palmyra', NULL, 'Energy', 'Crude Oil', 34.4167, 38.1667, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'operational', 'SPC', 'state_owned', 33.00, 0.80, 30000, NULL, 30000, '{"start_year":1991,"production_bpd":1000,"quality":"Medium","note":"Minimal / damaged","pipelines":"Palmyra area → T3 → Banias","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mustadira Field', 'Syrian Petroleum Company', 'Homs Governorate', NULL, 'Energy', 'Crude Oil', 34.6000, 37.9167, 'Syria', 'Homs', 'Mustadira', 'oil_field', 'operational', 'SPC', 'state_owned', 34.00, 0.70, 24000, NULL, 24000, '{"start_year":1993,"production_bpd":800,"quality":"Medium light","note":"Minimal","pipelines":"Western Palmyra gathering → T3","ports":"Banias","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jhar Gas Plant / T2-T3 Pumping Stations', 'Sytrol (Syrian pipeline company)', 'Palmyra corridor — pipeline infrastructure', NULL, 'Energy', 'Crude Oil', 34.5000, 38.6667, 'Syria', 'Homs', 'Palmyra', 'oil_field', 'inactive', 'SPC (Sytrol)', 'state_owned', NULL, NULL, 0, NULL, 0, '{"start_year":"1980s","production_bpd":"N/A","quality":"N/A (infrastructure node)","note":"Critical midstream infrastructure; processed ~150,000 bpd pre-war; ISIS destroyed T2/T3 multiple times 2014–2017; Russian military attempted repair 2017–2019; largely non-functional 2024","last_transaction":"T2 station seized and destroyed by ISIS multiple times","pipelines":"T2 → T3 → Banias spine (Syria''s main crude export pipeline — 800km Deir ez-Zor to Mediterranean)","ports":"Banias Crude Oil Terminal","rail":"Deir ez-Zor–Homs–Banias rail (damaged throughout)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Syria' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Syria' AND commodity_name = 'Crude Oil' ORDER BY region, title;
