-- ============================================================
-- Guatemala Oil Production Sites — 5 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- PETÉN REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Xan Field', 'Perenco Guatemala', 'Petén Department — northern Guatemala jungle', NULL, 'Energy', 'Crude Oil', 16.8333, -90.5000, 'Guatemala', 'Petén', 'Flores', 'oil_field', 'operational', 'Perenco Guatemala', 'private', 27.00, 1.20, 240000, 100000000, 240000, '{"start_year":1980,"production_bpd":8000,"quality":"Medium heavy","note":"Guatemala''s largest producing field; discovered 1974 by Basic Resources; Perenco 100% (French independent; operates in 16 countries)","last_transaction":"Perenco acquired from Basic Resources/Norcen ~2001; ~$200M investment; Perenco dominant Guatemalan operator","contract_duration":"Guatemalan petroleum contract to 2030s","pipelines":"Xan → Piedras Negras crude pipeline (~500km south) → Puerto Barrios export terminal","ports":"Puerto Barrios Oil Terminal (Santo Tomás de Castilla port complex)","rail":"None (jungle region)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rubelsanto Field', 'Perenco Guatemala', 'Alta Verapaz / Petén border — Chinajá region', NULL, 'Energy', 'Crude Oil', 15.6667, -90.3333, 'Guatemala', 'Petén', 'Cobán', 'oil_field', 'operational', 'Perenco Guatemala', 'private', 28.00, 1.00, 120000, 50000000, 120000, '{"start_year":1977,"production_bpd":4000,"quality":"Medium heavy","note":"Guatemala''s first commercial oil field; discovered 1974; mature; Perenco 100%","last_transaction":"Perenco consolidated Rubelsanto ~2005","contract_duration":"Guatemalan contract to 2030","pipelines":"Rubelsanto → Piedras Negras crude pipeline → Puerto Barrios","ports":"Puerto Barrios","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chinajá Field', 'Perenco Guatemala', 'Alta Verapaz — Rubelsanto area', NULL, 'Energy', 'Crude Oil', 15.5833, -90.2500, 'Guatemala', 'Petén', 'Cobán', 'oil_field', 'operational', 'Perenco Guatemala', 'private', 27.00, NULL, 90000, NULL, 90000, '{"start_year":1980,"production_bpd":3000,"quality":"Medium heavy","note":"Perenco 100%","contract_duration":"Guatemalan contract","pipelines":"Chinajá → Rubelsanto gathering → Piedras Negras pipeline","ports":"Puerto Barrios","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tierra Blanca Field', 'Perenco Guatemala', 'Petén Department', NULL, 'Energy', 'Crude Oil', 16.5000, -90.2500, 'Guatemala', 'Petén', 'Flores', 'oil_field', 'operational', 'Perenco Guatemala', 'private', 26.00, NULL, 45000, NULL, 45000, '{"start_year":1995,"production_bpd":1500,"quality":"Medium heavy","note":"Smaller field; Perenco 100%","contract_duration":"Guatemalan contract","pipelines":"Tierra Blanca → Xan gathering → Piedras Negras","ports":"Puerto Barrios","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Caribe Field', 'Perenco Guatemala', 'Petén — northeastern Guatemala near Belize border', NULL, 'Energy', 'Crude Oil', 17.1667, -89.3333, 'Guatemala', 'Petén', 'Flores', 'oil_field', 'operational', 'Perenco Guatemala', 'private', 25.00, NULL, 60000, NULL, 60000, '{"start_year":2009,"production_bpd":2000,"quality":"Heavy","note":"Perenco 100%","contract_duration":"Guatemalan contract","pipelines":"Caribe → Xan → Piedras Negras pipeline","ports":"Puerto Barrios","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Guatemala' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Guatemala' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
