-- ============================================================
-- Greece Oil Production Sites — 5 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- PRINOS FIELD (NORTH AEGEAN)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Prinos Field', 'Energean Oil & Gas', 'North Aegean Sea — Kavala Prefecture, offshore', NULL, 'Energy', 'Crude Oil', 40.7500, 24.5500, 'Greece', 'North Aegean', 'Kavala', 'oil_field', 'operational', 'Energean Oil & Gas', 'private', 28.00, 1.80, 135000, 15000000, 135000, '{"start_year":1981,"production_bpd":4500,"quality":"Medium heavy — Prinos crude; Greece''s only export crude grade","note":"Greece''s only significant producing oil field; discovered 1974; Kavala Oil until 2007; Energean 100%","last_transaction":"Energean listed London Stock Exchange 2018 (raised £460M) — first Greek oil company to list in London","contract_duration":"Greek state concession extended to 2033","pipelines":"Prinos offshore platform → Kavala onshore terminal (22km subsea)","ports":"Kavala Port (northeastern Greece — crude export tanker loading)","rail":"Kavala–Thessaloniki rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Prinos North Field', 'Energean Oil & Gas', 'North Aegean — adjacent to Prinos', NULL, 'Energy', 'Crude Oil', 40.7833, 24.5167, 'Greece', 'North Aegean', 'Kavala', 'oil_field', 'operational', 'Energean Oil & Gas', 'private', 27.00, NULL, 45000, 20000000, 45000, '{"start_year":1993,"production_bpd":1500,"quality":"Medium heavy sour","note":"Satellite development; Energean 100%","contract_duration":"Greek concession to 2033","pipelines":"Prinos North → Prinos platform → Kavala terminal","ports":"Kavala","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Epsilon Field', 'Energean Oil & Gas', 'North Aegean — Prinos cluster', NULL, 'Energy', 'Crude Oil', 40.8167, 24.4833, 'Greece', 'North Aegean', 'Kavala', 'oil_field', 'operational', 'Energean Oil & Gas', 'private', 30.00, 1.50, 105000, 40000000, 105000, '{"start_year":2019,"production_bpd":3500,"quality":"Medium","note":"Energean''s flagship Greek upstream project; development completed 2019; Energean 100%","last_transaction":"Epsilon development — ~€170M investment (2015–2019); 7 new production wells using jackup rig","contract_duration":"Greek concession to 2033","pipelines":"Epsilon → Prinos platform → Kavala terminal (tieback)","ports":"Kavala","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- WESTERN GREECE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Katakolo Field', 'HELLENiQ Energy + Energean', 'Western Greece — Ionian Sea, Peloponnese coast', NULL, 'Energy', 'Crude Oil', 37.6333, 21.2833, 'Greece', 'Western Greece', 'Pyrgos', 'oil_field', 'operational', 'HELLENiQ Energy + Energean', 'joint_venture', 40.00, NULL, 90000, 50000000, 90000, '{"start_year":null,"production_bpd":3000,"quality":"Light sweet (estimated)","note":"HELLENiQ Energy 75%, Energean 25%; discovered 1981; test production only; formal FID pending; long-delayed by permitting, archaeological concerns, tourism lobby","last_transaction":"Development blocked for decades; FID repeatedly deferred","contract_duration":"Greek state concession — under renegotiation","pipelines":"Planned → Pyrgos onshore terminal (short nearshore)","ports":"Katakolo Port (Peloponnese — cruise ship terminal, planned crude export)","rail":"Pyrgos–Patras rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ioannina Block', 'Repsol + HELLENiQ Energy', 'Northwestern Greece — Epirus, onshore', NULL, 'Energy', 'Crude Oil', 39.6667, 20.8500, 'Greece', 'Western Greece', 'Ioannina', 'oil_field', 'planned', 'Repsol + HELLENiQ', 'joint_venture', NULL, NULL, 0, 1000000000, 0, '{"start_year":2015,"production_bpd":0,"quality":"TBD","note":"Repsol 50%, HELLENiQ 50%; exploration; high prospective Ionian thrust belt; ~1B bbl potential (Repsol estimate)","last_transaction":"Repsol + Hellenic Petroleum exploration agreement 2015; seismic completed; drilling delayed by environmental protests + COVID + permitting","contract_duration":"Exploration license to 2026 (extension likely)","pipelines":"None (exploration only)","ports":"Igoumenitsa (Ionian coast — planned export if commercial)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Greece' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Greece' AND commodity_name = 'Crude Oil' ORDER BY region, title;
