-- ============================================================
-- Egypt, Ethiopia, Kenya Coal Mines — 4 Sites
-- Same structure as INSERT_BOTSWANA_COAL_MINES_FULL.sql
-- Run AFTER COAL_MINES_TABLE_SETUP.sql
-- ============================================================

INSERT INTO public.coal_mines (
  mine_name,
  operator,
  license_number,
  contact_email,
  contact_phone,
  country,
  region,
  address,
  latitude,
  longitude,
  nearest_port,
  nearest_railway,
  founded_year,
  years_in_operation,
  original_owner,
  ownership_changes,
  major_milestones,
  notable_incidents,
  estimated_mine_life_remaining_years,
  coal_type,
  grade,
  calorific_value_kcal_kg,
  moisture_percent,
  ash_percent,
  sulfur_percent,
  size_mm,
  annual_capacity_tonnes,
  available_stock_tonnes,
  mining_method,
  price_per_tonne_usd,
  price_basis,
  minimum_order_tonnes,
  payment_terms,
  contract_types,
  loading_port,
  transport_modes,
  lead_time_days,
  export_license,
  certifications
) VALUES
(
  'El Maghara Coal Mine',
  'Egyptian Mineral Resources Authority (EMRA)',
  NULL,
  NULL,
  NULL,
  'Egypt',
  'North Sinai Governorate',
  'Gebel El-Maghara, North Sinai, Egypt',
  30.706731,
  33.381687,
  'Port Said (~200km north)',
  'None — no railway connection; road access only',
  1964,
  NULL,
  'Egyptian state',
  '[{"year": 1964, "event": "Mine opened under Egyptian state ownership"}, {"year": 1967, "event": "Operations halted — Six-Day War; mine facilities destroyed and collapsed"}, {"year": 1982, "event": "Rehabilitation began with assistance of British company Babcock"}, {"year": 2005, "event": "Mine closed again due to technical and financial problems"}, {"year": 2014, "event": "Government approved resumption of operations under EMRA"}, {"year": 2022, "event": "Egyptian government announced plans to end coal ahead of COP27 hosting; mine status uncertain"}]'::jsonb,
  '[{"year": null, "event": "Only coal mine ever operated in Egypt"}, {"year": 1982, "event": "Rehabilitation with UK technical support (Babcock)"}, {"year": 2014, "event": "Government reapproval for operation"}, {"year": 2025, "event": "Listed as retired by Global Energy Monitor"}]'::jsonb,
  '[{"year": 1967, "event": "Mine destroyed during 1967 Sinai War; 15-year suspension"}]'::jsonb,
  NULL,
  'Bituminous (low-rank / high-volatile C)',
  'High Volatile C Bituminous — agglomerating',
  6939,
  2.48,
  9.23,
  NULL,
  NULL,
  NULL,
  NULL,
  'Underground',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Port Said (200km north) or Suez (possible alternative)',
  '["Road (desert highway to Ismailia / Canal Zone)", "Port Said for export"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
),
(
  'Yayu Coal Mine (Geba Basin — Yayu / Achibo-Sombo localities)',
  'Oromia Mines and Resources Authority (artisanal); formerly METEC',
  NULL,
  NULL,
  NULL,
  'Ethiopia',
  'Oromia Region',
  'Yayu, Illubabor Zone, Oromia, Ethiopia',
  8.3358,
  35.8225,
  'Djibouti (~1200km via Addis); Berbera (Somaliland, ~1400km)',
  'Addis Ababa–Djibouti Railway — nearest station Mieso/Dire Dawa, ~500km east',
  2012,
  NULL,
  'METEC (Metals and Engineering Corporation)',
  '[{"year": 2012, "event": "METEC awarded contract; Yayu Fertilizer Factory project launched; $500M project"}, {"year": 2012, "event": "Construction begun — plan: 9.2Mt extracted coal to produce 300,000t/year urea fertilizer"}, {"year": 2019, "event": "Ethiopian government cancelled fertilizer project with METEC; Oromia cancelled METEC coal mining rights"}, {"year": 2019, "event": "Oromia handed coal mining rights to ~500 youth-organized cooperatives"}, {"year": 2022, "event": "Government announced plans for coal revival"}, {"year": 2024, "event": "Minister of Mines criticized Yayu fertilizer project as attempted with improper resources"}]'::jsonb,
  '[{"year": 2010, "event": "UNESCO Biosphere Reserve designation (Yayu Coffee Forest)"}, {"year": 2012, "event": "METEC contract — largest state coal mining project in Ethiopian history"}, {"year": null, "event": "Chinese study (Changshi) confirmed 179Mt reserves at Yayu"}, {"year": 2019, "event": "Youth cooperative artisanal mining commenced"}, {"year": null, "event": "Cooperatives earned ETB 29 million in first fiscal year of artisanal operations"}]'::jsonb,
  '[{"year": null, "event": "METEC mining operations caused degradation of wild arabica coffee forest, hundreds of hectares destroyed"}, {"year": 2017, "event": "Mining expanded into UNESCO Biosphere Reserve core zone — documented by Kassahun Kelifa"}, {"year": null, "event": "Displacement of local communities reliant on wild coffee economy"}]'::jsonb,
  40,
  'Lignite to Sub-bituminous (low rank)',
  'Lignite category predominantly',
  2626,
  NULL,
  NULL,
  NULL,
  NULL,
  300000,
  NULL,
  'Open-pit (planned/artisanal); underground possible for future industrial-scale',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Djibouti (only viable export port, ~1200km via Addis Ababa)',
  '["Road (unpaved regional roads to Addis)", "Rail (Addis–Djibouti Railway, from Addis)"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
),
(
  'Delbi Coal Mine (Delbi-Moye Coalfield — Delbi Locality)',
  'Delbi Coal Mining PLC',
  NULL,
  NULL,
  NULL,
  'Ethiopia',
  'Oromia Region',
  'Delbi-Moye Basin, Jimma Zone, Oromia Region, Ethiopia',
  7.355,
  36.838,
  'Djibouti (~950km via Addis Ababa)',
  'Addis Ababa–Djibouti Railway (Addis Ababa station ~390km east)',
  NULL,
  NULL,
  'Delbi Coal Mining PLC / May Flower Mining Enterprise',
  '[{"year": 1991, "event": "Ministry of Mines and Energy conducted first formal geological and reserve study"}, {"year": 1993, "event": "Detailed geological mapping and reserve evaluation completed"}, {"year": 2013, "event": "Indian company announced $116M investment in Delbi Coal Mine"}, {"year": null, "event": "Delbi Coal Mining PLC and May Flower Mining Enterprise established"}]'::jsonb,
  '[{"year": null, "event": "Second-most studied coal deposit in Ethiopia after Yayu/Geba Basin"}, {"year": 2013, "event": "$116M Indian investment announced"}, {"year": null, "event": "21 boreholes drilled across 25km² basin area"}, {"year": null, "event": "Listed as operating by Global Energy Monitor"}]'::jsonb,
  '[]'::jsonb,
  NULL,
  'Lignite to Sub-bituminous (mixed; sapropelic at Delbi, humic at Moye)',
  'Thermal combustion (cement industry)',
  4684,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Open-pit (favorable conditions per MoM Ethiopia)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Djibouti (~950km via Addis Ababa)',
  '["Road to Jimma (~45km)", "Road Jimma to Addis Ababa (~350km)", "Addis Ababa–Djibouti Railway to Djibouti Port"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
),
(
  'Mui Basin Coal Project — Kitui County',
  'Fenxi Mining Industry Company Ltd',
  'Mining concession — Blocks C & D awarded Dec 23, 2013',
  NULL,
  NULL,
  'Kenya',
  'Eastern Kenya',
  'Mui Basin, Kitui County, Kenya',
  -1.05,
  38.2,
  'Mombasa (via road/planned rail, ~500km southeast)',
  'SGR (Standard Gauge Railway) — Nairobi to Mombasa; nearest station Nairobi (~270km west)',
  NULL,
  0,
  'Fenxi Mining Industry Ltd (Jung''u Group, Shanxi Province, China)',
  '[{"year": 2000, "event": "Ministry of Energy begins coal prospecting; 62 exploration wells drilled"}, {"year": 2010, "event": "400 million tonnes commercially viable reserves confirmed in Block C"}, {"year": 2010, "event": "Kenyan government awarded mining concession to Fenxi/Jung''u"}, {"year": 2013, "event": "Benefit-sharing agreement signed in Mwingi (December 23)"}, {"year": 2015, "event": "Additional Chinese consortium awarded mining rights; 960MW IPP coal plant tendered"}, {"year": 2017, "event": "Mining had still not commenced; community opposition intensified"}, {"year": 2019, "event": "Local residents petitioned Parliament to stop coal mining project"}, {"year": 2020, "event": "Kenya undecided on Mui Basin coal mining"}, {"year": 2021, "event": "Government allocated budget for 20 more exploration wells"}, {"year": 2025, "event": "No mining operations commenced; project in prolonged limbo"}]'::jsonb,
  '[{"year": 2010, "event": "400Mt reserve confirmed (Block C) — estimated value USD 40 billion"}, {"year": null, "event": "Ministry estimates total deposits over 1 billion tonnes"}, {"year": null, "event": "62 exploration wells drilled (primarily Block C)"}, {"year": 2013, "event": "Concession awarded to Fenxi/Jung''u"}, {"year": null, "event": "960MW coal IPP plant tendered for Kitui county"}, {"year": null, "event": "Planned 1050MW Lamu coal plant intended to receive Mui coal"}]'::jsonb,
  '[{"year": null, "event": "Widespread community and MP opposition"}, {"year": 2020, "event": "No EIAs completed despite legal requirement"}, {"year": null, "event": "~100,000 residents facing potential displacement"}, {"year": null, "event": "Project stalled by political disputes between national and county government"}]'::jsonb,
  NULL,
  'Sub-bituminous (Mui1 and Mui2 samples characterized)',
  'Thermal coal — power generation, cement',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  'Planned open-pit and/or underground (TBD — feasibility not completed)',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Mombasa (only viable export port, ~500km southeast via road)',
  '["Road (National Road Mwingi to Nairobi ~270km, then Mombasa Highway ~500km)", "SGR rail (Nairobi–Mombasa) — requires road haul to Nairobi first"]'::jsonb,
  NULL,
  false,
  '[]'::jsonb
)
ON CONFLICT (mine_name, country) DO UPDATE SET
  operator = EXCLUDED.operator,
  license_number = EXCLUDED.license_number,
  contact_email = EXCLUDED.contact_email,
  contact_phone = EXCLUDED.contact_phone,
  region = EXCLUDED.region,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  nearest_port = EXCLUDED.nearest_port,
  nearest_railway = EXCLUDED.nearest_railway,
  founded_year = EXCLUDED.founded_year,
  years_in_operation = EXCLUDED.years_in_operation,
  original_owner = EXCLUDED.original_owner,
  ownership_changes = EXCLUDED.ownership_changes,
  major_milestones = EXCLUDED.major_milestones,
  notable_incidents = EXCLUDED.notable_incidents,
  estimated_mine_life_remaining_years = EXCLUDED.estimated_mine_life_remaining_years,
  coal_type = EXCLUDED.coal_type,
  grade = EXCLUDED.grade,
  calorific_value_kcal_kg = EXCLUDED.calorific_value_kcal_kg,
  moisture_percent = EXCLUDED.moisture_percent,
  ash_percent = EXCLUDED.ash_percent,
  sulfur_percent = EXCLUDED.sulfur_percent,
  size_mm = EXCLUDED.size_mm,
  annual_capacity_tonnes = EXCLUDED.annual_capacity_tonnes,
  available_stock_tonnes = EXCLUDED.available_stock_tonnes,
  mining_method = EXCLUDED.mining_method,
  price_per_tonne_usd = EXCLUDED.price_per_tonne_usd,
  price_basis = EXCLUDED.price_basis,
  minimum_order_tonnes = EXCLUDED.minimum_order_tonnes,
  payment_terms = EXCLUDED.payment_terms,
  contract_types = EXCLUDED.contract_types,
  loading_port = EXCLUDED.loading_port,
  transport_modes = EXCLUDED.transport_modes,
  lead_time_days = EXCLUDED.lead_time_days,
  export_license = EXCLUDED.export_license,
  certifications = EXCLUDED.certifications,
  updated_at = NOW();
