-- ============================================================
-- Turkmenistan Oil Production Sites — 17 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- WESTERN TURKMENISTAN (ONSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Nebitdag Field', 'Turkmenneft', 'Balkan Province — Western Turkmenistan', NULL, 'Energy', 'Crude Oil', 39.5167, 54.3667, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 32.00, 0.80, 450000, 50000000, 450000, '{"start_year":1909,"production_bpd":15000,"quality":"Medium","note":"Tsarist era discovery; one of Turkmenistan''s oldest fields; mature, declining","contract_duration":"State concession (perpetual)","pipelines":"Nebitdag → Turkmenbashi (Krasnovodsk) refinery pipeline (~50km west)","ports":"Turkmenbashi Caspian Port (tanker to Azerbaijan/Iran)","rail":"Turkmenbashi–Ashgabat Trans-Caspian rail line"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Koturdepe Field', 'Turkmenneft', 'Balkan Province — Western Turkmenistan', NULL, 'Energy', 'Crude Oil', 39.6333, 54.1167, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 31.00, 0.90, 600000, 80000000, 600000, '{"start_year":1948,"production_bpd":20000,"quality":"Medium","note":"Mature field","contract_duration":"State concession","pipelines":"Koturdepe → Turkmenbashi refinery pipeline","ports":"Turkmenbashi Caspian Port","rail":"Turkmenbashi rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cheleken Field', 'Dragon Oil (ENOC) + Turkmenneft', 'Cheleken Peninsula, Balkan Province', NULL, 'Energy', 'Crude Oil', 39.4333, 53.1167, 'Turkmenistan', 'Balkan Province', 'Hazar', 'oil_field', 'operational', 'Dragon Oil (ENOC)', 'joint_venture', 33.00, 0.70, 1500000, 200000000, 1500000, '{"start_year":1999,"production_bpd":50000,"quality":"Medium light","note":"One of world''s earliest oil fields (1876); Dragon Oil ~45,000 bpd; Dragon Oil 100% operational rights via PSA; Turkmenneft retains sovereign ownership","last_transaction":"Dragon Oil PSA signed 2000; ENOC took private 2015 (~$3.7B valuation)","contract_duration":"PSA to 2025 (under renegotiation)","pipelines":"Cheleken → Turkmenbashi refinery (~80km); tanker export via Caspian Sea","ports":"Turkmenbashi Caspian Port (tanker to Baku → BTC pipeline)","rail":"Turkmenbashi rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Goturdepe Field', 'Dragon Oil (ENOC) + Turkmenneft', 'Cheleken area', NULL, 'Energy', 'Crude Oil', 39.5000, 53.2500, 'Turkmenistan', 'Balkan Province', 'Hazar', 'oil_field', 'operational', 'Dragon Oil (ENOC)', 'joint_venture', 32.00, 0.80, 150000, NULL, 150000, '{"start_year":"1960s","production_bpd":5000,"quality":"Medium","note":"Dragon Oil legacy field on Cheleken; part of Dragon Oil Cheleken total; redeveloped 2000s","contract_duration":"Dragon Oil PSA","pipelines":"Cheleken gathering → Turkmenbashi","ports":"Turkmenbashi","rail":"Turkmenbashi"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Barsa-Gelmes Field', 'Turkmenneft', 'Western Turkmenistan — Balkan', NULL, 'Energy', 'Crude Oil', 39.7500, 54.5000, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 30.00, 1.10, 240000, NULL, 240000, '{"start_year":1956,"production_bpd":8000,"quality":"Medium sour","note":"Mature field","contract_duration":"State concession","pipelines":"Barsa-Gelmes → Nebitdag → Turkmenbashi refinery","ports":"Turkmenbashi","rail":"Balkan Province rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kum-Dag Field', 'Turkmenneft', 'Balkan Province — onshore western', NULL, 'Energy', 'Crude Oil', 39.2167, 54.6167, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 31.00, 0.90, 300000, 40000000, 300000, '{"start_year":1942,"production_bpd":10000,"quality":"Medium","note":"Soviet WWII-era development; mature","contract_duration":"State concession","pipelines":"Kum-Dag → Turkmenbashi refinery pipeline","ports":"Turkmenbashi","rail":"Turkmenbashi–Balkanabat rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Balkanabat (Nebit-Dag) Cluster', 'Turkmenneft', 'Balkan Province — multiple small fields around Balkanabat', NULL, 'Energy', 'Crude Oil', 39.5500, 54.3833, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 31.00, NULL, 360000, NULL, 360000, '{"start_year":"1930s","production_bpd":12000,"quality":"Medium sour","note":"Combined cluster; Soviet era","contract_duration":"State concession","pipelines":"Balkanabat cluster → Turkmenbashi refinery","ports":"Turkmenbashi","rail":"Balkanabat rail hub (Trans-Caspian Railway)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Uzynada Field', 'Turkmenneft', 'Balkan Province — onshore', NULL, 'Energy', 'Crude Oil', 39.3333, 54.0000, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 33.00, NULL, 150000, NULL, 150000, '{"start_year":1968,"production_bpd":5000,"quality":"Medium light","note":"Onshore Balkan","contract_duration":"State concession","pipelines":"Uzynada → Turkmenbashi system","ports":"Turkmenbashi","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gyzylgaya Field', 'Turkmenneft', 'Balkan Province', NULL, 'Energy', 'Crude Oil', 39.8333, 54.7500, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 30.00, NULL, 120000, NULL, 120000, '{"start_year":1972,"production_bpd":4000,"quality":"Medium sour","note":"Northern Balkan","contract_duration":"State concession","pipelines":"Northern Balkan → Turkmenbashi","ports":"Turkmenbashi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ak-Patlauk Field', 'Turkmenneft', 'Western Turkmenistan', NULL, 'Energy', 'Crude Oil', 39.1667, 54.5000, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 32.00, NULL, 90000, NULL, 90000, '{"start_year":1975,"production_bpd":3000,"quality":"Medium","note":"Smaller field","contract_duration":"State concession","pipelines":"Balkan gathering → Turkmenbashi","ports":"Turkmenbashi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gokdere Field', 'Turkmenneft', 'Balkan Province — southern', NULL, 'Energy', 'Crude Oil', 38.8333, 54.1667, 'Turkmenistan', 'Balkan Province', 'Balkanabat', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 31.00, NULL, 105000, NULL, 105000, '{"start_year":1980,"production_bpd":3500,"quality":"Medium","note":"Southern Balkan","contract_duration":"State concession","pipelines":"Southern Balkan → Turkmenbashi","ports":"Turkmenbashi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CASPIAN SEA (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lam Field', 'Turkmenneft', 'Offshore Caspian — Turkmen sector', NULL, 'Energy', 'Crude Oil', 39.8333, 52.8333, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 34.00, 0.50, 450000, 400000000, 450000, '{"start_year":1972,"production_bpd":15000,"quality":"Medium light","note":"Soviet offshore development; LAM field","contract_duration":"State license","pipelines":"LAM → offshore platform → tanker loading","ports":"Turkmenbashi Caspian Export Terminal","rail":"None offshore"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Livanov Field', 'Turkmenneft', 'Offshore Caspian — Turkmen sector', NULL, 'Energy', 'Crude Oil', 40.0000, 52.6667, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'operational', 'Turkmenneft', 'state_owned', 33.00, 0.60, 300000, 250000000, 300000, '{"start_year":1978,"production_bpd":10000,"quality":"Medium light","note":"Offshore Caspian","contract_duration":"State license","pipelines":"Offshore → Turkmenbashi tanker","ports":"Turkmenbashi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Magtymguly (Okarem) Field', 'CNPC + Turkmenneft', 'Offshore Caspian — southern Turkmen sector', NULL, 'Energy', 'Crude Oil', 38.5000, 53.0000, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'operational', 'CNPC + Turkmenneft', 'joint_venture', 35.00, 0.40, 600000, 500000000, 600000, '{"start_year":2010,"production_bpd":20000,"quality":"Medium light","note":"CNPC 50%, Turkmenneft 50%; China''s first Caspian offshore agreement","last_transaction":"CNPC PSA signed 2007","contract_duration":"PSA to 2035","pipelines":"Offshore → Turkmenbashi tanker loading","ports":"Turkmenbashi","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Serdar (Kapaz) Field', 'Turkmenneft / SOCAR (disputed)', 'Offshore Caspian — disputed with Azerbaijan', NULL, 'Energy', 'Crude Oil', 40.3333, 51.6667, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'inactive', 'Disputed', 'joint_venture', 34.00, NULL, 0, 1000000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Medium light (estimated)","note":"Block 1 — Turkmenistan calls Serdar, Azerbaijan calls Kapaz; ownership unresolved since 1991; Soviet production 1950s–1980s halted post-1991; 2018 Caspian Convention did not resolve bilateral dispute","last_transaction":"Multiple failed negotiation rounds 1997–2023","contract_duration":"Disputed","pipelines":"None (undeveloped due to dispute)","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 2 (Offshore)', 'Dragon Oil + Turkmenneft', 'Offshore Caspian — Turkmen sector, near Iran border', NULL, 'Energy', 'Crude Oil', 38.1667, 52.5000, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'planned', 'Dragon Oil + Turkmenneft', 'joint_venture', NULL, NULL, 0, 300000000, 0, '{"start_year":2012,"production_bpd":0,"quality":"TBD","note":"Dragon Oil 50%, Turkmenneft 50%; exploration/pre-development","last_transaction":"Dragon Oil PSA Block 2 signed 2012","contract_duration":"PSA to 2032","pipelines":"None yet","ports":"Turkmenbashi (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dostluk Field', 'Turkmenistan + Azerbaijan', 'Offshore Caspian — joint Turkmenistan/Azerbaijan', NULL, 'Energy', 'Crude Oil', 39.8333, 51.9167, 'Turkmenistan', 'Caspian Sea', 'Turkmenbashi', 'oil_field', 'planned', 'Turkmenneft + SOCAR', 'joint_venture', 34.00, NULL, 0, 600000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Medium light (estimated)","note":"Turkmenistan 50%, Azerbaijan 50%; historic Dostluk (Friendship) agreement January 2021 — first joint Turkmen-Azeri Caspian development; FID expected 2025–2026","last_transaction":"Turkmenistan + Azerbaijan signed Dostluk agreement January 2021","contract_duration":"Joint development agreement 2021","pipelines":"Planned → Baku hub → BTC pipeline → Ceyhan, Turkey (Mediterranean) — first Turkmen access to BTC","ports":"Turkmenbashi + Baku (joint export via BTC)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Turkmenistan' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Turkmenistan' AND commodity_name = 'Crude Oil' ORDER BY region, operational_status, title;
