-- ============================================================
-- Russia Oil Production Sites — 56 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- WESTERN SIBERIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Samotlor Field', 'Rosneft', 'Khanty-Mansiysk Autonomous Okrug, Western Siberia', NULL, 'Energy', 'Crude Oil', 61.0833, 76.8333, 'Russia', 'Khanty-Mansiysk', 'Nizhnevartovsk', 'oil_field', 'operational', 'Rosneft (TNK-BP legacy)', 'state_owned', 29.00, 1.80, 7200000, 1500000000, 7200000, '{"start_year":1969,"production_bpd":240000,"quality":"Medium sour — Urals blend contributor","note":"Mature, EOR; declining from peak ~3.4M bpd (1980)","ooip":"28 billion barrels","last_transaction":"Rosneft acquired TNK-BP from BP and AAR for $55B (2013) — largest oil deal in Russian history","pipelines":"Samotlor → Transneft West Siberia trunk → Druzhba pipeline","ports":"Primorsk Baltic; Novorossiysk Black Sea; Ust-Luga","rail":"Nizhnevartovsk–Surgut rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Priobskoye Field', 'Rosneft / Gazprom Neft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.3333, 69.5000, 'Russia', 'Khanty-Mansiysk', 'Khanty-Mansiysk', 'oil_field', 'operational', 'Rosneft (Yuganskneftegaz) + Gazprom Neft', 'joint_venture', 30.00, 1.50, 13500000, 5000000000, 13500000, '{"start_year":1988,"production_bpd":450000,"quality":"Medium sour","note":"Russia''s current largest single producing field","ownership_split":"Rosneft 50.08%, Gazprom Neft 49.92%","last_transaction":"Yukos → Yuganskneftegaz expropriation 2004 (Rosneft ~$9.35B state auction)","pipelines":"Priobskoye → Transneft Western Siberia → ESPO + Druzhba","ports":"Primorsk, Novorossiysk, Kozmino (ESPO)","rail":"Surgut–Khanty-Mansiysk rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Fedorovskoye Field', 'Surgutneftegaz', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.4667, 73.8833, 'Russia', 'Khanty-Mansiysk', 'Surgut', 'oil_field', 'operational', 'Surgutneftegaz', 'private', 31.00, 1.60, 6000000, 2000000000, 6000000, '{"start_year":1971,"production_bpd":200000,"quality":"Medium sour","maturity":"Mature","pipelines":"Fedorovskoye → Surgut → Transneft West Siberia trunk","ports":"Primorsk, Novorossiysk","rail":"Surgut rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Malobalykskoye Field', 'Rosneft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.0000, 69.3333, 'Russia', 'Khanty-Mansiysk', 'Khanty-Mansiysk', 'oil_field', 'operational', 'Rosneft (Yuganskneftegaz)', 'state_owned', 30.00, 1.50, 3000000, NULL, 3000000, '{"start_year":1982,"production_bpd":100000,"quality":"Medium sour","pipelines":"West Siberia → Transneft trunk","ports":"Primorsk, Novorossiysk","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Salym Fields Cluster', 'Gazprom Neft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 60.5833, 70.6667, 'Russia', 'Khanty-Mansiysk', 'Salym', 'oil_field', 'operational', 'Gazprom Neft', 'state_owned', 31.00, 1.50, 3900000, 700000000, 3900000, '{"start_year":2004,"production_bpd":130000,"quality":"Medium sour","note":"Gazprom Neft acquired Shell''s 50% stake 2022; Shell exited post-Ukraine sanctions","last_transaction":"Shell sold 50% to Gazprom Neft for ~$95M (2022) — forced exit post-Ukraine invasion","pipelines":"Salym → Transneft West Siberia","ports":"Primorsk","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lyantorskoye Field', 'Surgutneftegaz', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.6167, 72.5000, 'Russia', 'Khanty-Mansiysk', 'Surgut', 'oil_field', 'operational', 'Surgutneftegaz', 'private', 30.00, 1.50, 2400000, NULL, 2400000, '{"start_year":1978,"production_bpd":80000,"quality":"Medium sour","pipelines":"Lyantor → Surgut → Transneft","ports":"Primorsk, Novorossiysk","rail":"Surgut rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tevlinsko-Russkinskoye Field', 'Surgutneftegaz', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.8333, 73.0833, 'Russia', 'Khanty-Mansiysk', 'Surgut', 'oil_field', 'operational', 'Surgutneftegaz', 'private', 29.00, 1.60, 3000000, NULL, 3000000, '{"start_year":1986,"production_bpd":100000,"quality":"Medium sour","pipelines":"West Siberia Surgutneftegaz network → Transneft","ports":"Primorsk","rail":"Surgut"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kholmogorskoye Field', 'Rosneft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 62.5000, 73.8333, 'Russia', 'Khanty-Mansiysk', 'Nizhnevartovsk', 'oil_field', 'operational', 'Rosneft', 'state_owned', 31.00, 1.50, 1200000, NULL, 1200000, '{"start_year":1978,"production_bpd":40000,"quality":"Medium sour","maturity":"Mature","pipelines":"Northern KMAO → Transneft","ports":"Primorsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Povkhovskoye Field', 'Lukoil', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.5833, 75.6667, 'Russia', 'Khanty-Mansiysk', 'Nizhnevartovsk', 'oil_field', 'operational', 'Lukoil (West Siberia)', 'private', 30.00, 1.50, 1800000, NULL, 1800000, '{"start_year":1982,"production_bpd":60000,"quality":"Medium sour","pipelines":"Lukoil West Siberia → Transneft trunk","ports":"Primorsk, Novorossiysk","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yuzhno-Balykskoe / Mamontovo Field', 'Rosneft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 60.9167, 73.2500, 'Russia', 'Khanty-Mansiysk', 'Nizhnevartovsk', 'oil_field', 'operational', 'Rosneft', 'state_owned', 30.00, 1.50, 1500000, NULL, 1500000, '{"start_year":1975,"production_bpd":50000,"quality":"Medium sour","maturity":"Mature","pipelines":"South Balyk → Transneft","ports":"Primorsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Krasnoleninskoe Field Cluster', 'Gazprom Neft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.2500, 66.5000, 'Russia', 'Khanty-Mansiysk', 'Khanty-Mansiysk', 'oil_field', 'operational', 'Gazprom Neft', 'state_owned', 32.00, 1.40, 2400000, NULL, 2400000, '{"start_year":1976,"production_bpd":80000,"quality":"Medium light","pipelines":"West KMAO → Transneft","ports":"Primorsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yuganskaya Group', 'Rosneft', 'KMAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.1667, 72.5833, 'Russia', 'Khanty-Mansiysk', 'Nizhnevartovsk', 'oil_field', 'operational', 'Rosneft (Yuganskneftegaz)', 'state_owned', 30.00, 1.50, 30000000, NULL, 30000000, '{"start_year":"1970s","production_bpd":1000000,"quality":"Medium sour (Urals blend)","note":"Yuganskneftegaz totals across all fields — Russia''s largest single production subsidiary; formerly Yukos flagship","last_transaction":"Yuganskneftegaz auctioned from Yukos for $9.35B (2004) — most controversial oil expropriation in modern history","pipelines":"Multiple KMAO → Transneft","ports":"Primorsk, Novorossiysk, Ust-Luga","rail":"Various KMAO hubs"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vyngapurovskoye Field', 'Gazprom Neft', 'Yamalo-Nenets AO, Western Siberia', NULL, 'Energy', 'Crude Oil', 63.2500, 75.8333, 'Russia', 'Yamalo-Nenets', 'Noyabrsk', 'oil_field', 'operational', 'Gazprom Neft', 'state_owned', 31.00, 1.50, 1500000, NULL, 1500000, '{"start_year":1978,"production_bpd":50000,"quality":"Medium sour","pipelines":"YNAO → Transneft","ports":"Primorsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Muravlenkovskoye Field', 'Gazprom Neft', 'YNAO, Western Siberia', NULL, 'Energy', 'Crude Oil', 63.7833, 74.5000, 'Russia', 'Yamalo-Nenets', 'Noyabrsk', 'oil_field', 'operational', 'Gazprom Neft (Noyabrskneftegaz)', 'state_owned', 30.00, 1.50, 1200000, NULL, 1200000, '{"start_year":1975,"production_bpd":40000,"quality":"Medium sour","maturity":"Mature","pipelines":"Muravlenko → YNAO Transneft trunk","ports":"Primorsk","rail":"Noyabrsk rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kholmogorskoye North', 'Rosneft', 'YNAO, Western Siberia', NULL, 'Energy', 'Crude Oil', 62.8333, 74.1667, 'Russia', 'Yamalo-Nenets', 'Noyabrsk', 'oil_field', 'operational', 'Rosneft', 'state_owned', 31.00, 1.50, 600000, NULL, 600000, '{"start_year":1980,"production_bpd":20000,"quality":"Medium sour","pipelines":"YNAO → Transneft","ports":"Primorsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lukoil West Siberia Cluster', 'Lukoil', 'KMAO/YNAO, West Siberia', NULL, 'Energy', 'Crude Oil', 61.7500, 74.5000, 'Russia', 'Khanty-Mansiysk', 'Surgut', 'oil_field', 'operational', 'Lukoil (West Siberia subsidiary)', 'private', 30.00, 1.50, 24000000, 5000000000, 24000000, '{"start_year":"1970s","production_bpd":800000,"quality":"Medium sour, Urals blend","note":"Lukoil WS totals — Lukoil''s largest production unit","pipelines":"Multiple KMAO/YNAO → Transneft","ports":"Primorsk, Novorossiysk, Ust-Luga","rail":"Surgut, Noyabrsk hubs"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VOLGA-URALS
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Romashkino Field', 'Tatneft', 'Tatarstan Republic', NULL, 'Energy', 'Crude Oil', 54.5500, 52.5167, 'Russia', 'Tatarstan', 'Almetyevsk', 'oil_field', 'operational', 'Tatneft', 'state_owned', 31.00, 1.60, 7200000, 800000000, 7200000, '{"start_year":1948,"production_bpd":240000,"quality":"Medium sour — Urals blend major contributor","note":"Mature — world''s 4th largest field historically; declining from peak ~1.7M bpd (1970)","ooip":"17 billion barrels","ownership":"Tatneft 100% (Tatarstan Republic effectively controls; 36% state-owned)","pipelines":"Romashkino → Transneft Druzhba pipeline; Almetyevsk hub","ports":"Primorsk Baltic; Novorossiysk Black Sea via Druzhba","rail":"Almetyevsk–Bugulma rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bavlinskoye Field', 'Tatneft', 'Tatarstan Republic', NULL, 'Energy', 'Crude Oil', 54.4000, 53.2500, 'Russia', 'Tatarstan', 'Bugulma', 'oil_field', 'operational', 'Tatneft', 'state_owned', 29.00, 1.60, 450000, 200000000, 450000, '{"start_year":1950,"production_bpd":15000,"quality":"Medium sour","maturity":"Mature","pipelines":"Tatarstan → Druzhba","ports":"Primorsk, Novorossiysk","rail":"Bugulma rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Arlanskoe Field', 'Rosneft', 'Bashkortostan Republic', NULL, 'Energy', 'Crude Oil', 55.9167, 54.5833, 'Russia', 'Bashkortostan', 'Ufa', 'oil_field', 'operational', 'Bashneft (Rosneft subsidiary)', 'state_owned', 28.00, 2.00, 1800000, 1500000000, 1800000, '{"start_year":1955,"production_bpd":60000,"quality":"Medium heavy sour","maturity":"Mature","last_transaction":"Rosneft acquired Bashneft from Sistema for $5.3B (2016) — controversial privatization reversal","pipelines":"Bashkortostan → Transneft Urals → Druzhba","ports":"Primorsk, Novorossiysk","rail":"Ufa rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shkapovskoe Field', 'Rosneft', 'Bashkortostan Republic', NULL, 'Energy', 'Crude Oil', 54.1667, 54.1667, 'Russia', 'Bashkortostan', 'Ufa', 'oil_field', 'operational', 'Bashneft (Rosneft)', 'state_owned', 30.00, 1.50, 600000, NULL, 600000, '{"start_year":1953,"production_bpd":20000,"quality":"Medium sour","maturity":"Mature","pipelines":"Bashkortostan → Druzhba","ports":"Primorsk","rail":"Ufa"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tuimazinskoye Field', 'Rosneft', 'Bashkortostan Republic', NULL, 'Energy', 'Crude Oil', 54.6000, 53.7000, 'Russia', 'Bashkortostan', 'Tuimazy', 'oil_field', 'operational', 'Bashneft (Rosneft)', 'state_owned', 31.00, 1.50, 450000, 100000000, 450000, '{"start_year":1944,"production_bpd":15000,"quality":"Medium sour","note":"One of USSR''s first major fields; very mature","pipelines":"Tuimazy → Druzhba pipeline (historical first connection point)","ports":"Primorsk, Novorossiysk","rail":"Tuimazy–Ufa rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Orenburgskoe Gas Condensate Field', 'Gazprom', 'Orenburg Oblast', NULL, 'Energy', 'Crude Oil', 52.0833, 55.1500, 'Russia', 'Orenburg', 'Orenburg', 'oil_field', 'operational', 'Gazprom (Orenburggazprom)', 'state_owned', 46.00, 0.10, 600000, 800000000, 600000, '{"start_year":1971,"production_bpd":20000,"quality":"Condensate sweet","note":"Gas + condensate","pipelines":"Orenburg → Soyuz gas pipeline (to Ukraine/Europe); condensate → Orenburg refinery","ports":"None direct (landlocked)","rail":"Orenburg rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Novo-Elkhovo Field', 'Tatneft', 'Tatarstan Republic', NULL, 'Energy', 'Crude Oil', 54.7500, 52.7500, 'Russia', 'Tatarstan', 'Almetyevsk', 'oil_field', 'operational', 'Tatneft', 'state_owned', 29.00, 1.60, 600000, NULL, 600000, '{"start_year":1958,"production_bpd":20000,"quality":"Medium sour","pipelines":"Tatarstan gathering → Druzhba","ports":"Primorsk","rail":"Almetyevsk"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Pervomaiskoye / Yuzhnyi Tatarstan Fields', 'Tatneft', 'Tatarstan cluster', NULL, 'Energy', 'Crude Oil', 54.2500, 51.8333, 'Russia', 'Tatarstan', 'Bugulma', 'oil_field', 'operational', 'Tatneft', 'state_owned', 30.00, 1.50, 750000, NULL, 750000, '{"start_year":"1960s","production_bpd":25000,"quality":"Medium sour","pipelines":"Tatarstan → Druzhba","ports":"Primorsk, Novorossiysk","rail":"Bugulma–Almetyevsk rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Perm Krai Fields — Lukoil Perm', 'Lukoil', 'Perm Krai', NULL, 'Energy', 'Crude Oil', 58.0000, 56.2500, 'Russia', 'Perm Krai', 'Perm', 'oil_field', 'operational', 'Lukoil (Lukoil-Perm subsidiary)', 'private', 29.00, 1.90, 5400000, 1500000000, 5400000, '{"start_year":"1930s","production_bpd":180000,"quality":"Medium heavy sour","note":"Permian Basin Russia; various 1930s–1970s","pipelines":"Perm → Transneft Druzhba","ports":"Primorsk (via Druzhba)","rail":"Perm rail hub (Trans-Siberian junction)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Samara Oblast Fields — Samaraneftegaz', 'Rosneft', 'Samara Oblast', NULL, 'Energy', 'Crude Oil', 53.5000, 51.5833, 'Russia', 'Samara Oblast', 'Samara', 'oil_field', 'operational', 'Rosneft (Samaraneftegaz)', 'state_owned', 30.00, 1.50, 1800000, NULL, 1800000, '{"start_year":1936,"production_bpd":60000,"quality":"Medium sour","note":"Mature cluster; Zhigulevsk area among USSR''s earliest; Samara key Druzhba routing node","pipelines":"Samara → Druzhba","ports":"Primorsk, Novorossiysk","rail":"Samara rail major hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Udmurtia Fields — Udmurtneft', 'Rosneft / CNPC', 'Udmurtia Republic', NULL, 'Energy', 'Crude Oil', 57.0000, 53.0000, 'Russia', 'Udmurtia', 'Izhevsk', 'oil_field', 'operational', 'Udmurtneft (Rosneft 51%, CNPC 49% JV)', 'joint_venture', 25.00, 2.30, 3600000, 600000000, 3600000, '{"start_year":1969,"production_bpd":120000,"quality":"Heavy sour","ownership_split":"Rosneft 51%, CNPC 49%","last_transaction":"CNPC acquired 49% of Udmurtneft for $3.5B (2006) — major early CNPC Russia entry","pipelines":"Udmurtia → Druzhba trunk","ports":"Primorsk","rail":"Izhevsk rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- EASTERN SIBERIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vankor Field', 'Rosneft / Indian consortium', 'Krasnoyarsk Krai, Eastern Siberia', NULL, 'Energy', 'Crude Oil', 67.8333, 83.5000, 'Russia', 'Krasnoyarsk Krai', 'Vankor', 'oil_field', 'operational', 'Rosneft (Vankorneft)', 'joint_venture', 35.00, 0.20, 9900000, 3400000000, 9900000, '{"start_year":2009,"production_bpd":330000,"quality":"Light — ESPO blend contributor (premium Asian-facing crude)","note":"Eastern Siberia''s largest; greenfield development","ownership_split":"Rosneft 50.1%; ONGC Videsh 26%, Oil India + Indian Oil 23.9%","last_transaction":"Indian consortium acquired 49.9% for ~$3.2B (2016) — largest Indian overseas oil acquisition","pipelines":"Vankor → ESPO pipeline (4,857km → Kozmino Pacific terminal)","ports":"Kozmino Pacific Export Terminal; Dudinka Arctic port (backup barge)","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Suzun Field', 'Rosneft', 'Krasnoyarsk Krai — Vankor cluster', NULL, 'Energy', 'Crude Oil', 67.5000, 83.2500, 'Russia', 'Krasnoyarsk Krai', 'Vankor', 'oil_field', 'operational', 'Rosneft (Vankorneft)', 'state_owned', 36.00, 0.20, 1500000, 500000000, 1500000, '{"start_year":2016,"production_bpd":50000,"quality":"Light, ESPO blend","note":"Vankor cluster development","pipelines":"Suzun → Vankor → ESPO","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tagul Field', 'Rosneft', 'Krasnoyarsk Krai — Vankor cluster', NULL, 'Energy', 'Crude Oil', 66.6667, 82.5000, 'Russia', 'Krasnoyarsk Krai', 'Vankor', 'oil_field', 'operational', 'Rosneft', 'state_owned', 35.00, 0.20, 900000, NULL, 900000, '{"start_year":2017,"production_bpd":30000,"quality":"Light","pipelines":"Tagul → Vankor → ESPO","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lodochnoye Field', 'Rosneft', 'Krasnoyarsk Krai — Vankor cluster', NULL, 'Energy', 'Crude Oil', 66.3333, 82.0000, 'Russia', 'Krasnoyarsk Krai', 'Vankor', 'oil_field', 'operational', 'Rosneft', 'state_owned', 35.00, 0.20, 600000, NULL, 600000, '{"start_year":2018,"production_bpd":20000,"quality":"Light","pipelines":"Vankor cluster → ESPO","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yurubcheno-Tokhomskoe Field', 'Rosneft', 'Krasnoyarsk Krai', NULL, 'Energy', 'Crude Oil', 62.3333, 96.6667, 'Russia', 'Krasnoyarsk Krai', 'Yurubchen', 'oil_field', 'operational', 'Rosneft', 'state_owned', 37.00, 0.15, 600000, 2000000000, 600000, '{"start_year":2017,"production_bpd":20000,"quality":"Light sweet, ESPO","note":"Development; slow ramp-up; targeting 100,000+ bpd","pipelines":"Yurubcheno → ESPO connection (under development)","ports":"Kozmino (planned full integration)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Verkhne-Chonskoye Field', 'Rosneft / Surgutneftegaz', 'Irkutsk Oblast', NULL, 'Energy', 'Crude Oil', 61.5000, 107.5000, 'Russia', 'Irkutsk Oblast', 'Taishet', 'oil_field', 'operational', 'Rosneft (Verkhnechonskneftegaz)', 'joint_venture', 38.00, 0.15, 3000000, 1300000000, 3000000, '{"start_year":2008,"production_bpd":100000,"quality":"Light sweet, ESPO blend (premium)","ownership_split":"Rosneft 96.86%, Surgutneftegaz 3.14%","pipelines":"Verkhne-Chonskoe → ESPO pipeline (Taishet start point)","ports":"Kozmino Pacific Terminal","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Talakan Field', 'Surgutneftegaz', 'Sakha Republic — Yakutia', NULL, 'Energy', 'Crude Oil', 60.5000, 118.0833, 'Russia', 'Sakha Republic', 'Talakan', 'oil_field', 'operational', 'Surgutneftegaz', 'private', 39.00, 0.15, 1800000, 1100000000, 1800000, '{"start_year":2008,"production_bpd":60000,"quality":"Light sweet, ESPO blend","pipelines":"Talakan → ESPO pipeline (Taishet)","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Srednebotuobinskoye Field', 'Rosneft / Surgutneftegaz', 'Sakha Republic', NULL, 'Energy', 'Crude Oil', 63.0000, 119.5000, 'Russia', 'Sakha Republic', 'Srednebotuobinsk', 'oil_field', 'operational', 'Rosneft + Surgutneftegaz', 'joint_venture', 36.00, 0.15, 1200000, 600000000, 1200000, '{"start_year":2013,"production_bpd":40000,"quality":"Light sweet","ownership_split":"Rosneft 99.9%","pipelines":"Srednebotuobinskoye → ESPO","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dulisminskoye Field', 'Irkutsk Oil Company', 'Irkutsk Oblast', NULL, 'Energy', 'Crude Oil', 58.5833, 107.0000, 'Russia', 'Irkutsk Oblast', 'Ust-Kut', 'oil_field', 'operational', 'Irkutsk Oil Company (INK)', 'private', 37.00, 0.15, 900000, 300000000, 900000, '{"start_year":2011,"production_bpd":30000,"quality":"Light sweet, ESPO","note":"INK — one of Russia''s largest private independents","last_transaction":"INK raised $600M Eurobond 2019","pipelines":"INK fields → ESPO (Taishet)","ports":"Kozmino","rail":"Trans-Siberian Railway (Ust-Kut junction)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yarakta Field', 'Irkutsk Oil Company', 'Irkutsk Oblast', NULL, 'Energy', 'Crude Oil', 60.0833, 105.8333, 'Russia', 'Irkutsk Oblast', 'Ust-Kut', 'oil_field', 'operational', 'INK (Irkutsk Oil Company)', 'private', 38.00, 0.15, 2400000, 600000000, 2400000, '{"start_year":2014,"production_bpd":80000,"quality":"Light sweet, ESPO","note":"INK flagship field","pipelines":"Yarakta → ESPO (INK pipeline to Taishet)","ports":"Kozmino","rail":"Ust-Kut rail (BAM railway)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kuyumba Field', 'Slavneft (Rosneft / Gazprom Neft)', 'Krasnoyarsk Krai', NULL, 'Energy', 'Crude Oil', 60.3333, 97.5000, 'Russia', 'Krasnoyarsk Krai', 'Taishet', 'oil_field', 'operational', 'Slavneft (Rosneft + Gazprom Neft 50/50 JV)', 'joint_venture', 36.00, 0.15, 750000, 600000000, 750000, '{"start_year":2017,"production_bpd":25000,"quality":"Light, ESPO","ownership_split":"Rosneft 50%, Gazprom Neft 50%","pipelines":"Kuyumba → Taishet → ESPO","ports":"Kozmino","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- RUSSIAN ARCTIC
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Prirazlomnoye Field', 'Gazprom Neft', 'Pechora Sea, offshore Arctic', NULL, 'Energy', 'Crude Oil', 69.2500, 57.3333, 'Russia', 'Nenets AO', 'Murmansk', 'oil_field', 'operational', 'Gazprom Neft', 'state_owned', 23.00, 2.50, 2400000, 500000000, 2400000, '{"start_year":2013,"production_bpd":80000,"quality":"Heavy sour — ARCO crude (Arctic Oil) unique export grade","note":"Russia''s first Arctic offshore oil field; landmark ice-resistant platform","last_transaction":"Greenpeace Arctic Sunrise protest/seizure 2013; ~$4.5B total development","pipelines":"Prirazlomnoye → ARCO shuttle tanker → Murmansk terminal (tanker only)","ports":"Murmansk Arctic Export Terminal; Varandey terminal","rail":"None (Arctic offshore)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Novoportovskoye Field', 'Gazprom Neft', 'Yamal Peninsula, onshore Arctic', NULL, 'Energy', 'Crude Oil', 67.6667, 72.6667, 'Russia', 'Yamalo-Nenets', 'Novy Port', 'oil_field', 'operational', 'Gazprom Neft', 'state_owned', 46.00, 0.10, 3300000, 1300000000, 3300000, '{"start_year":2014,"production_bpd":110000,"quality":"Light sweet — Novy Port crude Arctic premium grade","note":"Arctic onshore","last_transaction":"~$1.7B development investment 2012–2016","pipelines":"Novoportovskoye → Arctic Gate floating terminal (Ob Bay) → tankers","ports":"Arctic Gate Terminal (Ob estuary); Sabetta LNG port (nearby)","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Messoyakha Fields — East + West', 'Rosneft / Gazprom Neft', 'YNAO Arctic', NULL, 'Energy', 'Crude Oil', 67.3333, 82.8333, 'Russia', 'Yamalo-Nenets', 'Messoyakha', 'oil_field', 'operational', 'Rosneft + Gazprom Neft (50/50 JV)', 'joint_venture', 34.00, 0.50, 3300000, 1800000000, 3300000, '{"start_year":2016,"production_bpd":110000,"quality":"Medium light","ownership_split":"Rosneft 50%, Gazprom Neft 50%","last_transaction":"JV formed 2014; East Messoyakha FID 2014 ~$5B","pipelines":"Messoyakha → Vankor → ESPO + Arctic tanker loading","ports":"Dudinka (Yenisei River); Kozmino (via ESPO)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Payakha Field', 'Rosneft', 'Krasnoyarsk Krai — Arctic', NULL, 'Energy', 'Crude Oil', 71.0000, 82.8333, 'Russia', 'Krasnoyarsk Krai', 'Sever Bay', 'oil_field', 'planned', 'Rosneft (Neftegazholding)', 'state_owned', 42.00, 0.10, 0, 1200000000, 0, '{"note":"Development — massive planned project; planned 2024–2026","production_bpd":"Target ~100,000 Phase 1; ~600,000 ultimately","quality":"Light sweet (preliminary)","potential_reserves":"~5B total","last_transaction":"Rosneft acquired Neftegazholding for ~$9B (2019)","pipelines":"Planned Northern Sea Route (NSR) tanker → Sever Bay terminal","ports":"Planned Sever Bay Arctic Terminal (Yenisei Bay)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Titovskoe / Trebs & Titov Fields', 'Rosneft / Lukoil', 'Nenets AO, Timan-Pechora', NULL, 'Energy', 'Crude Oil', 67.5000, 52.5000, 'Russia', 'Nenets AO', 'Varandey', 'oil_field', 'operational', 'Bashneft-Polyus (Rosneft) + Lukoil', 'joint_venture', 34.00, 0.90, 2400000, 700000000, 2400000, '{"start_year":2013,"production_bpd":80000,"quality":"Medium","ownership_split":"Rosneft 74.9% (Bashneft-Polyus), Lukoil 25.1%","last_transaction":"Lukoil/Bashneft PSA signed 2010; Bashneft → Rosneft transferred 2016","pipelines":"Trebs/Titov → Varandey Arctic terminal; Transneft Timan-Pechora","ports":"Varandey Arctic Oil Terminal; Primorsk (via Transneft)","rail":"None direct"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yuzhno-Khylchuyu Field', 'Lukoil', 'Nenets AO — Timan-Pechora', NULL, 'Energy', 'Crude Oil', 68.1667, 53.8333, 'Russia', 'Nenets AO', 'Varandey', 'oil_field', 'operational', 'Lukoil (Naryanmarneftegaz)', 'private', 36.00, 0.60, 2400000, 700000000, 2400000, '{"start_year":2008,"production_bpd":80000,"quality":"Light","last_transaction":"ConocoPhillips sold 30% stake back to Lukoil for minimal value 2022 (forced sanctions exit)","pipelines":"Yuzhno-Khylchuyu → Varandey Terminal tanker loading","ports":"Varandey Arctic Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vostok Oil Project', 'Rosneft / Trafigura / Vitol', 'Krasnoyarsk Krai — mega Arctic cluster', NULL, 'Energy', 'Crude Oil', 70.5000, 87.5000, 'Russia', 'Krasnoyarsk Krai', 'Sever Bay', 'oil_field', 'planned', 'Rosneft (Vostok Oil flagship)', 'joint_venture', 42.00, 0.05, 0, 6000000000, 0, '{"note":"Development — Russia''s most ambitious upstream project; planned 2024–2030 ramp-up; FID 2021","production_bpd":"Target 600,000–1,000,000 by 2030","quality":"Light sweet, exceptionally low carbon intensity projected","ownership_split":"Rosneft 60%; Trafigura 10%; Vitol 5%; Indian/Chinese investors under discussion","last_transaction":"Trafigura acquired 10% for $7B (2021); Vitol 5% for ~$3.5B — largest Arctic upstream deal ever","pipelines":"Planned Northern Sea Route (NSR) tanker exports; new Arctic pipeline to Dikson/Sever Bay","ports":"Planned Sever Bay Terminal (Yenisei Bay, year-round NSR access)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- SAKHALIN ISLAND
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sakhalin-1 (Chayvo, Odoptu, Arkutun-Dagi)', 'Rosneft / ONGC / SODECO / ExxonMobil', 'Offshore/onshore Sakhalin Island', NULL, 'Energy', 'Crude Oil', 53.7500, 143.5000, 'Russia', 'Sakhalin Oblast', 'De-Kastri', 'oil_field', 'operational', 'Rosneft (replaced ExxonMobil 2022)', 'joint_venture', 36.00, 0.24, 2700000, 2300000000, 2700000, '{"start_year":2005,"production_bpd":90000,"quality":"Light — Sokol crude export grade","note":"Production significantly reduced post-ExxonMobil exit; down from ~250,000 peak pre-2022","ownership_split":"Rosneft 20% (+ operator 2022); ONGC Videsh 20%; SODECO Japan 30%; ExxonMobil 30% (operations frozen)","last_transaction":"ExxonMobil declared force majeure/exited 2022; Russian Presidential Decree transferred to new entity — ExxonMobil $4B+ write-off","pipelines":"Chayvo → De-Kastri terminal (mainland Khabarovsk); Odoptu → Chayvo processing","ports":"De-Kastri Export Terminal (Sea of Japan); Aniva Bay","rail":"None (sea-based export)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sakhalin-2 (Piltun-Astokhskoye + Lunskoye)', 'Gazprom / Shell / Mitsui / Mitsubishi', 'Offshore Sakhalin Island', NULL, 'Energy', 'Crude Oil', 52.8333, 143.2500, 'Russia', 'Sakhalin Oblast', 'Prigorodnoye', 'oil_field', 'operational', 'Sakhalin Energy', 'joint_venture', 38.00, 0.12, 2400000, 1000000000, 2400000, '{"start_year":1999,"production_bpd":80000,"quality":"Light sweet — Sakhalin Blend export grade","note":"Russia''s first LNG export project + major oil; 10.8 MTPA LNG","ownership_split":"Gazprom 50%+1, Shell 27.5%-1, Mitsui 12.5%, Mitsubishi 10%","last_transaction":"Shell forced to sell majority to Gazprom 2007; Shell wrote off ~$1.6B on exit 2022","pipelines":"Piltun-Astokhskoye FPSO → Onshore processing → Trans-Sakhalin pipeline (~800km) → Prigorodnoye LNG plant","ports":"Prigorodnoye LNG + Oil Export Terminal (Aniva Bay)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sakhalin-3 — Kirinskoye Block', 'Gazprom', 'Offshore Sakhalin Island', NULL, 'Energy', 'Crude Oil', 52.0000, 143.8333, 'Russia', 'Sakhalin Oblast', 'Aniva Bay', 'oil_field', 'operational', 'Gazprom', 'state_owned', 49.00, 0.05, 240000, 100000000, 240000, '{"start_year":2015,"production_bpd":8000,"quality":"Condensate sweet","note":"Gas dominant + condensate","reserves_gas":"~700 billion m³","pipelines":"Kirinskoye → Power of Siberia gas pipeline (planned); condensate by tanker","ports":"Aniva Bay (tanker)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sakhalin-5 — Kaigansko-Vasyukanskiy Block', 'Rosneft', 'Offshore Sakhalin Island', NULL, 'Energy', 'Crude Oil', 52.5000, 143.5000, 'Russia', 'Sakhalin Oblast', 'De-Kastri', 'oil_field', 'operational', 'Rosneft', 'state_owned', 35.00, 0.15, 150000, NULL, 150000, '{"start_year":2004,"production_bpd":5000,"quality":"Light","note":"Exploration / Early development — test production; BP exited 2022","last_transaction":"BP exited Sakhalin-5 as part of broader Russia exit 2022; wrote off ~$1.4B","pipelines":"Planned integration with Sakhalin infrastructure","ports":"De-Kastri / Aniva Bay","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Veninsky Block — Sakhalin-4', 'Rosneft', 'Offshore Sakhalin Island', NULL, 'Energy', 'Crude Oil', 52.3333, 143.3333, 'Russia', 'Sakhalin Oblast', 'Aniva Bay', 'oil_field', 'planned', 'Rosneft', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2005,"note":"Exploration stage","ownership_split":"Rosneft 74.9%, Sakhalinmorneftegas-Shelf 25.1%","pipelines":"Planned","ports":"Aniva Bay (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NORTH CAUCASUS
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ust-Balykskoe Field', 'Rosneft', 'Krasnodar Krai — historic', NULL, 'Energy', 'Crude Oil', 45.3333, 39.8333, 'Russia', 'Krasnodar Krai', 'Krasnodar', 'oil_field', 'operational', 'Rosneft (Krasnodarskiy kraiGaz)', 'state_owned', 40.00, 0.20, 240000, 50000000, 240000, '{"start_year":1864,"production_bpd":8000,"quality":"Light sweet — historically Russia''s best quality crude","note":"Very mature — Russia''s oldest oil province","pipelines":"Krasnodar → Novorossiysk Black Sea Terminal","ports":"Novorossiysk (Sheskharis terminal — Russia''s largest Black Sea export)","rail":"Krasnodar rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Maikopskoye Group', 'Rosneft', 'Republic of Adygea / Krasnodar Krai', NULL, 'Energy', 'Crude Oil', 44.5833, 40.1667, 'Russia', 'Krasnodar Krai', 'Maikop', 'oil_field', 'operational', 'Rosneft / Krasnodar independents', 'state_owned', 38.00, 0.20, 150000, NULL, 150000, '{"start_year":"1890s","production_bpd":5000,"quality":"Light sweet (Maikop formation — famous geological term)","note":"Very mature; colonial era production","pipelines":"North Caucasus → Novorossiysk","ports":"Novorossiysk","rail":"Maikop–Krasnodar rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Stavropol Fields', 'Rosneft / Lukoil', 'Stavropol Krai', NULL, 'Energy', 'Crude Oil', 45.0417, 41.9694, 'Russia', 'Stavropol Krai', 'Stavropol', 'oil_field', 'operational', 'Rosneft (Stavrolen) + Lukoil', 'joint_venture', 37.00, 0.20, 300000, NULL, 300000, '{"start_year":"1950s","production_bpd":10000,"quality":"Light","note":"Mature, gas dominant","pipelines":"Stavropol → North Caucasus → Novorossiysk","ports":"Novorossiysk","rail":"Stavropol rail hub"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Chechnya Fields', 'Rosneft / Chechen Republic', 'Grozny area — Chechen Republic', NULL, 'Energy', 'Crude Oil', 43.3167, 45.7000, 'Russia', 'Chechen Republic', 'Grozny', 'oil_field', 'operational', 'Rosneft (Grozneftegaz)', 'joint_venture', 44.00, 0.15, 450000, 300000000, 450000, '{"start_year":1893,"production_bpd":15000,"quality":"Light sweet — Grozny crude historically world''s finest quality","note":"Historically one of world''s first oil regions — second Baku; rehabilitated post-war","ownership_split":"Rosneft (Grozneftegaz) 51%, Chechen Republic government 49%","last_transaction":"Post-war rehabilitation agreement; Kadyrov government stake arrangement 2007","pipelines":"Grozny → North Caucasus trunk → Novorossiysk (Transneft)","ports":"Novorossiysk Black Sea Terminal","rail":"Grozny rail (rehabilitated post-war)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dagestan Fields', 'Rosneft', 'Republic of Dagestan — Caspian coast', NULL, 'Energy', 'Crude Oil', 43.0000, 47.5000, 'Russia', 'Dagestan', 'Makhachkala', 'oil_field', 'operational', 'Rosneft (Dagneft)', 'state_owned', 36.00, 0.20, 90000, NULL, 90000, '{"start_year":"1900s","production_bpd":3000,"quality":"Light sweet","note":"Mature, very small; Caspian Dagestan shelf early production","pipelines":"Dagestan → Makhachkala → Novorossiysk pipeline","ports":"Makhachkala Caspian Port; Novorossiysk (via pipeline)","rail":"Makhachkala–Rostov-on-Don rail (coastal)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ingushetia / North Ossetia Fields', 'Rosneft', 'North Caucasus', NULL, 'Energy', 'Crude Oil', 43.1667, 44.8333, 'Russia', 'North Caucasus', 'Vladikavkaz', 'oil_field', 'operational', 'Rosneft (Ingushneft)', 'state_owned', 38.00, 0.20, 60000, NULL, 60000, '{"start_year":"1930s","production_bpd":2000,"quality":"Light sweet","note":"Minimal output","pipelines":"North Caucasus regional → Grozny → Novorossiysk","ports":"Novorossiysk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- ============================================================
-- Verification
-- ============================================================
SELECT count(*) AS russia_oil_fields
FROM public.commodity_locations
WHERE country = 'Russia' AND commodity_name = 'Crude Oil';

SELECT count(*) AS total_locations
FROM public.commodity_locations;
