-- ============================================================
-- Romania Oil Production Sites — 15 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- PLOIEȘTI REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Boldești-Scăeni Field', 'OMV Petrom', 'Prahova County — Ploiești basin', NULL, 'Energy', 'Crude Oil', 45.0667, 26.0500, 'Romania', 'Ploiești', 'Ploiești', 'oil_field', 'operational', 'OMV Petrom', 'public', 36.00, 0.40, 90000, 30000000, 90000, '{"start_year":1857,"production_bpd":3000,"quality":"Light sweet — Romanian crude benchmark","note":"World''s oldest petroleum industry region; Romania first country to commercially record oil production 1857; Ploiești producing since 1840s artisanal","last_transaction":"OMV acquired 51% Petrom from Romanian state 2004 for €669M — largest FDI in Romanian history; OMV invested ~€10B in Romania 2004–2024","contract_duration":"Romanian petroleum concessions (Legea Petrolului) to 2040","pipelines":"Boldești → Ploiești refinery (Petrobrazi) (~15km); Ploiești → Constanța (Conpet ~235km)","ports":"Constanța Port (Black Sea)","rail":"Ploiești–București main rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Băicoi Field', 'OMV Petrom', 'Prahova County', NULL, 'Energy', 'Crude Oil', 45.0333, 25.8667, 'Romania', 'Ploiești', 'Ploiești', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 45000, NULL, 45000, '{"start_year":1860,"production_bpd":1500,"quality":"Light sweet","note":"Mature","contract_duration":"Romanian petroleum concession","pipelines":"→ Ploiești gathering → Petrobrazi refinery","ports":"Constanța","rail":"Ploiești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Câmpina Field', 'OMV Petrom', 'Prahova County — historic', NULL, 'Energy', 'Crude Oil', 45.1333, 25.7333, 'Romania', 'Ploiești', 'Câmpina', 'oil_field', 'operational', 'OMV Petrom', 'public', 34.00, NULL, 30000, NULL, 30000, '{"start_year":1857,"production_bpd":1000,"quality":"Medium light","note":"Among world''s first commercial oil fields; very mature","contract_duration":"Romanian petroleum concession","pipelines":"Câmpina → Ploiești refinery pipeline","ports":"Constanța","rail":"Câmpina–Ploiești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Moreni Field', 'OMV Petrom', 'Dâmbovița County — Ploiești basin', NULL, 'Energy', 'Crude Oil', 44.9833, 25.6667, 'Romania', 'Ploiești', 'Moreni', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 60000, 20000000, 60000, '{"start_year":1862,"production_bpd":2000,"quality":"Light sweet","note":"Among world''s earliest commercial fields; major WWII bombing target 1943 — Operation Tidal Wave USAAF","contract_duration":"Romanian petroleum concession","pipelines":"Moreni → Ploiești → Petrobrazi refinery","ports":"Constanța","rail":"Moreni–Ploiești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Gura Ocniței Field', 'OMV Petrom', 'Dâmbovița County', NULL, 'Energy', 'Crude Oil', 44.9167, 25.5833, 'Romania', 'Ploiești', 'Târgoviște', 'oil_field', 'operational', 'OMV Petrom', 'public', 34.00, NULL, 24000, NULL, 24000, '{"start_year":1900,"production_bpd":800,"quality":"Medium light","contract_duration":"Romanian petroleum concession","pipelines":"→ Ploiești gathering","ports":"Constanța","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Filipești de Târg Field', 'OMV Petrom', 'Prahova County', NULL, 'Energy', 'Crude Oil', 44.9500, 26.1000, 'Romania', 'Ploiești', 'Ploiești', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 36000, NULL, 36000, '{"start_year":1880,"production_bpd":1200,"quality":"Light sweet","contract_duration":"Romanian petroleum concession","pipelines":"Prahova gathering → Ploiești","ports":"Constanța","rail":"Ploiești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Brazi Field', 'OMV Petrom', 'Prahova County — near Petrobrazi refinery', NULL, 'Energy', 'Crude Oil', 44.9833, 26.0167, 'Romania', 'Ploiești', 'Brazi', 'oil_field', 'operational', 'OMV Petrom', 'public', 36.00, NULL, 15000, NULL, 15000, '{"start_year":1878,"production_bpd":500,"quality":"Light sweet","note":"Adjacent to Petrobrazi refinery","contract_duration":"Romanian petroleum concession","pipelines":"Brazi → Petrobrazi refinery (very short — adjacent)","ports":"Constanța","rail":"Brazi–Ploiești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BLACK SEA (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Histria (Totea) Field', 'OMV Petrom + Lukoil Romania', 'Romanian Black Sea — shallow water', NULL, 'Energy', 'Crude Oil', 44.5000, 29.5000, 'Romania', 'Black Sea', 'Constanța', 'oil_field', 'operational', 'OMV Petrom', 'joint_venture', 36.00, 0.30, 90000, 50000000, 90000, '{"start_year":1987,"production_bpd":3000,"quality":"Light sweet","note":"Soviet-era shallow shelf development; OMV Petrom 50%, Lukoil Romania 50%","last_transaction":"Post-2022 Ukraine sanctions created pressure on Lukoil Romania but no forced exit","contract_duration":"Romanian offshore concession to 2032","pipelines":"Histria offshore → Constanța onshore terminal (~50km subsea)","ports":"Constanța Black Sea Terminal","rail":"None offshore"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ana (Doina) Neptun Deep Field', 'Romgaz + OMV Petrom', 'Romanian Black Sea — Neptun Deep Block', NULL, 'Energy', 'Crude Oil', 44.3333, 29.8333, 'Romania', 'Black Sea', 'Constanța', 'oil_field', 'planned', 'Romgaz + OMV Petrom', 'joint_venture', 48.00, NULL, 0, 100000000, 0, '{"start_year":2027,"production_bpd":10000,"quality":"Condensate sweet (associated with deep gas)","note":"FID December 2023; Romania''s largest offshore project; first gas/condensate targeted 2027; ~42–84 Bcm gas + ~100M bbl condensate total","last_transaction":"ExxonMobil sold 50% to Romgaz 2024 for $1.06B after decade of delays; Romgaz + OMV Petrom FID Dec 2023 (~€4B); strategic for EU energy security","contract_duration":"Romanian concession to 2027 (extensions planned)","pipelines":"Planned subsea → Tuzla onshore terminal (Constanța coast)","ports":"Constanța / Tuzla","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- OLTENIA
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Videle Field', 'OMV Petrom', 'Teleorman County — southern Romania/Oltenia fringe', NULL, 'Energy', 'Crude Oil', 44.2833, 25.5167, 'Romania', 'Oltenia', 'Videle', 'oil_field', 'operational', 'OMV Petrom', 'public', 34.00, 0.50, 75000, 30000000, 75000, '{"start_year":1955,"production_bpd":2500,"quality":"Medium light","note":"Mature","contract_duration":"Romanian petroleum concession","pipelines":"Videle → Ploiești pipeline (via Conpet) → Petrobrazi refinery","ports":"Constanța","rail":"Videle–București rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bălești Field', 'OMV Petrom', 'Gorj County — Oltenia', NULL, 'Energy', 'Crude Oil', 44.9167, 23.6833, 'Romania', 'Oltenia', 'Târgu Jiu', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 60000, NULL, 60000, '{"start_year":1965,"production_bpd":2000,"quality":"Light sweet","note":"Oltenia sub-Carpathian fields","contract_duration":"Romanian petroleum concession","pipelines":"Oltenia → Pitești → Ploiești pipeline network","ports":"Constanța","rail":"Târgu Jiu–Craiova rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Totea-Jugureni (Teleajen) Field', 'OMV Petrom', 'Oltenia/Prahova border', NULL, 'Energy', 'Crude Oil', 45.0000, 26.2500, 'Romania', 'Oltenia', 'Ploiești', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 45000, NULL, 45000, '{"start_year":1958,"production_bpd":1500,"quality":"Light sweet","contract_duration":"Romanian petroleum concession","pipelines":"→ Ploiești gathering","ports":"Constanța","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mehedinți Field', 'OMV Petrom', 'Mehedinți County — western Oltenia', NULL, 'Energy', 'Crude Oil', 44.4167, 22.9167, 'Romania', 'Oltenia', 'Drobeta-Turnu Severin', 'oil_field', 'operational', 'OMV Petrom', 'public', 34.00, NULL, 30000, NULL, 30000, '{"start_year":1970,"production_bpd":1000,"quality":"Medium light","note":"Mature","contract_duration":"Romanian petroleum concession","pipelines":"Western Oltenia → Craiova → Pitești pipeline","ports":"Constanța (via Conpet)","rail":"Drobeta-Turnu Severin rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Icoana (Olt Valley) Field', 'OMV Petrom', 'Olt County', NULL, 'Energy', 'Crude Oil', 44.4667, 24.3333, 'Romania', 'Oltenia', 'Slatina', 'oil_field', 'operational', 'OMV Petrom', 'public', 35.00, NULL, 36000, NULL, 36000, '{"start_year":1972,"production_bpd":1200,"quality":"Light sweet","contract_duration":"Romanian petroleum concession","pipelines":"Olt Valley → Pitești → Ploiești","ports":"Constanța","rail":"Slatina–Pitești rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Schela Field', 'OMV Petrom', 'Gorj County — Oltenia', NULL, 'Energy', 'Crude Oil', 44.8333, 23.3333, 'Romania', 'Oltenia', 'Târgu Jiu', 'oil_field', 'operational', 'OMV Petrom', 'public', 36.00, NULL, 45000, NULL, 45000, '{"start_year":1960,"production_bpd":1500,"quality":"Light sweet","contract_duration":"Romanian petroleum concession","pipelines":"Gorj → Oltenia pipeline → Conpet → Constanța","ports":"Constanța","rail":"Târgu Jiu rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Romania' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Romania' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
