-- ============================================================
-- Yemen Oil Production Sites — 25 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- MARIB-JAWF BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Marib Field', 'SEPOC (SAFER) + Hunt Oil + Exxon + Korea LNG', 'Block 18 — Marib Governorate', NULL, 'Energy', 'Crude Oil', 15.4167, 45.3333, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'SEPOC (SAFER)', 'joint_venture', 52.00, 0.07, 0, 200000000, 0, '{"start_year":1987,"production_bpd":0,"quality":"Very light sweet — Marib Light benchmark; one of Middle East''s lightest crude grades","note":"SEPOC 51%; Hunt Oil 17.22%, Exxon 18.05%, Korea LNG 5.88%; severely disrupted by Houthi conflict; pipeline destroyed 2015; pre-war peak ~30,000 bpd","last_transaction":"Hunt Oil PSA Block 18 signed 1984 — Yemen''s first PSA with US company; force majeure 2015; all IOCs evacuated; ~$2B+ stranded assets","contract_duration":"PSA suspended (force majeure since 2015)","pipelines":"Marib → Ras Isa (~440km) — pipeline destroyed/sabotaged 2015–2024","ports":"Ras Isa Marine Terminal (Red Sea — severely damaged)","rail":"None (Yemen has no rail network)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Alif Field', 'SEPOC + Hunt Oil consortium', 'Block 18 — Marib', NULL, 'Energy', 'Crude Oil', 15.5000, 45.4167, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'SEPOC / Hunt Oil', 'joint_venture', 50.00, NULL, 0, 300000000, 0, '{"start_year":1988,"production_bpd":0,"quality":"Very light sweet — Marib Light blend contributor","note":"Same as Marib consortium; suspended; pre-war ~20,000 bpd","last_transaction":"Force majeure 2015 alongside Marib Field","contract_duration":"PSA suspended","pipelines":"Alif → Marib gathering → Ras Isa (inactive)","ports":"Ras Isa (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Kharir Field', 'SEPOC + Hunt Oil consortium', 'Block 18 — Marib', NULL, 'Energy', 'Crude Oil', 15.3333, 45.5000, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'SEPOC / Hunt Oil', 'joint_venture', 49.00, NULL, 0, 150000000, 0, '{"start_year":1992,"production_bpd":0,"quality":"Very light sweet","note":"Suspended; pre-war ~10,000 bpd","contract_duration":"PSA suspended","pipelines":"Kharir → Marib → Ras Isa (inactive)","ports":"Ras Isa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jawf Field', 'SAFER + Occidental Yemen', 'Al-Jawf Governorate — Block 5', NULL, 'Energy', 'Crude Oil', 16.2500, 45.6667, 'Yemen', 'Marib-Jawf Basin', 'Al-Jawf', 'oil_field', 'inactive', 'Occidental Petroleum Yemen', 'joint_venture', 40.00, 0.10, 0, 400000000, 0, '{"start_year":1993,"production_bpd":0,"quality":"Light sweet","note":"Al-Uqlah; SAFER 50%, Occidental Yemen 50%; Houthi-controlled territory; pre-war ~25,000 bpd","last_transaction":"Oxy PSA Block 5 signed 1990; Oxy force majeure 2015; ~$800M write-off","contract_duration":"PSA suspended","pipelines":"Jawf → Marib pipeline → Ras Isa (inactive)","ports":"Ras Isa (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Halewah Field', 'SAFER + Occidental Yemen', 'Al-Jawf — Block 5', NULL, 'Energy', 'Crude Oil', 16.0833, 45.5000, 'Yemen', 'Marib-Jawf Basin', 'Al-Jawf', 'oil_field', 'inactive', 'Occidental Yemen', 'joint_venture', 39.00, NULL, 0, NULL, 0, '{"start_year":1995,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, Oxy 50%; suspended; pre-war ~8,000 bpd","contract_duration":"PSA suspended","pipelines":"Halewah → Jawf → Marib → Ras Isa (inactive)","ports":"Ras Isa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hizyaz Field', 'SEPOC + Hunt Oil consortium', 'Marib — Block 18 satellite', NULL, 'Energy', 'Crude Oil', 15.6667, 45.2500, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'SEPOC / Hunt Oil', 'joint_venture', 48.00, NULL, 0, NULL, 0, '{"start_year":1997,"production_bpd":0,"quality":"Very light sweet","note":"Suspended; pre-war ~5,000 bpd","contract_duration":"PSA suspended","pipelines":"Hizyaz → Marib gathering (inactive)","ports":"Ras Isa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Safer Field', 'SEPOC (SAFER)', 'Marib Governorate — SAFER company namesake', NULL, 'Energy', 'Crude Oil', 15.2500, 45.2500, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'SEPOC (SAFER)', 'state_owned', 46.00, NULL, 0, 200000000, 0, '{"start_year":1986,"production_bpd":0,"quality":"Light sweet","note":"SAFER 100%; severely disrupted; FSO Safer — 1.1M bbl stranded 2015–2023; UN rescue operation completed July 2023 (transferred to Nautica)","last_transaction":"FSO Safer internationally notorious; Red Sea spill threat; UN-brokered rescue July 2023","contract_duration":"State concession","pipelines":"Safer → Ras Isa pipeline (inactive)","ports":"Ras Isa; Hodeidah (FSO Safer — now resolved)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wadi Ayna Field', 'SAFER + TotalEnergies', 'Marib — Block 4', NULL, 'Energy', 'Crude Oil', 15.8333, 44.9167, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'TotalEnergies Yemen', 'joint_venture', 42.00, NULL, 0, NULL, 0, '{"start_year":1999,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; pre-war ~8,000 bpd","last_transaction":"TotalEnergies force majeure 2015; ~$200M write-off","contract_duration":"PSA suspended","pipelines":"Wadi Ayna → Marib → Ras Isa (inactive)","ports":"Ras Isa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Damis Field', 'SAFER + TotalEnergies', 'Marib — Block 4', NULL, 'Energy', 'Crude Oil', 15.7500, 44.8333, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'TotalEnergies Yemen', 'joint_venture', 41.00, NULL, 0, NULL, 0, '{"start_year":2001,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; pre-war ~5,000 bpd","contract_duration":"PSA suspended","pipelines":"Damis → Marib pipeline (inactive)","ports":"Ras Isa","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jannah Field', 'SAFER + Hunt Oil', 'Block 5 — Al-Jawf/Marib border', NULL, 'Energy', 'Crude Oil', 16.3333, 46.5000, 'Yemen', 'Marib-Jawf Basin', 'Marib', 'oil_field', 'inactive', 'Hunt Oil Yemen', 'joint_venture', 43.00, NULL, 0, 200000000, 0, '{"start_year":1997,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, Hunt Oil 50%; suspended; pre-war ~15,000 bpd","last_transaction":"Hunt Oil force majeure 2015; second Hunt Oil Yemen asset alongside Marib","contract_duration":"PSA suspended","pipelines":"Jannah → Marib → Ras Isa (inactive)","ports":"Ras Isa (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- MASILA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Masila Field', 'HOC (Nexen/CNOOC + Occidental + PDVSA + SAFER)', 'Block 14 — Hadhramaut Governorate', NULL, 'Energy', 'Crude Oil', 15.6500, 49.8833, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'Hadramawt Oil Company (HOC)', 'joint_venture', 30.00, 0.65, 675000, 400000000, 675000, '{"start_year":1993,"production_bpd":22500,"quality":"Medium — Masila crude export grade","note":"SAFER/HOC 25%; Nexen (CNOOC since 2013) 25.5%; Occidental 19.6%; PDVSA 16.9%; Yemen''s most active remaining basin; southern government control","last_transaction":"CNOOC acquired Nexen 2013 ($15.1B); inherited Yemen Masila stake; pre-war peak ~60,000 bpd","contract_duration":"PSA Block 14 — extended negotiations ongoing","pipelines":"Masila → Ash Shihr Marine Terminal (~240km — functional)","ports":"Ash Shihr Export Terminal (Gulf of Aden — Yemen''s most functional oil export point)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sunah Field', 'HOC (Block 14 consortium)', 'Masila Basin — Block 14', NULL, 'Energy', 'Crude Oil', 15.5833, 49.7500, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'HOC', 'joint_venture', 29.00, 0.70, 105000, 200000000, 105000, '{"start_year":1993,"production_bpd":3500,"quality":"Medium","note":"Block 14 consortium; partially active; pre-war ~10,000 bpd","contract_duration":"PSA Block 14","pipelines":"Sunah → Masila gathering → Ash Shihr","ports":"Ash Shihr","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tawila Field', 'HOC (Block 14 consortium)', 'Masila Basin — Block 14', NULL, 'Energy', 'Crude Oil', 15.7500, 49.9167, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'HOC', 'joint_venture', 30.00, NULL, 60000, NULL, 60000, '{"start_year":1997,"production_bpd":2000,"quality":"Medium","note":"Tawila East/West; Block 14 consortium; partially active; pre-war ~8,000 bpd","contract_duration":"PSA Block 14","pipelines":"Tawila → Masila gathering → Ash Shihr","ports":"Ash Shihr","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Camaal Field', 'HOC (Block 14 consortium)', 'Masila Basin — Block 14', NULL, 'Energy', 'Crude Oil', 15.4167, 49.6667, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'HOC', 'joint_venture', 29.00, NULL, 45000, NULL, 45000, '{"start_year":2000,"production_bpd":1500,"quality":"Medium sour","note":"Block 14 consortium; partially active; pre-war ~5,000 bpd","contract_duration":"PSA Block 14","pipelines":"Camaal → Masila pipeline → Ash Shihr","ports":"Ash Shihr","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('East Masila Fields Cluster', 'HOC + Nexen (CNOOC)', 'Block 14 extensions', NULL, 'Energy', 'Crude Oil', 15.8333, 50.1667, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'HOC / Nexen (CNOOC)', 'joint_venture', 30.00, NULL, 75000, NULL, 75000, '{"start_year":2002,"production_bpd":2500,"quality":"Medium","note":"Block 14 consortium; various small field developments; partially active; pre-war ~8,000 bpd combined","contract_duration":"PSA Block 14","pipelines":"East Masila → Masila hub → Ash Shihr","ports":"Ash Shihr","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wadi Hadramawt Fields', 'Calvalley Petroleum + SAFER', 'Block 9 — Hadhramaut', NULL, 'Energy', 'Crude Oil', 16.0000, 49.1667, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'operational', 'Calvalley Petroleum + SAFER', 'joint_venture', 32.00, 0.80, 45000, NULL, 45000, '{"start_year":2003,"production_bpd":1500,"quality":"Medium","note":"Calvalley Petroleum 50%, SAFER 50%; partially active; smaller southern government area; pre-war ~5,000 bpd","last_transaction":"Calvalley suspended full operations 2015; skeleton crew maintaining minimal production; ~$100M stranded","contract_duration":"PSA suspended/minimal","pipelines":"Block 9 → Masila gathering → Ash Shihr (limited)","ports":"Ash Shihr","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sharyuf Field', 'DNO + SAFER', 'Block 10 — Shabwa Governorate', NULL, 'Energy', 'Crude Oil', 15.0833, 47.9167, 'Yemen', 'Masila Basin', 'Shabwa', 'oil_field', 'inactive', 'DNO (Norway)', 'joint_venture', 38.00, NULL, 0, 100000000, 0, '{"start_year":2001,"production_bpd":0,"quality":"Light sweet","note":"DNO 53.33%, SAFER 46.67%; suspended; conflict zone — Shabwa contested; pre-war ~8,000 bpd","last_transaction":"DNO Yemen suspended 2015; DNO wrote off ~$150M Yemen assets","contract_duration":"PSA suspended","pipelines":"Sharyuf → Balhaf terminal (inactive)","ports":"Balhaf LNG Terminal (Gulf of Aden)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Shabwa Field', 'SAFER + TotalEnergies', 'Shabwa Governorate — Block S2', NULL, 'Energy', 'Crude Oil', 15.1667, 47.0833, 'Yemen', 'Masila Basin', 'Shabwa', 'oil_field', 'inactive', 'TotalEnergies Yemen', 'joint_venture', 36.00, 0.20, 0, 150000000, 0, '{"start_year":1995,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; pre-war ~20,000 bpd","last_transaction":"TotalEnergies force majeure 2015; ~$300M write-off; Shabwa governorate contested","contract_duration":"PSA suspended","pipelines":"Shabwa → Balhaf terminal pipeline (inactive); Shabwa → Aden pipeline (inactive)","ports":"Balhaf; Aden (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Habban Field', 'SAFER + TotalEnergies', 'Shabwa — Block S2', NULL, 'Energy', 'Crude Oil', 14.9167, 46.9167, 'Yemen', 'Masila Basin', 'Shabwa', 'oil_field', 'inactive', 'TotalEnergies Yemen', 'joint_venture', 35.00, NULL, 0, NULL, 0, '{"start_year":1998,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; pre-war ~8,000 bpd","contract_duration":"PSA suspended","pipelines":"Habban → Shabwa → Balhaf (inactive)","ports":"Balhaf","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Aqabah Field', 'SAFER + TotalEnergies', 'Hadhramaut — Block S1', NULL, 'Energy', 'Crude Oil', 16.5833, 47.3333, 'Yemen', 'Masila Basin', 'Hadhramaut', 'oil_field', 'inactive', 'TotalEnergies Yemen', 'joint_venture', 37.00, NULL, 0, NULL, 0, '{"start_year":1999,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; pre-war ~5,000 bpd","contract_duration":"PSA suspended","pipelines":"Aqabah → Masila pipeline system (inactive)","ports":"Ash Shihr (indirect)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- OFFSHORE YEMEN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Balhaf Offshore Field', 'SAFER + TotalEnergies', 'Block 14 Nearshore — Gulf of Aden, Shabwa coast', NULL, 'Energy', 'Crude Oil', 14.0000, 48.1667, 'Yemen', 'Offshore Yemen', 'Shabwa', 'oil_field', 'inactive', 'SAFER + TotalEnergies', 'joint_venture', 36.00, NULL, 0, NULL, 0, '{"start_year":2000,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; nearshore development; pre-war ~5,000 bpd","contract_duration":"PSA suspended","pipelines":"Balhaf offshore → Balhaf onshore terminal (inactive)","ports":"Balhaf LNG/Oil Terminal (Gulf of Aden — inactive for oil)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hayl Field', 'SAFER + OMV Austria', 'Block 15 — Gulf of Aden', NULL, 'Energy', 'Crude Oil', 13.5000, 48.5000, 'Yemen', 'Offshore Yemen', 'Shabwa', 'oil_field', 'inactive', 'SAFER + OMV Austria', 'joint_venture', 35.00, NULL, 0, 100000000, 0, '{"start_year":2005,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, OMV 30%, others 20%; suspended; pre-war ~8,000 bpd","last_transaction":"OMV force majeure 2015; OMV Yemen ~$200M write-off","contract_duration":"PSA suspended","pipelines":"Hayl offshore → Balhaf terminal (inactive)","ports":"Balhaf; Aden (alternate, inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Taliwah Field', 'SAFER + TotalEnergies', 'Block 7 — Red Sea', NULL, 'Energy', 'Crude Oil', 14.5000, 43.5000, 'Yemen', 'Offshore Yemen', 'Hodeidah', 'oil_field', 'inactive', 'SAFER + TotalEnergies', 'joint_venture', 38.00, NULL, 0, NULL, 0, '{"start_year":2003,"production_bpd":0,"quality":"Light sweet","note":"SAFER 50%, TotalEnergies 50%; suspended; Red Sea — active Houthi maritime zone; pre-war ~3,000 bpd","last_transaction":"TotalEnergies force majeure 2015; Red Sea now extremely high risk (Houthi drone/missile attacks 2023–2024)","contract_duration":"PSA suspended","pipelines":"Taliwah → Ras Isa terminal (Red Sea — inactive)","ports":"Ras Isa (inactive; Houthi-controlled coast)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Farasan Block', 'SAFER', 'Block 1 — Offshore Red Sea, near Saudi border', NULL, 'Energy', 'Crude Oil', 16.8333, 42.1667, 'Yemen', 'Offshore Yemen', 'Hodeidah', 'oil_field', 'inactive', 'SAFER', 'state_owned', NULL, NULL, 0, 200000000, 0, '{"start_year":2008,"production_bpd":0,"quality":"TBD","note":"Exploration / suspended; SAFER 100%","contract_duration":"Exploration suspended","pipelines":"None","ports":"Planned Hodeidah (inactive)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Block 71 (East Gulf of Aden)', 'SAFER + BP', 'Block 71 — East Gulf of Aden, deepwater', NULL, 'Energy', 'Crude Oil', 12.5000, 51.5000, 'Yemen', 'Offshore Yemen', 'Shabwa', 'oil_field', 'inactive', 'SAFER + BP', 'joint_venture', NULL, NULL, 0, 500000000, 0, '{"start_year":2007,"production_bpd":0,"quality":"TBD","note":"SAFER 50%, BP 50%; exploration halted; frontier deepwater","last_transaction":"BP force majeure 2015; BP wrote off Yemen deepwater exploration; ~$300M sunk costs","contract_duration":"PSA suspended","pipelines":"None","ports":"Planned (Gulf of Aden)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Yemen' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Yemen' AND commodity_name = 'Crude Oil' ORDER BY region, operational_status, title;
