-- ============================================================
-- Brazil & Chile — Oil Production Sites (UPSERT)
-- Run this in Supabase SQL Editor
-- Brazil: 28 sites | Chile: 6 sites
-- ============================================================

-- =====================
-- BRAZIL — SANTOS BASIN (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lula Field', 'Petrobras + Shell + Galp', 'Santos Basin Pre-Salt — Block BM-S-11, offshore São Paulo/Rio de Janeiro', NULL, 'Energy', 'Crude Oil', -24.7167, -43.6667, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 29.00, 0.45, 850000, 5000000000, 25500000, '{"start_year":2010,"production_bpd":850000,"quality":"Lula crude — benchmark Brazilian pre-salt","note":"Petrobras 65%, Shell 25%, Galp 10%; Brazil''s largest oil field","pipelines":"Lula FPSOs → Santos Basin export → onshore terminals","ports":"Santos Port; DTSE Terminal; Rio de Janeiro","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Búzios Field', 'Petrobras + CNOOC + CNODC', 'Santos Basin Pre-Salt — Block BM-S-9', NULL, 'Energy', 'Crude Oil', -24.5000, -42.8333, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 28.00, 0.40, 750000, 6000000000, 22500000, '{"start_year":2018,"production_bpd":750000,"quality":"Medium heavy","note":"Petrobras 88.99%, CNOOC 9.65%, CNODC 1.36%; world''s largest deepwater oil field","pipelines":"Búzios FPSOs → Santos Basin gathering","ports":"Santos; DTSE Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sapinhoá Field', 'Petrobras + Repsol Sinopec Brasil + Shell + Petrogal Brasil', 'Santos Basin Pre-Salt — Block BM-S-9', NULL, 'Energy', 'Crude Oil', -25.0000, -43.0000, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 29.00, 0.50, 180000, 2000000000, 5400000, '{"start_year":2012,"production_bpd":180000,"quality":"Medium heavy","note":"Petrobras 45%, Repsol Sinopec 25%, Shell 25%, Petrogal 5%","pipelines":"Sapinhoá FPSOs → Santos gathering","ports":"Santos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Mero Field', 'Petrobras + Shell + TotalEnergies + CNOOC + CNPC + PPSA', 'Santos Basin Pre-Salt — Block BM-S-8', NULL, 'Energy', 'Crude Oil', -24.3333, -42.6667, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 28.00, NULL, 180000, 4000000000, 5400000, '{"start_year":2022,"production_bpd":180000,"quality":"Medium heavy","note":"Petrobras 38.6%, Shell 19.3%, TotalEnergies 19.3%, CNOOC 9.65%, CNPC 9.65%, PPSA 3.5%","pipelines":"Mero FPSOs → Santos gathering","ports":"Santos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Berbigão / Sururu / Atapu (BM-S-11A)', 'Petrobras + Petrogal Brasil + Barra Energia', 'Santos Basin Pre-Salt — Lula area satellites', NULL, 'Energy', 'Crude Oil', -25.0000, -43.3333, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 28.00, NULL, 120000, NULL, 3600000, '{"start_year":2019,"production_bpd":120000,"quality":"Medium heavy","note":"Petrobras 66.67%, Petrogal 28.33%, Barra Energia 5%","pipelines":"Berbigão/Sururu/Atapu FPSOs → Santos gathering","ports":"Santos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Sépia Field', 'Petrobras + Petrogal Brasil + QPI Brasil', 'Santos Basin Pre-Salt — Block BM-S-24', NULL, 'Energy', 'Crude Oil', -24.0000, -42.0000, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 29.00, NULL, 180000, 2000000000, 5400000, '{"start_year":2021,"production_bpd":180000,"quality":"Medium heavy","note":"Petrobras 55.5%, Petrogal 30%, QPI Brasil (Qatar Petroleum) 14.5%","pipelines":"Sépia FPSO → Santos gathering","ports":"Santos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Iara / Entorno de Iara', 'Petrobras + Shell + Galp', 'Santos Basin Pre-Salt — Block BM-S-11', NULL, 'Energy', 'Crude Oil', -25.2500, -43.7500, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'planned', 'Petrobras', 'joint_venture', 29.00, NULL, 0, 2500000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Medium heavy (estimated)","note":"Petrobras 65%, Shell 25%, Galp 10%; FID 2023; first oil targeted 2027","pipelines":"Planned FPSO → Santos gathering","ports":"Santos","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jupiter Field', 'Petrobras + Petrogal', 'Santos Basin Pre-Salt — Block BM-S-24, high CO2 gas + condensate', NULL, 'Energy', 'Condensate', -24.1667, -42.1667, 'Brazil', 'Santos Basin', 'Santos', 'oil_field', 'planned', 'Petrobras', 'joint_venture', 50.00, NULL, 0, 500000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Condensate (estimated)","note":"Petrobras 80%, Petrogal 20%; high CO2 content; FID pending; development on hold","pipelines":"None (undeveloped)","ports":"Santos (if developed)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BRAZIL — CAMPOS BASIN (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Marlim Complex (Marlim / Marlim Leste / Marlim Sul)', 'Petrobras', 'Campos Basin — offshore Rio de Janeiro', NULL, 'Energy', 'Crude Oil', -22.5000, -40.0000, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'state_owned', 20.00, 0.80, 300000, 1500000000, 9000000, '{"start_year":1991,"production_bpd":300000,"quality":"Marlim crude — Brazilian heavy benchmark","note":"Petrobras 100%; Brazil''s historic giant; mature post-salt","pipelines":"Marlim FPSOs → Campos gathering → Cabiúnas Terminal","ports":"Cabiúnas Terminal (Macaé)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Roncador Field', 'Petrobras + Equinor', 'Campos Basin — offshore Rio de Janeiro', NULL, 'Energy', 'Crude Oil', -22.2500, -39.7500, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 28.00, 0.40, 150000, 800000000, 4500000, '{"start_year":1999,"production_bpd":150000,"quality":"Medium","note":"Petrobras 75%, Equinor 25%; mature post-salt","pipelines":"Roncador FPSOs → Campos gathering → Cabiúnas","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Jubarte Field', 'Petrobras + Shell', 'Campos Basin — offshore Espírito Santo/Rio de Janeiro border', NULL, 'Energy', 'Crude Oil', -21.5000, -39.8333, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 31.00, 0.30, 80000, NULL, 2400000, '{"start_year":2008,"production_bpd":80000,"quality":"Medium light","note":"Petrobras 80%, Shell 20%; post-salt","pipelines":"Jubarte FPSO → Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Barracuda / Caratinga Fields', 'Petrobras + Shell', 'Campos Basin', NULL, 'Energy', 'Crude Oil', -22.7500, -40.1667, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 20.00, NULL, 100000, NULL, 3000000, '{"start_year":1996,"production_bpd":100000,"quality":"Heavy","note":"Petrobras 65%, Shell 35%; mature post-salt","pipelines":"Barracuda/Caratinga FPSOs → Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Albacora / Albacora Leste Fields', 'Petrobras', 'Campos Basin', NULL, 'Energy', 'Crude Oil', -22.3333, -39.8333, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'state_owned', 19.00, 0.90, 100000, NULL, 3000000, '{"start_year":1987,"production_bpd":100000,"quality":"Heavy","note":"Petrobras 100%; mature post-salt","pipelines":"Albacora FPSOs → Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Espadarte / Voador / Marimbá Complex', 'Petrobras + Shell', 'Campos Basin', NULL, 'Energy', 'Crude Oil', -22.0000, -40.2500, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 28.00, NULL, 50000, NULL, 1500000, '{"start_year":1990,"production_bpd":50000,"quality":"Medium","note":"Petrobras majority, Shell minority; mature","pipelines":"→ Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Golfinho / Caxaréu Fields', 'Petrobras + Chevron', 'Campos Basin', NULL, 'Energy', 'Crude Oil', -22.6667, -40.0833, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 30.00, NULL, 40000, NULL, 1200000, '{"start_year":2007,"production_bpd":40000,"quality":"Medium","note":"Petrobras 90%, Chevron 10%; mature","pipelines":"→ Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Peregrino Field', 'Equinor Brasil + Sinochem Brazil', 'Campos Basin — offshore Rio de Janeiro', NULL, 'Energy', 'Crude Oil', -22.3000, -40.5000, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Equinor Brasil', 'joint_venture', 14.00, 0.60, 100000, 600000000, 3000000, '{"start_year":2011,"production_bpd":100000,"quality":"Extra heavy — Brazil''s heaviest producing crude","note":"Equinor 60%, Sinochem 40%; Equinor-operated","pipelines":"Peregrino FPSOs → Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Frade Field', 'Chevron Brasil + Petrobras + Inpex', 'Campos Basin', NULL, 'Energy', 'Crude Oil', -22.8333, -40.3333, 'Brazil', 'Campos Basin', 'Macaé', 'oil_field', 'operational', 'Chevron Brasil', 'joint_venture', 27.00, NULL, 50000, NULL, 1500000, '{"start_year":2009,"production_bpd":50000,"quality":"Medium heavy","note":"Chevron 51.74%, Petrobras 30%, Inpex 18.26%; mature; 2011-2012 oil spills","pipelines":"Frade FPSO → Campos gathering","ports":"Cabiúnas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BRAZIL — ESPÍRITO SANTO BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Parque das Baleias (Golfinho Complex)', 'Petrobras + Shell', 'Espírito Santo Basin — offshore Espírito Santo', NULL, 'Energy', 'Crude Oil', -20.5000, -39.5000, 'Brazil', 'Espírito Santo', 'Vitória', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 30.00, NULL, 60000, NULL, 1800000, '{"start_year":2006,"production_bpd":60000,"quality":"Medium light","note":"Petrobras majority, Shell minority","pipelines":"Parque das Baleias → Espírito Santo gathering → Vitória","ports":"Vitória; Barra do Riacho Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cachalote Field', 'Petrobras', 'Espírito Santo Basin', NULL, 'Energy', 'Crude Oil', -20.7500, -39.7500, 'Brazil', 'Espírito Santo', 'Vitória', 'oil_field', 'operational', 'Petrobras', 'state_owned', 29.00, NULL, 20000, NULL, 600000, '{"start_year":2002,"production_bpd":20000,"quality":"Medium","note":"Petrobras 100%; mature","pipelines":"→ Espírito Santo gathering","ports":"Vitória","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Camarupim Norte Field', 'Petrobras + Enauta', 'Espírito Santo Basin', NULL, 'Energy', 'Crude Oil', -20.2500, -39.2500, 'Brazil', 'Espírito Santo', 'Vitória', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 31.00, NULL, 15000, NULL, 450000, '{"start_year":2015,"production_bpd":15000,"quality":"Medium light","note":"Petrobras 60%, Enauta 40%","pipelines":"→ Espírito Santo gathering","ports":"Vitória","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BRAZIL — SERGIPE-ALAGOAS BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Piranema Field', 'Petrobras + IBV Brasil', 'Sergipe-Alagoas Basin — offshore Sergipe/Alagoas', NULL, 'Energy', 'Crude Oil', -10.5000, -36.5000, 'Brazil', 'Sergipe-Alagoas', 'Atalaia Velha', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 36.00, 0.20, 25000, NULL, 750000, '{"start_year":1998,"production_bpd":25000,"quality":"Light sweet","note":"Petrobras 70%, IBV Brasil 30%; mature","pipelines":"Piranema FPSO → Atalaia Velha Terminal","ports":"Atalaia Velha Terminal (Sergipe)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Camorim Field', 'Petrobras + Enauta', 'Sergipe-Alagoas Basin', NULL, 'Energy', 'Crude Oil', -10.7500, -36.7500, 'Brazil', 'Sergipe-Alagoas', 'Atalaia Velha', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 35.00, NULL, 15000, NULL, 450000, '{"start_year":2011,"production_bpd":15000,"quality":"Light sweet","note":"Petrobras 50%, Enauta 50%","pipelines":"→ Sergipe-Alagoas gathering","ports":"Atalaia Velha","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Manati Field', 'Enauta + Petrobras + Brasoil', 'Camamu Basin — offshore Bahia, gas + condensate', NULL, 'Energy', 'Condensate', -13.5000, -38.5000, 'Brazil', 'Camamu Basin', 'Salvador', 'oil_field', 'operational', 'Enauta', 'joint_venture', 50.00, NULL, 3000, NULL, 90000, '{"start_year":2007,"production_bpd":3000,"quality":"Condensate","note":"Enauta 45%, Petrobras 45%, Brasoil 10%; gas-dominant with condensate","pipelines":"Manati subsea → Bahia onshore processing","ports":"Salvador (Bahia)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BRAZIL — AMAZON REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Urucu Field', 'Petrobras', 'Solimões Basin — onshore Amazonas state, remote jungle', NULL, 'Energy', 'Crude Oil', -4.8833, -65.2500, 'Brazil', 'Amazon', 'Coari', 'oil_field', 'operational', 'Petrobras', 'state_owned', 45.00, 0.02, 50000, 300000000, 1500000, '{"start_year":1988,"production_bpd":50000,"quality":"Urucu crude — Brazil''s lightest crude","note":"Petrobras 100%; Brazil''s only significant onshore oil; 650km SW of Manaus","pipelines":"Urucu → Coari (280km) → river barge → Belém","ports":"Coari; Belém","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rio Urucu / Leste do Urucu', 'Petrobras', 'Solimões Basin — Urucu area satellites', NULL, 'Energy', 'Crude Oil', -4.9167, -65.1667, 'Brazil', 'Amazon', 'Coari', 'oil_field', 'operational', 'Petrobras', 'state_owned', 44.00, NULL, 10000, NULL, 300000, '{"start_year":1990,"production_bpd":10000,"quality":"Light sweet","note":"Petrobras 100%; satellite to Urucu","pipelines":"→ Urucu gathering → Coari → river barge","ports":"Coari; Belém","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Foz do Amazonas Basin', 'Petrobras', 'Offshore Amazon mouth — exploration blocked', NULL, 'Energy', 'Crude Oil', 3.0000, -49.0000, 'Brazil', 'Amazon', NULL, 'oil_field', 'planned', 'Petrobras', 'state_owned', NULL, NULL, 0, 5000000000, 0, '{"start_year":null,"production_bpd":0,"quality":"Unknown","note":"Exploration blocked by IBAMA 2023-2024; environmental opposition; BP + TotalEnergies exited","pipelines":"None (blocked)","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BRAZIL — NORTHEAST ONSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Potiguar Basin', 'Petrobras + 3R Petroleum + PetroRecôncavo', 'Onshore Rio Grande do Norte state — northeastern Brazil', NULL, 'Energy', 'Crude Oil', -5.0000, -37.0000, 'Brazil', 'Northeast onshore', 'Guamaré', 'oil_field', 'operational', 'Petrobras', 'joint_venture', 37.00, 0.30, 40000, 500000000, 1200000, '{"start_year":1973,"production_bpd":40000,"quality":"Light sweet","note":"Petrobras majority; 3R Petroleum, PetroRecôncavo; mature onshore","pipelines":"Potiguar Basin → Guamaré Terminal","ports":"Guamaré Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Recôncavo Basin', 'PetroRecôncavo + Petrobras', 'Onshore Bahia state — Brazil''s first oil basin', NULL, 'Energy', 'Crude Oil', -12.5000, -38.5000, 'Brazil', 'Northeast onshore', 'São Francisco do Conde', 'oil_field', 'operational', 'PetroRecôncavo', 'joint_venture', 31.00, 0.80, 20000, 100000000, 600000, '{"start_year":1939,"production_bpd":20000,"quality":"Medium light","note":"PetroRecôncavo dominant; Brazil''s first commercial oil 1939","pipelines":"Recôncavo → Mataripe refinery; → São Francisco do Conde","ports":"São Francisco do Conde Terminal (Bahia)","rail":"Bahia state rail (limited)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CHILE — MAGALLANES BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Arenal Field', 'ENAP', 'Magallanes Region — onshore Tierra del Fuego, Chilean side', NULL, 'Energy', 'Crude Oil', -53.3333, -69.0000, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'ENAP', 'state_owned', 37.00, 0.40, 3500, 5000000, 105000, '{"start_year":1945,"production_bpd":3500,"quality":"Light sweet","note":"ENAP 100%; Chile''s first commercial oil field; Chile''s largest","pipelines":"Arenal → Clarencia Terminal","ports":"Clarencia Terminal (Punta Arenas); Cabo Negro","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Posesión Field', 'ENAP', 'Magallanes Region — onshore Chilean mainland, Strait of Magellan', NULL, 'Energy', 'Crude Oil', -52.5000, -69.2500, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'ENAP', 'state_owned', 36.00, NULL, 1000, NULL, 30000, '{"start_year":1960,"production_bpd":1000,"quality":"Light sweet","note":"ENAP 100%; mature","pipelines":"Posesión → Clarencia Terminal","ports":"Clarencia Terminal; Punta Arenas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Daniel Field', 'ENAP', 'Magallanes Region — onshore Tierra del Fuego Chilean side', NULL, 'Energy', 'Crude Oil', -53.5000, -68.7500, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'ENAP', 'state_owned', 38.00, NULL, 500, NULL, 15000, '{"start_year":1978,"production_bpd":500,"quality":"Light sweet","note":"ENAP 100%; small","pipelines":"Daniel → Arenal gathering → Clarencia","ports":"Clarencia; Cabo Negro","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CHILE — OFFSHORE
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tranquilo-Mataura Block', 'GeoPark Chile', 'Offshore Magallanes Basin — Strait of Magellan', NULL, 'Energy', 'Crude Oil', -53.7500, -70.5000, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'GeoPark Chile', 'private', 34.00, NULL, 500, NULL, 15000, '{"start_year":2003,"production_bpd":500,"quality":"Medium light","note":"GeoPark 100%; small offshore production","pipelines":"Offshore → subsea pipeline → Clarencia Terminal","ports":"Clarencia Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Campanario Field', 'GeoPark Chile', 'Offshore Magallanes Basin — Strait of Magellan', NULL, 'Energy', 'Crude Oil', -53.0000, -70.0000, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'GeoPark Chile', 'private', 35.00, NULL, 300, NULL, 9000, '{"start_year":2009,"production_bpd":300,"quality":"Light sweet","note":"GeoPark 100%; small","pipelines":"Campanario → Strait of Magellan subsea → Clarencia","ports":"Clarencia","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Fell Block', 'ENAP', 'Onshore/Offshore Magallanes — gas + condensate', NULL, 'Energy', 'Condensate', -53.2500, -69.5000, 'Chile', 'Magallanes Basin', 'Punta Arenas', 'oil_field', 'operational', 'ENAP', 'state_owned', 45.00, NULL, 200, NULL, 6000, '{"start_year":1975,"production_bpd":200,"quality":"Condensate","note":"ENAP 100%; gas-dominant with minimal condensate","pipelines":"Fell → Punta Arenas gas pipeline; condensate to Clarencia","ports":"Clarencia","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();
