-- ============================================================
-- Poland Oil Production Sites — 7 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- BALTIC SEA (OFFSHORE)
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('B3 (Petrobaltic) Field', 'Orlen Upstream', 'Polish Baltic Sea — offshore', NULL, 'Energy', 'Crude Oil', 55.1667, 18.2500, 'Poland', 'Baltic Sea', 'Gdańsk', 'oil_field', 'operational', 'Orlen Upstream', 'state_owned', 37.00, 0.20, 150000, 30000000, 150000, '{"start_year":1994,"production_bpd":5000,"quality":"Light sweet — Baltic Blend crude","note":"Poland''s only offshore oil production; discovered 1986; LOTOS Petrobaltic → Orlen Upstream (PKN Orlen acquired LOTOS 2022)","last_transaction":"PKN Orlen acquired LOTOS Group 2022 for ~€2.2B (Polish state-mandated merger; EU required partial asset sales to Saudi Aramco, MOL, Eni)","contract_duration":"Polish mining concession to 2035","pipelines":"B3 platform → FPSO Petrobaltic → tanker export; Gdańsk refinery via tanker","ports":"Gdańsk Port; Gdynia","rail":"Gdańsk–Warsaw rail (indirect)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('B8 Field', 'Orlen Upstream', 'Polish Baltic Sea', NULL, 'Energy', 'Crude Oil', 55.0833, 18.5000, 'Poland', 'Baltic Sea', 'Gdańsk', 'oil_field', 'operational', 'Orlen Upstream', 'state_owned', 36.00, NULL, 60000, NULL, 60000, '{"start_year":2003,"production_bpd":2000,"quality":"Light sweet","note":"Orlen Upstream 100%; PGNiG absorbed into Orlen 2022","contract_duration":"Polish mining concession","pipelines":"B8 → Petrobaltic FPSO → Gdańsk","ports":"Gdańsk","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- CARPATHIAN REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Górna Ropa Field', 'PGNiG/Orlen', 'Małopolska — Carpathian foothills, Gorlice District', NULL, 'Energy', 'Crude Oil', 49.6500, 21.1833, 'Poland', 'Carpathian', 'Gorlice', 'oil_field', 'operational', 'PGNiG/Orlen', 'state_owned', 33.00, 0.60, 24000, 5000000, 24000, '{"start_year":1854,"production_bpd":800,"quality":"Medium light","note":"Historic — world''s first commercial oil well area; Ignacy Łukasiewicz drilled first oil well in Bóbrka nearby 1854 — birthplace of modern petroleum industry; very mature","last_transaction":"PGNiG absorbed into Orlen 2022","contract_duration":"Polish mining concession (perpetual historic)","pipelines":"Carpathian fields → Jasło refinery (historic crude processing center)","ports":"None (landlocked southern Poland)","rail":"Nowy Sącz–Kraków rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bóbrka Field', 'PGNiG/Orlen', 'Subcarpathian Province — Krosno District', NULL, 'Energy', 'Crude Oil', 49.6667, 21.8167, 'Poland', 'Carpathian', 'Krosno', 'oil_field', 'operational', 'PGNiG/Orlen', 'state_owned', 32.00, NULL, 6000, 1000000, 6000, '{"start_year":1854,"production_bpd":200,"quality":"Medium light","note":"World''s oldest continuously producing oil field — since 1854; Ignacy Łukasiewicz + Jan Zeh — first recorded commercial oil well in history; Bóbrka museum-field still producing; UNESCO heritage significance","last_transaction":"Maintained as working museum","contract_duration":"Polish mining concession","pipelines":"Bóbrka → Krosno gathering → Jasło","ports":"None","rail":"Krosno–Rzeszów rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Grabownica Field', 'PGNiG/Orlen', 'Subcarpathian Province', NULL, 'Energy', 'Crude Oil', 49.7000, 22.0833, 'Poland', 'Carpathian', 'Sanok', 'oil_field', 'operational', 'PGNiG/Orlen', 'state_owned', 33.00, NULL, 15000, NULL, 15000, '{"start_year":1895,"production_bpd":500,"quality":"Medium light","note":"Mature; Austro-Hungarian era Galician oil rush","contract_duration":"Polish mining concession","pipelines":"Subcarpathian gathering → Jasło → Gdańsk pipeline (PERN Przyjaźń)","ports":"Gdańsk (via PERN pipeline)","rail":"Sanok–Rzeszów rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Wańkowa (Mrukowa) Field', 'PGNiG/Orlen', 'Subcarpathian — Krosno area', NULL, 'Energy', 'Crude Oil', 49.7500, 21.9167, 'Poland', 'Carpathian', 'Krosno', 'oil_field', 'operational', 'PGNiG/Orlen', 'state_owned', 32.00, NULL, 9000, NULL, 9000, '{"start_year":1890,"production_bpd":300,"quality":"Medium light","note":"Galician oil boom era","contract_duration":"Polish mining concession","pipelines":"Krosno gathering → Jasło","ports":"Gdańsk (indirect)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lubaczów Field', 'PGNiG/Orlen', 'Subcarpathian — near Ukraine border', NULL, 'Energy', 'Crude Oil', 50.1667, 23.1167, 'Poland', 'Carpathian', 'Lubaczów', 'oil_field', 'operational', 'PGNiG/Orlen', 'state_owned', 34.00, NULL, 18000, NULL, 18000, '{"start_year":1960,"production_bpd":600,"quality":"Medium light","note":"Eastern Subcarpathian cluster; small cluster; PGNiG/Orlen 100%","contract_duration":"Polish mining concession","pipelines":"Eastern Subcarpathian → PERN pipeline → Gdańsk","ports":"Gdańsk","rail":"Rzeszów–Przemyśl rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- VERIFICATION
-- =====================
-- SELECT COUNT(*) FROM commodity_locations WHERE country = 'Poland' AND commodity_name = 'Crude Oil';
-- SELECT title, region, operational_status, current_production, reserves_estimate FROM commodity_locations WHERE country = 'Poland' AND commodity_name = 'Crude Oil' ORDER BY region, current_production DESC;
