-- ============================================================
-- Qatar Oil Production Sites — 29 Fields (UPSERT)
-- Run this in Supabase SQL Editor
-- ============================================================

-- =====================
-- OFFSHORE QATAR
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Shaheen Field', 'TotalEnergies / QatarEnergy', 'Offshore Qatar — Block 5, North', NULL, 'Energy', 'Crude Oil', 26.1667, 51.5833, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'TotalEnergies (operator) + QatarEnergy', 'joint_venture', 28.00, 2.60, 9000000, 2100000000, 9000000, '{"start_year":1994,"production_bpd":300000,"quality":"Medium heavy, Sour — Al-Shaheen crude export blend","note":"Qatar''s largest oil field","ownership_split":"TotalEnergies 30%, QatarEnergy 70%","last_transaction":"TotalEnergies PSA renewed 2017 for 20 years; acquired Maersk Oil 2018 for $7.45B","contract_duration":"PSA to 2037","pipelines":"Al-Shaheen FPSO → subsea pipeline → Halul Island Export Terminal","ports":"Halul Island Crude Oil Terminal; Ras Laffan Industrial City","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Maydan Mahzam Field', 'QatarEnergy', 'Offshore Qatar — central', NULL, 'Energy', 'Crude Oil', 25.5833, 51.9167, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 36.00, 1.40, 1800000, 800000000, 1800000, '{"start_year":1963,"production_bpd":60000,"quality":"Light","maturity":"Mature","last_transaction":"Fully nationalized 1977","pipelines":"Maydan Mahzam → Halul Island subsea pipeline","ports":"Halul Island Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bul Hanine Field', 'QatarEnergy', 'Offshore Qatar — southeastern', NULL, 'Energy', 'Crude Oil', 25.2500, 51.8333, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 32.00, 2.10, 1500000, 1200000000, 1500000, '{"start_year":1972,"production_bpd":50000,"quality":"Medium","note":"Redevelopment phase; targeting 80,000 bpd post-redevelopment","last_transaction":"QatarEnergy awarded $2.5B redevelopment contract 2018","pipelines":"Bul Hanine → Halul Island subsea pipeline (upgraded)","ports":"Halul Island Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Idd El Shargi North Dome (ISND) Field', 'Occidental / QatarEnergy', 'Offshore Qatar — eastern', NULL, 'Energy', 'Crude Oil', 25.6500, 52.3333, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'Occidental Petroleum (Oxy) + QatarEnergy', 'joint_venture', 37.00, 1.20, 2400000, 700000000, 2400000, '{"start_year":1994,"production_bpd":80000,"quality":"Light","ownership_split":"Oxy 100% technical operator; QatarEnergy sovereign","last_transaction":"Oxy PSA renewed 2016 for 15 years — Oxy''s flagship Qatar asset","contract_duration":"PSA to 2031","pipelines":"ISND → Halul Island subsea export pipeline; FPSO storage + tanker loading","ports":"Halul Island Terminal; direct FPSO tanker loading","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Idd El Shargi South Dome (ISSD) Field', 'Occidental / QatarEnergy', 'Offshore Qatar', NULL, 'Energy', 'Crude Oil', 25.5167, 52.2500, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'Occidental Petroleum + QatarEnergy', 'joint_venture', 35.00, 1.50, 900000, 300000000, 900000, '{"start_year":1997,"production_bpd":30000,"quality":"Light","ownership_split":"Oxy operator; QatarEnergy sovereign","pipelines":"ISSD → Halul Island pipeline","ports":"Halul Island","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Rayyan Field', 'QatarEnergy', 'Offshore Qatar — Block 4', NULL, 'Energy', 'Crude Oil', 25.4167, 51.6667, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 33.00, 1.80, 450000, 200000000, 450000, '{"start_year":1996,"production_bpd":15000,"quality":"Medium","pipelines":"Al-Rayyan → Halul Island pipeline","ports":"Halul Island Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Khalij Field', 'TotalEnergies / QatarEnergy', 'Offshore Qatar — Block 6', NULL, 'Energy', 'Crude Oil', 25.8333, 52.0833, 'Qatar', 'Offshore', 'Halul', 'oil_field', 'operational', 'TotalEnergies + QatarEnergy', 'joint_venture', 29.00, 2.30, 750000, 250000000, 750000, '{"start_year":2000,"production_bpd":25000,"quality":"Medium heavy","ownership_split":"TotalEnergies 40%, QatarEnergy 60%","last_transaction":"TotalEnergies PSA signed 1996","contract_duration":"PSA to 2026 (renewal expected)","pipelines":"Al-Khalij → Halul Island subsea pipeline","ports":"Halul Island Terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Bunduq Field', 'QatarEnergy / ADNOC', 'Offshore Qatar — shared with UAE', NULL, 'Energy', 'Crude Oil', 25.0000, 52.5833, 'Qatar', 'Offshore', 'Das Island', 'oil_field', 'operational', 'UPDC', 'joint_venture', 37.00, 1.10, 450000, 300000000, 450000, '{"start_year":1975,"production_bpd":15000,"quality":"Light","note":"Qatar share ~7,500 bpd; joint development zone with UAE","ownership_split":"QatarEnergy 50%, Abu Dhabi (ADNOC/ADPC) 50%","last_transaction":"UPDC operating agreement ongoing since 1970s","contract_duration":"Joint zone agreement (perpetual treaty)","pipelines":"El Bunduq → Abu Dhabi Das Island (UAE export terminal)","ports":"Das Island Terminal (UAE); Halul Island (Qatar share, indirect)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Salwa Field', 'QatarEnergy', 'Offshore Qatar — southwestern, near Saudi border', NULL, 'Energy', 'Crude Oil', 24.8333, 50.9167, 'Qatar', 'Offshore', 'Mesaieed', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 30.00, 1.50, 240000, 100000000, 240000, '{"start_year":1981,"production_bpd":8000,"quality":"Medium sour","maturity":"Mature, smaller","pipelines":"Salwa → Mesaieed (onshore) pipeline","ports":"Mesaieed Industrial City / Ras Abu Fontas terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Overhead / Al-Wajba Offshore Condensate', 'QatarEnergy', 'Offshore Qatar — near Ras Laffan', NULL, 'Energy', 'Crude Oil', 25.9167, 51.5500, 'Qatar', 'Offshore', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 50.00, 0.03, 360000, NULL, 360000, '{"start_year":2005,"production_bpd":12000,"quality":"Condensate sweet","note":"Condensate associated with offshore gas","pipelines":"Offshore → Ras Laffan Industrial City condensate pipeline","ports":"Ras Laffan Port","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Ras Abu Fontas Offshore Area', 'QatarEnergy', 'Near shore, central west coast, Qatar', NULL, 'Energy', 'Crude Oil', 25.1167, 51.5500, 'Qatar', 'Offshore', 'Mesaieed', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 34.00, 1.00, 150000, NULL, 150000, '{"start_year":1975,"production_bpd":5000,"quality":"Medium","maturity":"Mature nearshore","pipelines":"Ras Abu Fontas → Mesaieed terminal (very short)","ports":"Ras Abu Fontas / Mesaieed","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qatar Petroleum Offshore Block A/B', 'QatarEnergy / ExxonMobil', 'Deep offshore Qatar', NULL, 'Energy', 'Crude Oil', 26.5000, 53.0000, 'Qatar', 'Offshore', 'Ras Laffan', 'oil_field', 'planned', 'QatarEnergy + ExxonMobil', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2018,"note":"Exploration — deep offshore frontier","ownership_split":"ExxonMobil 30%, QatarEnergy 70%","last_transaction":"Deep offshore PSA signed 2018","contract_duration":"PSA to 2038","pipelines":"None yet","ports":"Ras Laffan (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- DUKHAN FIELD
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan Field — Jaleha Reservoir', 'QatarEnergy', 'Onshore Western Qatar', NULL, 'Energy', 'Crude Oil', 25.4333, 50.7833, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 41.00, 0.70, 2400000, 500000000, 2400000, '{"start_year":1940,"production_bpd":80000,"quality":"Light sweet — Dukhan crude, Qatar''s premium onshore export grade","note":"Qatar''s only significant onshore oil field; discovered 1935 by Anglo-Persian/IPC; production 1949","ooip":"2.1 billion barrels (all Dukhan reservoirs); ~500M remaining","last_transaction":"Full nationalization completed 1977","pipelines":"Dukhan–Mesaieed crude export pipeline (~85km); Dukhan–Umm Said pipeline","ports":"Mesaieed Industrial City Export Terminal; Ras Abu Fontas","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan Field — Khatiyah Reservoir', 'QatarEnergy', 'Onshore Western Qatar', NULL, 'Energy', 'Crude Oil', 25.6167, 50.7500, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 40.00, 0.70, 750000, 300000000, 750000, '{"start_year":1961,"production_bpd":25000,"quality":"Light sweet","note":"Part of Dukhan total","pipelines":"Khatiyah → Dukhan gathering → Mesaieed pipeline","ports":"Mesaieed","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan Field — Fahahil Reservoir', 'QatarEnergy', 'Onshore Western Qatar', NULL, 'Energy', 'Crude Oil', 25.3167, 50.8000, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 38.00, 0.70, 450000, 200000000, 450000, '{"start_year":1966,"production_bpd":15000,"quality":"Light sweet","pipelines":"Fahahil → Dukhan gathering → Mesaieed","ports":"Mesaieed","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan Field — Uwainat Reservoir', 'QatarEnergy', 'Onshore Western Qatar', NULL, 'Energy', 'Crude Oil', 25.2000, 50.8333, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 36.00, 0.90, 300000, 150000000, 300000, '{"start_year":1972,"production_bpd":10000,"quality":"Medium light","note":"Deep carbonate reservoir, EOR gas injection","pipelines":"Uwainat → Dukhan → Mesaieed pipeline","ports":"Mesaieed","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan Gas Cap — Khuff Reservoir', 'QatarEnergy', 'Dukhan, deep gas + condensate', NULL, 'Energy', 'Crude Oil', 25.5000, 50.7667, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 52.00, 0.03, 600000, 400000000, 600000, '{"start_year":1974,"production_bpd":20000,"quality":"Condensate very light sweet","note":"Major gas reservoir beneath Dukhan oil — Khuff carbonate; condensate from 1978","reserves_gas":"~8 TCF","pipelines":"Khuff gas → Dukhan gas plant → QAFCO; condensate → Mesaieed","ports":"Mesaieed","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Dukhan NGL / Condensate Stabilization', 'QatarEnergy', 'Dukhan onshore plant, Qatar', NULL, 'Energy', 'Crude Oil', 25.4000, 50.7667, 'Qatar', 'Dukhan', 'Dukhan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', NULL, NULL, 1050000, NULL, 1050000, '{"start_year":1949,"production_bpd":"~35,000 bbl/day equivalent condensate + NGL","quality":"NGL, propane, butane, stabilized condensate","note":"Processing facility for entire Dukhan output; expansions 1974, 1988, 2005","pipelines":"Dukhan Plant → Mesaieed pipeline; LPG to Ras Abu Fontas","ports":"Mesaieed LPG/condensate terminal","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- NORTH FIELD REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('North Field — Alpha (NFA) Condensate', 'QatarEnergy', 'Offshore North Field, Qatar', NULL, 'Energy', 'Crude Oil', 26.2500, 51.5000, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy', 'state_owned', 55.00, 0.02, 6000000, 3000000000, 6000000, '{"start_year":1991,"production_bpd":200000,"quality":"Ultra-light condensate sweet — Qatar Land/Marine blend contributors","note":"World''s largest gas field development; gas from 1991, condensate from 1993; NFA expansion FID 2021","reserves_gas":"~900 TCF (entire North Field, shared with Iran South Pars)","last_transaction":"NFA expansion $28.75B FID 2021; NFE $28.75B FID 2021 — combined ~$57.5B NF expansion","pipelines":"North Field offshore → Ras Laffan (~100km); condensate stabilization → export jetties","ports":"Ras Laffan Industrial City; Halul Island (backup)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('North Field — East (NFE) Expansion', 'QatarEnergy / TotalEnergies / ExxonMobil / Shell / ConocoPhillips / Eni', 'Offshore North Field, Qatar', NULL, 'Energy', 'Crude Oil', 26.5000, 51.8333, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy + IOCs', 'joint_venture', 55.00, 0.02, 0, NULL, 0, '{"start_year":2021,"production_bpd":"~130,000 at plateau (from NFE trains, first train 2026)","quality":"Ultra-light condensate sweet","note":"NFE FID 2021; first LNG train 2026; major expansion underway","ownership_split":"QatarEnergy 75%; TotalEnergies 6.25%, ExxonMobil 6.25%, Shell 6.25%, ConocoPhillips 3.125%, Eni 3.125%","last_transaction":"IOC PSA agreements signed 2021–2022; TotalEnergies first to sign Oct 2021","contract_duration":"27 years from first LNG cargo (to ~2053)","pipelines":"NFE offshore wellheads → Ras Laffan NGL/condensate processing","ports":"Ras Laffan — 4 new LNG mega-trains + condensate export jetties","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('North Field — South (NFS) Expansion', 'QatarEnergy / TotalEnergies', 'Offshore North Field, Qatar', NULL, 'Energy', 'Crude Oil', 26.0000, 51.2500, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'planned', 'QatarEnergy + TotalEnergies', 'joint_venture', 54.00, 0.02, 0, NULL, 0, '{"start_year":2022,"production_bpd":"~100,000 condensate at plateau","quality":"Ultra-light condensate sweet","note":"NFS FID 2022; targeted 2027–2028","ownership_split":"QatarEnergy 80%, TotalEnergies 20%","last_transaction":"TotalEnergies NFS PSA signed Jan 2022","contract_duration":"27 years from first cargo","pipelines":"NFS → Ras Laffan processing","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('North Field — West (NFW) / Spur Fields', 'QatarEnergy', 'Offshore North Field, Qatar', NULL, 'Energy', 'Crude Oil', 25.8333, 51.1667, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'planned', 'QatarEnergy', 'state_owned', 53.00, 0.02, 0, NULL, 0, '{"note":"Exploration / Development planning","production_bpd":"Potential ~50,000 condensate","quality":"Ultra-light condensate","pipelines":"Planned → Ras Laffan","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Barzan Field', 'QatarEnergy / ExxonMobil', 'North Field fringe — offshore gas + condensate', NULL, 'Energy', 'Crude Oil', 26.3333, 51.3333, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy + ExxonMobil (Rasgas era)', 'joint_venture', 52.00, 0.03, 750000, 200000000, 750000, '{"start_year":2014,"production_bpd":25000,"quality":"Condensate light sweet","note":"Gas + condensate for domestic supply; + 1.4 BCFD gas domestic","reserves_gas":"~3 TCF (dedicated domestic allocation)","ownership_split":"QatarEnergy 93%, ExxonMobil 7%","last_transaction":"ExxonMobil Barzan Gas Agreement signed 2007; project cost ~$10B","contract_duration":"Gas sales agreement to 2043","pipelines":"Barzan offshore → Ras Laffan Barzan plant → domestic QEWC grid; condensate → Ras Laffan export","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qatargas 1 / North Field Trains 1–3', 'QatarEnergy / TotalEnergies / ExxonMobil / Marubeni / Mitsui', 'Offshore North Field + Ras Laffan', NULL, 'Energy', 'Crude Oil', 26.1667, 51.2167, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy (QG1)', 'joint_venture', 54.00, 0.02, 1200000, NULL, 1200000, '{"start_year":1996,"production_bpd":40000,"quality":"Ultra-light condensate sweet","note":"Original LNG trains — condensate byproduct; condensate since 1997","ownership_split":"QatarEnergy 65%, TotalEnergies 10%, ExxonMobil 10%, Marubeni 7.5%, Mitsui 7.5%","last_transaction":"QG1 original PSA 1992; QatarEnergy restructured Qatargas/Rasgas 2022","contract_duration":"LNG SPAs to 2021–2024 (some extended)","pipelines":"North Field → Ras Laffan QG1 trains; condensate → export jetties","ports":"Ras Laffan Industrial City","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Qatargas 2 / North Field Trains 4–5', 'QatarEnergy / ExxonMobil / Total', 'Offshore North Field', NULL, 'Energy', 'Crude Oil', 26.2000, 51.2500, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy + ExxonMobil', 'joint_venture', 55.00, 0.02, 1650000, NULL, 1650000, '{"start_year":2009,"production_bpd":55000,"quality":"Ultra-light condensate sweet","note":"Mega-trains 7.8 MTPA each — world''s largest LNG trains when built","ownership_split":"QG2: QatarEnergy 70%, ExxonMobil 30% (T4); QatarEnergy 65%, Total 16.7%, ExxonMobil 18.3% (T5)","last_transaction":"QG2 PSA signed 2003; $14B project","pipelines":"QG2 → Ras Laffan condensate stabilization → export jetties","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Rasgas / North Field Trains 6–7', 'QatarEnergy / ExxonMobil', 'Offshore North Field', NULL, 'Energy', 'Crude Oil', 26.2333, 51.2833, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy + ExxonMobil (Rasgas legacy)', 'joint_venture', 54.00, 0.02, 1350000, NULL, 1350000, '{"start_year":2009,"production_bpd":45000,"quality":"Ultra-light condensate sweet","ownership_split":"QatarEnergy 70%, ExxonMobil 30%","last_transaction":"QatarEnergy merged Qatargas and Rasgas into single entity 2022","contract_duration":"LNG SPAs to 2030s+","pipelines":"RasGas trains → Ras Laffan condensate → export","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Al-Khaleej Condensate Field', 'QatarEnergy / TotalEnergies', 'North Field fringe — offshore', NULL, 'Energy', 'Crude Oil', 26.0833, 51.6667, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy + TotalEnergies', 'joint_venture', 53.00, 0.02, 600000, 150000000, 600000, '{"start_year":2008,"production_bpd":20000,"quality":"Ultra-light sweet","ownership_split":"QatarEnergy 70%, TotalEnergies 30%","last_transaction":"TotalEnergies Al-Khaleej PSA signed 2004","contract_duration":"PSA to 2034","pipelines":"Al-Khaleej → Ras Laffan condensate pipeline","ports":"Ras Laffan","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Laffan Condensate Refinery Output', 'QatarEnergy / Total / Idemitsu / Cosmo / Shell / Mitsui / Marubeni', 'Ras Laffan — condensate processing', NULL, 'Energy', 'Crude Oil', 26.1333, 51.5667, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'operational', 'QatarEnergy (Laffan Refinery 1 + 2)', 'joint_venture', 55.00, 0.02, 4380000, NULL, 4380000, '{"start_year":2009,"production_bpd":"~146,000 refined products from condensate (naphtha, kerosene, gasoil)","quality":"Input API ~55°; outputs: naphtha, kerosene, diesel","note":"Condensate refinery processing North Field condensate — LR1 2009, LR2 2016","ownership_split":"LR1: QatarEnergy 84.4%, Total 9.8%, Idemitsu 3.3%, Cosmo 2.5%; LR2: QatarEnergy 63.3%, Shell 18.3%, Total 9.3%, Idemitsu 5.8%, Cosmo 2.5%, Mitsui/Marubeni 0.8%","last_transaction":"LR2 $1.4B investment, FID 2012","contract_duration":"Refinery agreement to 2040+","pipelines":"North Field condensate → Laffan Refinery → product pipeline → export jetties","ports":"Ras Laffan Industrial City (product tanker loading)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('North Field Offshore Block NF-1', 'QatarEnergy / Shell', 'Deep exploration — offshore', NULL, 'Energy', 'Crude Oil', 27.0000, 51.8333, 'Qatar', 'North Field', 'Ras Laffan', 'oil_field', 'planned', 'QatarEnergy + Shell', 'joint_venture', NULL, NULL, 0, NULL, 0, '{"start_year":2019,"note":"Exploration — deep exploration block frontier","ownership_split":"Shell 30%, QatarEnergy 70%","last_transaction":"Shell deep exploration PSA signed 2019","contract_duration":"PSA to 2034","pipelines":"None yet","ports":"Ras Laffan (planned)","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- ============================================================
-- Verification
-- ============================================================
SELECT count(*) AS qatar_oil_fields
FROM public.commodity_locations
WHERE country = 'Qatar' AND commodity_name = 'Crude Oil';

SELECT count(*) AS total_locations
FROM public.commodity_locations;
