-- ============================================================
-- Argentina & Bolivia — Oil Production Sites (UPSERT)
-- Run this in Supabase SQL Editor
-- Argentina: 22 sites | Bolivia: 10 sites
-- ============================================================

-- =====================
-- ARGENTINA — NEUQUÉN BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vaca Muerta Formation', 'YPF + Vista Energy + Tecpetrol + Shell + ExxonMobil + Chevron + TotalEnergies + Equinor', 'Neuquén Province — unconventional shale oil/gas', NULL, 'Energy', 'Crude Oil', -38.5000, -69.5000, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'YPF', 'joint_venture', 44.00, 0.20, 300000, 16000000000, 9000000, '{"start_year":2010,"production_bpd":300000,"quality":"Vaca Muerta crude — premium tight oil","note":"Argentina''s largest unconventional play; targeting 1M+ bpd by 2030","pipelines":"Vaca Muerta → Oldelval → Bahía Blanca","ports":"Bahía Blanca","rail":"Ferrosur Roca crude-by-rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Loma Campana', 'YPF + Chevron', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.3333, -69.8333, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'YPF', 'joint_venture', 44.00, NULL, 80000, 3000000000, 2400000, '{"start_year":2015,"production_bpd":80000,"quality":"Light sweet","note":"YPF 50%, Chevron 50%; Vaca Muerta''s largest producing block","pipelines":"Loma Campana → Oldelval → Bahía Blanca","ports":"Bahía Blanca","rail":"Vaca Muerta crude-by-rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bandurria Sur', 'Vista Energy', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.7500, -69.2500, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'Vista Energy', 'private', 43.00, NULL, 50000, 1500000000, 1500000, '{"start_year":2017,"production_bpd":50000,"quality":"Light sweet","note":"Vista Energy 100%; Miguel Galuccio flagship asset","pipelines":"Bandurria Sur → Oldelval","ports":"Bahía Blanca","rail":"Crude-by-rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Aguada Pichana Este', 'Shell Argentina + ExxonMobil', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.4167, -69.6667, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'Shell Argentina', 'joint_venture', 45.00, NULL, 30000, NULL, 900000, '{"start_year":2019,"production_bpd":30000,"quality":"Light sweet","note":"Shell 70%, ExxonMobil 30%","pipelines":"→ Oldelval","ports":"Bahía Blanca","rail":"Rail option"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Bajada del Palo Oeste', 'Tecpetrol', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.6667, -69.5000, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'Tecpetrol', 'private', 43.00, NULL, 25000, NULL, 750000, '{"start_year":2018,"production_bpd":25000,"quality":"Light sweet","note":"Tecpetrol 100% (Techint Group)","pipelines":"→ Oldelval","ports":"Bahía Blanca","rail":"Rail option"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('La Amarga Chica', 'TotalEnergies + Wintershall Dea + PAE', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.2500, -70.0000, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'TotalEnergies', 'joint_venture', 44.00, NULL, 20000, NULL, 600000, '{"start_year":2019,"production_bpd":20000,"quality":"Light sweet","note":"TotalEnergies 41%, Wintershall Dea 37%, PAE 22%","pipelines":"→ Oldelval","ports":"Bahía Blanca","rail":"Rail option"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Orejano', 'Equinor Argentina + YPF', 'Vaca Muerta — Neuquén Province', NULL, 'Energy', 'Crude Oil', -38.8333, -69.3333, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'Equinor Argentina', 'joint_venture', 43.00, NULL, 15000, NULL, 450000, '{"start_year":2020,"production_bpd":15000,"quality":"Light sweet","note":"Equinor 50%, YPF 50%","pipelines":"→ Oldelval","ports":"Bahía Blanca","rail":"Rail option"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Centenario', 'YPF + multiple', 'Neuquén Basin — conventional', NULL, 'Energy', 'Crude Oil', -38.8333, -69.2333, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'YPF', 'joint_venture', 28.00, 1.20, 20000, 200000000, 600000, '{"start_year":1918,"production_bpd":20000,"quality":"Medium heavy","note":"Historic Argentine oil heartland; conventional predates Vaca Muerta","pipelines":"Centenario → Neuquén gathering → Oldelval","ports":"Bahía Blanca","rail":"Ferrosur Roca"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Plaza Huincul', 'YPF + PAE', 'Neuquén Basin — conventional', NULL, 'Energy', 'Crude Oil', -38.9167, -69.2167, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'YPF', 'joint_venture', 26.00, 1.50, 15000, NULL, 450000, '{"start_year":1918,"production_bpd":15000,"quality":"Heavy","note":"Mature conventional","pipelines":"Plaza Huincul → Neuquén gathering → Oldelval","ports":"Bahía Blanca","rail":"Ferrosur Roca"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Lindero Atravesado', 'YPF + Vista Energy', 'Neuquén Basin — conventional + unconventional', NULL, 'Energy', 'Crude Oil', -39.0000, -69.0000, 'Argentina', 'Neuquén Basin', 'Bahía Blanca', 'oil_field', 'operational', 'YPF', 'joint_venture', 38.00, NULL, 20000, NULL, 600000, '{"start_year":1960,"production_bpd":20000,"quality":"Light (unconventional) / Medium (conventional) mixed","note":"YPF, Vista Energy","pipelines":"→ Oldelval","ports":"Bahía Blanca","rail":"Ferrosur Roca"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ARGENTINA — SAN JORGE BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cerro Dragón', 'YPF + Pan American Energy', 'Chubut Province — San Jorge Basin', NULL, 'Energy', 'Crude Oil', -45.6667, -67.5833, 'Argentina', 'San Jorge Basin', 'Comodoro Rivadavia', 'oil_field', 'operational', 'YPF', 'joint_venture', 33.00, 0.80, 80000, 300000000, 2400000, '{"start_year":1961,"production_bpd":80000,"quality":"San Jorge Basin crude benchmark","note":"YPF 50%, PAE 50%; Argentina''s largest conventional field","pipelines":"Cerro Dragón → Caleta Olivia → Caleta Córdova Marine Terminal","ports":"Caleta Córdova (Comodoro Rivadavia)","rail":"Comodoro Rivadavia–Buenos Aires (limited)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Koluel Kaike', 'YPF + PAE', 'Chubut Province — San Jorge Basin', NULL, 'Energy', 'Crude Oil', -45.8333, -67.7500, 'Argentina', 'San Jorge Basin', 'Comodoro Rivadavia', 'oil_field', 'operational', 'YPF', 'joint_venture', 32.00, NULL, 20000, NULL, 600000, '{"start_year":1944,"production_bpd":20000,"quality":"Medium light","note":"YPF, PAE; mature","pipelines":"Koluel Kaike → Caleta Olivia → Caleta Córdova","ports":"Caleta Córdova","rail":"Comodoro Rivadavia rail"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Manantiales Behr', 'YPF + PAE + others', 'Chubut Province — San Jorge Basin', NULL, 'Energy', 'Crude Oil', -45.5000, -67.3333, 'Argentina', 'San Jorge Basin', 'Comodoro Rivadavia', 'oil_field', 'operational', 'YPF', 'joint_venture', 31.00, 0.90, 25000, NULL, 750000, '{"start_year":1959,"production_bpd":25000,"quality":"Medium light","note":"YPF, PAE, others","pipelines":"Manantiales Behr → Caleta Olivia → Caleta Córdova","ports":"Caleta Córdova","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Tordillo', 'YPF + PAE + Total Austral', 'Santa Cruz Province — San Jorge Basin south', NULL, 'Energy', 'Crude Oil', -47.0000, -67.5000, 'Argentina', 'San Jorge Basin', 'Caleta Córdova', 'oil_field', 'operational', 'YPF', 'joint_venture', 30.00, NULL, 15000, NULL, 450000, '{"start_year":1978,"production_bpd":15000,"quality":"Medium","note":"YPF, PAE, Total Austral","pipelines":"El Tordillo → Pico Truncado → Caleta Córdova","ports":"Caleta Córdova; Punta Loyola","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cañadón Perdido', 'YPF', 'Chubut Province — San Jorge Basin', NULL, 'Energy', 'Crude Oil', -46.0000, -67.8333, 'Argentina', 'San Jorge Basin', 'Comodoro Rivadavia', 'oil_field', 'operational', 'YPF', 'state_owned', 32.00, NULL, 10000, NULL, 300000, '{"start_year":1965,"production_bpd":10000,"quality":"Medium light","note":"YPF 100%","pipelines":"Cañadón Perdido → Caleta Olivia gathering","ports":"Caleta Córdova","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('El Huemul', 'YPF + PAE', 'Santa Cruz Province — offshore San Jorge Gulf', NULL, 'Energy', 'Crude Oil', -46.5000, -67.2500, 'Argentina', 'San Jorge Basin', 'Comodoro Rivadavia', 'oil_field', 'operational', 'YPF', 'joint_venture', 28.00, NULL, 5000, NULL, 150000, '{"start_year":2001,"production_bpd":5000,"quality":"Medium heavy","note":"YPF 50%, PAE 50%; offshore shallow water","pipelines":"El Huemul platform → Caleta Córdova subsea pipeline","ports":"Caleta Córdova","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ARGENTINA — AUSTRAL BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Cañadón Alfa / Tierra del Fuego Fields', 'Total Austral + YPF + Wintershall Dea', 'Tierra del Fuego Province — southernmost oil production', NULL, 'Energy', 'Crude Oil', -53.8333, -67.7500, 'Argentina', 'Austral Basin', 'Río Grande', 'oil_field', 'operational', 'Total Austral', 'joint_venture', 29.00, 1.00, 25000, 300000000, 750000, '{"start_year":1949,"production_bpd":25000,"quality":"Medium","note":"Total Austral 37.5%, YPF 27.5%, Wintershall Dea 35%; Argentina''s southernmost oil","pipelines":"Cañadón Alfa → Cabo Peñas Terminal","ports":"Cabo Peñas (Strait of Magellan); Río Grande","rail":"None (Tierra del Fuego isolated)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Hidra / Aries / Vega Pléyade', 'Total Austral + Wintershall Dea + YPF', 'Offshore Austral Basin — Argentine continental shelf', NULL, 'Energy', 'Crude Oil', -52.5000, -67.0000, 'Argentina', 'Austral Basin', 'Río Grande', 'oil_field', 'operational', 'Total Austral', 'joint_venture', 30.00, NULL, 10000, NULL, 300000, '{"start_year":2007,"production_bpd":10000,"quality":"Medium","note":"Total Austral 37.5%, Wintershall Dea 35%, YPF 27.5%; offshore Tierra del Fuego","pipelines":"Offshore platforms → subsea pipeline → Tierra del Fuego","ports":"Cabo Peñas; Río Grande","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- ARGENTINA — NORTHWEST
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Aguaragüe', 'Tecpetrol + Pluspetrol', 'Salta Province — Tarija Basin Argentina extension', NULL, 'Energy', 'Crude Oil', -22.2500, -63.7500, 'Argentina', 'Northwest Argentina', 'Tartagal', 'oil_field', 'operational', 'Tecpetrol', 'joint_venture', 35.00, 0.40, 8000, 100000000, 240000, '{"start_year":1972,"production_bpd":8000,"quality":"Light sweet","note":"Tecpetrol 50%, Pluspetrol 50%; mature conventional","pipelines":"Aguaragüe → Campo Durán refinery (Salta)","ports":"None (landlocked); crude to regional refineries","rail":"General Belgrano Railway"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Madrejones', 'Tecpetrol + YPF', 'Salta Province — Northwest Argentina', NULL, 'Energy', 'Crude Oil', -23.5833, -64.2500, 'Argentina', 'Northwest Argentina', 'Campo Durán', 'oil_field', 'operational', 'Tecpetrol', 'joint_venture', 36.00, NULL, 5000, NULL, 150000, '{"start_year":1969,"production_bpd":5000,"quality":"Light sweet","note":"Tecpetrol, YPF","pipelines":"Madrejones → Campo Durán refinery","ports":"None","rail":"General Belgrano Railway"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Caimancito', 'Pluspetrol + YPF', 'Jujuy Province — Northwest Argentina', NULL, 'Energy', 'Crude Oil', -23.7500, -64.5833, 'Argentina', 'Northwest Argentina', 'Campo Durán', 'oil_field', 'operational', 'Pluspetrol', 'joint_venture', 37.00, NULL, 3000, NULL, 90000, '{"start_year":1966,"production_bpd":3000,"quality":"Light sweet","note":"Pluspetrol, YPF; mature","pipelines":"Caimancito → Campo Durán","ports":"None","rail":"General Belgrano"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Palmar Largo', 'Tecpetrol', 'Salta Province — Northwest Argentina', NULL, 'Energy', 'Crude Oil', -22.0000, -63.5000, 'Argentina', 'Northwest Argentina', 'Campo Durán', 'oil_field', 'operational', 'Tecpetrol', 'private', 35.00, NULL, 4000, NULL, 120000, '{"start_year":1977,"production_bpd":4000,"quality":"Light sweet","note":"Tecpetrol 100%","pipelines":"→ Campo Durán gathering","ports":"None","rail":"General Belgrano"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BOLIVIA — SANTA CRUZ REGION
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Monteagudo Field', 'YPFB + Petrobras Bolivia', 'Chuquisaca / Santa Cruz border — southern Bolivia', NULL, 'Energy', 'Crude Oil', -19.8167, -63.9667, 'Bolivia', 'Santa Cruz', 'Villamontes', 'oil_field', 'operational', 'YPFB', 'state_owned', 32.00, 0.90, 12000, 100000000, 360000, '{"start_year":1924,"production_bpd":12000,"quality":"Medium light","note":"YPFB 100%; Bolivia''s largest oil field; nationalized 2006","pipelines":"Monteagudo → Villamontes → Argentina export","ports":"None (landlocked)","rail":"Bolivia Eastern Railway"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Tita Field', 'YPFB + Petrobras Bolivia', 'Santa Cruz Department — eastern Bolivia', NULL, 'Energy', 'Crude Oil', -18.3333, -63.5000, 'Bolivia', 'Santa Cruz', 'Santa Cruz', 'oil_field', 'operational', 'YPFB', 'state_owned', 33.00, NULL, 5000, NULL, 150000, '{"start_year":1960,"production_bpd":5000,"quality":"Medium light","note":"YPFB 100%; Petrobras service contractor","pipelines":"Tita → Santa Cruz → Sica Sica refinery","ports":"None","rail":"Bolivia Eastern Railway"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Vibora Field', 'YPFB + Repsol Bolivia', 'Santa Cruz Department', NULL, 'Energy', 'Crude Oil', -18.5000, -63.7500, 'Bolivia', 'Santa Cruz', 'Santa Cruz', 'oil_field', 'operational', 'YPFB', 'state_owned', 32.00, NULL, 4000, NULL, 120000, '{"start_year":1973,"production_bpd":4000,"quality":"Medium light","note":"YPFB 100%; Repsol service contractor","pipelines":"Vibora → Santa Cruz gathering","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Patujú Field', 'YPFB + Repsol Bolivia', 'Santa Cruz Department — gas + condensate', NULL, 'Energy', 'Condensate', -17.5000, -63.0000, 'Bolivia', 'Santa Cruz', 'Santa Cruz', 'oil_field', 'operational', 'YPFB', 'state_owned', 50.00, NULL, 3000, NULL, 90000, '{"start_year":2014,"production_bpd":3000,"quality":"Condensate light sweet","note":"YPFB 100%; gas-dominant with condensate","pipelines":"Patujú → Río Grande processing → Santa Cruz","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Margarita-Huacaya Field', 'YPFB + Repsol Bolivia + Shell', 'Santa Cruz Department — gas + condensate', NULL, 'Energy', 'Condensate', -21.0000, -63.5000, 'Bolivia', 'Santa Cruz', 'Santa Cruz', 'oil_field', 'operational', 'YPFB', 'state_owned', 55.00, NULL, 8000, 150000000, 240000, '{"start_year":1998,"production_bpd":8000,"quality":"Ultra-light condensate sweet","note":"YPFB 100%; Bolivia''s largest gas field; condensate byproduct","pipelines":"Margarita-Huacaya → Río Grande → GASBOL to Brazil","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

-- =====================
-- BOLIVIA — TARIJA BASIN
-- =====================

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Yacuiba / Caipipendi Field', 'YPFB + Pluspetrol Bolivia', 'Tarija Department — southern Bolivia, Argentina border', NULL, 'Energy', 'Crude Oil', -22.0333, -63.6833, 'Bolivia', 'Tarija Basin', 'Villamontes', 'oil_field', 'operational', 'YPFB', 'state_owned', 35.00, 0.50, 6000, NULL, 180000, '{"start_year":1968,"production_bpd":6000,"quality":"Light sweet","note":"YPFB 100%; Pluspetrol service contractor; exports to Argentina","pipelines":"Yacuiba → Villamontes → Argentina export pipeline","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Surubí Field', 'YPFB + Petrobras Bolivia', 'Tarija Department', NULL, 'Energy', 'Crude Oil', -21.5000, -63.2500, 'Bolivia', 'Tarija Basin', 'Tarija', 'oil_field', 'operational', 'YPFB', 'state_owned', 34.00, NULL, 3000, NULL, 90000, '{"start_year":1972,"production_bpd":3000,"quality":"Medium light","note":"YPFB 100%; gas + oil","pipelines":"Surubí → Tarija gathering → GASBOL system","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('San Alberto / San Antonio Fields', 'YPFB + Petrobras Bolivia + TotalEnergies Bolivia + Repsol', 'Tarija Department — Tarija Basin gas + condensate', NULL, 'Energy', 'Condensate', -21.7500, -63.7500, 'Bolivia', 'Tarija Basin', 'Río Grande', 'oil_field', 'operational', 'YPFB', 'state_owned', 58.00, NULL, 10000, 200000000, 300000, '{"start_year":1996,"production_bpd":10000,"quality":"Ultra-light condensate","note":"YPFB 100%; gas-dominant mega-fields; feed GASBOL to Brazil","pipelines":"San Alberto/San Antonio → Río Grande → GASBOL (3,150km)","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Itaú Field', 'YPFB + Repsol Bolivia', 'Tarija Department', NULL, 'Energy', 'Condensate', -21.2500, -63.5000, 'Bolivia', 'Tarija Basin', 'Tarija', 'oil_field', 'operational', 'YPFB', 'state_owned', 52.00, NULL, 4000, NULL, 120000, '{"start_year":2004,"production_bpd":4000,"quality":"Condensate","note":"YPFB 100%; gas + condensate","pipelines":"Itaú → GASBOL system","ports":"None","rail":"None"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();

INSERT INTO public.commodity_locations (title, owner, address, contact, commodity_type, commodity_name, latitude, longitude, country, region, city, location_type, operational_status, operator, ownership_type, api_gravity, sulfur_content, current_production, reserves_estimate, supply_volume, additional_info) VALUES
('Los Penocos / Río Grande Area', 'YPFB + Chaco', 'Santa Cruz Department — central Bolivia', NULL, 'Energy', 'Crude Oil', -18.5000, -63.0000, 'Bolivia', 'Santa Cruz', 'Santa Cruz', 'oil_field', 'operational', 'YPFB', 'state_owned', 30.00, NULL, 2000, NULL, 60000, '{"start_year":1965,"production_bpd":2000,"quality":"Medium","note":"YPFB 100%; mature conventional","pipelines":"Río Grande → Santa Cruz → Sica Sica refinery (La Paz)","ports":"None","rail":"Bolivia railway (limited)"}'::jsonb)
ON CONFLICT (title, country, commodity_name) DO UPDATE SET owner=EXCLUDED.owner, address=EXCLUDED.address, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, region=EXCLUDED.region, city=EXCLUDED.city, location_type=EXCLUDED.location_type, operational_status=EXCLUDED.operational_status, operator=EXCLUDED.operator, ownership_type=EXCLUDED.ownership_type, api_gravity=EXCLUDED.api_gravity, sulfur_content=EXCLUDED.sulfur_content, current_production=EXCLUDED.current_production, reserves_estimate=EXCLUDED.reserves_estimate, supply_volume=EXCLUDED.supply_volume, additional_info=EXCLUDED.additional_info, updated_at=NOW();
