-- ============================================
-- NORWAY OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:24:52.049878
-- Total sites: 43
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN RETURN NULL; END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN RETURN date_text::DATE; END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN RETURN (date_text || '-01')::DATE; END IF;
  IF date_text ~ '^[0-9]{4}$' THEN RETURN (date_text || '-01-01')::DATE; END IF;
  RETURN NULL;
EXCEPTION WHEN OTHERS THEN RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('(operator', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Aker BP', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('ConocoPhillips', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('DNO', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Equinor', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Harbour Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('OKEA', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Repsol', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Shell', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('TotalEnergies', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Vår Energi', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING NORWAY DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Norway';

-- ============================================
-- STEP 5: INSERT NORWAY SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'JOHAN SVERDRUP',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.0,
  2.5,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Equinor',
  'JV (incl. Norwegian state interests via SDFI/Petoro)',
  'Operator: Equinor; SDFI (Petoro) participates (17.36% as of 31 Dec 2024, per Petoro SDFI facts); other partners not fully enumerated here.',
  9600000,
  116800000,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2019-01-01'),
  NULL,
  'light/medium (exact API not found in sources used)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Johan Sverdrup export pipeline system (field-specific export via NCS network; exact line names not fully enumerated here)'],
  ARRAY['Sture (associated crude export terminal for parts of the area; exact field routing not fully enumerated here)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'TROLL',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  60.6,
  3.7,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (incl. Norwegian state interests via SDFI/Petoro)',
  'Operator: Equinor; licensees include Equinor, Petoro, Norske Shell, TotalEnergies, ConocoPhillips (as stated in coverage of Equinor statement).',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1996-01-01'),
  NULL,
  'gas/condensate with oil leg (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Troll Oil Pipeline I + II'],
  ARRAY['Kollsnes (gas processing/export hub; port/terminal complex)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'OSEBERG',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  60.5,
  2.8,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (incl. Norwegian state interests via SDFI/Petoro)',
  'Owner kind shown as BUSINESS ARRANGEMENT AREA (Oseberg Area Unit) in FactPages Overview; operator Equinor.',
  3270000,
  39785000,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1988-01-01'),
  NULL,
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Oseberg Transport System (OTS)'],
  ARRAY['Sture terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'GULLFAKS',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  61.2,
  2.1,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (incl. Norwegian state interests via SDFI/Petoro)',
  'Operator: Equinor; SDFI (Petoro) participates (30% in Gullfaks and Gullfaks Sør per Petoro SDFI facts).',
  2130000,
  25915000,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1986-01-01'),
  NULL,
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Exports via Tampen/North Sea pipeline network; exact line names not fully enumerated here)'],
  ARRAY['(North Sea Norwegian export terminals; exact terminal for Gullfaks crude not fully enumerated here)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'STATFJORD',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  61.25,
  1.85,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (cross-border field; Norwegian share noted)',
  'Statfjord is on the border between Norwegian and UK sectors; Norwegian share is 85.47% per FactPages Description. Operator: Equinor (historically Statoil).',
  660000,
  8030000,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1979-01-01'),
  NULL,
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Tampen export network; exact pipeline names not fully enumerated here)'],
  ARRAY['(North Sea export terminals; not fully enumerated here)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'VESLEFRIKK',
  '(operator',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  60.8,
  2.9,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'closed',
  '(operator',
  'JV',
  'FactPages Description notes shutdown in 2022; decommissioning to be completed by end of 2027.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1990-01-01'),
  parse_flexible_date('2022-01-01'),
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Oseberg Transport System (OTS)', 'Statpipe'],
  ARRAY['Sture terminal', 'Kårstø terminal'],
  ARRAY[]::text[],
  '(operator',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ALBUSKJELL',
  'ConocoPhillips',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  56.5,
  3.0,
  'Energy',
  'Natural Gas',
  'oil_field',
  'closed',
  'ConocoPhillips',
  'JV',
  'FactPages Description: shut down in 1998; platforms removed 2011/2013; evaluation for redevelopment in combination with other decommissioned fields in the area.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1979-01-01'),
  parse_flexible_date('1998-01-01'),
  'gas/condensate (chalk reservoir; API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Pipeline to Ekofisk Complex (wellstream transport, per FactPages Description)'],
  ARRAY['(Ekofisk area export infrastructure; specific terminals not enumerated here)'],
  ARRAY[]::text[],
  'ConocoPhillips',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ATLA',
  'TotalEnergies',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.3,
  2.0,
  'Energy',
  'Natural Gas',
  'oil_field',
  'closed',
  'TotalEnergies',
  'JV',
  'FactPages Description: Atla shut down in 2023; tied back via Skirne/Byggve subsea facility to Heimdal for processing/export.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2012-01-01'),
  parse_flexible_date('2023-01-01'),
  'gas/condensate (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Skirne/Byggve subsea tie-back (to Heimdal)'],
  ARRAY['(Heimdal-linked export system; terminals not enumerated here)'],
  ARRAY[]::text[],
  'TotalEnergies',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ALVHEIM',
  'Aker BP',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.6,
  1.9,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Aker BP',
  'JV',
  'FactPages Description: oil stabilized/stored on Alvheim FPSO; export by tankers; rich gas exported via pipeline to UK SAGE system.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2008-01-01'),
  NULL,
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Pipeline from Alvheim to SAGE (UKCS connection)'],
  ARRAY['(FPSO offloading to shuttle tankers; no fixed port)'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'BALDER',
  'Vår Energi',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.3,
  2.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Vår Energi',
  'JV',
  'FactPages Description: Balder and Ringhorne in tail production; extended field life work and relocation of Jotun FPSO planned/used to leverage area infrastructure.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1999-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Area export system; not enumerated here)'],
  ARRAY['(FPSO/tanker offloading; no fixed port)'],
  ARRAY[]::text[],
  'Vår Energi',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'BRAGE',
  '(operator',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  60.5,
  3.0,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  '(operator',
  'JV',
  'Status shown as Producing in FactPages Status table.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('1993-01-01'),
  NULL,
  'oil/gas (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(North Sea export network; not enumerated here)'],
  ARRAY['(Norway export terminals; not enumerated here)'],
  ARRAY[]::text[],
  '(operator',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'BREIDABLIKK',
  'Equinor',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.2,
  2.6,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Equinor',
  'JV (incl. Norwegian state interests via SDFI/Petoro)',
  'SDFI (Petoro) participating interest 22.2% as of 31 Dec 2024 per Petoro SDFI facts; operator shown as Equinor in FactPages Status/Overview tables.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2023-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Tie-back/export not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'BLANE',
  'Repsol',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  57.5,
  1.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Repsol',
  'JV (Business Arrangement Area: BLANE UNIT)',
  'Owner kind shown as BUSINESS ARRANGEMENT AREA; operator Repsol Norge AS per FactPages Overview.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2007-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Export infrastructure not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Repsol',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'TAMBAR',
  'Aker BP',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  57.6,
  2.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Aker BP',
  'JV',
  'Operator Aker BP per FactPages Overview.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  NULL,
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Export infrastructure not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'TAMBAR ØST',
  'Aker BP',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  57.6,
  2.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Aker BP',
  'JV (Business Arrangement Area: TAMBAR ØST UNIT)',
  'Owner kind shown as BUSINESS ARRANGEMENT AREA; operator Aker BP per FactPages Overview.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2007-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Export infrastructure not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'NOVA',
  'Harbour Energy',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  59.5,
  2.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Harbour Energy',
  'JV',
  'Operator Harbour Energy Norge AS per FactPages Overview.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2020-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Export infrastructure not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Harbour Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ODA',
  'Aker BP',
  'North Sea (Norwegian sector)',
  'Norway',
  'North Sea (Norwegian sector)',
  57.4,
  3.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Aker BP',
  'JV',
  'Operator Aker BP per FactPages Overview.',
  0,
  0,
  'barrels_oil_equivalent',
  0,
  'boe',
  parse_flexible_date('2010-01-01'),
  NULL,
  'oil (API not captured here)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['(Export infrastructure not enumerated here)'],
  ARRAY['(Export terminals not enumerated here)'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ÅSGARD',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.1,
  6.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (Production licences / business arrangement area; includes state participation via Petoro)',
  'Equinor Energy AS (operator) and partners include Petoro AS, Vår Energi ASA, TotalEnergies EP Norge AS; latest public split seen in industry reporting: Equinor 35.01%, Petoro 34.53%, Vår Energi 22.65%, TotalEnergies 7.81%.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('1999-05-18'),
  NULL,
  'oil/gas/condensate (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Åsgard Transport System (ÅTS) to Kårstø', 'Europipe II (from Kårstø to continental Europe)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'HEIDRUN',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.3,
  7.3,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence; includes state participation via Petoro in many NCS assets)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('1995-10-17'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Haltenpipe', 'Åsgard Transport System (ÅTS)'],
  ARRAY['Tjeldbergodden terminal', 'Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'DRAUGEN',
  'OKEA',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.35,
  7.8,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'OKEA',
  'JV (production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('1993-10-18'),
  NULL,
  'oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Offloading/loading buoy lines (two pipelines from platform to loading buoy)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'OKEA',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'NJORD',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.6,
  7.2,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (business unit/production licence)',
  'Partnership (per operator public description): Harbour Energy Norge AS (50%), Equinor (operator, 27.5%), Vår Energi ASA (22.5%).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('1997-09-29'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Gas pipeline to Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal (via ÅTS)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'NORNE',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.0,
  8.0,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (business arrangement area)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0.67,
  'million Sm3 oil (Norwegian share; from Norwegian O',
  parse_flexible_date('1997-11-05'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Gas pipeline to Åsgard and Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal (via ÅTS)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'KRISTIN',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.0,
  6.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2005-11-02'),
  NULL,
  'gas/condensate (with some light oil)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Åsgard Transport System (ÅTS) to Kårstø'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'TYRIHANS',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.0,
  6.8,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (business unit/production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2009-07-08'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied-back to Kristin; exports via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'MARIA',
  'Harbour Energy',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.7,
  6.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Harbour Energy',
  'JV (production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2017-12-16'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied-back to Kristin; exports via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Harbour Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ORMEN LANGE',
  'Shell',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  63.3,
  5.3,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Shell',
  'JV (business arrangement area; includes state participation via Petoro)',
  'Partners include Petoro AS and others; detailed current split not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2007-09-12'),
  NULL,
  'gas',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Langeled pipeline to the UK (from Nyhamna)', 'Export pipeline to Nyhamna processing plant'],
  ARRAY['Nyhamna terminal'],
  ARRAY[]::text[],
  'Shell',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'AASTA HANSTEEN',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  67.1,
  7.1,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  19.8,
  'billion Sm3 gas (remaining, Norwegian share; from ',
  parse_flexible_date('2018-12-15'),
  NULL,
  'gas (with some condensate/light oil offloaded)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Polarled pipeline to Nyhamna'],
  ARRAY['Nyhamna terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'SKARV',
  'Aker BP',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.7,
  7.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Aker BP',
  'JV (business unit/production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2012-12-31'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Gas export via Åsgard Transport System (ÅTS) (per Skarv-area export setup)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'MIKKEL',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.9,
  6.4,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (business unit/production licence)',
  'Owners/percentages not extracted in this run (see Norwegian Offshore Directorate FactPages owners table for current splits).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2003-07-31'),
  NULL,
  'gas/condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Åsgard Subsea Compressor system to Åsgard B', 'Åsgard Transport System (ÅTS) to Kårstø', 'Europipe II (from Kårstø to continental Europe)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'URD',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.0,
  7.8,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2005-11-07'),
  NULL,
  'oil (with associated gas)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied-back to Norne FPSO; gas export via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'SKULD',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.1,
  7.9,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2013-03-18'),
  NULL,
  'oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tied-back to Norne FPSO; gas export via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ALVE',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.0,
  8.2,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2009-03-18'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  51,
  'USD',
  parse_flexible_date('2024-05-08'),
  NULL,
  ARRAY['Tied-back to Norne FPSO'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'MARULK',
  'DNO',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.8,
  7.6,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'DNO',
  'JV (production licence)',
  'Ownership changed via DNO acquisition from Vår Energi (portfolio included Marulk). Current percentages not extracted here.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2012-04-01'),
  NULL,
  'gas',
  NULL,
  NULL,
  NULL,
  51,
  'USD',
  parse_flexible_date('2024-05-08'),
  NULL,
  ARRAY['Tied-back to Norne FPSO; gas export via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'DNO',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'HYME',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.9,
  7.3,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2013-03-01'),
  NULL,
  'oil/gas (mixed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Pipeline to Njord A (tie-back)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'BAUGE',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.8,
  7.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Equinor',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2023-04-07'),
  NULL,
  'oil',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back to Njord A'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'FENJA',
  'Vår Energi',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  64.5,
  7.0,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Vår Energi',
  'JV (production licence)',
  'Partners listed by Norwegian Petroleum; operator Vår Energi ASA. A 2023 partner statement referenced Sval Energi, Neptune Energy, Vår Energi, and DNO as licence partners (percentages stated in that statement).',
  0,
  0,
  'boe (reported in boe/day in sources; bbl not extra',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2023-04-27'),
  NULL,
  'oil/gas (mixed; waxy crude mentioned in partner statement)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back to Njord A', 'Åsgard Transport System (ÅTS) (gas export)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Vår Energi',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'VERDANDE',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.0,
  8.0,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (business unit/production licence)',
  'Equinor is operator. Additional partners exist (Petoro and others reported in media); current percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  36,
  'million bbl oil (reported in Norwegian business pr',
  parse_flexible_date('2025-11-30'),
  NULL,
  'oil (with some gas export via ÅTS)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  parse_flexible_date('2023-01-01'),
  NULL,
  ARRAY['Tie-back to Norne FPSO; gas export via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ANDVARE',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  66.1,
  8.1,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (tie-in development near Norne)',
  'Per company release: Equinor Energy (53%), DNO Norge (32%), ORLEN Upstream Norway (15%).',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (not available; company release emphasizes gas',
  parse_flexible_date('2025-09-29'),
  NULL,
  'gas',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back to Norne FPSO; gas onward to Kårstø via Åsgard Transport'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'HALTEN ØST',
  'Equinor',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.0,
  6.5,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (PDO-approved field tied back to Åsgard)',
  'Consists of multiple discoveries (Natalia, Sigrid, Nona, Flyndretind, Gamma, Harepus) developed as tie-backs to Åsgard; ownership splits not extracted here.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2025-03-01'),
  NULL,
  'gas/condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back to Åsgard infrastructure; exports via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'ÆRFUGL NORD',
  'Aker BP',
  'Norwegian Sea',
  'Norway',
  'Norwegian Sea',
  65.9,
  7.5,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Aker BP',
  'JV (production licence)',
  'Owners/percentages not extracted in this run.',
  0,
  0,
  'bbl (not available from public sources in this ext',
  0,
  'bbl (remaining reserves not converted in this extr',
  parse_flexible_date('2021-11-05'),
  NULL,
  'gas/condensate',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY['Tie-back to Skarv FPSO; exports via Åsgard Transport System (ÅTS)'],
  ARRAY['Kårstø terminal'],
  ARRAY[]::text[],
  'Aker BP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Snøhvit',
  'Equinor',
  'Troms og Finnmark',
  'Norway',
  'Troms og Finnmark',
  71.5,
  21.0,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'Equinor',
  'JV (licence partners + state participation via Petoro)',
  'Partners include Equinor (operator), Petoro, TotalEnergies, Vår Energi and Harbour Energy (exact field equity split not retrieved in sources due to FactPages access timeouts).',
  0,
  0,
  'barrels (liquids) - not available from public sour',
  0,
  'barrels - not available from public sources used',
  parse_flexible_date('2007-08-20'),
  NULL,
  'gas/condensate (condensate is light)',
  NULL,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  NULL,
  ARRAY['Snøhvit pipeline (subsea export line ~160 km to Melkøya, Hammerfest)'],
  ARRAY['Melkøya / Hammerfest LNG terminal (LNG/LPG/condensate shipping)'],
  ARRAY[]::text[],
  'Equinor',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Goliat',
  'Vår Energi',
  'Troms og Finnmark',
  'Norway',
  'Troms og Finnmark',
  71.3,
  22.3,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Vår Energi',
  'JV (licence partners)',
  'Vår Energi ASA 65%, Equinor Energy AS 35% (PL229).',
  0,
  0,
  'barrels - not available from public sources used',
  0,
  'barrels - not available from public sources used',
  parse_flexible_date('2016-03-11'),
  NULL,
  'light crude',
  42.0,
  NULL,
  NULL,
  NULL,
  'NOK',
  NULL,
  16.0,
  ARRAY['Planned: tie-in from Goliat area to Snøhvit pipeline for gas export (concept under evaluation)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Vår Energi',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Johan Castberg',
  'Equinor',
  'Troms og Finnmark',
  'Norway',
  'Troms og Finnmark',
  72.5,
  20.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Equinor',
  'JV (licence partners + state participation via Petoro)',
  'Equinor Energy AS (operator) 46.3%, Vår Energi ASA 30.0%, Petoro AS 23.7%.',
  0,
  0,
  'barrels - peak capacity reported in bbl/d; monthly',
  550000000,
  'barrels (recoverable oil; midpoint of 450-650 mill',
  parse_flexible_date('2025-03-30'),
  NULL,
  'light sweet crude',
  34.7,
  0.16,
  NULL,
  NULL,
  'NOK',
  parse_flexible_date('2025-03-18'),
  40.0,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Equinor',
  NULL
);
