-- ============================================
-- TUNISIA OIL & GAS FIELDS SETUP
-- Generated: 2026-02-04T16:17:29.661318
-- Total sites: 29
-- ============================================

-- ============================================
-- STEP 1: SCHEMA MODIFICATIONS
-- ============================================

-- Add new columns if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='operator') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN operator TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ownership_details') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ownership_details TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_monthly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_monthly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_yearly') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_yearly DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='production_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN production_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='start_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN start_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='closing_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN closing_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='estimated_reserves') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN estimated_reserves DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='reserves_unit') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN reserves_unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='api_gravity') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN api_gravity DECIMAL(5,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_type') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_type TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='quality_sulfur_content') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN quality_sulfur_content DECIMAL(5,3);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='grade') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN grade TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_value') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_value DECIMAL(20,2);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_currency') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_currency TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='last_transaction_date') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN last_transaction_date DATE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='contract_duration_years') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN contract_duration_years INTEGER;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='pipelines') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN pipelines TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='ports') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN ports TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='rail_connections') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN rail_connections TEXT[];
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='commodity_locations' AND column_name='company') THEN
    ALTER TABLE public.commodity_locations ADD COLUMN company TEXT;
  END IF;
END $$;

-- ============================================
-- STEP 2: DATE PARSING FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION parse_flexible_date(date_text TEXT)
RETURNS DATE AS $$
BEGIN
  IF date_text IS NULL OR date_text = '' THEN RETURN NULL; END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN RETURN date_text::DATE; END IF;
  IF date_text ~ '^[0-9]{4}-[0-9]{2}$' THEN RETURN (date_text || '-01')::DATE; END IF;
  IF date_text ~ '^[0-9]{4}$' THEN RETURN (date_text || '-01-01')::DATE; END IF;
  RETURN NULL;
EXCEPTION WHEN OTHERS THEN RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- STEP 3: INSERT COMPANIES
-- ============================================

INSERT INTO public.companies (name, type, headquarters_country, commodities_traded)
VALUES
  ('ETAP', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Eni', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('OMV', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('PA', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Panoro Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Petrofac', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Pioneer Natural Resources', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('SEREPT', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Serinus Energy', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('Shell', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas']),
  ('TPS', 'producer', 'Unknown', ARRAY['Crude Oil', 'Natural Gas'])
ON CONFLICT (name) DO UPDATE SET commodities_traded = EXCLUDED.commodities_traded;

-- ============================================
-- STEP 4: DELETE EXISTING TUNISIA DATA
-- ============================================

DELETE FROM public.commodity_locations WHERE country = 'Tunisia';

-- ============================================
-- STEP 5: INSERT TUNISIA SITES
-- ============================================

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Ashtart Field',
  'SEREPT',
  'Offshore (Gulf of Gabes, off Sfax)',
  'Tunisia',
  'Offshore (Gulf of Gabes, off Sfax)',
  34.3667,
  11.8833,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'SEREPT',
  'JV',
  'SEREPT is a JV between ETAP and OMV (reported 50/50).',
  0,
  0,
  'bbl (unknown/varies)',
  0,
  'bbl (not reliably available from public sources fo',
  parse_flexible_date('1974-01-01'),
  NULL,
  'crude oil (type not publicly specified in sources used)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['La Skhirra oil terminal (export terminal commonly used for crude in the Sfax/Gabes area)'],
  ARRAY[]::text[],
  'SEREPT',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Miskar Gas & Condensate Field',
  'ETAP',
  'Offshore (Gulf of Gabes, Amilcar permit)',
  'Tunisia',
  'Offshore (Gulf of Gabes, Amilcar permit)',
  34.2,
  11.5,
  'Energy',
  'Natural Gas',
  'offshore_field',
  'active',
  'ETAP',
  'PSC / state participation (historical)',
  'Developed/operated historically by BG Group (later Shell) under arrangement with ETAP; current operatorship reported transitioned to ETAP/APO after Shell withdrawal (exact current WI split not consistently published in open sources).',
  0,
  0,
  'boe (gas/condensate; current public production not',
  1500000000,
  'scf (historical proven reserves reported ~1.5 Tcf;',
  parse_flexible_date('1996-01-01'),
  NULL,
  'sour natural gas with condensate',
  NULL,
  NULL,
  NULL,
  70000000,
  'USD',
  parse_flexible_date('2002-08-20'),
  20,
  ARRAY['Subsea export pipeline from Miskar to Hannibal gas treatment plant (near Sfax)'],
  ARRAY['La Skhirra (used for liquids export in the region; condensate export reported via this terminal in industry descriptions)'],
  ARRAY[]::text[],
  'ETAP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Hasdrubal Gas & Condensate Field',
  'Shell',
  'Offshore (Gulf of Gabes, Amilcar permit)',
  'Tunisia',
  'Offshore (Gulf of Gabes, Amilcar permit)',
  34.25,
  11.55,
  'Energy',
  'Natural Gas',
  'offshore_field',
  'active',
  'Shell',
  'JV',
  'BG Group 50%, ETAP 50% (as reported in project/industry sources).',
  0,
  0,
  'boe (gas/condensate; not consistently published in',
  25000000,
  'bbl (condensate; recoverable condensate reported i',
  parse_flexible_date('2009-03-01'),
  NULL,
  'gas & condensate',
  NULL,
  NULL,
  NULL,
  150000000,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['La Skhirra (regional liquids export terminal used for crude/condensate exports)'],
  ARRAY[]::text[],
  'Shell',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Chergui Gas & Condensate Field',
  'Petrofac',
  'Kerkennah Islands (Gulf of Gabes, near Sfax)',
  'Tunisia',
  'Kerkennah Islands (Gulf of Gabes, near Sfax)',
  34.7,
  11.1,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'Petrofac',
  'JV',
  'Petrofac 45% and operator; ETAP 55% (as stated by Petrofac).',
  0,
  0,
  'scf (gas; plateau initially ~20 MMscf/d)',
  0,
  'unknown',
  parse_flexible_date('2008-08-08'),
  NULL,
  'gas & condensate',
  NULL,
  NULL,
  NULL,
  100000000,
  'USD',
  parse_flexible_date('2008-08-11'),
  NULL,
  ARRAY['57 km pipeline to shore tying into STEG facilities at Ain Turkia near Sfax'],
  ARRAY['Sfax (regional port)', 'La Skhirra (regional liquids export terminal used for crude/condensate exports)'],
  ARRAY[]::text[],
  'Petrofac',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Cercina Field (TPS Assets)',
  'TPS',
  'Shallow-water offshore/onshore interface near Sfax (Kerkennah West/Cercina area)',
  'Tunisia',
  'Shallow-water offshore/onshore interface near Sfax (Kerkennah West/Cercina area)',
  34.6,
  11.0,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'TPS',
  'JV (state + private)',
  'ETAP and Panoro (through SPC) jointly participate; Panoro reports 49% interest in the TPS Assets and 50% interest in the TPS operating company structure (remaining held by ETAP).',
  0,
  0,
  'bbl (field-level not disclosed; TPS Assets gross ~',
  13000000,
  'bbl (gross 2P reserves reported for TPS licences a',
  parse_flexible_date('1980-01-01'),
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY['Intra-field pipelines to processing/storage; crude transported to La Skhirra export terminal (~70 km south)'],
  ARRAY['La Skhirra oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Cercina Sud Field (TPS Assets)',
  'TPS',
  'Sfax region (TPS Assets area)',
  'Tunisia',
  'Sfax region (TPS Assets area)',
  34.6,
  11.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (state + private)',
  'ETAP with Panoro interest reported at 49% in TPS Assets (asset-group level).',
  0,
  0,
  'bbl (field-level not disclosed; TPS Assets gross ~',
  13000000,
  'bbl (gross 2P reserves reported for TPS licences a',
  parse_flexible_date('1980-01-01'),
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY['Intra-field pipelines to processing/storage; crude transported to La Skhirra export terminal (~70 km south)'],
  ARRAY['La Skhirra oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Rhemoura Field (TPS Assets)',
  'TPS',
  'Sfax region (TPS Assets area)',
  'Tunisia',
  'Sfax region (TPS Assets area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (state + private)',
  'ETAP with Panoro interest reported at 49% in TPS Assets (asset-group level).',
  0,
  0,
  'bbl (field-level not disclosed; TPS Assets gross ~',
  13000000,
  'bbl (gross 2P reserves reported for TPS licences a',
  parse_flexible_date('1990-01-01'),
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY['Intra-field pipelines to processing/storage; crude transported to La Skhirra export terminal (~70 km south)'],
  ARRAY['La Skhirra oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Ain/Gremda Field (TPS Assets)',
  'TPS',
  'Sfax region (TPS Assets area)',
  'Tunisia',
  'Sfax region (TPS Assets area)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (state + private)',
  'ETAP with Panoro interest reported at 49% in TPS Assets (asset-group level).',
  0,
  0,
  'bbl (field-level not disclosed; TPS Assets gross ~',
  13000000,
  'bbl (gross 2P reserves reported for TPS licences a',
  parse_flexible_date('1990-01-01'),
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY['Intra-field pipelines to processing/storage; crude transported to La Skhirra export terminal (~70 km south)'],
  ARRAY['La Skhirra oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Hajeb / Guebiba Field (TPS Assets)',
  'TPS',
  'Sfax region (TPS Assets area; El Hajeb/Guebiba concession)',
  'Tunisia',
  'Sfax region (TPS Assets area; El Hajeb/Guebiba concession)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (state + private)',
  'ETAP and Panoro (via SPC) participate; Panoro reports 49% interest in TPS Assets at asset-group level.',
  0,
  0,
  'bbl (field-level not disclosed; TPS Assets gross ~',
  13000000,
  'bbl (gross 2P reserves reported for TPS licences a',
  parse_flexible_date('1990-01-01'),
  NULL,
  'crude oil',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY['Intra-field pipelines to processing/storage; crude transported to La Skhirra export terminal (~70 km south)'],
  ARRAY['La Skhirra oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Didon Field (Zarat Permit)',
  'PA',
  'Offshore (Gulf of Gabes, Zarat permit)',
  'Tunisia',
  'Offshore (Gulf of Gabes, Zarat permit)',
  34.3,
  11.7,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'closed',
  'PA',
  'private (reported)',
  'Reported as 100% owned and operated by PA Resources in project profile sources.',
  0,
  0,
  'bbl',
  100000000,
  'bbl (revised reserves estimate reported historical',
  parse_flexible_date('1998-05-01'),
  parse_flexible_date('2014-01-01'),
  'light crude',
  35.4,
  0.85,
  NULL,
  NULL,
  'USD',
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['FSO export (Didon FSO reported in project profile sources)'],
  ARRAY[]::text[],
  'PA',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Salloum Discovery (Sfax Offshore Exploration Permit - SOEP)',
  'Panoro Energy',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  'Tunisia',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  34.4,
  11.3,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Panoro Energy',
  'JV (state + private)',
  'SOEP operated by Panoro; Panoro reports 87.5% interest in SOEP (via SPC) with remaining interest held by ETAP (exact split beyond Panoro share not fully detailed in open sources).',
  0,
  0,
  'bbl (not onstream; discovery)',
  20000000,
  'bbl (gross recoverable estimate for three SOEP dis',
  NULL,
  NULL,
  'crude oil (discovery; not specified)',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY[]::text[],
  ARRAY['La Skhirra oil terminal (likely export outlet if developed; nearby existing infrastructure referenced in industry sources)'],
  ARRAY[]::text[],
  'Panoro Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Ras El Besh Discovery (Sfax Offshore Exploration Permit - SOEP)',
  'Panoro Energy',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  'Tunisia',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Panoro Energy',
  'JV (state + private)',
  'SOEP operated by Panoro; Panoro reports 87.5% interest in SOEP (via SPC) with remaining interest held by ETAP (exact split beyond Panoro share not fully detailed in open sources).',
  0,
  0,
  'bbl (not onstream; discovery)',
  20000000,
  'bbl (gross recoverable estimate for three SOEP dis',
  NULL,
  NULL,
  'crude oil (discovery; not specified)',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY[]::text[],
  ARRAY['La Skhirra oil terminal (likely export outlet if developed; nearby existing infrastructure referenced in industry sources)'],
  ARRAY[]::text[],
  'Panoro Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Jawahra (Jawhara) Discovery (Sfax Offshore Exploration Permit - SOEP)',
  'Panoro Energy',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  'Tunisia',
  'Offshore (Northern Gulf of Gabes / Pelagian Basin, SOEP)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'offshore_field',
  'active',
  'Panoro Energy',
  'JV (state + private)',
  'SOEP operated by Panoro; Panoro reports 87.5% interest in SOEP (via SPC) with remaining interest held by ETAP (exact split beyond Panoro share not fully detailed in open sources).',
  0,
  0,
  'bbl (not onstream; discovery)',
  20000000,
  'bbl (gross recoverable estimate for three SOEP dis',
  NULL,
  NULL,
  'crude oil (discovery; not specified)',
  NULL,
  NULL,
  NULL,
  18200000,
  'USD',
  parse_flexible_date('2023-04-18'),
  NULL,
  ARRAY[]::text[],
  ARRAY['La Skhirra oil terminal (likely export outlet if developed; nearby existing infrastructure referenced in industry sources)'],
  ARRAY[]::text[],
  'Panoro Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Borma Oil Field (Permis du Sud)',
  'Eni',
  'Tataouine Governorate (southern Tunisia, near Algeria border)',
  'Tunisia',
  'Tataouine Governorate (southern Tunisia, near Algeria border)',
  31.7,
  9.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Eni',
  'JV (state + IOC)',
  'ETAP 50%, Eni/Agip 50% (operator)',
  600000,
  7300000,
  'barrels (crude oil)',
  200000000,
  'barrels (estimate; remaining not publicly disclose',
  parse_flexible_date('1966-01-01'),
  NULL,
  'light crude (Zarzaitine-type)',
  42.5,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('1989-12-31'),
  NULL,
  ARRAY['Local gathering system to southern Tunisia export system (field-specific pipeline names not consistently disclosed publicly)'],
  ARRAY['La Skhira oil terminal (export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Adam Oil Field',
  'Eni',
  'Tataouine Governorate (Borj El Khadra area; southern Tunisia / Ghadames Basin)',
  'Tunisia',
  'Tataouine Governorate (Borj El Khadra area; southern Tunisia / Ghadames Basin)',
  31.6,
  9.3,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Eni',
  'JV / concession partnership',
  'ETAP + Eni + OMV + Anglo Tunisian Oil & Gas + Sirius Petroleum (percentages not consistently disclosed in open sources)',
  42000,
  510000,
  'barrels (crude oil + condensate, approximate; fiel',
  5000000,
  'barrels (recoverable remaining; estimate)',
  parse_flexible_date('2007-01-01'),
  NULL,
  'light oil / condensate (not consistently disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2011-02-18'),
  NULL,
  ARRAY['Gathering to southern Tunisia export system (specific line names not consistently disclosed publicly)'],
  ARRAY['La Skhira oil terminal (export)'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Cherouq Production Concession (incl. El-Badr area)',
  'OMV',
  'Tataouine Governorate (southern Tunisia / Ghadames Basin)',
  'Tunisia',
  'Tataouine Governorate (southern Tunisia / Ghadames Basin)',
  31.5,
  9.4,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'OMV',
  'Concession JV',
  'OMV operated (notably 50% operator stake referenced for El-Badr-5 well); other partner details not fully disclosed in open press material',
  22500,
  273750,
  'boe (reported well rate basis; site-level estimate',
  10000000,
  'boe (estimate)',
  parse_flexible_date('2011-01-01'),
  NULL,
  'oil/condensate (not consistently disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2011-02-18'),
  NULL,
  ARRAY['Cherouq facilities tie-in / gathering network (names not consistently disclosed publicly)'],
  ARRAY['La Skhira oil terminal (export)'],
  ARRAY[]::text[],
  'OMV',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Nawara Gas-Condensate Field (Nawara Production Concession)',
  'ETAP',
  'Tataouine Governorate (south Tunisia / Ghadames Basin)',
  'Tunisia',
  'Tataouine Governorate (south Tunisia / Ghadames Basin)',
  31.4,
  9.5,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'ETAP',
  'JV (state + IOC)',
  'ETAP 50%, OMV 50%',
  0,
  0,
  'barrels (condensate not separately disclosed; proj',
  0,
  'barrels (condensate; not publicly separated)',
  parse_flexible_date('2020-01-01'),
  NULL,
  'gas-condensate (condensate quality not consistently disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2010-01-01'),
  NULL,
  ARRAY['STGP gas pipeline (export to Tunisian gas market; Nawara-fed)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'ETAP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Warda Discovery Area (Jenein Sud / Nawara related discoveries)',
  'ETAP',
  'Tataouine Governorate (south Tunisia / Ghadames Basin)',
  'Tunisia',
  'Tataouine Governorate (south Tunisia / Ghadames Basin)',
  31.4,
  9.5,
  'Energy',
  'Natural Gas',
  'oil_field',
  'active',
  'ETAP',
  'JV (state + IOC)',
  'OMV and ETAP partnership in southern Tunisia permits; percentages vary by permit/concession',
  0,
  0,
  'barrels (not disclosed; gas/condensate area)',
  0,
  'barrels (not applicable / not disclosed)',
  parse_flexible_date('2010-01-01'),
  NULL,
  'gas/condensate (not disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2003-01-01'),
  NULL,
  ARRAY['Potential tie-in to STGP pipeline system (project-dependent; not publicly confirmed at field granularity)'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  'ETAP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Sabah Oil & Gas Field (Acacus reservoir)',
  'ETAP',
  'Tataouine Governorate (Ghadames Basin, southern Tunisia)',
  'Tunisia',
  'Tataouine Governorate (Ghadames Basin, southern Tunisia)',
  31.3,
  9.6,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'ETAP',
  'JV (state + IOC)',
  'Eni + ETAP (percentages not publicly detailed in the cited secondary source)',
  0,
  0,
  'barrels (not publicly disclosed)',
  0,
  'barrels (oil equivalent resources mentioned public',
  parse_flexible_date('2025-01-01'),
  NULL,
  'oil & gas (quality not disclosed)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2025-03-31'),
  NULL,
  ARRAY['Expected tie-in to southern Tunisia gathering / gas infrastructure (not publicly specified)'],
  ARRAY['La Skhira (likely export route for liquids; not publicly confirmed for this field)'],
  ARRAY[]::text[],
  'ETAP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Borma Oil Field (SITEP / Permis du Sud)',
  'Eni',
  'Tataouine Governorate (southwest)',
  'Tunisia',
  'Tataouine Governorate (southwest)',
  31.7,
  9.2,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Eni',
  'JV (ETAP + Eni/Agip)',
  'ETAP 50%, Eni/Agip 50% (operator via SITEP)',
  582000,
  7081000,
  'barrels (crude oil)',
  148000000,
  'tonnes oil in place (historical estimate; not rema',
  parse_flexible_date('1966-01-01'),
  NULL,
  'light sweet crude (Zarzaitine blend)',
  42.5,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2025-03-31'),
  NULL,
  ARRAY['El Borma-area gathering lines to central facilities (field system)', 'Export via TRAPSA pipeline system to La Skhira terminal (country export system)'],
  ARRAY['La Skhira (La Skhirra) oil terminal'],
  ARRAY[]::text[],
  'Eni',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Chouech Es Saida Oil Field (Winstar/Serinus)',
  'Serinus Energy',
  'Tataouine Governorate (southern Tunisia)',
  'Tunisia',
  'Tataouine Governorate (southern Tunisia)',
  31.8,
  9.1,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Serinus Energy',
  'Private/State partnership (concession with ETAP participation typical; exact split not confirmed in ',
  'Operated by Serinus Energy; historical operators include Agip (Eni), Athanor; current working interest details not consistently published in open sources.',
  0,
  0,
  'barrels (crude oil)',
  2830000,
  'barrels (remaining recoverable; modelled estimate)',
  parse_flexible_date('1977-01-01'),
  NULL,
  'crude oil (type not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2001-01-01'),
  NULL,
  ARRAY['~80 km pipeline to El Borma (treated oil export route via El Borma system)'],
  ARRAY['La Skhira (La Skhirra) oil terminal (via national export system)'],
  ARRAY[]::text[],
  'Serinus Energy',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Nawara Gas-Condensate Field / Nawara Concession (Nawara Development Project)',
  'ETAP',
  'Tataouine Governorate (south)',
  'Tunisia',
  'Tataouine Governorate (south)',
  31.4,
  9.5,
  'Energy',
  'Natural Gas',
  'gas_field',
  'active',
  'ETAP',
  'JV (ETAP/OMV)',
  'ETAP 50%, OMV 50%',
  210000,
  2555000,
  'barrels (condensate; design capacity basis)',
  0,
  'barrels (not disclosed in open sources)',
  parse_flexible_date('2010-01-01'),
  NULL,
  'condensate (API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2011-01-01'),
  NULL,
  ARRAY['South Tunisia Gas Pipeline (STGP) 24-inch, ~370 km Nawara-to-Gabès'],
  ARRAY['Gabès (industrial port area; gas treatment plant location)'],
  ARRAY[]::text[],
  'ETAP',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Cherouq Concession (Jenein Nord area; Pioneer/ETAP)',
  'Pioneer Natural Resources',
  'Tataouine Governorate (south)',
  'Tunisia',
  'Tataouine Governorate (south)',
  31.5,
  9.4,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Pioneer Natural Resources',
  'JV (ETAP + foreign operator)',
  'Approved Dec 17, 2007: Pioneer 50%, ETAP 50% (Pioneer as operator at that time).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  parse_flexible_date('2007-01-01'),
  NULL,
  'crude oil (Silurian sandstone production; API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2010-10-27'),
  NULL,
  ARRAY['Local gathering/export to Tunisian sales system (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal (via national export system; not field-specific)'],
  ARRAY[]::text[],
  'Pioneer Natural Resources',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Anaguid Permit / Concession (incl. Mona discovery; Pioneer/ETAP/Medco structure)',
  'Pioneer Natural Resources',
  'Tataouine Governorate (south)',
  'Tunisia',
  'Tataouine Governorate (south)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'Pioneer Natural Resources',
  'PSC/JV (ETAP + foreign partners)',
  'Pioneer planned 30% in concession derived from Anaguid; ETAP 50%; Medco 20% (as reported in 2010).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  parse_flexible_date('2011-01-01'),
  NULL,
  'crude oil (Silurian discovery; API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2010-10-27'),
  NULL,
  ARRAY['Local gathering/export to Tunisian sales system (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal (via national export system; not field-specific)'],
  ARRAY[]::text[],
  'Pioneer Natural Resources',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Cercina / Cercina Sud Concessions (South Tunisia)',
  'TPS',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  'Tunisia',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  34.6,
  11.0,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (ETAP + foreign partner; divested)',
  'OMV held 49% (via OMV Tunisia Upstream GmbH) and ETAP held remaining stake; OMV sold OMV Tunisia Upstream GmbH to Panoro Energy ASA subsidiary (closed Dec 21, 2018).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  NULL,
  NULL,
  'crude oil (API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  65000000,
  'USD',
  parse_flexible_date('2018-12-21'),
  NULL,
  ARRAY['Export via Tunisian crude logistics to coastal terminals (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Ain / Gremda Concessions (South Tunisia)',
  'TPS',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  'Tunisia',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (ETAP + foreign partner; divested)',
  'OMV held 49% (via OMV Tunisia Upstream GmbH) and ETAP held remaining stake; OMV sold OMV Tunisia Upstream GmbH to Panoro Energy ASA subsidiary (closed Dec 21, 2018).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  NULL,
  NULL,
  'crude oil (API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  65000000,
  'USD',
  parse_flexible_date('2018-12-21'),
  NULL,
  ARRAY['Export via Tunisian crude logistics to coastal terminals (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'El Hajeb / Guebiba Concessions (South Tunisia)',
  'TPS',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  'Tunisia',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (ETAP + foreign partner; divested)',
  'OMV held 49% (via OMV Tunisia Upstream GmbH) and ETAP held remaining stake; OMV sold OMV Tunisia Upstream GmbH to Panoro Energy ASA subsidiary (closed Dec 21, 2018).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  NULL,
  NULL,
  'crude oil (API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  65000000,
  'USD',
  parse_flexible_date('2018-12-21'),
  NULL,
  ARRAY['Export via Tunisian crude logistics to coastal terminals (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Rhemoura Concession (South Tunisia)',
  'TPS',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  'Tunisia',
  'South Tunisia (governorate not specified in OMV release; generally southern Tunisia)',
  NULL,
  NULL,
  'Energy',
  'Crude Oil',
  'oil_field',
  'active',
  'TPS',
  'JV (ETAP + foreign partner; divested)',
  'OMV held 49% (via OMV Tunisia Upstream GmbH) and ETAP held remaining stake; OMV sold OMV Tunisia Upstream GmbH to Panoro Energy ASA subsidiary (closed Dec 21, 2018).',
  0,
  0,
  'barrels (crude oil)',
  0,
  'barrels (not disclosed in open sources)',
  NULL,
  NULL,
  'crude oil (API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  65000000,
  'USD',
  parse_flexible_date('2018-12-21'),
  NULL,
  ARRAY['Export via Tunisian crude logistics to coastal terminals (exact pipelines not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal'],
  ARRAY[]::text[],
  'TPS',
  NULL
);

INSERT INTO public.commodity_locations (
  title, owner, address, country, region, latitude, longitude,
  commodity_type, commodity_name, location_type, operational_status,
  operator, ownership_type, ownership_details,
  production_monthly, production_yearly, production_unit,
  estimated_reserves, reserves_unit, start_date, closing_date,
  quality_type, api_gravity, quality_sulfur_content, grade,
  last_transaction_value, last_transaction_currency, last_transaction_date,
  contract_duration_years, pipelines, ports, rail_connections, company, additional_info
) VALUES (
  'Sabria Oil Field (Winstar/Serinus)',
  'Serinus Energy',
  'Kebili Governorate (central-southern Tunisia)',
  'Tunisia',
  'Kebili Governorate (central-southern Tunisia)',
  33.0,
  8.5,
  'Energy',
  'Oil & Gas',
  'oil_field',
  'active',
  'Serinus Energy',
  'JV (private operator + state company)',
  'Serinus/Winstar 45% working interest (operator), ETAP 55%',
  47100,
  573400,
  'boe (gross; oil+gas equivalent; based on 1,550 boe',
  0,
  'boe (not disclosed in open sources)',
  parse_flexible_date('1998-01-01'),
  NULL,
  'oil and gas (boe; crude API not disclosed in open sources)',
  NULL,
  NULL,
  NULL,
  NULL,
  'USD',
  parse_flexible_date('2015-07-27'),
  NULL,
  ARRAY['Local gathering to Sabria CPF; export via Tunisian pipeline/oil logistics (names not disclosed in open sources)'],
  ARRAY['La Skhira (La Skhirra) oil terminal (for crude/condensate exports via national logistics)'],
  ARRAY[]::text[],
  'Serinus Energy',
  NULL
);
